### ISSUE TITLE
Light leak / Bloom

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1000]
**Describe the bug**

similar to #792

The Exorcist Pinball Possessed from Joe Picasso & Remdwass
https://vpuniverse.com/files/file/16530-the-exorcist-original-2023/

**To Reproduce**

VPinballX_GL-10.8.0-1635-da14fd0-Release-win-x86 
(same with GL)

1. Start table The Exorcist Pinball Possessed
2. Insert coin
3. Start game
4. Wait for voice "what an excellent day..." to end
5. Bloom / leak appears

**Expected behavior**

**Screenshots**

Build 1579 (Normal)

![image](https://github.com/vpinball/vpinball/assets/161305/cc8e3cad-f9f2-4e88-a118-c82afac392a7)

Build 1635 (Issue)

![image](https://github.com/vpinball/vpinball/assets/161305/66213477-a46a-4374-9ad2-69f36b36e299)

**Comment by Crrispy** [comment]
Ah damn, it's back.

**Comment by vbousquet** [comment]
Without a link to the table and your settings, there is nothing that can be done

**Comment by francisdb** [comment]
Settings are default as provided with vpinball
Table will be released in 2 days
https://www.youtube.com/watch?v=McvhzWn5GFU&list=WL&index=1

**Comment by francisdb** [comment]
Fixed in 114330e539c697ce75dfdd5c42b614ea6c834aee
