### ISSUE TITLE
Framerate limiter doesn't work on some tables

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#1004]
**Describe the bug**
The maximum framerate in the graphics setup doesn't work. I've set it 120 and vsync off in the nvidia driver, it still goes over to 140/150fps (as reported by F11 screen) and then framerate fluctuates a lot and the ball stutters.

**To Reproduce**
Set "Maximum framerate" to the max refresh rate of your display and vsync off on the gfx driver.
Start a table which is not limited by your hardware, press F11 and check that the framerate goes over the value set in the settings.

**Expected behavior**
Framerate should be capped to the value entered in settings.

**Versions & Settings**
 - VPX: 10.8 build 1635 , GL x64
 - Windows version: 11
 - GPU: RTX2080 , latest Nvidia driver

[VPinballX.log](https://github.com/vpinball/vpinball/files/13191423/VPinballX.log)

**Comment by Crrispy** [comment]
Edit (I can't edit the text body anymore, only title): the issue does not happen with all tables. To reproduce it, use VPW's Johnny Mnemonic: https://vpuniverse.com/files/file/15487-johnny-mnemonic-williams-1995/
With other tables like Spongebob, the frame limiter works fine.

**Comment by Crrispy** [comment]
Also doesn't work on Totan 4K  https://vpuniverse.com/files/file/12652-tales-of-the-arabian-nights-4k-williams-1996/

**Comment by francisdb** [comment]
Aha, that sounds like the issue where vsync is sometimes forced by tables user settings. Try overriding the value in the table specific ini to see if that works.

JM is known to force vsync overriding the default. I need to set it to 0 (no sync) to have the table run properly.

**Comment by Crrispy** [comment]
> Aha, that sounds like the issue where vsync is sometimes forced by tables user settings. Try overriding the value in the table specific ini to see if that works.
> 
> JM is known to force vsync overriding the default. I need to set it to 0 (no sync) to have the table run properly.
> 
> `Johnny Mnemonic (Williams 1995) VPW v1.1.ini`
> 
> ```ini
> [Player]
> SyncMode = 0
> ```

Hello, well, this is quite the opposite, I have vsync off in the nvidia control panel, but the frame limiter set to 120 in VPX. This works fine for some tables, not for some others. But there it's rather disabling the global VPX frame limiter parameter since it goes well over 120. I will try your suggestion though.

**Comment by francisdb** [comment]
For some more testing you can also add this to the player section

```ini
MaxFramerate = 120
```

**Comment by Crrispy** [comment]
Hello, it turns out that there was already a .ini for these tables and in it there was MaxFramerate=0, so it was overriding the global VPX setting. How did this arrive in these .ini files, I have absolutely NO idea... Of course I didn't set it manually. But false positive here, the frame limiter does work on all tables it seems.

**Comment by francisdb** [comment]
The table specific ini system is replacing pov files + more. Iif you save the pov in the camera setup this file is created including default table overrides.

**Comment by Crrispy** [comment]
> The table specific ini system is replacing pov files + more. Iif you save the pov in the camera setup this file is created including default table overrides.

Yep, but for the POV, it seems to need some tuning still, see #1025
