### ISSUE TITLE
Ramp visuals broken of Police Force (Williams 1989) VPW in the latest release

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#1006]
**Describe the bug**
See this image then you see exactly what goes wrong in the latest release: https://imgur.com/0Z28593
In releases from ~2 - 1,5 month ago (at around the time of the release of the Police Force table and a couple of releases after that) it worked fine. I don't know which release exactly broke it.

**To Reproduce**
Play Police Force (Williams 1989) VPW in version VPinballX_GL-10.8.0-1635-da14fd0-Release-win-x64 in VR and wait until certail lights flash (you don't even need to start the table, it already happens when you don't and wait for a while)

Hereby the link to the table: https://vpuniverse.com/files/file/15712-police-force-williams-1989-vpw/

**Expected behavior**
The ramp should be like on the left side of this image: https://imgur.com/0Z28593

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1635-da14fd0-Release-win-x64
 - VR
 - My ini file could be found in bug report 811: https://github.com/vpinball/vpinball/issues/811

**Additional context**
The screenshots are made by the "mirror window" of my OpenXR software since the regular VR capture is broken, see: https://github.com/vpinball/vpinball/issues/978 & https://github.com/vpinball/vpinball/issues/605

Thank you for your attention.

**Comment by vbousquet** [comment]
Fixed in latest
