### ISSUE TITLE
Lighting/blooming bug in: The Who's Tommy Pinball Wizard (Data East 1994) VPWMod in the latest release

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#1007]
**Describe the bug**
See here the bug, a picture tells more than words: https://imgur.com/VbUGUh1

**To Reproduce**
Play The Who's Tommy Pinball Wizard (Data East 1994) VPWMod in the latest release(1635) in VR and you'll see what is shown in the screenshot. 

Hereby a link to the table: https://vpuniverse.com/files/file/10193-the-whos-tommy-pinball-wizard-data-east-1994-vpwmod/

**Expected behavior**
The lights should behave as before in previous releases. In a release from ~1,5 month's ago (at the time that "Godzilla VPW table" was released), the problem wasn't there. The lights just appeared normal as they always did in that table.

**Versions & Settings**
- VPX: VPinballX_GL-10.8.0-1635-da14fd0-Release-win-x64 doesn't happen in releases from ~1,5 month ago.
- VR
- My ini file could be found in bug report 811: https://github.com/vpinball/vpinball/issues/811

**Additional context**
I made the two pictures through the lens of my headset because that shows the issue more clear than in a "VR mirror" because of the higher resolution in the headset compared to my low resolution monitor.

**Comment by francisdb** [comment]
@TurboHenk just a note, you can paste images directly in github

Dupe of #1000 which is a regression of #792?

**Comment by TurboHenk** [comment]
> @TurboHenk just a note, you can paste images directly in github
> 
> Dupe of #1000 which is a regression of #792?

Yes it looks similair BUT I just tested Red & Ted's Roadshow(the recent update from VPW I think that a link is not needed but it's on VPuniverse) and it's even much worse there so I'm not 100% sure if it's the same issue. 

Hereby a screenshot:
![table_reflections_broken_2](https://github.com/vpinball/vpinball/assets/132104433/4c85b778-cad1-4591-a1ed-ec5866f59a4d)

And somehow the table reflections on zero also seem to be broken in release 1641 for that reason also a screenshot of the emulator:
![table_reflections_broken](https://github.com/vpinball/vpinball/assets/132104433/79427b13-4686-4437-bc2a-ec260a3349f1)

0 should disable it, but it does nothing. Do I need to make a new report about this bug? Because it's clearly a second but non related bug. Because the strength is non adjustable now.

**Comment by TurboHenk** [comment]
> @TurboHenk just a note, you can paste images directly in github
> 
> Dupe of #1000 which is a regression of #792?

Yes it seems to be similar. But I never had this issue in the past.

**Comment by vbousquet** [comment]
Thgis should be fixed in 1643. Could you confirm that this is good for you (I was not able to reproduce but I think it's the same bug I fixed in 1643)

**Comment by TurboHenk** [comment]
> Thgis should be fixed in 1643. Could you confirm that this is good for you (I was not able to reproduce but I think it's the same bug I fixed in 1643)

"I thought that it was a Pimax issue but...." 👍  all jokes aside:

Thank you for the great fix! It's perfect now for sure. I'm closing this with this comment.
