### ISSUE TITLE
Ball physics have severe collision problems with plungers and drains on certain tables as of 8281e9f

### ISSUE THREAD

**Issue by SuperFromND** [vpinball/vpinball#1021]
**Describe the bug**
As of commit 8281e9f, ball physics in general seem to have issues when colliding with certain aspects of a table, mostly around the plunger and outlane areas.

More specifically, certain tables will not properly "let go" of the ball when dispensing it into the plunger, effectively soft-locking it and making it impossible to play. This bug most likely predates that particular commit, but that's what I'm testing on.

I've also observed at least two instances of the ball getting stopped by seemingly nothing when approaching the outlane. This seems to also be table-specific, though I can confirm this did not happen as recently as be82ae0.

**List of affected tables that I've encountered strange ball behaviors in include:**
- [Sixtoe's Eight Ball Deluxe](https://vpuniverse.com/files/file/6003-eight-ball-deluxe-minimal-vr-room-bally-1980/): Impossible to plunge the ball.
- [VPW's The Machine: Bride of Pinbot v1.04](https://vpuniverse.com/files/file/12029-the-machine-bride-of-pinbot-williams-1991-vpw-mod/): Impossible to plunge the ball.
- [Sixtoe's Strikes and Spares](https://vpuniverse.com/files/file/6023-strikes-and-spares-minimal-vr-room-bally-1978/): Strange drain behavior.
- [Sixtoe's Space Jam](https://vpuniverse.com/files/file/6025-space-jam-minimal-vr-room-sega-1996/): Strange drain behavior.

**To Reproduce**
1. Download the version of VPX mentioned by this commit, possibly a few commits earlier as well.
2. Start up one of the affected tables listed above.
3. Observe ball behavior as you play; immediately for the former two tables, and when draining the ball for the latter.

**Expected behavior**
I think this one is pretty self-explanatory, but the ball should not float in the middle of the plunger nor seemingly defy the laws of gravity when approaching the outlane on certain tables.

**Screenshots**
I rendered a video showcasing these physics issues, with all four affected tables listed above.

https://github.com/vpinball/vpinball/assets/22881403/dc6e430e-a3f4-486f-9b5b-d79032c01b89

**Versions & Settings**
 - VPX: be82ae0, 64-bit Release version
 - Windows 10 Pro, 22H2 19045.3570
 - NVidia RTX 3060 Ti, Driver 536.23 (via Windows Update, not through Nvidia's own site)
 - [VPinballX.ini](https://github.com/vpinball/vpinball/files/13197891/VPinballX.ini.log)
 - [vpinball.log](https://github.com/vpinball/vpinball/files/13197889/vpinball.log) [note: not recorded at the same time as the video example above, but covers two of the affected tables regardless!]

**Comment by havemusic** [comment]
This issue seems to have started around release 1645 Attack from Mars new release does not all ball into trough.

**Comment by michroch** [comment]
Confirming also on my side with build 1658 with the new Wednesday table, went back to 1635 and working fine.

**Comment by michroch** [comment]
Still a problem on Black Hole (Gottlieb 1981) table with build 1663

Table: https://www.vpforums.org/index.php?app=downloads&showfile=12893 or https://www.vpforums.org/index.php?app=downloads&showfile=17369

**Comment by SuperFromND** [comment]
Things are definitely better now, but I also ran into a couple tables that still have this problem. _Bride of Pinbot_ mentioned above is still impossible to plunge the ball on; I'm guessing it just doesn't set a glass position and the default value is being set too low.

Similarly, _[Black Knight 2000](https://vpuniverse.com/files/file/9054-black-knight-2000-williams-1989-w-vr-room/)_ mostly works, but shooting a ball into the draw-bridge ramp causes it to get stuck, most likely for similar reasons.

**Comment by vbousquet** [comment]
Fixed (for good this time) in latest

**Comment by SuperFromND** [comment]
Believe me, I hate to say this, but it appears _Bride of Pinbot_ is *STILL* suffering from this even after the second set of fixes you pushed. :<


https://github.com/vpinball/vpinball/assets/22881403/edb86ff7-422e-427b-a8a3-df0d3654bf46


I swear, this table has to be cursed or something.
