### ISSUE TITLE
player Y and Z working only as global setting

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#1026]
Using the last build 1663 if you change PLAYER Y or PLAYER Z on the camera view (F6) and save, then the global PLAYER Y and Z will be modified, and looks like all the tables uses the global values no matter if there are a saved ini

**Comment by dacstyle** [comment]
tested 1669 and the issue persists

**Comment by vbousquet** [comment]
This was not a bug (in Window mode, you should never have to change these), but changed in latest

**Comment by dacstyle** [comment]
I also think that setting should never change, but in most of tables a value of 20 for PLAYER Y looks Great, but if you play VPW's GNR with that setting you can't see the ball in the inlane section. 
So I changed  that value for GNR and saved the .ini, later I noticed it changed globally.

Looks like some tables need a different setting maybe because the particular design of each table.
