### ISSUE TITLE
Ninuzzu's ball shadow problem

### ISSUE THREAD

**Issue by michroch** [vpinball/vpinball#1029]
There is a weird round line around the ball with tables who have the Ninuzzu's ball shadow code in the script.

Tables example: 

- Beat the clock (Bally 1985)  https://www.vpforums.org/index.php?app=downloads&showfile=17354
- Batter Up (Gottlieb 1970) https://vpuniverse.com/files/file/8788-batter-up-gottlieb-1970/

**Screenshots**
![20231029_224431](https://github.com/vpinball/vpinball/assets/105334350/9cba0655-4369-405a-b7ab-743c644d732c)

**Versions & Settings**
 - VPInblall 10.8 1663 x64 or x86
 - Windows Spectre 10
 - I7 5820K
 - Nvidia GTX 1660 Super 6G

**Comment by michroch** [comment]
![Uploading 20231029_234829.jpg…]()

**Comment by michroch** [comment]
If unchecking the Additional Screen Space Reflections in the Video/Graphics Options of VPX, the line around the ball is gone. I don't know if this option is checked by default though, but this is the answer for this problem I got.

![20231030_001937](https://github.com/vpinball/vpinball/assets/105334350/cf84d3d0-9620-4a0e-b068-f9ace43e3800)

**Comment by vbousquet** [comment]
This is not a bug but the way the table is built. For fake blob shadow to work correctly, they need to have the 'hide behind' option unchecked (was added in 10.8 for this purpose, and is described in the docs)
