### ISSUE TITLE
Ball reflection playfield flasher overlap issue

### ISSUE THREAD

**Issue by unclewilly6988** [vpinball/vpinball#1037]
**Describe the bug**
Hey.  I'm unclewilly from the forums.  This bug can be seen in pinball magic at vpf.  Where the captive ball sits there is a playfield light.  A flasher sits at .1 and is an additive blend.  The reflection of the captive ball disappears and reappears when that light turns on and off

**To Reproduce**
Load pinball magic v1.9 in vpx8 1666.
Let attract mode start and look at the ball reflection of the captive ball.  It disappears and reappears when the flasher changes states.

**Expected behavior**
Insert light and flasher lightmap have no effect on the balls playfield reflection

**Comment by vbousquet** [comment]
Hi ! This is not a bug in VPX but the way the table is built. It uses a wall for the playfield (named PFW) raised at height 100. To get proper reflection, this need to be setup with the a primitive with the new render probe settings.
