### ISSUE TITLE
Post Action #2155 POV Files Still Active

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#1038]
**Describe the bug**
As of the last build I tested (1658 dx x64), and in response to Action 2155 (remove POV in favor of INI)... VPX still has a functioning export .pov menu and will still create a .pov.  Is this intended?  Are the .pov files no longer necessary?  How to manually save information that was previously stored in the .pov as .ini?  Do we need to keep our .pov's going forward?

**To Reproduce**
Use export .pov

**Expected behavior**
Unknown at this point... Action 2155 seems to say that .pov is no longer being used or necessary, but not sure how the new .ini process should work.

**Versions & Settings**
 - VPX: Last tested in VPX DX 1658 x64
 - Windows 11
 - [VPinballX.log](https://github.com/vpinball/vpinball/files/13211715/VPinballX.log)

**Additional context**
Thanks, Vincent!   :)

**Comment by vbousquet** [comment]
Fixed in latest (refactoring of settings still in progress though)
