### ISSUE TITLE
starting a table in VR (GL) creates a table INI file (without doing anything)

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#1039]
**Describe the bug** & **To Reproduce**
When I launch a table in VR with 'VPinballX_GL-10.8.0-1669-9ed597f-Release-win-x64' it creates already an table INI file with just the following information : 
```
[PlayerVR]
Slope = 6.500000
Orientation = 0.000000
TableX = 0.000000
TableY = 0.000000
TableZ = 80.000000
```
this doesn't s make sense to create a table ini with this info as when you  re-center (refocus or whatever) the table, these settings will be overwritten.
When this information is needed, write it to the default ini file

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
All tables

**Expected behavior**
Not making a table ini, so the table folder only has table ini's with specific settings for that table (not the users position)

**Screenshots**
NA

**Crash dump**
NA

**Versions & Settings**
 - VPX: GL-10.8.0-1669-9ed597f-Release-win-x64
 - Windows version: 11 22h2
 - GPU and video settings if applicable : RTX 3080
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**

**Comment by vbousquet** [comment]
Fixed in latest (refactoring of settings still in progress though)
