### ISSUE TITLE
Certain table .wav files not playing sound

### ISSUE THREAD

**Issue by MrMcGruff** [vpinball/vpinball#105]
**Describe the bug**
have noticed some wav files in tables do not playback

Example table/s
1. Go to "Clue or DreamDaddy
2. Sound in question - fx-warning.wav

Can export sound and it works fine. Hope this helps. 

**Versions**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable

**Comment by toxieainc** [comment]
@MrMcGruff Did you also try with a newer prerelease build? E.g. https://github.com/vpinball/vpinball/suites/8190490882/artifacts/356428836

**Comment by toxieainc** [comment]
@MrMcGruff ping

**Comment by vbousquet** [comment]
Just tried the table with latest VPX version andall samples did play well. fx_warning did play correctly too, so I will close this issue for now.
