### ISSUE TITLE
Ball trail/blur not visible on some VPW tables

### ISSUE THREAD

**Issue by keithhov** [vpinball/vpinball#1053]
Unable to produce any amount of blur or motion trails on two tables below when enabling ball trail strength in video/graphics options.  Other VPW tables can produce trail/blur.  All versions of 10.8 beta

https://vpuniverse.com/files/file/15487-johnny-mnemonic-williams-1995/

https://vpuniverse.com/files/file/16258-no-fear-dangerous-sports-williams-1995/

**Comment by vbousquet** [comment]
These tables have there playfield set with a negative depth bias which in turns make them render after the ball trail, therefore hiding it. This is not a VPX bug but the table needs a little fix.

**Comment by keithhov** [comment]
Thanks ,,,, Mike da spike suggested reaching out to you …. He to assumed it might be a  table issue.   Thanks so much for what you do… love this hobby .Sent from my iPhoneOn Nov 11, 2023, at 3:18 AM, Vincent Bousquet ***@***.***> wrote:﻿
These tables have there playfield set with a negative depth bias which in turns make them render after the ball trail, therefore hiding it. This is not a VPX bug but the table needs a little fix.

**Comment by Rud8289** [comment]
How do I go about changing the playfield’s depth bias?  I’ve looked in the main layout, etc. but there’s no way to change the depth bias specific to the playfield.  As OP said thanks so much for all you do.

**Comment by keithhov** [comment]
edit.....select element....find playfield mesh....then  on right side look under properties....then render options and you will see depth bias,..

I "fixed" a few tables like this but only works about half the time... other times it creates major visual problems..
I made some comments on vpuniverse but no one really seemed interested...... I know VPW's godzilla is one I couldnt get any ball trail without major visual glitches. 
I don't like "ball trail" but I do think the ball looks much smoother with a low amount enabled.,, even on my 144 hertz playfield I prefer a small amount of trail.

**Comment by francisdb** [comment]
_side note: 10.8.1 will have motion blur for the ball_

**Comment by Rud8289** [comment]
@keithhov Thank you!!!!!!!  What do you normally set the depth bias to?  And good to know, I figured that might be the case, messing with depth bias could potentially cause more harm than good in some situations.  And agreed, I have a 60hz TV for my playfield and enabling a low amount of ball trail hides the ball 'judder' and makes it look much smoother. 

@francisdb I've seen mentions of motion blur, looking forward to trying it out!

**Comment by keithhov** [comment]
not a clue what "normal" would be....I am just good at trial and error......I think many older tables the depth bias wasn't really relevant.   Seems to be more relevant in newer tables with fancy lighting and shadows.....

I had 60 hertz in the past and yeah a lot of judder without ball trail....then I went to 120.... much smoother,,,, currently at 144 on my cabinet......166 on my desktop.   I have herd some talk of eliminating the "trail" but yeah we definitely need some type of motion blur.....
I enjoy playing on cabinet the most, as soon as I see ball judder the illusion of playing a "real" pinball table is gone.
