### ISSUE TITLE
Flasher ball reflection overlap

### ISSUE THREAD

**Issue by unclewilly6988** [vpinball/vpinball#1054]
Hey.  Its me again.  Same bug I posted before.  I saw your responce.  You were looking at mine and Roth and djrob x version.  The update to vpx8 that I just released on vpforums was completely rebuilt and no longer sits on a raised playfield  it uses vpx's default playfield with a playfield mesh at height 0.
That's why I reported it.  As it may effect other people if they use flashers to enhance the inserts and the flasher overlaps a captive balls playtield reflection.

**To Reproduce**
To reproduce the issue grab unclewillys pinballmagic hybrid from vpforums
Load the table and watch attractmode and the ball reflection at the captive ball.

https://www.vpforums.org/index.php?app=downloads&showfile=17871

**Comment by vbousquet** [comment]
Could you entirely fill in the issue template ? There is no way to help without the requested informations
