### ISSUE TITLE
1692 need to completely clos VPX after save ini

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#1055]
Testing the VPX 1692 GL 64 I see that after modify a pov and save the INI file, you need to completely close VPX and open again the software and the tablemin order to see the changes.

If you quit to editor and launch the table without completely close VPX the INI file recently saved will be ignored.

Also the right and left flippers buttons are inverted on the pov editing page, now the left is + and the right is -

**Comment by pacleary** [comment]
I tried debug and release of 1692 GL 64. The debug version had the flippers inverted in POV, but the release didn't. I'm having trouble saving the POV even with closing VPX completely.

**Comment by dacstyle** [comment]
Working Great! Thanks!

**Comment by pacleary** [comment]
Hmm.. Not working for me in 1705. Do I need to clear a cache of some kind? I try to edit a table POV and there is no Asterisk in the title to signify a change and saving does nothing. When I load the table, it reverts to the previous POV.

**Comment by vbousquet** [comment]
> Hmm.. Not working for me in 1705. Do I need to clear a cache of some kind? I try to edit a table POV and there is no Asterisk in the title to signify a change and saving does nothing. When I load the table, it reverts to the previous POV.

Therer is no asterisk since now, you are not modifying the table (this is one of the aims of all the latest change). You are just adjusting your settings (the ini file). If you do not press credit key, then this is not exported and therefore it is normal not to be there on next run.

**Comment by pacleary** [comment]
> > Hmm.. Not working for me in 1705. Do I need to clear a cache of some kind? I try to edit a table POV and there is no Asterisk in the title to signify a change and saving does nothing. When I load the table, it reverts to the previous POV.
> 
> Therer is no asterisk since now, you are not modifying the table (this is one of the aims of all the latest change). You are just adjusting your settings (the ini file). If you do not press credit key, then this is not exported and therefore it is normal not to be there on next run.

Perfect. Thank you. I figured I was missing something!
