### ISSUE TITLE
1692 crashes with some tables

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#1056]
Testing some tables on 1692 GL 64 I see GNR and police force both from VPW are crashing
[crash.dmp](https://github.com/vpinball/vpinball/files/13233494/crash.dmp)

**Comment by pacleary** [comment]
Still an issue in 1694.

**Comment by PEandS1Ws** [comment]
Pinball Magic (Capcom 1995) same issue. Reverted back to an earlier build and it works. Win 86x version

**Comment by michroch** [comment]
Confirming also for VPW's GNR , also Aerosmith an Aces of Speed. I deleted those tables and reinstalling again and it works

**Comment by jsm174** [comment]
Standalone might give a little more helpful stacktrace:

```
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4332011504
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      102354000-103178000    [ 14.1M] r-x/r-x SM=COW  .../VPinballX_GL

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   VPinballX_GL                  	       0x1025757e4 RenderProbe::ApplyAreaOfInterest(RenderPass*) + 32
1   VPinballX_GL                  	       0x10248c674 Player::RenderDynamics() + 1088
2   VPinballX_GL                  	       0x102490aa8 Player::PrepareFrame() + 684
3   VPinballX_GL                  	       0x102490128 Player::OnIdle() + 200
4   VPinballX_GL                  	       0x10245f338 VPinball::MainMsgLoop() + 36
5   VPinballX_GL                  	       0x1024423a8 WinMain + 184
6   dyld                          	       0x181c110e0 start + 2360
```

**Comment by pacleary** [comment]
I tried build 1691 and it had the same issues. 
1. Not being able to save POV.
2. Inverted flipper controls for POV (I think just in the debug)
3. Crashing certain tables.

I went back to 1679 (my prior download) and everything works. Not sure if it is helpful for anyone to try builds prior to 1691.

**Comment by jsm174** [comment]
I'm sure this will get fixed soon:

![Screenshot 2023-11-02 at 10 30 24 AM](https://github.com/vpinball/vpinball/assets/1197137/c85c5a74-aefa-4722-8cdc-606cdbf3aaee)

**Comment by dacstyle** [comment]
> Confirming also for VPW's GNR , also Aerosmith and Aces of Speed. I deleted those tables and reinstalling again from the original and they are working again without crashing. (None GL build 1694)

I tried the same process too, but still crashing on GL. I didn't tested DX yet.

**Comment by pacleary** [comment]
SpongeBob and GNR open in 1689 GL 64bit debug, but wasn't able to save the POV and the flippers were reversed for POV.

So whatever causes the crashing happened after 1689, but the other issues were present in 1689.

**Comment by dacstyle** [comment]
tested 1694 dx and gl, same problem, tried deleting the cache folder, same problem

**Comment by vbousquet** [comment]
Fixed in latest

**Comment by dacstyle** [comment]
Solved, thank you.
