### ISSUE TITLE
Editing tables and run it causes lot of time crashes

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#1057]
**Describe the bug**
I'm not an author, but more a modder that adds VR-room enviorment to tables.
When adding primitives, flasher, or even changing images, and run the table, it mostly crashes. Even when opening the table again and run, could result in a crash of VP
This is happening a long time with most versions and even with version : VPinballX-10.8.0-1692-4b04ad0-Release-win-x64

It's not really a reproducable issue, as sometimes its working fine,, but I noticed it when changing Images (reimport images) or adding flasher and adding primitives.

For myself I found a workaround :
When I remove the used_textures.xml from the cache directory, I avoid the crash and table launch normally.

**Versions & Settings**
 - VPX: VPinballX-10.8.0-1692-4b04ad0-Release-win-x64
 - Windows version 11 22h1
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**
Maybe an option to disable the "use cache" would be an option ?

**Comment by dacstyle** [comment]
This must be related to issue #1056 I wil check if deleting that cache file allow to run the tables.

**Comment by MikedaSpike** [comment]
Not sure, i have it the last 200 revisions as well, but today discovered that deleting the file was a workaround for me

**Comment by vbousquet** [comment]
Is this still happening ? There was a (huge) lot of changes and I don't get crashes on my side and have no clue what is happening for you here

**Comment by MikedaSpike** [comment]
yes, still happening. Even with latest.
if it is just me, just leave it, but it makes it hard for me to make any modification to the table

`Crash report VPX - v10.8.0 Beta (Rev. 1750 (58b2b69), windows DirectX 64bits)
============
Process: VPinballX64.exe
Reason: 0xC0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:000000007B732F10
Attempt to read from 0x5EF750D0
Thread ID: 0x47D4 [18388]

Call stack
==========
000000007B732F10 VPinMAME64.dll (0xFFFFFFFFFFAE6200 0xFFFFFFFFFFAD6300 0xFFFFFFFFFFAD6400 0xffffffffffae6500)

Environment
===========
Date/time: 12/11/2023, 11:28:46:297
Number of CPUs: 6
Processor type: 8664
System: Windows 10 (10.0 22621)

Memory status
=============
Total Reserved: 572120K (558M) bytes
Total Commited: 1966076K (1919M) bytes
Total Free: 1656044K (1617M) bytes
Largest Free: 4159612K (4062M) bytes

Registers
=========
RAX=00000200 RBX=530C7040 RCX=0000002A RDX=5EF750D0
RSI=7D73DB00 RDI=530C7040 RBP=00000100 RSP=19EAF9A0 RIP=7B732F10
FLG=00010206 CS=0033 DS=002B SS=002B ES=002B FS=0053 GS=002B


Failed to save minidump.
`

**Comment by MikedaSpike** [comment]
@vbousquet 
Vincent, set this one to closed. I now used the latest 10..8.0 and it doesn't crashes that often anymore. It looks more stable (occasionally crashes, but had it with 10.7 as well.

**Comment by vbousquet** [comment]
Ok, if you have crashes with insight, just tell and we'll have a look (would be nice to have an app that won't crash at all :) )
