### ISSUE TITLE
Strange artifacts on the playfield in Atlantis (Bally 1989) w VR Room in release 1694

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#1060]
**Describe the bug**
See these 3 pictures:
![1](https://github.com/vpinball/vpinball/assets/132104433/f14a8e03-fd3f-4250-affb-06e2ae50565e)
![2](https://github.com/vpinball/vpinball/assets/132104433/4c857621-08ba-4051-85d5-a2729862dcf6)
![3](https://github.com/vpinball/vpinball/assets/132104433/9f3a4cd3-06d2-4287-a98d-f35d875e2849)

These artifacts change constantly when I move my head. Some kind of "trail" it creates.

**To Reproduce**
Use VR with Atlantis (Bally 1989) w VR Room: https://vpuniverse.com/files/file/10348-atlantis-bally-1989-w-vr-room/

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1694-272ee3c-Release-win-x64 (it DIDN'T happen with releases from ~a week ago since I played this table recently, so a recent change must have caused this)
 - 4090 / Pimax Crystal so VR
 - Most recent log: 
[VPinballX.log](https://github.com/vpinball/vpinball/files/13246677/VPinballX.log)

And the info from the table ini:
[Player]
BallTrailStrength = 0.501961

[PlayerVR]
Slope = 6.500000
Orientation = 1.085201
TableX = -21.868313
TableY = 136.296692
TableZ = 120.000000

**Comment by TurboHenk** [comment]
All tables seem to have issues with reflections.

All playfields now have some kind of extra reflections.

Example:

This is are 2 screenshots of Bad Cats:
![4](https://github.com/vpinball/vpinball/assets/132104433/0922c675-30cb-4cb8-8561-a8a10e1c6370)

![5](https://github.com/vpinball/vpinball/assets/132104433/77d0a6b6-8424-425a-bbe6-13a94b068f04)

I tested this with 1694 and 1703, both have the same issue with this table.

**Comment by SuperFromND** [comment]
Seems like this might be related to #1073; can you guys check on latest when you get a chance?

**Comment by TurboHenk** [comment]
> Seems like this might be related to #1073; can you guys check on latest when you get a chance?

Yes a big part is fixed, this part: The strobing/trail artifacts are fixed, so the table reflections work again. The bright light on the bad cats table(orange licht with circle) is also fixed.

But one thing isn't fixed yet and that is that the issue shown on the last bad cats image: 

The "light reflections of the VR room" that normally only happen on the cabinet/lockbar now also reflect on the playfield and some plastics in some tables. 

This is really an unwanted effect in VR and should be undone or optional if it's intended behaviour(which I hope not, because it ruins the tables where it happens completely for me).

This bug was an old bug of the 10.71/10.72 releases(for a longggg time) and it's now returned sadly enough. I hope that this could be fixed too.
