### ISSUE TITLE
INI files are not loading window POV settings on next table load

### ISSUE THREAD

**Issue by shro2023** [vpinball/vpinball#1065]
**Describe the bug**
In recent builds editing tables in camera mode no longer creates a POV file just an INI file. I believe this is by design though these INI files seem to be ignored on next table load with the camera reverting to Legacy POV despite being changed to Window mode. Opening INI file manually in a text editor also does not seem to reflect the options set via the Camera mode.

**To Reproduce**
1. Open a table in Camera Mode in VPX GL 10.8 1697 x64
2. Change POV mode to Window
3. Adjust Table X Scale and Table YZ Scale as required
4. Press Start button to output POV settings - only INI file is created
5. Close VPX Editor and table
6. Reopen VPX GL 10.8 1697 x64 and select table you made POV settings change in. Table will load but in Legacy camera mode and on switching to Window mode previous X and YZ Scale adjustments will be reverted to default values.

**Expected behavior**
On Step 6 expect VPX Editor to load the settings previously set in camera mode for the table and so load straight into Window Mode with camera settings from INI file.

**Screenshots**
Not Applicable

**Crash dump**
Not Applicable

**Versions & Settings**
 - VPX: 10.8 GL 1697 x64
 - Windows 11 (Ghost Spectre)
 - Geforce GTX 1080ti though don't believe this is applicable

**Comment by vbousquet** [comment]
Not sure when you experienced the problem but with version 1705, I followed the steps you describe and everything worked as it should. I will close for now. Please just post a comment if you're still experiencing the problem and I will reopen
