### ISSUE TITLE
VR broken since "VR: add free form fitted preview, with F10 to toggle #2220"

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#1066]
**Describe the bug**
Because with the new VR mirror implementation:
- all tables with a "[PinUP Virtual Pinball System]" are broken. Lots errors come up when I launch a table and it's impossible to render the PinUP window on the left side of the mirror because the mirror is taking the full screen.
- The second issue is that when I disable the mirror and go back to the pimaxxr mirror windows (because that would be the only way to still use PinUP windows), it also creates a full black screen(before it created a small black window). So this makes it also impossible to disable the mirror, because B2S and PinUP both cannot be rendered.
- The third problem is that there is no normal mirror anymore. Mirror 1 (without pressing F10) renders a streched image on my 16:9 screen(looks distorted) and pressing F1 again renders 2 eyes instead of 1 so looks akward and pressing it 3 times creates an even stranger situation with 3 windows where the above is bugged(a rendered part of the other windows keeps stuck). I don't understand the benefit of this at all. The old mirror just worked great.

Please give us the option to use the VR mirror as it was.(including disabling the mirror so that we could use an alternative mirror + pinup system) 

It was just functioning properly for one day after your great fix with VPinballX_GL-10.8.0-1694-272ee3c-Release-win-x64

The new implementation is unusable.

I'm using VR with the Pimax Crystal. My log could be found here:
[VPinballX.log](https://github.com/vpinball/vpinball/files/13254735/VPinballX.log)

**Comment by retro27** [comment]
Same Issue with my Quest, when I disable the preview, its showing a full black screen, causing PUP and DMD not to show.

**Comment by vbousquet** [comment]
The preview window size is now defined from the video options to whatever size/display you want

**Comment by TurboHenk** [comment]
Thank you for your reply. This works but there are 2 issues with this compared to the previous implementation:

When I use fullscreen on my 16:9 1440P screen and render one eye (which is the preferred setting for non-pup tables, nobody wants 2 eyes) with the exclusive fullscreen setting of 1440P resolution then the image is zoomed in.

This is what I see on the 1440P screen with the left eye setting: 
![left_eye](https://github.com/vpinball/vpinball/assets/132104433/108e7284-a913-4b83-bc3f-ac2c3b4ea620)

This is what I see in the lens:
![lensshot](https://github.com/vpinball/vpinball/assets/132104433/babfd771-c0a9-4fe9-85f2-33eec4ab52fe)

So the image is zoomed in a lot on the 16:9 setting. When I play pinball with multiple people (what I do mostly) then the person that watches the screen couldn't see the DMD/backglass. 

So it would be great if the full left/right eye is rendered, so that in case of 16:9 the image could be "zoomed out" so that the person that looks at the screen could also see the dmd/backglass/the same as the one that is using VR could see.

The second issue is that when I choose "windowed" that it renders all the way to the left of the screen, hereby a screenshot: 
![batmanexample](https://github.com/vpinball/vpinball/assets/132104433/0ec348f3-d472-4b18-b28e-3d068f2a7b67)

So this isn't usable at all. I tried to change WindowPosX = 0 WindowPosY = 0 to all kind of different settings in the vpinballx ini and in the table ini, but both are fully ignored somehow so I couldn't move the window to the left/middle.

**Comment by vbousquet** [comment]
These are expected behaviors:
- the preview is not an additional render but a copy of what is rendered in the headset. Previously, tou would not choose the size, and VPX would take the size of the headset and do a (bugged) copy. so no fitting was involved. Now you choose the size and you get a clean fit and scale. to get the complete view, you just need to choose a preview of the same width/height ratio as the headset lens
- before the change, the window could not be moved, Now you can by pressing ESC and dragging it (like when playing in desktop mode). This position is persisted

From your feedback, I understand that one additional enhancement would be to add a scale down to fit option (with black bars).

**Comment by TurboHenk** [comment]
_"From your feedback, I understand that one additional enhancement would be to add a scale down to fit option (with black bars)."_

Thank you, I would really appreciate that! Yes that would make the mirror perfect for playing pinball together in VR(in non-pup tables, for the pup-tables windowed mode is needed but because of the override it should be possible to use both).

_"before the change, the window could not be moved, Now you can by pressing ESC and dragging it (like when playing in desktop mode). This position is persisted"_

I wanted to test that (ESC and dragging, great that it should be possible, I didn't know about that) but unfortunately I ran into a new bug: I tried to get "windowed mode" enabled again(it worked before with an other table), but somehow I'm not able to get it working. In VR settings I have the right eye selected but no matter what I do in the "Video Graphics options"; I'm not able to get it working in Windowed mode, it always goes to Exclusive fullscreen 1440P. 

Hereby a screenshot of what goes wrong:
![videosettingserror](https://github.com/vpinball/vpinball/assets/132104433/61baf887-d57c-4243-b6f8-91d6faea23f0)
I tried multiple times to configure it (also deleted the table ini to start all over again), but it always opens in Exclusive fullsceen 1440P when I start the table. And as you can see both are selected, Window and Exclusive fullscreen. This while I wanted for this table Window selected.

In the table *.ini is this info:
[PlayerVR]
Slope = 6.500000
Orientation = 3.849130
TableX = -18.355196
TableY = 129.848358
TableZ = 118.000000

[Player]
AAFactor = 1.000000
USEAA = 0
Width = 1460
Height = 1946
FullScreen = 0
FXAA = 3

But it somehow gets "ignored". This is with release: VPinballX_GL-10.8.0-1713-a5ff75e-Release-win-x64

**Comment by vbousquet** [comment]
The video (& audio) dialogs should be good now

**Comment by TurboHenk** [comment]
> The video (& audio) dialogs should be good now

Thank you. After deleting the table *.ini's and saving the overrides again, it indeed worked to select Windowed mode(with a custom resolution) and I can move the windows now.

But there's still an issue: _"This position is persisted"_ This isn't the case. I need to move the window again every time that I start the table. Where is this info stored? (the window location of each table on the monitor) I don't see it in the table *.ini's.

**Comment by TurboHenk** [comment]
Update: multiple tables that I set the override for with Windowed mode(with a custom resolution) still launch in exclusive fullscreen mode. So it simply doesn't always work. Hereby an table ini that causes an override that doesn't work:

[Player]
OverrideTableEmissionScale = 0
Width = 1100
Height = 1466
FullScreen = 0
PFReflection = 1

**Comment by vbousquet** [comment]
VR preview can now be set as shrink to fit
Window position is persisted

**Comment by TurboHenk** [comment]
> VR preview can now be set as shrink to fit Window position is persisted

Thank you! The shrinking works great.

**BUT** the biggest bug isn't fixed so please reopen this: 
When I select WINDOWED mode then it still gets exclusive full screen. In all cases so with and without overrides, it simply doesn't work, it always goes to exclusive fullscren. So this setting doesn't "save" anymore since you fixed it visually (a~week ago).

The ONLY way that it works is by editing in notepad the table ini itself manually to:
fullscreen 0 and a custom resolution. But somehow the exe doesn't write it anymore. This while other settings still work normal.

This is tested with the latest release: VPinballX_GL-10.8.0-1746-8b85744-Release-win-x64
