### ISSUE TITLE
POV data not saved in ini file at first try

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#1071]
Hello,

This is the follow up of #1025 which was closed. There are still issues with this in build 1696.

It doesn't work at first try on a table, after editing and saving the POV (osd says the .ini file was saved when pressing the start button), here is a sample content of the .ini file, and of course it doesn't work when reloading the table, POV has not been saved:

[Player]
BallTrailStrength = 0.392157

[TableOverride]
OverrideEmissionScale = 1

And that's it, no POV info.

But if editing/saving the POV a 2nd time on the same table, then the data is properly saved in the .ini and it works:

ViewCabMode = 2
ViewCabScaleX = 1.229881
ViewCabScaleY = 1.059393
ViewCabScaleZ = 0.976499
ViewCabPlayerX = 0.000000
ViewCabPlayerY = -235.431229
ViewCabPlayerZ = 1556.724731
ViewCabLookAt = 22.000019
ViewCabRotation = 0.000000
ViewCabFOV = 48.400028
ViewCabLayback = 39.999920
ViewCabHOfs = 0.000000
ViewCabVOfs = -2.800000
ViewCabWindowTop = 448.500000
ViewCabWindowBot = 103.000000

**Comment by shro2023** [comment]
Thanks @Crrispy thought I was going mad as could not get this to work. Will try with doing twice later and confirm if I get the same as not tried that, mine just never saves POV but expect this is because I have only tried applying once before closing.

**Comment by Crrispy** [comment]
> Thanks @Crrispy thought I was going mad as could not get this to work. Will try with doing twice later and confirm if I get the same as not tried that, mine just never saves POV but expect this is because I have only tried applying once before closing.

I had closed the table in between, I have not yet tried to save twice in a row without exiting.

**Comment by Crrispy** [comment]
It seems to be fixed in 1712 or intermediate version, thanks!

**Comment by shro2023** [comment]
Thanks @Crrispy will try that, updated to 1706 earlier but was still an issue and would not be resolved even after 2 separate attempts. My ini file also looks very different to yours and whilst this does store the correct mode (window) any changes made seem to be completely ignore. Will try 1712 and report back here.


[TableOverride]
OverrideEmissionScale = 1
Difficulty = 56.000000
ViewDTMode = 0
ViewDTScaleX = 1.000000
ViewDTScaleY = 1.000000
ViewDTScaleZ = 1.000000
ViewDTPlayerX = 0.000000
ViewDTPlayerY = 172.000000
ViewDTPlayerZ = -150.000000
ViewDTLookAt = 40.000000
ViewDTRotation = 0.000000
ViewDTFOV = 45.000000
ViewDTLayback = 0.000000
ViewDTHOfs = 0.000000
ViewDTVOfs = 0.000000
ViewDTWindowTop = 370.541931
ViewDTWindowBot = 138.953217
ViewCabMode = 2
ViewCabScaleX = 1.249993
ViewCabScaleY = 0.933500
ViewCabScaleZ = 1.000000
ViewCabPlayerX = 0.000000
ViewCabPlayerY = 180.368149
ViewCabPlayerZ = 1144.124634
ViewCabLookAt = 6.700005
ViewCabRotation = 0.000000
ViewCabFOV = 55.600098
ViewCabLayback = 105.599533
ViewCabHOfs = 0.000000
ViewCabVOfs = 4.519995
ViewCabWindowTop = 221.541931
ViewCabWindowBot = 91.953217
ViewFSSMode = 0
ViewFSSScaleX = 1.000000
ViewFSSScaleY = 1.000000
ViewFSSScaleZ = 1.000000
ViewFSSPlayerX = 0.000000
ViewFSSPlayerY = 0.000000
ViewFSSPlayerZ = 0.000000
ViewFSSLookAt = 25.000000
ViewFSSRotation = 0.000000
ViewFSSFOV = 45.000000
ViewFSSLayback = 0.000000
ViewFSSHOfs = 0.000000
ViewFSSVOfs = 0.000000
ViewFSSWindowTop = 370.541931
ViewFSSWindowBot = 138.953217

[Player]
SSRefl = 0
BallTrailStrength = 0.490196
AlphaRampAccuracy = 2
EmissionScale = 0.120000
SoundVolume = 100
MusicVolume = 100
DynamicDayNight = 0

**Comment by shro2023** [comment]
Nope still not working for me even under 1712. No matter what I do the view configured in the camera mode does not have the settings applied into the ini file correctly and the inbuilt table POV is shown instead.

As an example this is for Lethal Weapon 3 table, I set Table X Scale to 53 and Table YZ to 41 and TableTopZ to 15 and TableBottomZ to 3 using the camera mode. Hit start button to save these to ini file with message that output created then on screen. However, on then loading table again the previous camera view was shown and checking the ini file shows the following settings.

[TableOverride]
OverrideEmissionScale = 1
Difficulty = 56.000000
ViewDTMode = 0
ViewDTScaleX = 1.000000
ViewDTScaleY = 1.000000
ViewDTScaleZ = 1.000000
ViewDTPlayerX = 0.000000
ViewDTPlayerY = 172.000000
ViewDTPlayerZ = -150.000000
ViewDTLookAt = 40.000000
ViewDTRotation = 0.000000
ViewDTFOV = 45.000000
ViewDTLayback = 0.000000
ViewDTHOfs = 0.000000
ViewDTVOfs = 0.000000
ViewDTWindowTop = 370.541931
ViewDTWindowBot = 138.953217
ViewCabMode = 2
**ViewCabScaleX = 1.243493**
**ViewCabScaleY = 0.961001**
ViewCabScaleZ = 1.000000
ViewCabPlayerX = 0.000000
ViewCabPlayerY = 133.490295
ViewCabPlayerZ = 1136.275024
ViewCabLookAt = 6.700005
ViewCabRotation = 0.000000
ViewCabFOV = 55.600098
ViewCabLayback = 105.599533
ViewCabHOfs = 0.000000
ViewCabVOfs = 4.019995
**ViewCabWindowTop = 277.541931**
**ViewCabWindowBot = 55.953217**
ViewFSSMode = 0
ViewFSSScaleX = 1.000000
ViewFSSScaleY = 1.000000
ViewFSSScaleZ = 1.000000
ViewFSSPlayerX = 0.000000
ViewFSSPlayerY = 0.000000
ViewFSSPlayerZ = 0.000000
ViewFSSLookAt = 25.000000
ViewFSSRotation = 0.000000
ViewFSSFOV = 45.000000
ViewFSSLayback = 0.000000
ViewFSSHOfs = 0.000000
ViewFSSVOfs = 0.000000
ViewFSSWindowTop = 370.541931
ViewFSSWindowBot = 138.953217

[Player]
SSRefl = 0
BallTrailStrength = 0.490196
AlphaRampAccuracy = 2
EmissionScale = 0.120000
SoundVolume = 100
MusicVolume = 100
DynamicDayNight = 0

**Comment by shro2023** [comment]
Ok done some more testing as this did not fix it for me but then realised I use anaglyph which others are prob not. Switched off anaglyph and now working. Will raise a new bug.

**Comment by vbousquet** [comment]
Ok I will close this bug then and follow up in the other bug report
https://github.com/vpinball/vpinball/issues/1080
