### ISSUE TITLE
Credit Reels Not Working

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#1086]
**Describe the bug**
Credit reels are not showing any numbers when "coins" are inserted.  Credit reels and LEDs are blank.

**To Reproduce**
Insert coin on almost any table and credit reel/led does not register a number.

**Expected behavior**
Credit reels should register the number of coins that have been inserted.

**Versions & Settings**
 - VPX: 10.8 DX x64 1707
 - Windows 11
 [VPinballX.log](https://github.com/vpinball/vpinball/files/13259796/VPinballX.log)

**Additional context**
This has been going on for a while, and unfortunately, I'm unable to say which build it started.  I'm not sure if it's related to the VPX beta or something on my end.  I apologize that this isn't as helpful as it could be.

**Comment by vbousquet** [comment]
I had a look but everything works perfectly well on my side. I'm not sure I can help without more informations (at least a table that exhibits this)

**Comment by Drybonz** [comment]
Thanks, Vincent.  It might be on my end, but I'm not sure.  It affects many tables but one EM and SS example is Wrd's 2001 and Bord's Centaur.  
https://vpuniverse.com/files/file/13886-2001-gottlieb-1972-loserman-tribute-mod/
https://vpuniverse.com/files/file/12948-centaur-bally-1981/

**Comment by Crrispy** [comment]
For Centaur you have to enable credit display in the dip switches (F6), it's disabled by default. For the EM, no idea.

**Comment by Drybonz** [comment]
Thanks.  I appreciate the information.  I have this on a bunch of tables, those were just two random examples.

**Comment by Drybonz** [comment]
That seems to have done the trick, Vincent... I couldn't find any that weren't working.  Thanks again.
