### ISSUE TITLE
Some objects in Haunted House VR Room become invisible or extremely difficult to see.

### ISSUE THREAD

**Issue by rothbauerw** [vpinball/vpinball#1087]
Testing with build 1731 GL in VR, the object VR_Spider is now invisible. It can be restored by increaing the depth bias value, but this was not needed in Beta 5. In addition, the object VR_Fence004 has become extremely dark, almost black, and cannot be seen very well against the black background. In Beta 5, the colors of the texture were much more obvious. There are other VR_FenceXXX objects where the texture can be seen clearly in 1731, so I'm not sure why VR_Fence004 is so difficult to see compared to the others. 

Here is a link to the table used for testing:

https://drive.google.com/file/d/1siWDbDZyu-eqUZ7pTyQZwSMYV8I1rd17/view

![HHFence1731](https://github.com/vpinball/vpinball/assets/76694094/09b07c2e-3d52-43a9-886c-06076984fd00)
![HHFenceBeta5](https://github.com/vpinball/vpinball/assets/76694094/93eea243-ceba-411d-a6bc-c2e280e42fa9)
![HHSpider1731](https://github.com/vpinball/vpinball/assets/76694094/a8bc9b3a-12d0-484b-b253-bbab1b34a119)
![HHSpiderBeta5](https://github.com/vpinball/vpinball/assets/76694094/9ccb30bb-1c5c-4984-9e12-0f9857854bbf)

**Comment by vbousquet** [comment]
I have fixed this in the latest build. The spider is back:
![image](https://github.com/vpinball/vpinball/assets/2796036/f17f88cb-a442-4995-9a94-8b182001e089)

I will close fo rnow. If you still find issue, please tell me and I will reopen
