### ISSUE TITLE
Potential bug with JP Salas tables?

### ISSUE THREAD

**Issue by pacleary** [vpinball/vpinball#1088]
**Describe the bug**
Both JP's Space Cadet 4.3 and Hellraiser 1.2 (based on JP's Mago of Oz) error out after changing the POV settings, saving the ini, then closing and reopening. I am able to play the tables when resuming after setting the POV. The error only shows after exiting VPX, then reopening. One thing to note: I am running my playfield in portrait, not landscape, so I'm guessing that might be the issue. Hoping someone else who has a portrait playfield can test.

**To Reproduce**
1. Open table
2. Adjust camera
3. Save ini and close VPX
4. Reopen table

Space Cadet
![SC-error](https://github.com/vpinball/vpinball/assets/128317770/c80815db-79c6-4c8d-9ee4-a3bfbe287ba8)
Hellraiser
![HR-error](https://github.com/vpinball/vpinball/assets/128317770/fd0ee432-c406-4de3-8231-c8d177d4c641)

https://www.vpforums.org/index.php?app=downloads&showfile=16091
https://vpuniverse.com/files/file/11755-hellraiser/

**Expected behavior**
Only happens with these two, so it might be the coding of these specific tables.

**Versions & Settings**
 - VPX 10.8 revision 1717
 - Windows 11 Pro
 - AMD 6600XT

[VPinballX.log](https://github.com/vpinball/vpinball/files/13259967/VPinballX.log)

**Comment by Smilelikejoker** [comment]
Woa...  I'm dealing with this error too on the Big Trouble in Little China 1.5 version that was just released.  EXACT same error. 
 However, I do not have the issue on the 1.4 version.  I've checked and nothing was changed between the versions script-wise so I'm kinda playing around T/S'ing. 

I've narrowed it down to when you change the script to use FlexDMD.  I'm trying to find a version of VPX 10.8 DX 64bit that doesn't have the issue.  With it not happening on the 1.4 version with the same change, I'm not sure what is actually happening.

**Comment by Smilelikejoker** [comment]
Troubleshooting update:  Table - https://vpuniverse.com/files/file/11309-big-trouble-in-little-china/
Interesting find.  I don't know if it will be helpful.  I've managed to make the table NOT crash upon the change, but it's not a fix.  

You can make the change to the line and immediately launch the table.  It will run without any issue and FlexDMD takes over like it should.  The issue starts when you save the table.  Once it is saved, it will crash.

**Comment by pacleary** [comment]
Good to know it wasn't just me!

**Comment by michroch** [comment]
Doing it to me also with Albator and Deadpool 1.1 color rush. If I modify anything in properties/visuals and save the table, restart the table and freeze on Starting Game Scripts

**Comment by pacleary** [comment]
> Doing it to me also with Albator and Deadpool 1.1 color rush. If I modify anything in properties/visuals and save the table, restart the table and freeze on Starting Game Scripts
> 
> Versions & Settings
> 
> VPinballX-10.8.0-1722 X64 or X86 Windows Spectre 10 I7 5820K Nvidia GTX 1660 Super 6G

I was thinking this issue might only apply the JP's recently updated tables, but I think Deadpool 1.1 color rush was last updated in March and Albator was in April.

**Comment by toddsay** [comment]
I'm seeing this same error in build 1720, on the `OnePiece` table (after adding a line 60 `UseFlexDMD = True` to enable DMD. Table is https://vpuniverse.com/files/file/16492-one-piece. At first I assumed I had some issue with FlexDMD, but my error matches the others in this issue report.

**Comment by francisdb** [comment]
Are you also saving the table or only the ini?

**Comment by pacleary** [comment]
> Are you also saving the table or only the ini?

I've tried both. Error happens regardless.

**Comment by Smilelikejoker** [comment]
Just tried 10.8 DX x64 rev1725.  Why not give it a shot?  You never know...

- Loaded up my working version 1.5 Big Trouble in Little China table.  
- Went into the script and changed the number of balls on the table from 3 to 5.  I wanted to pick something that wasn't directly related to FlexDMD.  Compiled, ran the table, and it worked correctly. 
- Went back to the Editor and saved the table upon VPX exit.  Restarted VPX and tried to launch the table.  No dice... script error as in the first post.

**Comment by Smilelikejoker** [comment]
Ok...  I narrowed down the revision where the issue starts. @vbousquet 
Working: 
Update to 2.28.5 vpinball#2217 - 10.8 DX x64 rev 1697
https://github.com/vpinball/vpinball/actions/runs/6746634781

Broke:
Render all opaque parts (as of render state) during opaque render - vpinball#2218 - 10.8 DX x64 rev 1702
https://github.com/vpinball/vpinball/actions/runs/6748160753

**Comment by wiesshund** [comment]
You can make this happen even with non JP tables, just the demo table even
Key thing here is
If the image asset lives outside the vpx file, no error
if the image is inside the vpx file, you get the above error

I am guessing that there is perhaps a change to the internal file structure in vpx

Not sure if fix is within VPX or in FlexDMD
@vbousquet

**Comment by michroch** [comment]
> You can make this happen even with non JP tables, just the demo table even Key thing here is If the image asset lives outside the vpx file, no error if the image is inside the vpx file, you get the above error
> 
> I am guessing that there is perhaps a change to the internal file structure in vpx
> 
> Not sure if fix is within VPX or in FlexDMD @vbousquet

Confirming also, it is on every table which have the DMDScene code in it.

**Comment by vbousquet** [comment]
The bug is not in VPX but in FlexDMD. I have just pushed a fix for it, available as a preliminary build on github for the time being: https://github.com/vbousquet/flexdmd/actions/runs/6836823342
