### ISSUE TITLE
User tab in 5able properties panel gone

### ISSUE THREAD

**Issue by unclewilly6988** [vpinball/vpinball#1099]
**Describe the bug**
The user tab in the table properties is no longer there in vpx 1722
I'm looking for the day/night slider
Only place I can find it is the override in video options but seems to have no effect on the table

**To Reproduce*
Open a table in vpx 1722
While table is selected look at properties panel.  No user tab. No day/night slider
Go to video options override with global slider  sill no effect on table

**Comment by vbousquet** [comment]
The user settings have been moved away from the table properties. No feature was removed during the process but the UI is not fully finished for this.

Regarding the day/night slider. It is in the table lighting properties. This is the lighting the table author set up for the table (named scene lighting scale):
![image](https://github.com/vpinball/vpinball/assets/2796036/8eaa12e7-ca6e-4003-a627-897d7cb04094)

If a user wants to override the day/night slider (either globally or for a specific table), he can do so in the video settings:
![image](https://github.com/vpinball/vpinball/assets/2796036/78260faf-dc16-4fd6-83f7-335747ad287d)
