### ISSUE TITLE
VR preview issue when set to disabled

### ISSUE THREAD

**Issue by millertv79** [vpinball/vpinball#1106]
**Describe the bug**
With VR preview disabled, a large black box still opens and fills the entire screen now. Used to just be a small box. There is also bad screen tearing in VR, and it crashes on every table I've tried.

**To Reproduce**
1. Go to  VPX_GL64
2. Click on Any Table
3. Play in VR 

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
A small black box to appear like in previos versions, and it not to introduce screen tearing,

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: 10.8.0 Beta Rev 1731 (e701b01) 64 bits
 - Windows version 11 Home
 - GPU RTX 4060ti
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**
[VPinballXini.zip](https://github.com/vpinball/vpinball/files/13321326/VPinballXini.zip)

**Comment by vbousquet** [comment]
The size of the preview is now decided by the user in the video settings.
Regarding screen tearing, this was a bug and is now fixed

**Comment by millertv79** [comment]
Thank you! Works as expected now.
