### ISSUE TITLE
Refcount triggers when using DEBUG_REFCOUNT_TRIGGER for decals and textboxes

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1117]
**Describe the bug**
Using a build of 3a9cd60ae1138e708185705827cf647fa4078c50 with DEBUG_REFCOUNT_TRIGGER enabled and loading e.g. the full example table, triggers refcount msgboxes for decals and on closing also textboxes.

**Comment by vbousquet** [comment]
I will add the DEBUG_REFCOUNT_TRIGGER to all debug build and have a look (likely due to the rendering refactoring/cleanups)
