### ISSUE TITLE
[Standalone] DMD content not showing on The Getaway

### ISSUE THREAD

**Issue by Nicals** [vpinball/vpinball#1119]
**Describe the bug**
The DMD is not showing on [The Getaway - High Speed II (Williams 1992)_Bigus(MOD) 2.0](https://www.vpforums.org/index.php?app=downloads&showfile=15448&st=20#commentsStart) using standalone version 9d32c198caff7a6743b87f4d6f540b658154b241 (Thu Nov 9 17:08:14 2023 -0500).

**To Reproduce**
1. Get the table with rom
2. Run the game
3. Notice the DMD does not show any informations

**Expected behavior**
I expect the DMD content to be shown in the placeholder

**Screenshots**
DMD content should be shown on the upper left.
![getaway](https://github.com/vpinball/vpinball/assets/2552707/0b6dc034-f9e1-425b-a247-39d92c7b43b7)

**Crash dump**
N/1

**Versions & Settings**
 - VPX: standalone branch, , commit 9d32c198caff7a6743b87f4d6f540b658154b241
 - Debian Linux (Debian GNU/Linux trixie/sid)
 - GPU and video settings if applicable
 - [VPinballX.ini.zip](https://github.com/vpinball/vpinball/files/13325153/VPinballX.ini.zip)
 - Terminal output: [gateway.stdout.log](https://github.com/vpinball/vpinball/files/13325155/gateway.stdout.log)

**Additional context**
The following line from the log are the only one that seems to show an error. I don't know if its related to this issue or another side effect.
```
2023-11-11 11:09:00.712 ERROR [1359797] [external_log_error@718] MessageBox(): caption=Visual Pinball Error, text=Failed to create the synchronization device.
Synchronization switched to adaptive sync.
2023-11-11 11:09:00.712 ERROR [1359797] [RenderDevice::CreateDevice@1158] Failed to create the synchronization device for frame pacing. Synchronization switched to adaptive sync.
```

**Comment by francisdb** [comment]
Have you tried this?

1. extract the sidecar script next to the table using eg `./VPinballX_GL -extractvbs "Godzilla (Sega 1998) VPW v1.0.vpx"`
2. just before the `LoadVPM` call in the script ad the following

```vbs
UseVPMDMD = true
' or UseVPMColoredDMD = true

Sub ImplicitDMD_Init
   Me.x = 30
   Me.y = 30
   Me.width = 128 * 2
   Me.height = 32 * 2
   Me.fontColor = RGB(255, 255, 255)
   Me.visible = true
   Me.intensityScale = 1.5
End Sub
```

The  `synchronization device` device error is because vpinball defaults to `Frame pacing` which is not available on mac/linux. You can get rid of the wrning by setting `SyncMode = 0` (No sync) in ~/.vpinball/VPinballX.ini

**Comment by jsm174** [comment]
Unfortunately this is not a bug. Not all tables render their DMD inside the table. 

For more information on the why and workaround, please refer to:

https://github.com/vpinball/vpinball/tree/standalone/standalone#my-game-is-not-displaying-a-dmd

(Basically exactly what @francisdb mentioned above)
