### ISSUE TITLE
Rendering issue with build 1746

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#1125]
**Describe the bug**

Several tables render with a black playfield and wrong elements. Example https://www.vpforums.org/index.php?app=downloads&showfile=15357  but others too

**Reverting to 1737 solves the issue.**

Load the table in DX version x64 build 1746. See picture:

![1746 issue](https://github.com/vpinball/vpinball/assets/28100190/028915b6-60af-4d59-8a17-1d8d6eaf2f2a)

**Versions & Settings**
 - VPX: 10.8 x64 build 1746
 - Windows 11 November update
 - RTX 4070Ti, latest Nvidia driver

**Comment by Crrispy** [comment]
Still there in 1751, reverted to 1737 again

**Comment by Crrispy** [comment]
I made more tests and 1740 has the issue, too. As usual, just replacing the files with 1737 build solves the issue. So it happened exactly between 1737 and 1740.

**Comment by Drybonz** [comment]
The action for 1737 was "rendering cleanup", so that makes sense.  I'm guessing Vincent probably already knows what happened though.

**Comment by Loadedweapon** [comment]
Yes I can Confirm this also..

**Comment by Smilelikejoker** [comment]
Can you guys link any more tables where you have this issue?  I tried wanted to see if I had the issue on the Shrek table linked by the op.  I did not.  It loaded perfectly fine.  We have to have something different in our setup...
VPX 10.8 DX x64 rev 1748
Win 11 Pro
NVidia 3080TI driver 546.01 (30 Oct)

SIDENOTE:  Getting ready to update to rev 1758.  Will edit with result.

**Comment by Loadedweapon** [comment]
Try 48hrs

**Comment by Drybonz** [comment]
Tonight I had this happen on a table.  It happened after I set the Ambient Occlusion setting to static.  Then, if I switched it back to dynamic it rendered normally.  Only tested on one table so far.

**Comment by Smilelikejoker** [comment]
I can't find any table called 48hrs (searched 48hrs, 48 hrs, forty eight, etc..).

@Drybonz YAHTZEE!!  I just changed Ambient Occlusion setting to 'Static' and tested the op's linked game of Shrek.  Problem appeared.  I switched back to 'Dynamic' and the issue was fixed also.  

So...
- Something is wrong with Ambient Occlusion while set to 'Static' on select tables.
- Changing to 'Dynamic' is the temp work-around.

**Comment by Drybonz** [comment]
Thanks, Vincent.   :)

**Comment by Loadedweapon** [comment]
Sorry 48hrs is how much sleep I need lol. Ment 24... but it's fixed now
thanks

**Comment by Crrispy** [comment]
I confirm it's fixed in 1760, thanks Vincent!
