### ISSUE TITLE
Day/Night Override value is bugged in POV settings

### ISSUE THREAD

**Issue by droscoe** [vpinball/vpinball#1135]
**Describe the bug**
Using the latest build, I loaded CFTBL and set POV.  I then went to the options page where you can adjust Day/Night override value.  Using the flippers, I raised up to about 200% to check that the POV correctly set the corners.  I then pressed the plunger key to revert to default.  The Day/Night override suddenly jumped to 400,000,000%

To confirm its not specific to the table, I tried with Doctor Who as well, with the same behavior, though this time it was 800,000,000%

**To Reproduce**
Load a table
Bring up the pause menu
Select Adjust Camera Angle
Set WINDOW POV mode
Navigate to Day/Night override page
Adjust value
Press Plunger button

**Comment by jsm174** [comment]
I can confirm as I've seen this too for a while now. (Sorry for not reporting earlier.)
