### ISSUE TITLE
New 'Filmic' TM mode features no table reflections

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1138]
**Describe the bug**
Using latest build 424fd6716b27ae19663bb5984e1deb4876c49415 Filmic TM mode seems to be miswired somewhere to not enable reflections (only tested 'Static and Unsynced Dynamic).

**Comment by droscoe** [comment]
> **Describe the bug** Using latest build [424fd67](https://github.com/vpinball/vpinball/commit/424fd6716b27ae19663bb5984e1deb4876c49415) Filmic TM mode seems to be miswired somewhere to not enable reflections (only tested 'Static and Unsynced Dynamic).

What is "Filmic TM"?

**Comment by francisdb** [comment]
https://github.com/vpinball/vpinball/blob/85117e3956d81a1a75da5fc1d574156255c83975/txt/Changelog.txt#L190-L193
