### ISSUE TITLE
cannot enter Sound Command Mode

### ISSUE THREAD

**Issue by linojon** [vpinball/vpinball#1139]
**Describe the bug**
Some roms do not let me enter Sound Command Mode. I'm trying to save wave files for an altsound. Tried acd_170, acd_170h, acd_160 roms. Works ok with other tables' roms. If this is expected for this specific table, can you explain why? or is there a workaround? Thanks

**To Reproduce**
Open rom in pinmame32 (using v3.6-573-5d6459d and also tried older ones)
Double click the rom
Press any key
Press F4 to enter Sound Command Mode, nothing happens
Press DEL to enter Manual Mode, nothing happens

**Comment by toxieainc** [comment]
Unless i remember it wrong (too much information overload at the moment ;)), the Stern SAM (+SPIKE1/2) platform does not feature sound files/commands like previous generations anymore, but just mixes all sound/music internally.
Thus one needs to replace sounds within the ROM itself instead, e.g. via https://pinside.com/pinball/forum/topic/acdc-display-and-modify-dot-matrix-images .

**Comment by linojon** [comment]
hi, quick followup question. I now can see the sounds. And i've uploaded a new audio for several of them, saved the rom and it runs in vpx. Yaay. Question is this really the process for these roms or can i use altsound still?

Likewise, if i'm aiming to have an altcolor to replace the dmd display, do i replace that in the rom too or is there a way to still use altcolor (e.g. serum)?

thanks :)
