### ISSUE TITLE
DOF contactors work fine in vpx 10.7.3 but not with 10.8 for most non ROM based tables 

### ISSUE THREAD

**Issue by Jeanpierrepinball** [vpinball/vpinball#1143]
bug description :
 I've realized that the flipper contactors on my pincab no longer were activated on a few tables - only specific (not all) 'original' tables without ROMs, with VPX 10.8.0 beta 5. Some other DOF toys (eg: shaker) worked ok though. When switching to vpx 10.7.3 final I realized that this specific version had "disable b2s" ticked in the settings, whereas it was unticked on my 10.8.0. After enabling b2s in 10.7.3, the contactors work fine on the tables I mention below but they still don't work with 10.8.0, except for "BLOOD MACHINES"

**To Reproduce**
1. Launch VPX 10.8.0 beta 5 (either the GL version or the regular version, either x86 or x64, same behaviour)
2. Open one of these tables :  Batman 66,  Deadpool, Stranger Things LE, Guardians of the Galaxy, Big trouble in little china,
4. Press flippers, notice that the contactors/solenoids are not activated
 
Note : Some original tables work fine : Blood Machines, Spongebob, Iron Maiden LOTB, Goonies
 
**Expected behavior**
The contactor sounds should be heard when pressing the flippers, and it works with VPX10.7.3

**Versions & Settings**
 - VPX: 10.8.0 beta 5 rev 1347 3d585e7  version x86 or x64. Seems it's also an issue with previous versions more recent than 10.7.3
 - Windows 10
 
[vpinball.log](https://github.com/vpinball/vpinball/files/13370613/vpinball.log)
[VPinballX.zip](https://github.com/vpinball/vpinball/files/13370609/VPinballX.zip)

Happy to give more details and help troubleshoot the issue ! Others have reported it but it's not easy to detect/pinpoint.

**Comment by Karl030167** [comment]
no global error - for me all these tables are working with all dof toys. Version x86 1769. 
If you can open an issue, then i expect you can download the latest version from actions... yours is way old

**Comment by Jeanpierrepinball** [comment]
I understand it may not affect everyone, but I've seen a few other people pulling their hair with this issue.  
The problem remains the same with version x86 1769 and several other recent versions I had pulled from GitHub (no flipper contactors when you open most non ROM tables, but not all of them) . 
10.8.0 beta 1 (version 1138) does work so it seems something changed after that.
Again, I'm more than happy to try things and provide more details as needed.

**Comment by Jeanpierrepinball** [comment]
Adding 2 notes :
- I'm not sure what happened but I retried with 10.8.0 beta 1 (v 1138) and DOF is not working on the original tables I mentioned with this version, contrarily to what I wrote above. It does work on 10.7.3 though
- could the issue be related to this one ? I tried launching an EM table and had exactly the same symptoms, DOF works in 10.7.3 but not 10.8 
[https://github.com/vpinball/vpinball/issues/1252](https://github.com/vpinball/vpinball/issues/1252)

**Comment by vbousquet** [comment]
Yes the issue looks related and likely originate in a wrong configuration file. You may apply the same test I advised: "could you delete your VPinballX.ini (from %AppData%/VpinballX), do your configuration in the UI (don't forget to press save, you may check in the new VPinballX.ini that will be create dthat the ocnfiguration suits you) and check what is happening then ?"

 @Jeanpierrepinball Can you check and tell me if I can close this ?

**Comment by Jeanpierrepinball** [comment]
Hi @vbousquet , thanks for getting back to us on this.
I can't test your proposal unfortunately as I managed to solve the issue by "brute force", going into regedit to modify some values. 
It was certainly a consequence of upgrading everything to 64bit and registering directoutputcomobject from the directoutput_x64 folder on top of the x86 version. 
My understanding is that depending on how the "controller" script of a table is written, VPX might have been fetching dof settings from registry keys of old VPX versions and ignoring the software settings. 

What fixed the issue for me : looking for DirectOutputComObject.dll in regedit + correcting all folder locations to C:\DirectOutput-x86\   +  changing the value of the "DirectOutputComObject.dll " version to have the same version everywhere (I had 3.1.7698.40088 and 3.1.8440.34790)

Thanks for your hard work !

**Comment by vbousquet** [comment]
After checking again, as said in the duplicate, this is most likely an invalid user setup (likely due to using previous beta). Without further feedback, I will close for now
