### ISSUE TITLE
Don't save pov

### ISSUE THREAD

**Issue by Pinbalbilly** [vpinball/vpinball#1148]
**Describe the bug**
Don't save pov in VP 10.8. 1779

**To Reproduce**

Hello, from version 10.8 1770 ( this one does save)  onwards the ini/POV are not saved in window mode.  If you have doubts, I'll add more information, just launch a table in POV window mode, save, exit, re-enter and the POV will not have changed.

**Versions & Settings**
 - VPX: 10.8.0 GL 1779 (7123832), 64
 - Windows version 10

**Additional context**
Thanks

**Comment by dacstyle** [comment]
same problem

**Comment by Drybonz** [comment]
It looks like you have to manually press "start" 1 to save the settings.  Not sure if this is intended, but the auto save would be welcome.

**Comment by dacstyle** [comment]
I did press start as always, the .ini file was not created.

**Comment by studlygoorite** [comment]
Same, pressing start is not saving a table POV/ini

**Comment by droscoe** [comment]
Can confirm that its not limited to Window mode.

**Comment by jreiman** [comment]
Confirming the issue as well that when pressing the "start" key to export POV file, the export message does display, but the ini file is not being exported / updated.  I am running the 1779 build 64 bit non-GL version.  Windows 11.
