### ISSUE TITLE
Environment Emission not stored in pov file

### ISSUE THREAD

**Issue by toccata10** [vpinball/vpinball#1149]
**Describe the bug**
I can change the Environment Emission in the "Adjust Camera" menu. When I save the pov by pressing "1", it's not stored. Next time, I launch the table, it's back to table's default.

**To Reproduce**
1. Go to 'Adjust Camera'
2. Change "Environment Emission"
3. Save the save.
4. The settings is not stored in .pov file

**Versions & Settings**
 - VPX: vpx-standalone batocera rev39 beta, Visual Pinball X 10.8.0 beta 5
 - Windows version: 10 and linux

**Additional context**
This setting is very useful to brighten/darken tables. I can't see it stored in neither .pov files (which would be the best), neither in .ini files. I'm wondering why it's the (only ?) editable setting in "Adjust Camera" that doesn't stick.

**Comment by mbp2728** [comment]
I´m facing this issue. As workaround I change the lightning settings directly in the table properties and save the VPX file.

**Comment by toccata10** [comment]
@mbp2728 : glad I'm not alone facing this problem. As a workaround, I think I can do this in the .ini file, but it's not the same as changing the "Environment Emission"
```
[Player]
OverrideTableEmissionScale = 1
EmissionScale = 0.3
```

**Comment by francisdb** [comment]
I don't think this is a specific standalone issue as the description mentions `Windows version: 10 and linux`

**Comment by mbp2728** [comment]
> @mbp2728, @toccata10
> 
> what versions are you using? there should be no diffs between master and standalone. (ie we don't do anything in standalone to change how this would work)

Hi, 10.8.5

**Comment by jsm174** [comment]
Please try again with the latest from the CI.

**Comment by vbousquet** [comment]
Just checked on latest master and it does exactly as intended, that is to say export and ini with 
```
OverrideTableEmissionScale = 1
EmissionScale = 0.210000
```
in it. I will close for now. Just tell if it's not working for you
