### ISSUE TITLE
Latest DX Build not saving POV

### ISSUE THREAD

**Issue by droscoe** [vpinball/vpinball#1151]
**Describe the bug**
Running the latest DX build of VPX on desktop, I went into Adjust Camera Mode, set my POV and pressed start game.  The screen indicated that the POV was exported to a table-specific .ini file with the correct path and name, but when I reload the game, its back to default POV.  Looking at the table directory, the .ini file isn't there.

I do not know if this is specific to desktop or a general issue.  I have not tried it on my cab.  I also do not know if this is limited to the DX build as I have not tried the GL

**To Reproduce**
1. Load a game with latest DX build on desktop
2. Adjust POV and export
3. Inspect table folder

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
Expectation is for a .ini file to be created with the table name, in the correct directory

**Comment by michroch** [comment]
Same for GL

**Comment by Crrispy** [comment]
Hello, I think it's a duplicate of #1148

**Comment by droscoe** [comment]
> Hello, I think it's a duplicate of #1148

Yes, you are correct.  Will close this one
