### ISSUE TITLE
Vertical offset - the response speed in changing the value is very slow

### ISSUE THREAD

**Issue by eliory** [vpinball/vpinball#1157]
Hello dear developers,

Is it possible to improve the speed of the change to the value of Vertical offset please in the next updates as it was before?

As someone who changes the POV a lot in order to take advantage of all the amazing capabilities of this feature, sometimes I have to change this value quite a bit and it can take several minutes until I reach the desired value.

The speed of the change so far has been great, please bring it back.

Thanks in advance
Elior

**Comment by vbousquet** [comment]
The fix does not restore the prvious behavior but instead allow to adjust speed based on length of press (the longer the faster)
