### ISSUE TITLE
Anaglyph glasses calibration for Magenta/Green switches to Red/Cyan after calibration completed

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#1161]
**Describe the bug**
In live view, when adjusting the anaglyph glasses calibration for Magenta/Green, the label at bottom of window (just above "Calibrate Glasses") switches to Red/Cyan after calibration completed. I am attempting to use the Magenta/Green option to further calibrate Trioviz glasses.

**To Reproduce**
1. Open a table and play.
2. Q Menu, select Live View
3. Select Video Options
4. Press "Calibrate Glasses" and adjust anaglyph calibration for Magenta/Green (faces calibration)
5. Note that after completing the calibration the title next to the two colour squares switches to Red/Cyan and the separation colours also seem to be red/cyan and incorrect for glasses.

**Expected behavior**
Title and colours should remain within the Magenta/Green range.

**Screenshots**
![calibration_bug](https://github.com/vpinball/vpinball/assets/95056536/21671e73-d16d-43f4-98c5-5b3ff9afa9e7)

**Versions & Settings**
 - VPX: [10.8.0 Beta Revision 1726 (3c066b0), 32 bit DirectX9.
 - Windows version 10
 - GPU HD 4000

**Comment by vbousquet** [comment]
This is normal as colors are deduced from calibration. You need to redo your calibration or reset to defaults
