### ISSUE TITLE
In Legacy adjust camera mode, X,Y and Z are selected together for scaling

### ISSUE THREAD

**Issue by 7heS4ge** [vpinball/vpinball#1165]
On version 10.8 beta6 : in Legacy adjust camera mode, X,Y and Z are selected together for scaling : only X and Y must be selected.

![image](https://github.com/vpinball/vpinball/assets/15269042/c7169145-05ea-4c5e-9e8d-58f72a523f24)

**Comment by vbousquet** [comment]
That's expected, just select the next option and you'll be good

**Comment by 7heS4ge** [comment]
Legacy is the view by default, I don't understand why I must choose another view. If X,Y and Z move together, we can't change anything : the table stay in the same location.
With 10.8 a 'Window' view has appeared, but I don't understand what it is. Is there a tutorial that explains ? All my tables installed in my cabinet have a 'Legacy' view by default.

**Comment by 7heS4ge** [comment]
> That's expected, just select the next option and you'll be good

Legacy is the view by default, I don't understand why I must choose another view. If X,Y and Z move together, we can't change anything : the table stay in the same location.
With 10.8 a 'Window' view has appeared, but I don't understand what it is. Is there a tutorial that explains ? All my tables installed in my cabinet have a 'Legacy' view by default.
