### ISSUE TITLE
Default table view is wrong when cabinet playfield is in portrait mode

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1172]
**Describe the bug**

on 10.8 beta 6

1. Set your first monitor to portrait mode in windows
2. Set up vpinball to cabinet mode and use below settings (same with fullscreen)
4. Start any table that has no custom pov/ini yet.
5. Table will be shown horizontally Like in screenshot

![image](https://github.com/vpinball/vpinball/assets/161305/fb3470c8-9c81-4775-9406-b538168d6817)

![image](https://github.com/vpinball/vpinball/assets/161305/770c1efb-7c52-45ff-a741-013e8e730ef1)

![image](https://github.com/vpinball/vpinball/assets/161305/5cde0e87-d223-47b6-9a72-a8e049e86d38)

Going to POV setup and clicking enter rotates the table correctly.

**Comment by vbousquet** [comment]
Not sure what is wrong here. Made a few tests and everything worked like in 10.7. So, is it a standalone only bug ? Did I miss something ?

**Comment by francisdb** [comment]
The same thing happens on my windows cab that has the playfield monitor in portrait mode. So it is by design that the table is rendered horizontally like in the screenshot?

**Comment by vbousquet** [comment]
I don't know, there are too many information missing. I don't know what you are doing, with which settings, which POV mode,...

**Comment by francisdb** [comment]
More info added in description

**Comment by vbousquet** [comment]
Not sure where is the bug here. I think it has always been like that since POV used to depend on OS settings. Most tables have a POV for landscape so if you run in portrait it is turned.

Note that in fact, 10.8 solves this by introducing the window mode for cabs which handles this automatically

**Comment by francisdb** [comment]
> Note that in fact, 10.8 solves this by introducing the window mode for cabs which handles this automatically

Do you mean that tables that are saved with 10.8 for cab window mode should appear correctly?

**Comment by vbousquet** [comment]
Window mode is always oriented along longest side of screen, so it will be good whatever the screen orientation is
