### ISSUE TITLE
No more LUT feedback display on 10.8 beta 6.

### ISSUE THREAD

**Issue by Dicentim974** [vpinball/vpinball#1173]
**Describe the bug**
When pressing the magna save keys the LUT is changing but there's no display anymore on the playfield to indicate which LUT is selected 

Thanks.

**Comment by Drybonz** [comment]
I'm wondering if the same problem that was preventing sprites from rendering on top might also have affected extDMD (Freezy)?  It looks like Freezy's DMD is no longer displaying on top like it used to.
