### ISSUE TITLE
Dots appear on ball when perf graph is visible

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1180]
VPinballX_GL-10.8.0-1798-9b3f362-Release-win-x64 
https://vpuniverse.com/files/file/16321-spongebobs-bikini-bottom-pinball-vpw/

press F11 twice and the ball gets white dots

![image](https://github.com/vpinball/vpinball/assets/161305/88f68e45-63c8-4e0b-89d1-6b155ff919b9)

**Comment by vbousquet** [comment]
This is the expected behavior (and was already what happened before)

**Comment by francisdb** [comment]
What's the purpose of these dots?

**Comment by toxieainc** [comment]
To better see the ball spin.
