### ISSUE TITLE
VPW Monster Bash no longer works in beta 6 

### ISSUE THREAD

**Issue by fink1982** [vpinball/vpinball#1186]
Hi,

I'm using VPW 1.0  version of Mosterbash on the GL version of VP Beta 6,  although I've tried it on the DX version too, and the ball makes the sound that its in the shoot,.but it cant be seen and it doesn't fire? I rolled VP back to Beta 5 and it works perfectly? Any ideas? 

Keep up the great work 😎👊

**Comment by Pinbalbilly** [comment]
Hello, try deleting the pov and making a new one.

**Comment by fink1982** [comment]
Hi, I'll give it a go, Thank you 👍

**Comment by studlygoorite** [comment]
Or maybe try deleting your VPinballX.ini, I just played the table with both VPX and GL beta and latest release v1804.
