### ISSUE TITLE
Standalone Android: Handling only by touchscreen

### ISSUE THREAD

**Issue by Wesie** [vpinball/vpinball#1193]
I've try to play a table on my tablet (Beta). 
After install the apk and load a table on the tablet, the table was loaded, but I couldn't start because:
How could I insert a coin? Select (maybe) one or to Player?

In the apk Android version, I would be nice, if the needed keys are available on the touchscreen. On the tablet there is no further input device connected

**Comment by gjupp** [comment]
The screen is divided into hidden touch areas, you can turn on a grid to show you where these areas are. Insert coin is by pressing top left of screen area. I think top right is menu. Bottom left is start game, bottom right is shoot, Slightly up from the bottom at left and right is flipper control.

**Comment by Wesie** [comment]
Thank for clarification,  Ill try it

**Comment by jsm174** [comment]
@Wesie - I just tested iOS and Android with touch controls, no issues.

Closing this issue.
