### ISSUE TITLE
VPX 10.8.6 1786 no longer saves .POV files

### ISSUE THREAD

**Issue by mbp2728** [vpinball/vpinball#1195]
**Describe the bug**
VPX 10.8.6 no longer saves .POV. It saves only .INI files. I´m configuring the tables in "Window" mode

**To Reproduce**
1. Select 'File' menu
2. Click on 'Export'->'POV'
3. The file saved has .INI extension and not .POV extension

The issue happens for any table.

**Expected behavior**
1. Select 'File' menu
2. Click on 'Export'->'POV'
3. It should save a .POV extension file

My entire system relies on POV files. I have more than 400 tables with POV files.

**Screenshots**

**Crash dump**
N/A

**Versions & Settings**
 - VPX: 10.8.6 build 1786
 - Windows version 10
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file
 - See attached the log file. As you can see, in version 10.8.5 the function PinTable::ExportBackdropPOV, creates a POV extension file. In version 10.8.6, it creates a .INI extension file
* Version 10.8.5
2023-11-20 13:00:20.521 INFO  [5888] [PinTable::ExportBackdropPOV@6198] View setup exported to 'C:\Visual Pinball\Tables\Big House (Gottlieb 1989) 3D.pov'
2023-11-20 13:10:50.978 INFO  [5888] [PinTable::ExportBackdropPOV@6198] View setup exported to 'C:\Visual Pinball\Tables\Big Shot (Gottlieb 1974) 3D.pov'
* Version 10.8.6
2023-11-25 10:06:06.978 INFO  [4212] [PinTable::ExportBackdropPOV@6218] View setup exported to 'C:\Visual Pinball\Tables\Monday Night Football (Data East 1989) 3D.ini'
[vpinball.zip](https://github.com/vpinball/vpinball/files/13464260/vpinball.zip)
[VPinballX.zip](https://github.com/vpinball/vpinball/files/13464261/VPinballX.zip)

**Comment by Pinbalbilly** [comment]
This is not a bug, the POV system changed with the latest 10.8 versions, it is saved as an .ini file.

**Comment by Crrispy** [comment]
It's a feature, not a bug.
