### ISSUE TITLE
10.8.1: Build 1826 - playfield remains displayed when exiting to editor

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#1201]
**Describe the bug**

About everything is in the title. Build 1826 DX x64, 3 screens cab setup. When pressing esc then clicking "exit to editor" , VPX does not complete the exit to editor, the playfield remains on top of the desktop and you're pretty much stuck there. CTRL-esc works to open the start menu and the taskbar appears, but even right-clicking on the VPX icon in the systray and choosing "Close window" has no effect. I did this several times and ended up each time choosing "sign out" in the start menu to force VPX to close and get back control after relogging in.
This was with the VPW Spongebob table, I didn't try others yet.

I reverted to build 1798 (due to #1197) and the problem does not occur at all.

**Comment by vbousquet** [comment]
Note that this is a very preliminary first commit on the 10.8.1 branch.

**Comment by vbousquet** [comment]
Close as duplicate
