### ISSUE TITLE
Improve Tournament Mode

### ISSUE THREAD

**Issue by syd711** [vpinball/vpinball#1206]
I tested the latest release with the new tournament mode and thought about an integration/tooling inside my VPin Studio for it.
After some discussions on the VPC/VPX channel on Discord, this is how I understood the tournament works:

- An administrator selects a table, sets the UseVPMDMD in the script, locks it and shares it with other players.
- The tournament starts and player can achieve new highscores.
- If an highscore was achieved, the user has to press ESC/enter pause menu and exports the encrypted highscore text file.
- The players sends the text file to the admin who can generate a PNG from it via e.g.
  _**"VPinballX.exe -TournamentFile "Tables\Attack from Mars 2.0.1.vpx" "Tables\Attack from Mars 2.0.1.vpx.txt""**_
  ...which than can be posted on somewhere, e.g.

When thinking about an integration I came up with the following questions/suggestions:
- Does the player have to export the highscore right after the game or at any time? Can the textfile generation triggered via key binding or via command line? This way it could easily be triggered from any other tool and the player can just press one button instead of entering the pause menu.
- Can the text file export and png generation be executed headless? I noticed that the whole UI is started for the png export.
- Can the _UseVPMDMD_ flag somehow be set without modifying the script? I was thinking about a command line option here too which also includes the locking of the table. It would be nice a the process for starting a tournament could be triggered automatically. Customizing scripts and locking the table does block that.

**Comment by toxieainc** [comment]
>     * Does the player have to export the highscore right after the game or at any time? Can the textfile generation triggered via key binding or via command line? This way it could easily be triggered from any other tool and the player can just press one button instead of entering the pause menu.

It would have to be a special key then. I'll look into it.

>     * Can the text file export and png generation be executed headless? I noticed that the whole UI is started for the png export.

In principle yes, but the way the pipeline works (codepath is shared with exporting scripts, etc) at the moment, no.
But it also closes itself again after export, so.. ..
It could be run minimized.

>     * Can the _UseVPMDMD_ flag somehow be set without modifying the script? I was thinking about a command line option here too which also includes the locking of the table. It would be nice a the process for starting a tournament could be triggered automatically. Customizing scripts and locking the table does block that.

No, this is not possible, as to VPX the script is more or less a blackbox. But in general i guess somebody will review the table and its settings anyway, so is this really an issue in practice?

**Comment by syd711** [comment]
> No, this is not possible, as to VPX the script is more or less a blackbox. But in general i guess somebody will review the table and its settings anyway, so is this really an issue in practice?

I think we will see. This was just an usability suggestion. I've never heard of that flag and adding something to a table script is something different than changing an existing flag. When setting up a table I'm usually happy when I don't have to deal with anything script related.

**Comment by syd711** [comment]
Let's ignore the other points here. But the export key binding would be nice.

**Comment by toxieainc** [comment]
Unfortunately this is part of the process to be able to grab the DMD for verification.

I guess that over time, table authors will just setup their tables accordingly anyway. In the past, this explicit VPM<->VPX DMD connection was suggested to only be made if running in desktop mode (as only then the DMD -> screen output was usually done via VPX rendering), to save a bit of processing time.
Now, >5 years later, this tiny bit of processing overhead does not really matter anymore anyway, given how much more complex the majority of tables have gotten, so authors could just enable it all the time.

**Comment by toxieainc** [comment]
Keeping the Lockbar-key pressed and then pressing the Start-key now also triggers the export.
Also VPX will run minimized when converting the file to .png.

So closing for now.
