### ISSUE TITLE
VPinballX.ini / POV not loading when tables load

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1212]
VPinballX.ini is not setting POV defaults for tables.
Others on the forums have reported having the same problem

1. When using VPX menu to 'export POV', it only exports INI
2. When converting that into VPinballX.ini (in app root folder) it is not loading with tables that have Legacy settings.

**To Reproduce**
1. export INI for table using 'Windows' POV settings
3. copy those settings into VPinball.INI
4. run any table with Legacy POV settings
5. press F6 and see the POV is not loading from the INI, still using Legacy settings

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
need a way to 'auto load' a default POV for tables that do not have specific POV or INI

**Versions & Settings**
 - VPX: 10.6 & 10.7 beta
 - Windows 11

**Comment by francisdb** [comment]
https://github.com/vpinball/vpinball/blob/39824d6a80936ed52ad0a840862c729e60695f2e/txt/Changelog.txt#L110-L114

Your default settings can be added in `VPinballX.ini`

https://github.com/vpinball/vpinball/blob/a42292b4b3c942a173a084d5b940e846a42c230c/src/assets/Default%20VPinballX.ini#L255-L308

**Comment by francisdb** [comment]
If you have a mix of ini and pov it might be a mess
See also https://github.com/vpinball/vpinball/issues/1081

**Comment by Ltek** [comment]
I have no (zero) POV files

**Comment by vbousquet** [comment]
Just checked and the ini is working as intended.

It loads from main app ini, and table ini (same name), the later taking precedence other the former. So, I will close for now. If you still have problems with this, you may share on VPF to get some help
