### ISSUE TITLE
Since version 1689, 3D depth has no separation between things (flat)

### ISSUE THREAD

**Issue by strangeleo7** [vpinball/vpinball#1213]
**Describe the bug**
Since version 1689, 3D depth has no separation between things (flat)

I tried many versions, I went down until I found the one that creates a realistic environment with separation between the levels. THE best 1689, from then on they all appear deep but FLAT!

**To Reproduce**
1.Last version Tested 1826
2.3D dont look deep

Try at VPW Last Action Hero or Batman DE

**Expected behavior**
I would like the 3D behavior to return to the versions where it looked incredible

**Versions & Settings**
 - VPX: 108 1689 
 - Windows version 10
 - Ryzen 5 / 3070

THANKS FOR ADVANCE and I want to thank those involved from here for their titanic work. We enjoy all the progress day by day.

**Comment by dacstyle** [comment]
I did test this and had the same result, 3D looks better on 1826.

Maybe there are some settings to change?

**Comment by strangeleo7** [comment]
Voy a probar la gl entonces

**Comment by gjupp** [comment]
It may be a different issue, but I did discover several months ago that the 3D becomes flat if the inclination in the POV setting is set to zero. See this closed bug https://github.com/vpinball/vpinball/issues/442

**Comment by vbousquet** [comment]
Just tested and separation is still there but if you are using the DX version or 'fake stereo', you will have to adjust your setting (and likely for each table). It will work (just tested it  and saw others having succes with it) but it is tedious. I would suggest to go for the OpenGL version using true stereo
