### ISSUE TITLE
Playfield transparency not always working

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1215]
**Describe the bug**
Playfield stays transparent, even though a black wall is under it.

**To Reproduce**
Put a wall over the whole table, material e.g. Plastic Black. Playfield material "Playfield" with transparency.

**Expected behavior**
I would like to not see the backdrop through the playfield.

**Screenshots**
See through playfield.
![2023-11-30 12_18_41-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/9be4c3d5-bc1a-4151-acf1-4679e3ab540e)
View from below.
![2023-11-30 12_19_19-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/0567a601-262c-4211-b98f-86ba496007fb)
See through playfield.
![2023-11-30 12_05_11-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/cbb9823a-486f-46f9-b1a2-f45a304e6712)
Black wall seen from below.
![2023-11-30 12_05_30-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/c6d550ff-a6fe-40e4-be07-470b65c75974)

**Versions & Settings**
 - VPX: v10.8.0 Beta (Rev. 1807 (39824d6), windows DirectX 64bit)
 - Windows version 11
 - GPU and video settings: GForce 3070TI

**Comment by vbousquet** [comment]
This is not a bug but the intended behavior. Playfield is rendered before everything else unless using a dedicated primitive, and adjusting depth bias accordingly
