### ISSUE TITLE
Standalone: altsound support

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1217]
**Is your feature request related to a problem? Please describe.**
As far as I know altsound/g-sound is currently not supported

Guess it would be best to start with `g-sound/altsound 2.0` as that is the new format

https://vpinhub.com/altsound2

**Comment by jsm174** [comment]
- altsound support is now in `standalone` and `10.8.1` branches in the `vpinball` repo
- `altsound.log` will get written to the pref path, ex. `$HOME/.vpinball/`
- the repo for `libaltsound` is temporarily at: https://github.com/jsm174/libaltsound
- hoping @toxieainc and @mrgrynch can review and figure out if we can do anything with this or just leave it for standalone.

**Comment by vbousquet** [comment]
This is very nice and add more interest to designing a global module/plugin system that would allow to move away from COM and the B2S/plugin hacky arch. I'm quite low on free time lately but definitely something to be looked more thoroughly
