### ISSUE TITLE
VR/pre-alpha 10.8.1: VPX crashes in a variety of situations

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1223]
**Describe the bug**
VPX can run any table. "Creating live table" and the application quits.

**Comment by francisdb** [comment]
What was the fix?

**Comment by tweety231323** [comment]
[vpinball.log](https://github.com/vpinball/vpinball/files/13537103/vpinball.log)
[crash.txt](https://github.com/vpinball/vpinball/files/13537105/crash.txt)
crash.dmp (zipped) is too big to upload. Do you need it? Let me know...
[VPinballXini.txt](https://github.com/vpinball/vpinball/files/13537108/VPinballXini.txt)

**Comment by Crrispy** [comment]
I can confirm the same beahviour here. It works fine in 1828, but any recent 10.8.1 build and it crashes to desktop when starting a table at the "Creating live table" step right after you press F5.

**Comment by toxieainc** [comment]
@tweety231323 @Crrispy Can you please try a new 10.8.1 beta build? Should be fixed.

**Comment by tweety231323** [comment]
I tested 10.8.1 rev1940 with SteamLink app on Quest 3:
VR is running, but the display resolution is extremely reduced.
In 10.8.0 rev1836 the resolution is 100% of what the Quest can display. In rev1940 it looks like the resolution is more like 640x480.

**Comment by toxieainc** [comment]
This one is tracked in #1291 already, so closing here then, thanks!!

**Comment by Crrispy** [comment]
Hello,  I confirm that VR works here with rev 1940, and also that #1291 is
still there too :-)
Thanks.
