### ISSUE TITLE
Built In 'Table Ruleset Guide' Option when hitting Q to bring up menu (or similar method)

### ISSUE THREAD

**Issue by Smilelikejoker** [vpinball/vpinball#1224]
Add a feature to be able to pull up a self generated table guide while playing.  Some of the newer tables being created are pretty complex so some authors include the rule sets with the table download.

- There would need to be an agreed upon format and what could be displayed.  Maybe start with something simple, such as a text document, and later try to enhance the feature to include pictures/embedded gifs.
- Would need ability to scroll up/down along with determining a proper scale to use.  Folks need to be able to read it lol.
- Since some tables do not use roms, it would need be tied to the table name similar to a b2s file.

Since hitting Q is similar to pausing, it seems like the most logical place to use for access to a table guide.

**Comment by francisdb** [comment]
There is actually a field for the rules in the table metadata. I think it is shown when esc is pressed. This is however plain text and don't think it supports html or markdown.

**Comment by Smilelikejoker** [comment]
I see that in the editor (now lol) in the Table Info section, but I don't see how to pull that up live on the table.  When I hit escape (Q), all that I see displayed are the table notes.  Am I missing something?

It does look like there was some thought on it at one point, but could use a revamp to make it relevant.  I'm thinking more along the lines of a separate file that can be viewed.  Hit escape (Q), pick 'Table Ruleset', and then see the file.

**Comment by Smilelikejoker** [comment]
@vbousquet I just tested this new feature.  Thanks for adding it. :)

I found a bug with it though.  You can scroll down correctly, but text can be cut off at the top.  You can see what I mean on the following table: https://vpuniverse.com/files/file/16113-attack-from-mars-bally-1995-g5k-1311vpx/
The author was kind enough to write out the rules.

I can put up a separate bug report, for tracking purposes, if you want.
Joker
