### ISSUE TITLE
Some Tables run 1.6fps when most run 144fps - GL and DX builds

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1227]
**Describe the bug**
Using both GL64 & DX64 bit some tables play at exactly 1.6fps while all my other tables play at 130-144fps. On 10.7.x they played fine, I play them for 6+ months on 10.7.x without issues, even when I had a GPU 1/3rd the power as the RTX2060

two examples... Mortal Kombat II & Bigus's Star Trek LE (VPWs version works fine)

**To Reproduce**
just load the tables and press F11 to see FPS

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

Mortal Kombat II... https://vpuniverse.com/files/file/4361-mortal-kombat-ii-pinball-edition/
Bigus's Star Trek LE... https://www.vpforums.org/index.php?app=downloads&showfile=15217

**Expected behavior**
130+ FPS

**Versions & Settings**
 - VPX 10.8.0 Beta rev 1807 39824d6
 - Windows 11 all patches
 - NVidia RTX2060
 - INI attached as ZIP
 - Log attached as ZIP

[VPinballX_INI.zip](https://github.com/vpinball/vpinball/files/13536808/VPinballX_INI.zip)
[vpinball_LOG.zip](https://github.com/vpinball/vpinball/files/13536810/vpinball_LOG.zip)
![20231202_093223](https://github.com/vpinball/vpinball/assets/1626802/70fe964e-6229-4e65-8c73-b11d0f17006a)

**Comment by Smilelikejoker** [comment]
I'm trying to reproduce on the Bigus ST LE table.  No luck yet.  Mine runs a solid 60fps or 120fps.  I'll keep playing around.
SIDENOTE:  You should try switching to 'Frame Pacing' in your Synchronization Mode.  That should help your latency a lot.

**Comment by toxieainc** [comment]
@Ltek There are some errors about the shader compilation in your log, please update the shaders folder.

**Comment by toddsay** [comment]
I have this same symptom, 1.6 FPS only on some tables (Volkan for example), but only when using Frame Pacing. I had added a comment with a few other details on https://github.com/vpinball/vpinball/issues/755.

**Comment by vbousquet** [comment]
After checking, the problem is on the table side, not VPX. The table has a lot of timers expected to be ran every 1ms. When running in Frame Pacing mode, most of these will be honored causing lags. The tables have to be fixed or just don't use Frame Pacing with these tables
