### ISSUE TITLE
[Feature Request] AUTOPOV for 10.8 -- use PinballX.ini as default POV for tables without INI or POV

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1229]
**Is your feature request related to a problem? Please describe.**
AUTOPOV was really nice and with the re-work of the POV system, having a replacement for it would be helpful. It looks like the PinballX.INI does not automatically set the POV for tables that do not already have an INI (or POV). 

**Describe the solution you'd like**
Please have a 'default' POV so when a table without a POV or INI loads it will automatically use the default POV in the PinballX.ini

**Describe alternatives you've considered**
manually copy existing INI and change name (sux if you have hundreds of tables)

**Comment by vbousquet** [comment]
As far as I can tell, this is what is already implemented and what VPX does (obviously unless you have a pov/autopov/ini which is imported over this). So I will close for now
