### ISSUE TITLE
Incorrect display (scaling) of stereo 3D modes

### ISSUE THREAD

**Issue by jueank** [vpinball/vpinball#1230]
When using interlaced 3D mode (or top/down & left/right 3D mode), the table rendering is stretched horizontally by factor ~2. The table depth (z) seems to be doubled as well.
Reducing the eye distance by 2 (63cm -> 32.5cm) and scaling x to 50% of the YZ table scale helps reducing the issue.
This issue happens every time a table is started directly for playing. It can only be circumvented when starting a table from editor in anaglyph mode and switching to interlaced 3D from the Live editor.
I'm using 10.8.0 beta 7, 64bit, GL version
The attached picture shows a horizontally stretched table. This table would normally fit into the visible area of the screen.
![20231203_125544](https://github.com/vpinball/vpinball/assets/42673804/34482406-d548-45de-aad5-140cf4c13a2e)

**Comment by jueank** [comment]
As described in #1241, there are additional drawbacks to this issue. So compensating the horizontal scaling issue by adjusting POV values only helps partially and does not lead to a satisfying result.

**Comment by toxieainc** [comment]
@vbousquet Any chance to fix this for the 10.8 final?

**Comment by gjupp** [comment]
> @vbousquet Any chance to fix this for the 10.8 final?
Would certainly be good to have fixed. Do you have an interlaced 3D screen to test @toxieainc  ?

**Comment by jueank** [comment]
As this happens also with side by side 3D modes (top/down & left/right), you can judge the behavior also without having a 3D capable TV.

**Comment by gjupp** [comment]
@jueank , can you please confirm if the fake stereo fix also fixed true stereo bug in GL? I am unable to run GL to test.

**Comment by jueank** [comment]
@gjupp @vbousquet I grabbed this asset [VPinballX_GL-10.8.0-1856-97c4d50-Release-win-x64](https://github.com/vpinball/vpinball/actions/runs/7562264739/artifacts/1176576329) from here https://github.com/vpinball/vpinball/actions/runs/7562264739 following your commit. Unfortunately I cannot see any change. Tables are still rendered as before (with my adjusted settings: X scaling at 1/2 normal (~50%) and eye distance also at 1/2 normal (~33.5cm)). When using X scaling of ~100% and eye distance of 67cm, it looks still incorrect. Is this the right artifact?

**Comment by jueank** [comment]
I can confirm that the issue is fixed not.
Thank you very much @vbousquet 😊
