### ISSUE TITLE
analog nudge is not working in 1828

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#1232]
**Describe the bug**
analog nudge is not working anymore in 1828

**To Reproduce**
1. Open any table in 1828 GL 64 bits
2. Start a game and try to nudge or try with the nudge and calibration table
3. nudge is not working

**Versions & Settings**
 - VPX 10.8 1828 GL 64 bits
 - Windows 10

**Comment by workerb0y** [comment]
I have the same on 1828 and 1831 too. I switched back to Beta7 (1807) and it works fine.
