### ISSUE TITLE
Debugger Window not working in VPX 10.7.4 beta

### ISSUE THREAD

**Issue by jpsalas59** [vpinball/vpinball#1242]
**Describe the bug**
The text window is not showing up in the debugger window.

**To Reproduce**
Press D while playing and you'll see the text box, where the debug data is displayed, is missing.

**Expected behavior**
To open the text box, as it was in older versions.

**Versions & Settings**
 - VPX:  1.7.4 Final Revision 422

**Comment by toxieainc** [comment]
New beta: https://github.com/vpinball/vpinball/releases/tag/v10.7.4-424-e2c9b7c
Thanks!!

**Comment by jpsalas59** [comment]
Thanks! That was quick!
