### ISSUE TITLE
South park dmd very dark when rendered by vpinball

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1244]
**Describe the bug**
Below screenshot shows the difference between DMDExt and VPinball rendering the dmd for south park

![image](https://github.com/vpinball/vpinball/assets/161305/b43428a8-56d7-4fdc-aeac-622e0fbaa263)

Big dmd = dmdext

**To Reproduce**
1. Install the table
2. Add a Text Box and enable `Use Script DMD` on it
3. Add this to the script just before LoadVPM
  ```vbscript
Dim UseVPMDMD
UseVPMDMD=True
```
4. Set the text color to a bright orange

![image](https://github.com/vpinball/vpinball/assets/161305/8ff527e9-7916-4c70-9e8b-138afe631ce1)

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
https://vpuniverse.com/files/file/10531-south-park-sega-1999/

**Expected behavior**
Both DMD's have similar luminancy

**Versions & Settings**
 - VPX: 10.8.0 beta7
 - Windows 11
 - Default settings

**Comment by toxieainc** [comment]
This is due to the color LUT that the table uses.
Either set this one to <None>, or scale the brightness of the DMD with the number to the right of the color.

**Comment by francisdb** [comment]
> In case this is helpful for anyone else stumbling on the South Park DMD thread:  I added Me.intensityScale = 1.5 to the ImplicitDMD_Init declaration in the DMD .vbs patch, and that helped quite a bit.  It probably could be bumped even higher, but it's good enough for now.

https://discord.com/channels/652274650524418078/1076655472846831667/1189293328341147819
