### ISSUE TITLE
Standalone: Pinscape nudge not working because of standalone controller code

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1247]
**Describe the bug**
Currently the joystick from the pinscape board is not recognized. 

This is because standalone has some specific controller code/directives added which disables the joystick code

Played a bit with the code before and got it working but lost my changes.

_There's also the issue that a default Pinscape board will reset every 10 seconds if the joystick output is not read. This happens on Linux only. During this reset keyboard events don't work. This reset can be disabled in the pinscape config tool_

**Comment by Crrispy** [comment]
Hi,

I confirm that pinscape nudging doesn't work anymore in recent builds. Accelerometer test in the pinscape tool is OK.

**Comment by francisdb** [comment]
@Crrispy are you having this on windows? As there is no pinscape tool for linux/mac? 10.8.1 builds?

**Comment by Crrispy** [comment]
> @Crrispy are you having this on windows? As there is no pinscape tool for linux/mac? 10.8.1 builds?

Hi, yes, Windows 11.

**Comment by omigeot** [comment]
At least on linux, analog input from joypads doesn't seem to be processed either. Digital input work (following the default button map given in standalones readme), but that's about it.

**Comment by francisdb** [comment]
Man, spent a whole day looking into this

### Nudge

With the current code with pinscape is working properly here. Pinscape needs to be programmed with `2G` in the following screen to behave properly with the default vpinball gain/max acceleration.

![image](https://github.com/vpinball/vpinball/assets/161305/b2a9ddb7-267f-4ba7-b3fc-8ffab9c7e6fa)

```ini
PBWAccelGainX = 150 ;default
PBWAccelGainY = 150 ;default
PBWAccelMaxX = 100 ;default
PBWAccelMaxY = 100 ;default
EnableNudgeFilter = 0 ;default
DeadZone = 1
```

`DeadZone` is used by both plunger and nudge. Setting it to default for me caused "nudge drift" so I set it to `1`

The actual dead zone used seems to be `DeadZone * MaxJoystickRange / 100` 

### Plunger

As for the plunger, vpinball defaults to axis 3, however in sdl axis 3 is left trigger which has a different range an can not be used. Also this axis seems to have a multiplier of 256 defined, no idea why. This will give you extreme plunger values.

Therefore we choose axis 5 which maps to the right analog y.

```ini
PlungerAxis = 5
```

`~/.vpinball/gamecontrollerdb.txt`
```
03004c80fafa0000f700000011010000,mjrnet Pinscape Controller,platform:Linux,leftx:a0,lefty:a1~,righty:a2,
```

Use the SDL2 `./standalone/linux/tmp/SDL2-2.30.0/build/test/controllermap` to see which analog channels are provided
That binary is created by setting the following in `external.sh`
```
   -DSDL_TEST=ON \
   -DSDL_TESTS=ON \
```

### Some more info regarding axis expectations in the code/ vpinball config:

1) Left X - SDL `leftx`
2) Left Y - SDL `lefty`
3) Z - SDL `lefttrigger`
4) Right X - SDL `rightx`
5) Right Y - SDL `righty`
6) Z - SDL `righttrigger`

**Comment by francisdb** [comment]
Going to close this issue but I expect more similar issues to pop up regarding plunger / nudge / game controller and combinations of those.

**Comment by francisdb** [comment]
More info on the restart issue:

>  Looks like the board is working properly and that linux by default does not read the joystick unless something is connected.
> Lights went from **orange-red** to **green-blue** when running `sudo jstest /dev/input/by-id/usb-mjrnet_Pinscape_Controller_PSC0026700258804E45C008-joystick`
So I just disabled the auto-reboot to make sure the keyboard keeps working when vpinball is not running.

**Comment by aarcro** [comment]
This is the only place on the internet that says you have to populate your gamecontrollerdb.txt, and it doesn't say to use sdl-jstest to get the GUID of your controller, which I had to do because it was not a 1:1 match with the ID here.

And I did have to use Axis 5 (on my 3 axis controller). Glad it works now, but this information needs to be more readily available.
