### ISSUE TITLE
DOF Settings returning null

### ISSUE THREAD

**Issue by MauiPunter** [vpinball/vpinball#1252]
I have installed VPX 10.7.4 32bit and 64bit, and VPX 10.8 beta 5 in 32bit and 64bit.  DOF works fine for ROM based tables.  However, for EM based tables, that use the SoundFXDOF() function, are not finding the Setting data structure to get the DOF configurations:

DisableB2S    = CInt(Setting("Controller", "ForceDisableB2S"))
DOFeffects(DOFContactors)  = CInt(Setting("Controller", "DOFContactors"))
DOFeffects(DOFKnocker)     = CInt(Setting("Controller", "DOFKnocker"))
DOFeffects(DOFChimes)      = CInt(Setting("Controller", "DOFChimes"))
DOFeffects(DOFBell)        = CInt(Setting("Controller", "DOFBell"))
DOFeffects(DOFGear)        = CInt(Setting("Controller", "DOFGear"))
DOFeffects(DOFShaker)      = CInt(Setting("Controller", "DOFShaker"))
DOFeffects(DOFFlippers)    = CInt(Setting("Controller", "DOFFlippers"))
DOFeffects(DOFTargets)     = CInt(Setting("Controller", "DOFTargets"))
DOFeffects(DOFDropTargets) = CInt(Setting("Controller", "DOFDropTargets"))

If I hack the controller script and use the old Windows Registry, it works perfectly fine and DOF functions as expected.  However, since I am on the latest VPX code for each release, its now using the Setting() function, but my install is not able to get these values.

The UI is configured for DOF and have specified "Both" for all DOF toys.

I am running on Windows 11 if that matters.

If I use a DOF command directly, it fires the solenoids.

**Comment by Jeanpierrepinball** [comment]
Thanks @MauiPunter for reporting this. I think what I reported in issue #1143 might be linked to the same underlying problem, though I was pointing to original tables. I assume it may make sense since for some original tables DOF works ok and for others it no longer does.

**Comment by vbousquet** [comment]
It looks like you have wrong settings.
@MauiPunter could you delete your VPinballX.ini (from %AppData%/VpinballX), do your configuration in the UI (don't forget to press save, you may check in the new VPinballX.ini that will be create dthat the ocnfiguration suits you) and check what is happening then ?

**Comment by vbousquet** [comment]
Without feedback and after checking the code, I will close as this as my understanding is that this is a user setup bug, not a VPX bug

**Comment by rickmcclanahan** [comment]
I have the same issue with 10.74 (v433).  DOF for many tables is off or missing many dof calls.  Run the exact same table in 10.73 (v395) and the dof calls all work.  Batman 66 (stern) is a prime example
