### ISSUE TITLE
Volume progress bar hidden

### ISSUE THREAD

**Issue by zack06007** [vpinball/vpinball#1254]
**Describe the bug**
The volume progress bars (SSF, night mode, Normal volume) are in the background of VPX and are no longer visible on the playfield on beta 7.

**To Reproduce**
1. Launch table in beta 7, change volume and see. No progression bar?
 
 
**Versions & Settings**
 - VPX: 10.8.7
 - Windows version 11
 - AMD Ryzen 5 7600X 6-Core Processor

**Comment by francisdb** [comment]
Hmm, should #1167 not have fixed this?

**Comment by zack06007** [comment]
I don't know
On v10.8 beta 7 i have this visual volume problem.

I wait beta 8 for fix it? or i change files in my cab? thx

**Comment by toxieainc** [comment]
@zack06007 Can you please retry with newer beta/builds?

**Comment by vbousquet** [comment]
As said, this is supposed to be fixed in latest master build (just checked and it was ok on my side). Without feedback, I will close for now. Just tell if things still looks broken on your side
