### ISSUE TITLE
Only left eye picture in anaglyph 3D with BAM Headtracking

### ISSUE THREAD

**Issue by PG248** [vpinball/vpinball#1256]
**Describe the bug**
When I enable BAM Headtracking anaglyph 3D mode shows only the picture for the left eye.

**To Reproduce**
Enable BAM Headtracking in Preferences, Video/Graphics Options. 
Play a table. 
Press F10 to select any anaglyph mode.
You see the color change but the table is as sharp as in non-3d mode because the picture for the right eye is missing.

Repeat the steps with BAM-Headtracking disabled. Now you get the 3D double image.

**Versions & Settings**
 - VPX: 10.8.0 Beta (Rev. 1807 (39824d6), windows OpenGL 64bits)
 - Windows version: 11Pro, 22H2

**Comment by vbousquet** [comment]
This is not a bug: headtracking with stereo is simply not supported (it never had). I think fake stereo may work though
