### ISSUE TITLE
Ease of upgrade: can we read registry for existing joystick mappings, write to INI?

### ISSUE THREAD

**Issue by EngineersNeedArt** [vpinball/vpinball#1260]
**Is your feature request related to a problem? Please describe.**
Going from an earlier version of vpinball to 10.8 and I had to re-enter my button control settings. I understand this is because earlier versions of vpinball stored these mappings in the Registry and 10.8 saves them in a file.

It's not a big deal for me to re-enter those however it took me a while to realize that was why my cabinet was not working (and here I first thought that the beta was DOA).

**Describe the solution you'd like**
I'm assuming it's not a lot of work to maintain the old code to *read* the registry and if the control setting file has not yet been created, initialize it with the button settings from the Registry.

**Describe alternatives you've considered**
If nothing else, somehow we should let users know about this change so they don't panic like I did. :-)

**Comment by toxieainc** [comment]
In theory this worked at some point as the 10.8 cycle started, so i think this is a bug.

**Comment by vbousquet** [comment]
I think most of the settings are imported but some did change (name, value meaning, ...) and it's a bit difficult to track. I tried to add sensible defaults for these but the 'sensible' is somewhat subjective. @EngineersNeedArt do you know which settings ar not imported ?

**Comment by EngineersNeedArt** [comment]
It was the **Button assignments** for controls like the flippers, plunger, etc.

You can test by using a _pre_-10.8 vpinball and then go to: **Preferences > Configure Keys, Nudge and DOF...**
There select a Button Assignment for a control. For example, for **Left Flipper** select **Button 1**.

I think you'll find when you launch 10.8 vpinball that when you go to **Preferences > Configure Keys, Nudge and DOF...** that **Button 1** is no longer assigned to **Left Flipper**.
