### ISSUE TITLE
Setting going back to default

### ISSUE THREAD

**Issue by multigametechniek** [vpinball/vpinball#1261]
Every once in a while my VPX 10.8 (any beta version) looses the settings and restores the default settings. This goes for the Video, sound, UI and all other settings. It just goes back to default about once a month, sometimes once a week. Since I run things in a cabinet and the default is desktop (since 10.8 - in 10.7 default was cabinet) I have to change it back to cabinet. Also the rest, like I run SSF 7.1 and default is stereo.
I wonder if I am the only one with this problem because I can not find any issue on the forums regarding this.

This bug is not table related.

**Versions & Settings**
 - VPX: 10.8 beta-x 64bit (but same problem with the 32bit version
 - Windows version 10 Pro 64bit
 - GPU: nvidia RTX 4060TI (but same problem with sifferent GPU's
 - CPU: Ryzen 7 (but same problem with Ryzen 5 and Ryzen 9)
 - RAM: 16G
 
[VPinballX.ini.txt](https://github.com/vpinball/vpinball/files/13641676/VPinballX.ini.txt)

**Comment by vbousquet** [comment]
Now that the settings changes have stabilized, and after one year of testing without new issue identified, I will close this one. Just tell if it's still a problem in latest release

**Comment by multigametechniek** [comment]
Indeed i have not encountered this issue in the past 6 months or so.
I think it is solved

Op di 29 okt 2024 12:13 schreef Vincent Bousquet ***@***.***>:
