### ISSUE TITLE
making something invisible that can't be invisible crashes VPX

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1263]
**Describe the bug**
VPX crashes when you script .visible=0 on an item that cannot switch visibility.

**To Reproduce**
New -> Completely blank table
Add timer anywhere
Open script and enter:
timer001.visible=0
Run table -> crash

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well. -- crash.dmp too big
[crash.txt](https://github.com/vpinball/vpinball/files/13650912/crash.txt)

**Versions & Settings**
 - VPX: v10.8.0 Beta (Rev. 1828 (debb52b), windows DirectX 64bits)
 - Windows version 11
[VPinballX.ini.txt](https://github.com/vpinball/vpinball/files/13650924/VPinballX.ini.txt)
[vpinball.log](https://github.com/vpinball/vpinball/files/13650927/vpinball.log)

**Comment by tweety231323** [comment]
Similar crashes with:
2023-12-13 07:43:07.616 ERROR [30684] [CodeViewer::OnScriptError@1111] Script Error at line 1263 : Typenkonflikt: 'HSScore'
2023-12-13 07:53:13.279 ERROR [30532] [CodeViewer::OnScriptError@1111] Script Error at line 1825 : Variable ist nicht definiert: 'tape'

**Comment by toxieainc** [comment]
Please verify the workaround..

**Comment by tweety231323** [comment]
Confirmed: workaround is fine. No more crashes.
