### ISSUE TITLE
"Overwrite Physics by Global Set" feature is not working in rev-1828, 64bit.

### ISSUE THREAD

**Issue by wrd1972** [vpinball/vpinball#1264]
**Describe the bug**
The "Overwrite Physics by Global Set" feature" does not appear to be working using rev-1828, 64bit, W10

**To Reproduce**
I can run the table with the table physics (found in table properties) all set to .1 for testing purposes, then choose a setting from "OverWrite Physics by Global Set", and that setting will not install. If the table is played, the test physics of .1 (as found in the table properties) will be used instead. Seems to affect all tables.

**Expected behavior**
I would expect any table to use the physics as defined in "COnfigure Optional Global Physics Sets" to be used when the "Overwrite Physics By Global Set" feature is used. Currently, this is not working after considerable testing.

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**

**Comment by wrd1972** [comment]
Found something revealing to aid in fix this feature. It appears that table slope does work within the OPGS feature, but the table friction does not. Cant really tell about the other PF physics settings.

So since slope works, but friction does not, maybe that well help to isolate and address the issue. Hope that helps a bit.

**Comment by wrd1972** [comment]
Some more hopefully useful info. I have determined that if you revise the OPGS setting in the editor, then those changes are indeed reflected in the the Vpinball Config file in the new location. See below.
![Untitled](https://github.com/vpinball/vpinball/assets/119364072/98b876c5-07dd-45e3-a0ae-d77091ba80b0)

When selecting OPGS in the table propoerties, it iooks like the table is simply ignoring the playfield friction setting in OPGS, but not ignoring table slope.

**Comment by wrd1972** [comment]
I have spent considerable time testing OPGS to determine what works and what does not. From what I can tell, the following two values will not defer to OPGS when they are expected to:
-playfield friction
-playfield elasticity

Everything else in OPGS is working the way iot should from what I can tell. Can the devs please take a quick look at this and see if its a simple bug to fix and apply the fix. If its more complex, I understand that are likely things of higher importance. Just trying to help out here to speed things up where I can, and I will gladly test is notified to do so.
![Untitled](https://github.com/vpinball/vpinball/assets/119364072/ead711b4-cf62-4618-9d71-4c5b751b11f1)

**Comment by toxieainc** [comment]
For reference, VPX version tested is https://github.com/vpinball/vpinball/commit/debb52b0ac5dcff976b73bb33181f742008a7ab9 (10.8.0)
