### ISSUE TITLE
ExtractVBS not working with relative paths on standalone

### ISSUE THREAD

**Issue by Chaos99** [vpinball/vpinball#1267]
**Describe the bug**
When starting the standalone version via ./VPinballX_GL -ExtractVBS tables/example.vpx, no .vbs is extracted.

**To Reproduce**
1. Execute `./VPinballX_GL -ExtractVBS tables/example.vpx`
2. see no file created

**Expected behavior**
.vbs file extracted and saved alongside the .vpx

*
**Versions & Settings**
 - VPX: 10.8 standalone (current HEAD)
 - Linux64bit version
 

**Additional context**
I debugged the application and found that the file creation at 
(https://github.com/vpinball/vpinball/blob/d190cd453edaae090132acd5002630ecc7ab748c/codeview.cpp#L1841) 

fails due to the relative path from the command line used as filename usually points to an non-existing folder as the current working directory has been changed in the mean time in 
(https://github.com/vpinball/vpinball/blob/d190cd453edaae090132acd5002630ecc7ab748c/vpinball.cpp#L1191)
.

Commenting out the last mentioned line fixes the .vbs extract, but might have other consequences. Please check if this is a valid fix.

**Comment by francisdb** [comment]
As a workaround you can use [vpxtool](https://github.com/francisdb/vpxtool/)

```
> vpxtool extractvbs '/home/me/vpinball/tables/4 Aces (Williams 1970)/4 Aces (Williams 1970) JP_VPX8.vpx'
CREATED /home/me/vpinball/tables/4 Aces (Williams 1970)/4 Aces (Williams 1970) JP_VPX8.vbs
```

And it's much faster, see #814

**Comment by jsm174** [comment]
@Chaos99 - I tried to replicate this on macos, and was unsuccessful.

From your debugging, are you saying 

`chdir("")`

on linux changes the directory to some unknown folder?
