### ISSUE TITLE
Additional way to open 'F12' menu for cabinet users

### ISSUE THREAD

**Issue by jueank** [vpinball/vpinball#1273]
Having a central, unified menu system for all table settings is a great improvement!
For cabinet users, it would be good if there is an additional way to open the 'F12' menu besides using the keyboard. Saying: A combination of cabinet buttons. Ideally something which is not pressed accidentally during play. e.g. left + right magna save would not be a good combination imho. Right magnasave + 'Start' could be a good combination instead.
Alternatively, the combination of buttons is made configurable in the 'Configure keys' Dialog in VPX.

**Comment by alaw-lufc** [comment]
I second this.. the 'tweak' in game key is semi redundant to me at the moment as during play i have no keyboard, just cab buttons.  I don't have a spare button on the cab either - so if a two button combination could be assigned by the user in key preferences that would be great (i would probably assign L+R magnas, but other may prefer Start + a magna like @jueank suggests)

**Comment by francisdb** [comment]
I have a small rii mini wireless keyboard next to my cab for this purpose.

**Comment by jueank** [comment]
I should have checked what is possible currently before raising this feature request. turns out, it's quite easily possible to configure an additional (virtual) button for accessing the menu. This virtual button can be triggered through (in my case) the pinscape controller and you can map it to any of your physical cab buttons. Also in combination with a 'shift' button.
