### ISSUE TITLE
No playfield video recording possible in VPX GL beta. Issue with image grabbing

### ISSUE THREAD

**Issue by jueank** [vpinball/vpinball#1274]
Using 10.8.0 beta 7, 64bit, GL version.
Also using PinballY.
PinballY offers grabbing an image of the playfield as well as recording videos. In the GL version of VPX, there are issues with this.
- When trying to grab an image of the playfield, there is only a static snapshot of the VPXPlayer window being 'visible' to the external application (PinballY) from the point in time when the table is being shown first time on screen. All following screen updates (by OpenGL) are not 'visible' to the capturing application. I assume this has something to do with what is exposed to GDI / 2D in Windows / whatever. As a workaround, the user has to switch to another application with 'Alt + Tab' and then switch back to VPXPlayer. Grabbing an image is working then.
- Recording videos is not working at all. There is again only a single still image of the VPXPlayer window being exposed to the external application (PinballY) doing the recording through ffmpeg. The recoded video shows this static frame only. There is not workaround known to me yet.

**Comment by CarnyPriest** [comment]
Yeah, this is PinballY issue not VPX. PinballY uses FFMPEG gdigrab feature for screen recording. It is well known that OpenGL (i.e., Future Pinball) would not be supported. PinballY would need an update to use more recently introduced features from FFMPEG. PinballY and FFMPEG, they are both open source. Alternatively the GPU driver can probably manage screen recording. Or OBS or FRAPS can be used.

My AutoHotkey script that uses OBS to capture three screens simultaneously and copy output to the PinballY/media folder. It is stripped down feature-wise but does enough for me as a PinballY user:

https://forums.gameex.com/forums/topic/15207-capture-videos-to-pinballx-media-table-backglass-and-dmd/?do=findComment&comment=213953

**Comment by toxieainc** [comment]
Closing this then, thanks Carny for the explanations!
