### ISSUE TITLE
Standalone: FlexDMD based DMD no longer updates

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1276]
Tested 10.8.1 branch with Linux

**Describe the bug**
Tried tables using FlexDMD:

- Megadeth
- Big Trouble in Little China
- JP's Wrath of Olympus
- JP's Space Cadet

For all the DMD stays at Game Over/First screen when the game is started / during play

![image](https://github.com/vpinball/vpinball/assets/161305/2d4cecbd-6553-4421-9bf5-3879c5d29929)

**Comment by francisdb** [comment]
Somehow `The Goonies Never Say Die Pinball` does not have this problem?

**Comment by jsm174** [comment]
Related to https://github.com/vpinball/vpinball/issues/1246
