### ISSUE TITLE
Standalone: ball control not working

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1281]
**Describe the bug**
Normally you can control the ball with the mouse if ini setting `BallControlAlwaysOn` is true, this is not working on standalone.

Probably because the related code is in a `#ifdef _WIN32`

https://github.com/vpinball/vpinball/blob/75d89c2abd72bdb54c0ab8f9b6c5b4f1c9d7f29f/pininput.cpp#L484-L505

**Comment by jsm174** [comment]
this isn't a bug, but rather a feature. all the mouse logic would need to be converted SDL.

**Comment by francisdb** [comment]
From the user perspective it's an existing feature that works on windows but not on Linux. 😁

**Comment by francisdb** [comment]
This was fixed by #1436
