### ISSUE TITLE
"Visuals" tab gets duped when selecting lights and other objects

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#1282]
**Describe the bug**
You end up with duplicated "Visuals" tab for objects. This is a breaking bug as user cannot know which has the correct values. When this problem occurs, one needs to save, exit and reload. Otherwise it is possible that you did not store the desired values to correct objects.

**To Reproduce**
1. Select lights and primitives
2. Selecting different primitives does not trigger this, it must be light objects it seems
3. Once the tab gets duplicated, you cannot get rid of it. Any object you select will have 2 "visuals" tabs. And I also had 3 "visuals" tabs at some point, so maybe some other object type is affected too.

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/86254776/f75cfd53-871a-4912-a4e4-a931bfc5e034)

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: 10.8 beta7
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Comment by toxieainc** [comment]
@iaakki I fail to repro this behavior with beta 7 (both 32 and 64bits). Could you please provide an exact repro (i.e. table/version and which elements to select in which order)?

**Comment by iaakki** [comment]
It happens with many of the projects I have worked past months or two. Apophis also saw it too but could not find a clear way how to repro. They are making games using toolkit mostly, so it does not appear as easily on those projects. Just because you fiddle mostly with primitives only.

So usually this happens on legacy kind of games where you have walls, lights, primitives. It takes maybe 5 minutes moving and editing objects and it happens. Most "visual" tabs I had was probably 4. The last tab is the correct one, but it is really easy to make accidents when editing atm.

So choose prim, edit values, choose light, edit values, start game, end game, choose wall, edit values.. Repeat.

**Comment by vbousquet** [comment]
@iaakki I have cleaned up this part but since I had difficulties to recreate the bug, I'm not 100% sure it is gone. Could you confirm it is ok on your side ?

**Comment by iaakki** [comment]
Sure! I'll take a new version in use next week. 😊
