### ISSUE TITLE
Script error in Vikings (Bally 1980) Bord Version when ini created

### ISSUE THREAD

**Issue by Duracuir62** [vpinball/vpinball#1283]
I 'm using VPX 10.8.0 1829.
In Vikings (Bally 1980) table , bord version , when modifying the view and creating an ini associed to the table , script error line 300 concerning BCright variable not defined
When no ini created , table works fine

**Comment by vbousquet** [comment]
Just had a look and this is a table bug: the script has some left overs that you can hit depending on the keyboard inputs. Not a VPX bug
