### ISSUE TITLE
Live edit playfield camera settings — not saved for table

### ISSUE THREAD

**Issue by EngineersNeedArt** [vpinball/vpinball#1287]
**Describe the bug**
vPinball 10.8.0 Beta 7 — I have opened and edited the camera settings for two tables now and have not seen those changes preserved/saved to the table.

**To Reproduce**
1. In vPinball 10.8.0 Beta 7 open a table (**Evel Knievel** is a table I opened that showed the bug).
2. Click the movie camera icon in the tool palette to live-edit the camera settings for the table.
3. Make some obvious changes — for example, set the **Inclination** to 0.0.
4. Quit back to edit mode.
5. Two errors can now be shown: 1) if you quit vPinball now it will **not** ask you to save changes, and 2) if you specifically **Save** the table and then quit, the changes will **not** have been preserved.

Here is the table mentioned above: https://vpuniverse.com/files/file/16372-evel-knievel-bally-1977v50/

**Expected behavior**
I expect changes made to the camera settings for the table to be saved. I expect vPinball to prompt me when quitting to save changes. (I imagine the two bugs have the same underlying cause.)

**Versions & Settings**
 - vPinball 10.8.0 Beta 7
 - Windows 10 (?)
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Comment by francisdb** [comment]
You need to press `start` (1) to save the settings in the table ini file.

**Comment by EngineersNeedArt** [comment]
Thank you — for both comments.

Should vPinball warn you if you make changes in live-camera-edit mode and then quit to editor without hitting `start`?

**Comment by francisdb** [comment]
See #1255 for a proposed change that might make this more obvious.
