### ISSUE TITLE
Strange white lines on sides of tables

### ISSUE THREAD

**Issue by lesebio** [vpinball/vpinball#1288]
![Sans titre-1](https://github.com/vpinball/vpinball/assets/42131861/b75bdb44-83ba-4f5f-8aba-2f7562b54fc0)

I get two white line on sides of some table (friday the 13 for example)

table link : https://www.vpforums.org/index.php?app=downloads&module=display&section=download&do=confirm_download&hash=7473785548c1396c5ebe24d305201c50

vpinball version with bug : VPinballX-10.8.0-1807-39824d6 32bit

i don't have this bug With : VpinballX-10.8.0-1271-71581f5 32bit

**Comment by lesebio** [comment]
After testing different beta versions.

The bug appear since VPinballX-10.8.0-1786-588c765-Release-win-x64 (Visual Pinball X 10.8.0 beta 6) and newer versions (beta 7 and 8)
There is no bug with VPinballX-10.8.0-1347-3d585e7-Release-win-x86 (Visual Pinball X 10.8.0 beta 5) and older versions (beta 4, 3, 2 and 1).

You can take a look in beta 6 version compared to beta 5 for this bug.

**Comment by Smilelikejoker** [comment]
Can confirm this same bug on the op's table.  Running VPX DX 10.8.0 x64 rev 1837.

It kinda looks like this old bug: Issue #529
https://github.com/vpinball/vpinball/issues/529

**Comment by Smilelikejoker** [comment]
Got bored and wanted to see if I could figure out the issue and a fix.  No luck yet...  However, I figured I'd add tables that I find with the issue:
JP's Friday the 13th 4.3.0 (https://www.vpforums.org/index.php?app=downloads&showfile=16344)
Indianapolis 500 (Bally 1995) ver 1.36 (https://vpuniverse.com/files/file/14539-indianapolis-500-bally-1995/)
Big Trouble in Little China ver 1.5 (https://vpuniverse.com/files/file/11309-big-trouble-in-little-china/?tab=details)
Will edit if I find more...

VPX DX 10.8.0 x64 rev 1837

**Comment by Mrtr32** [comment]
The seem to be related to the inside cabinet image
This line is present on side wall defined as wall
The side wall image defined as primitive

this lines is a contour of transparent png inside wall I think!

Happy new year and
thanks for all your work !

**Comment by Smilelikejoker** [comment]
Found another table : The A-Team ver 2.0.7 (https://vpuniverse.com/files/file/17525-the-a-team-original-pinball/)

I played around with what Mrtr32 said on the A-Team table.  He's 100% right.   The white lines are the transparent edge of the PNG images used for Wall34 & Wall35.
