### ISSUE TITLE
Question: Is there a way to get 2D Screen/Client point from 3D DirectX/World vertex (inverse of Pin3D::Get3DPointFrom2D)

### ISSUE THREAD

**Issue by garybrowndev** [vpinball/vpinball#129]
Hey vpinball contributors - 

I am looking for a way to convert a 3D Vertex (Vertex3Ds) to the corresponding 2D POINT client/screen coordinates.
In other words, if I draw a single point using a Vertex3Ds within the view port/virtual world, what would be the equivalent POINT (x,y) client/screen coordinates where that pixel would show up on the screen/monitor?

Currently there is a function Pin3D::Get3DPointFrom2D() in pin3d.h which converts from 2D to 3D (with some assumptions); I am looking for the inverse.
If this doesn't already exist, would implementing the mathematical inverse of Get3DPointFrom2D() or studying some math be a good place to start?

Thanks

**Comment by garybrowndev** [comment]
I asked ChatGPT "Write me a function in C++ which converts a 3d vertex in DirectX to screen space x/y coordinate" and it gave me a good starting point, I ended up with this.

```
POINT BallHistory::Get2DPointFrom3D(Player &player, const Vertex3Ds& vertex)
{
   D3DMATRIX viewMatrix;
   D3DMATRIX projectionMatrix;
   player.m_pin3d.m_pd3dPrimaryDevice->GetTransform(TRANSFORMSTATE_VIEW, &viewMatrix);
   player.m_pin3d.m_pd3dPrimaryDevice->GetTransform(TRANSFORMSTATE_PROJECTION, &projectionMatrix);

   // Calculate the view-projection matrix
   D3DXMATRIX viewProjectionMatrix;
   D3DXVECTOR3 transformedVertex;
   D3DXMatrixMultiply(&viewProjectionMatrix, (D3DXMATRIX*)&viewMatrix, (D3DXMATRIX*)&projectionMatrix);

   // Transform the vertex from 3D world space to 2D screen space
   D3DXVec3TransformCoord(&transformedVertex, (D3DXVECTOR3*)&vertex, &viewProjectionMatrix);

   // Calculate the screen space (x, y) coordinate
   POINT screenPoint = 
   {
      LONG((transformedVertex.x + 1.0f) * 0.5f * player.m_width),
      LONG((-transformedVertex.y + 1.0f) * 0.5f * player.m_height)
   };

   return screenPoint;
}
```

**Comment by toxieainc** [comment]
Oh my  :)
Great new world!
