### ISSUE TITLE
adjust user setting (camera) -> F6 not working anymore since v10.8.0-1786-588c765

### ISSUE THREAD

**Issue by Hoppaz** [vpinball/vpinball#1290]
**Describe the bug**
With change from v10.8.0-1347-3d585e7 to v10.8.0-1786-588c765

adjust user setting (camera) -> F6
does not work properly anymore.

I can not use flipper/magnasafe and so on to adjust viewpoint etc.

Tried with several tables. Flipper buttons just show next menu.

**To Reproduce**
1. Load table
2. F6 in VPX editor or F12 from running game
3. Use flipper/magna safe buttons to adjust
4. Flipper buttons just show next menu. No way to select a value to change.

**Expected behavior**
Adjust table viewpoint and so on via flipper buttons/magna safe.

**Versions & Settings**
 - VPX: v10.8.0-1786-588c765
 - Windows version: win10
[vpinball.log](https://github.com/vpinball/vpinball/files/13725279/vpinball.log)
[VPinballX.ini.log](https://github.com/vpinball/vpinball/files/13725280/VPinballX.ini.log)

**Additional context**
Add any other context about the problem 
[signal-2023-12-20-100830](https://github.com/vpinball/vpinball/assets/1319036/bd0519fd-df02-47ae-bef4-782ad6e2589e)

There is a message in red (see screenshot): "You are using window mode but haven't defined your display physical size. This will break the overall scale as well as the stereo rendering.".
Maybe it has something todo with the problem.

**Comment by toxieainc** [comment]
Version tested: https://github.com/vpinball/vpinball/commit/588c765

**Comment by vbousquet** [comment]
Just checked with latest **master** build and everything is working as expected.
Note that flipper keys are supposed to change settings page and this is fully normal.
You need to use magna save key to move to the option you want to change.
There was a bug that would not import magna save (and others) keyboard settings from previous VPX version. I think you had this. You will need to delete your vpinball.ini or to redefine your keyboard shortcuts in the setting UI.

I will close for now. Just tell if things looks broken on your side
