### ISSUE TITLE
Standalone: Compilation fails with error `clang unknown argument: '-fapprox-func'`

### ISSUE THREAD

**Issue by ephraimg** [vpinball/vpinball#1296]
**Describe the bug**

Compilation of standalone can't be completed due to errors from command `cmake --build build -- -j$(sysctl -n hw.ncpu)`. Terminal output is:

```
[  0%] Built target glad
[  0%] Building CXX object CMakeFiles/vpinball.dir/imgui/imgui.cpp.o
[  0%] Building CXX object CMakeFiles/vpinball.dir/bulb.cpp.o
[  0%] Building CXX object CMakeFiles/vpinball.dir/backGlass.cpp.o
[  1%] Building CXX object CMakeFiles/vpinball.dir/codeviewedit.cpp.o
clangclang: : clang: error: clangunknown argument: '-fapprox-func'
: error: unknown argument: '-fapprox-func'
error: unknown argument: '-fapprox-func'
error: unknown argument: '-fapprox-func'
make[2]: *** [CMakeFiles/vpinball.dir/backGlass.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/vpinball.dir/codeviewedit.cpp.o] Error 1
make[2]: *** [CMakeFiles/vpinball.dir/bulb.cpp.o] Error 1
make[2]: *** [CMakeFiles/vpinball.dir/imgui/imgui.cpp.o] Error 1
make[1]: *** [CMakeFiles/vpinball.dir/all] Error 2
make: *** [all] Error 2
```

**To Reproduce**

Follow instructions for MacOS x64

```
brew install cmake bison curl
export PATH="$(brew --prefix bison)/bin:$PATH"
git clone -b standalone https://github.com/vpinball/vpinball
cd vpinball/standalone/macos-x64
./external.sh
cd ../..
cp standalone/cmake/CMakeLists_gl-macos-x64.txt CMakeLists.txt
cmake -DCMAKE_BUILD_TYPE=Release -B build
cmake --build build -- -j$(sysctl -n hw.ncpu)
```

**Expected behavior**

Compilation succeeds

**Versions & Settings**
- MacOS Big Sur 11.2.3
 - Processor 2.2 GHz Dual-Core Intel Core i7
 - Apple clang version 12.0.5 (clang-1205.0.22.11)
 - bison (GNU Bison) 3.8.2

**Comment by jsm174** [comment]
Unfortunately Big Sur isn't supported. (I'm really only supporting Ventura and Sonoma at the moment)

With a later OS and current build tools, you'll see the CIs build macos x64 fine:

https://github.com/vpinball/vpinball/actions/runs/7308638271
https://github.com/vpinball/vpinball/actions/runs/7279775786

![Screenshot 2023-12-23 at 10 49 00 AM](https://github.com/vpinball/vpinball/assets/1197137/193d91dd-d356-4191-8a90-38d2559cef76)

**Comment by ephraimg** [comment]
Thanks for the quick response @jsm174! A good reason to upgrade I guess. :)
