### ISSUE TITLE
VPX GL 64Bit  Seems to have stopped working since #2366

### ISSUE THREAD

**Issue by WilsonBradley** [vpinball/vpinball#1297]
Hangs/ Does not start after launching any tables, just hangs on all GL 64bit versions after #2366
After the port master change over, it broke things.. So everything after #2366 crashes. It's the last one that works for me without crashing when starting a table for Vpin GL64 10.8.1
[https://github.com/vpinball/vpinball/actions/runs/7033142093](https://github.com/vpinball/vpinball/actions/runs/7033142093?fbclid=IwAR2sJ5R-IJRb8Mb5BLP8vyjgSqiauV656oFE8AHPp-vneUlYXYtxNLXoC_Q)
On a RTX4080 Super i7-3900K 32Gb 

![412280885_10161114297390561_5022129988997413288_n](https://github.com/vpinball/vpinball/assets/8173893/df7351c8-31f1-4609-a9be-7db6a194d783)

**Comment by Crrispy** [comment]
Hello, this must be a local issue on your machine, no major problems here with x64 GL builds up to 1837 at least.

**Comment by pinballguy66** [comment]
WilsonBradley, I tried several tables with the version that you have linked to in your OP, VPX X64 GL did not crash for me.
