### ISSUE TITLE
EMReel triggering playsound

### ISSUE THREAD

**Issue by sverrewl** [vpinball/vpinball#130]
I'm quite confident that I've found a bug, but, a bit hard to explain what is going on. Started editing Honey, ref : http://www.vpforums.org/index.php?app=downloads&showfile=11741 - opened in vpx - saved and began editing. Opened up the debugger, and see that it can't find sample "100" that it trires to play. Could not find any ref to this sample in the table script, nor can I find it in the EMReels. But, I'm quite sure that it stuck there - somewhere. Because, I can select all the reels, then change the sound sample to "\<NONE>\", and then the debugger starts to say that it can't play "\<NONE>\". So, the NONE has kind of become a "valid" string for the sample. Looking at this table in 9.21, I can't find any samples named 100 in the EMReels, but, I don't have a debugger that tells me if it tries to play it or not. Not a critical issue, but, well, I believe it to be a bug.

**To Reproduce**
Download http://www.vpforums.org/index.php?app=downloads&showfile=11741 - open it in vpx, save. Start game, press 'd' and look at the output from the script. Can't find "100". Only sample that I found in the EMReels where "Reel", but, you kind of can't disable playsound being called.

I tried to figure out which reel it believe to be 100, by changing onle reel at the time. But, I was not able to find it. It felt like it was hidden outside of reach as it was not on the same object next time I loaded the table.

**Expected behavior**
Be quiet - at least, don't tell me that NONE isn't found :)

**Versions**
 - VPX: 10.7.2RC and probably many version before - tried a few.
 - Windows 10

**Comment by toxieainc** [comment]
Its in fact 2 separate things in play here:
1) The table has indeed names for the reel sound(s) saved in the .vpt (10,100,..), but it seems like the matching sounds have then been deleted before the table was shipped.
2) Your newly selected <None> from the dropdown is never filtered away when the reel is moving, so the engine just tries to play this name. I fixed that issue now.
