### ISSUE TITLE
SIGSEGV (Segmentation fault) when loading Lawman texture

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1301]
**Describe the bug**

Not sure if this is vpinball standalone specific

Got this crash when starting https://vpuniverse.com/files/file/8298-lawman-gottlieb-1971/

```
_mm_store_si128(long long __vector(2)*, long long __vector(2)) emmintrin.h:736
copy_bgr_rgb Texture.h:318
BaseTexture::CreateFromFreeImage Texture.cpp:252
Texture::LoadFromMemory Texture.cpp:835
Texture::LoadToken Texture.cpp:928
BiffReader::Load fileio.cpp:614
Texture::LoadFromStream Texture.cpp:713
PinTable::LoadImageFromStream pintable.cpp:8234
operator() pintable.cpp:3978
std::__invoke_impl<…>(std::__invoke_other, struct {...} &) invoke.h:61
std::__invoke<…>(struct {...} &) invoke.h:96
std::_Bind::__call<…>(std::tuple<…> &&, std::_Index_tuple<…>) functional:506
std::_Bind::operator()<…>(void) functional:591
std::__invoke_impl<…>(std::__invoke_other, std::_Bind<…> &) invoke.h:61
std::__invoke_r<…>(std::_Bind<…> &) invoke.h:114
operator() future:1491
std::__future_base::_Task_setter::operator()(void) const future:1409
std::__invoke_impl<…>(std::__invoke_other, std::__future_base::_Task_setter<…> &) invoke.h:61
std::__invoke_r<…>(std::__future_base::_Task_setter<…> &) invoke.h:116
std::_Function_handler::_M_invoke(const std::_Any_data &) std_function.h:291
std::function::operator()() const std_function.h:591
std::__future_base::_State_baseV2::_M_do_set(std::function<…> *, bool *) future:589
std::__invoke_impl<…>(std::__invoke_memfun_deref, void (std::__future_base::_State_baseV2::*&&)(std::function<…> *, bool *), std::__future_base::_State_baseV2 *&&, std::function<…> *&&, bool *&&) invoke.h:74
std::__invoke<…>(void (std::__future_base::_State_baseV2::*&&)(std::function<…> *, bool *), std::__future_base::_State_baseV2 *&&, std::function<…> *&&, bool *&&) invoke.h:96
<lambda#1>::operator()() const mutex:900
<lambda#1>::operator()() const mutex:836
<lambda#1>::_FUN() mutex:836
__pthread_once_slow 0x00007ffff4a9ccbf
__gthread_once gthr-default.h:700
std::call_once<…>(std::once_flag &, void (std::__future_base::_State_baseV2::*&&)(std::function<…> *, bool *), std::__future_base::_State_baseV2 *&&, std::function<…> *&&, bool *&&) mutex:907
std::__future_base::_State_baseV2::_M_set_result(std::function<…>, bool) future:428
std::__future_base::_Task_state::_M_run(void) future:1494
std::packaged_task::operator()() future:1628
operator() ThreadPool.h:155
std::__invoke_impl<…>(std::__invoke_other, struct {...} &) invoke.h:61
std::__invoke_r<…>(struct {...} &) invoke.h:111
std::_Function_handler::_M_invoke(const std::_Any_data &) std_function.h:290
std::function::operator()() const std_function.h:591
<lambda#1>::operator()() const ThreadPool.h:287
std::__invoke_impl<…>(std::__invoke_other, <lambda#1> &&) invoke.h:61
std::__invoke<…>(<lambda#1> &&) invoke.h:96
std::thread::_Invoker::_M_invoke<…>(std::_Index_tuple<…>) std_thread.h:292
std::thread::_Invoker::operator()() std_thread.h:299
std::thread::_State_impl::_M_run() std_thread.h:244
<unknown> 0x00007ffff4ee6333
start_thread 0x00007ffff4a97ada
clone3 0x00007ffff4b2847c
```

**To Reproduce**
1. Start the table in vpinball standalone on linux. Have not tested windows.

vpinball branch `10.8.1` 44d4027f8e3d7acd27e985e8a7d69de99cb05a27 standalone

**Comment by toxieainc** [comment]
@francisdb Please verify, thanks!

**Comment by jsm174** [comment]
@toxieainc, I've been getting some weird issues that started around the time of the texture updates and I wonder if related.

https://github.com/vpinball/vpinball/assets/1197137/0ac69f08-29f1-4b19-a65d-05666ff48e61

**Comment by jsm174** [comment]
![Screenshot 2024-01-02 at 1 22 29 PM](https://github.com/vpinball/vpinball/assets/1197137/de69aec5-632b-4149-99b2-41a93c5d2b90)

@toxieainc - okay, these weird issues started with 

`avoid unnecessary memsets in Texture ctor` - https://github.com/vpinball/vpinball/commit/1264c05b63f78036e1d04f61e005e8bac14c799d

This is the last build that doesn't do it:

`fix crash` - https://github.com/vpinball/vpinball/commit/bcba01770300765aad338b7f43c4e64982bd8358

**Comment by toxieainc** [comment]
@jsm174 Can you please test with the latest commit above again?

**Comment by francisdb** [comment]
@jsm174 I can confirm there are still issues, looks like something is not clearing a buffer?

This is Haunted Hotel when switching LUT's, left top part. (darkness is a different issue, see #1277 ) Not sure what is normally shown there.


![image](https://github.com/vpinball/vpinball/assets/161305/e2ccc7bb-c19c-4f1e-8781-54508610198c)

**Comment by jsm174** [comment]
> @jsm174 Can you please test with the latest commit above again?

Thanks. I just rebased everything, and it looks like the issue is still there:

![Screenshot 2024-01-03 at 8 03 50 AM](https://github.com/vpinball/vpinball/assets/1197137/bf08edc2-4cdc-4911-986d-a1a09eed6a6d)

Guessing maybe we should open a new issue to track?

**Comment by toxieainc** [comment]
So just to be clear, this is all about a short temporary effect until the 1st image(s) are captured/displayed, right?

**Comment by jsm174** [comment]
no, if you look at the video, it stays on the screen. I did notice the bottom anomaly goes away as you change LUTs.

**Comment by toxieainc** [comment]
Okay got it now. Due to standalone not blitting yet text to textboxes. I added a workaround to restore the previous behavior, please verify.

**Comment by jsm174** [comment]
ahh okay, totally makes sense. 

Have to add that to the list of things with standalone too. You think we should be able to accomplish textboxes with SDL_ttf?

**Comment by toxieainc** [comment]
I'd guess so. 
The question is rather: Do VP-textboxes still make sense nowadays, or should we rather modernize them in general. I think(!) that these are only used for debugging purposes in 99.99% of the tables released in the last years.

**Comment by francisdb** [comment]
> I'd guess so. The question is rather: Do VP-textboxes still make sense nowadays, or should we rather modernize them in general. I think(!) that these are only used for debugging purposes in 99.99% of the tables released in the last years.

Here are 2 examples of them being used but they are mostly used as a way to show the dmd in desktop mode
https://github.com/jsm174/vpx-standalone-scripts/issues/104
https://github.com/jsm174/vpx-standalone-scripts/issues/100

**Comment by jsm174** [comment]
I'd agree with something more modern but I guess will always have to support legacy..

@toxieainc, Btw, just to close the loop, I cherry picked https://github.com/vpinball/vpinball/commit/bb7524c43ada2cf70ceb7dda0b70056264e88b02 into standalone, and tested 10.8.1, and the the garbage is now gone. Thank you for fixing that!

**Comment by toxieainc** [comment]
No problem, i broke it, so.. .. ..  ;)
