### ISSUE TITLE
How to get full DMD on android 

### ISSUE THREAD

**Issue by PsyVHS77** [vpinball/vpinball#1307]
Some tables does not have a full DMD and I try put DMD file on the web server but I can not find a folder for DMD b2b files?

**Comment by jsm174** [comment]
@PsyVHS77  - please refer to here: https://github.com/vpinball/vpinball/tree/standalone/standalone#my-game-is-not-displaying-a-dmd

Even though separate B2S and DMD windows are included in android and iOS version, you can't really use the separate SDL windows just yet. - a) i'm not sure if they are even displayed, b) if they are they would be below the main window

I'm waiting for SDL3 which has some new utility window features.
