### ISSUE TITLE
DTArray failing on many Tables

### ISSUE THREAD

**Issue by cpzengel** [vpinball/vpinball#1310]
Sub DoDTAnim()
	Dim i
	For i=0 to Ubound(DTArray)
		DTArray(i)(4) = DTAnimate(DTArray(i)(0),DTArray(i)(1),DTArray(i)(2),DTArray(i)(3),DTArray(i)(4))
	Next
End Sub

will result in

2024-01-07 00:40:10.328 ERROR [222672] [CodeViewer::OnScriptError@1180] Script Error at line 4495 : 
2024-01-07 00:40:10.328 ERROR [222672] [CodeViewer::AppendLastErrorTextW@3946] Runtime error: Line: 4495, Character: 2, Description unavailable

Found on Indiana Jones and Black Knight 2000

Visual Pinball v10.8.0 Beta (Rev. 0 (unknown), macos OpenGL 64bits)

**Comment by francisdb** [comment]
All required script patches are available here: https://github.com/jsm174/vpx-standalone-scripts

You can just put the .vbs next to the .vpx file with same filenames.

There is also https://github.com/francisdb/vpxtool which can apply the DT/STArray fixes for you. But the files in the repository might contain even more required fixes.

**Comment by jsm174** [comment]
@cpzengel - Please review the Readme for standalone. 

https://github.com/vpinball/vpinball/tree/standalone/standalone#workarounds
