### ISSUE TITLE
Alien: hard crash when leaving game back to editor

### ISSUE THREAD

**Issue by JPJ-TeamPP** [vpinball/vpinball#1316]
When i leave my Alien Table (quit to editor) when i play it, VPX crashs and don't go back to the editor, it quit the editor itself. With 32 and 64 bits

The last time it worked, was with the Rev 1731.

Crash dump :

Crash report VPX - v10.8.0 Beta (Rev. 1836 (43556db), windows DirectX 32bits)
============
Process: VPinballX.exe
Reason: 0xC0000005 - EXCEPTION_ACCESS_VIOLATION at 0023:00632282
Attempt to read from 0x000002D4
Thread ID: 0x25C4 [9668]
 
Call stack
==========
00632282 VPinballX.exe (0x0019D94C 0x00000422 0x1E376370 0x0019e598)
00631FBA VPinballX.exe (0x00000000 0x1E379E20 0x00000010 0x3f7746eb)
 
Environment
===========
Date/time: 1/1/2024, 14:04:41:332
Number of CPUs: 12
Processor type: 586
System: Windows 10 (10.0 17763)
 
Memory status
=============
Total Reserved: 263632K (257M) bytes
Total Commited: 1851208K (1807M) bytes
Total Free: 2079400K (2030M) bytes
Largest Free: 1889452K (1845M) bytes
 
Registers
=========
EAX=C0ED2B30 EBX=000002C0 ECX=000002C0 EDX=404F0F38
ESI=C53B17D4 EDI=00000422 EBP=00000000 ESP=0019E5A0 EIP=0042C6D9
FLG=00010286 CS=0023 DS=002B SS=002B ES=002B FS=0053 GS=002B
 
 
Failed to save minidump.

Thanks 
JPJ

**Comment by toxieainc** [comment]
There was a bug in https://github.com/vpinball/vpinball/commit/43556db4349b94812d2ca56844f8b796dc503184
could you please try a newer/the newest build?

**Comment by JPJ-TeamPP** [comment]
Yes i will try this tonight !! Thanks Toxie !!!! ;)

**Comment by JPJ-TeamPP** [comment]
where to find newer version ? Or newer not online here ?

**Comment by toxieainc** [comment]
e.g. here: https://github.com/vpinball/vpinball/actions/runs/7475649249

**Comment by JPJ-TeamPP** [comment]
Hi Toxie, sorry but it does the same... i put here the two versions of the crash report, 32 and 64 bits (not GL)
[crash32.txt](https://github.com/vpinball/vpinball/files/13890881/crash32.txt)
[crash64.txt](https://github.com/vpinball/vpinball/files/13890883/crash64.txt)
thanks for all Toxie

**Comment by toxieainc** [comment]
Hmmm.. Where to find the table then, so i could test myself?

**Comment by JPJ-TeamPP** [comment]
https://mega.nz/file/et42TbDJ#ay8YYvFkOryXcTQtBjsdlfdAFoou42OcBrmWjRBXPrs
Of course you can try ;)
Thanks ;)

**Comment by toxieainc** [comment]
So far i fail to repro.. :/
@vbousquet Does it crash for you?

**Comment by vbousquet** [comment]
Nope, works perfectly fine here (using latest master, x64)

**Comment by JPJ-TeamPP** [comment]
Ok guys ;) thanks for all, i think i will install again all softwares ;) both thanks for your Time !!!!!
Jpj

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by toxieainc** [comment]
Please keep us updated if it still happens then..

**Comment by vbousquet** [comment]
Tried again and no crash. I will close for now. Just get back to us if you're still experiencing issues with the latest builds
