### ISSUE TITLE
Standalone externals `libaltsounds` needs cmake 3.25

### ISSUE THREAD

**Issue by ffes** [vpinball/vpinball#1323]
I've tried to build the `standalone` version on Ubuntu 22.04.3, following the instructions mentioned in https://github.com/vpinball/vpinball/blob/standalone/standalone/README.md#linux-ubuntu-2204

When I run the `./external.sh` script it eventually fails when it comes to `libaltsound` with the error:

```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.25 or higher is required.  You are running version 3.22.1
```

And indeed the very first line in `vpinball/standalone/linux/tmp/libaltsound-816cc987db61c428c61746b65ab30aa765c87116/CMakeLists.txt` says: 

```cmake
cmake_minimum_required(VERSION 3.25)
```

When I look at a recent GitHub Action https://github.com/vpinball/vpinball/actions/runs/7455219572/job/20283962478#step:6:14906 it works as expected with the same libaltsound sha and nowhere I see an update of cmake in the build script.

**Comment by jsm174** [comment]
Hello. The CI machines have the latest cmake installed. So 1) update your cmake on your distro, or 2) update the CMakeLists.txt file to 3.22. You shouldn't have any issues.

**Comment by francisdb** [comment]
here you can find what versions are in use on github actions ubuntu latest:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools
