### ISSUE TITLE
(Request) Landscape mode on android 

### ISSUE THREAD

**Issue by PsyVHS77** [vpinball/vpinball#1325]
Hi I like this pinball simulator on android so I have ask a question?
Can you add a landscape mode on vpx ?
I want play pinball tables with full screen so I try my phone on landscape and it wasn't have it that feature yet so that's asking you guys adding this feature it be more awesome with landscape and I love it more of this app
The app gets better and better of pasting time and I playing vpx a lot on my android phone so thanks for reading my long question and thank you for the app on android
You guys are awesome. 👍👍👍😁😁😁

**Comment by jsm174** [comment]
This is a complete hack, but try holding your phone in landscape while opening the app.

**Comment by PsyVHS77** [comment]
Thanks bro 😊👍

**Comment by gjupp** [comment]
Suggest also trying some of the amazing FSS tables in portrait mode available at https://www.fss-pinball.com/ as you'll be able to see the whole table and backglass.

**Comment by PsyVHS77** [comment]
Thanks bro I really not see this site coming 👍

**Comment by gjupp** [comment]
> Thanks bro I really not see this site coming 👍

A bit off topic, but the table on that site also work quite well running the android APK natively on Quest VR, its not true VR but just looks like playing on a huge screen.

**Comment by toxieainc** [comment]
Yes, the FSS tables are ace! They also have all kinds of additional features (day<->night mode is perfect, etcetcetc).
