### ISSUE TITLE
Latest Builds Not Working For it-pinball-madness DMD Just Shows Game Over...

### ISSUE THREAD

**Issue by movieguru1** [vpinball/vpinball#1327]
**Describe the bug**
When using any built later than #1830 The DMD Just Shows GAME OVER during Gameplay. With #1830 it works as it should....

**To Reproduce**
when I install this build the DMD just shows game over:
https://github.com/vpinball/vpinball/actions/runs/7453870095
if I use this build the DMD functions as it should:
https://github.com/vpinball/vpinball/actions/runs/7154311601

here is a link to the table:
https://vpuniverse.com/files/file/11995-it-pinball-madness/

**Expected behavior**
Should Show Credits and Keep Score on the DMD but the DMD just shows Game Over on it.

**Comment by jsm174** [comment]
FWIW, the first action is pointing to 10.8.1 while, the second action is master which is 10.8.0.

I think 10.8.1 still has some startup issues, see https://github.com/vpinball/vpinball/issues/1246

**Comment by movieguru1** [comment]
sorry, let me double check on the build number that is working and update
the post..
the build I have got to work fine is from 12/30/23 and when I got back from
vacation I tried a bunch of the latest ones and all have the same issue.

**Comment by jsm174** [comment]
![Screenshot 2024-01-10 at 11 37 20 AM](https://github.com/vpinball/vpinball/assets/1197137/91f35631-1d54-4352-b95e-4a92daa2ff6d)

When looking at the actions, if your fine with 10.8.0, grab the ones labeled master.

**Comment by movieguru1** [comment]
ok, you were correct.. the one that is working for me is 10.8.0 rev 1806 64bit GL version
It does seems to be the flexDMD issue that you mentioned in your link..,

**Comment by movieguru1** [comment]
Closed since this seems to be duplicate of https://github.com/vpinball/vpinball/issues/1246
