### ISSUE TITLE
standalone: table gfx no longer update after exiting magna save menu

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1345]
**Describe the bug**
vpinball 10.8.1 branch standalone on linux

**To Reproduce**
1. Get https://vpuniverse.com/files/file/14466-the-last-action-hero-data-east-1993/
2. Go in the game
3. Use left and right magna save menu keys to enter magna save menu
4. Click left magna save menu button to exit magna save menu
5. Table window no longer updates, pinmame window / ZeDMD still works and I can still use flippers

**Comment by jsm174** [comment]
So I'm not sure if this is a standalone specific problem, or a 10.8.1 issue, but after researching how CyberRace works: 

At the end of `Options_Open` it calls `DisableStaticPrerendering = True`
At the end of `Options_Close` it calls `DisableStaticPrerendering = False`

If you were to do the same in this table, does that fix it?

**Comment by jsm174** [comment]
As far as the `DisableStaticPrerendering`, looping in @vbousquet .

> Also strange that it tries to restart ZeDMD/Pixelcade and fails

Thats not strange at all and is expected. 

Everytime you open and close the options menu, a new "DMD" is actually being created, and its looking for an external DMD to render on. 

Would be interesting to see, if you started the table, waited a few seconds, unplugged your ZeDMD, and then plugged it back in if you'd see the Options Menu.

**Comment by francisdb** [comment]
> Would be interesting to see, if you started the table, waited a few seconds, unplugged your ZeDMD, and then plugged it back in if you'd see the Options Menu.

Magnasave menu indeed shown on ZeDMD (first frame missing) but now vpinball locks up totally when pressing Q. Even when not opening the magnasave menu after unplugging ZeDMD.

**Comment by francisdb** [comment]
This is fixed, at least on 10.8.1 branch :+1:
