### ISSUE TITLE
Blackwater 100 ball gets stuck

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#1365]
When playing Blackwater 100 (Bally 1988), ball gets stuck at the bottom on the left

It happens when shooting the ball to the left upper ramp.

I'm using 10.8.0 v1866 64bit. I have a 4K laptop NVIDIA 3080ti.
When using 10.7.4, no issues.
![Image 10 8 0 v1866](https://github.com/vpinball/vpinball/assets/81928693/be6c6a0f-72bc-4b2e-a858-22f188ec5d07)

Please find a solution. Thanks in advance.

**Comment by Karl030167** [comment]
Can't reproduce your error.
With x.8.0 v1869 dx and table 1.1 no ball stuck at all

**Comment by JorgePedro65** [comment]
I'll check it tomorrow and I will tell.

**Comment by JorgePedro65** [comment]
I downloaded the table again and the problem was solved. Thanks.

**Comment by JorgePedro65** [comment]
Thank you so much.
