### ISSUE TITLE
Long delay when running ./VPinballX_GL

### ISSUE THREAD

**Issue by Blad3forc3** [vpinball/vpinball#1371]
Hi, I have compiled the latest source (21/01/2024) and when running anything with ./VPinballX_GL from a terminal i get a long delay before it is run.
Running ./VPinballX_GL -listres takes 20 seconds or more before outputting the available list
Running ./VPinballX_GL -play "path to table" takes a similar amount of time before the table is displayed

This is my system

Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-14-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4460 CPU @ 3.20GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: H81M-S2H

**Comment by jsm174** [comment]
what does your log file show?

**Comment by jsm174** [comment]
I just built from source on ubuntu, ran a game and did a listres all in ~21 seconds. Might want to check your what you have installed on your distro. Unfortunately I'm not a linux expert, so not much more I can help with.
 

https://github.com/vpinball/vpinball/assets/1197137/efe98583-9dd7-42c1-96af-bbc3f7b86b5e

**Comment by francisdb** [comment]
I also run ubuntu 23.10

```
./build/VPinballX_GL -listres  0,02s user 0,02s system 33% cpu 0,116 total
```

I'm running wayland with an AMD gpu
Used to have a NVIDIA gpu and and there only X11 would give me proper framerates
