### ISSUE TITLE
problem on 10.8 > rev 1347 on batman dark knight

### ISSUE THREAD

**Issue by TchouK62** [vpinball/vpinball#1372]
**Describe the bug**
When the scarecrow mission is launch, pushing right flipper validate the crane without contact with the ball.

**To Reproduce**
1. Go to scarecrow
2. Push right flipper button
3. Crane is validated and goes to the next point.

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
Appears on NZ & TT version, and Bord mod too.

**Versions & Settings**
 - VPX: 10.8 > rev 1347
 - Windows version :11
 - GPU all tested (1660Ti and 6700XT)

**Additional context**

**Comment by toxieainc** [comment]
Did you also update VPinMAME or which version do you use there?
And is this about 10.8 or 10.8.1?

**Comment by TchouK62** [comment]
Vpinmame is up to date. I'm on vpx 10.8. I wasn't aware that 10.8.1 exists.

**Comment by toxieainc** [comment]
So which exact versions do you test (see VPX about dialogue)? And VPM ist 3.5 or a 3.6 beta build (in case the latter, please also post the version)?

**Comment by TchouK62** [comment]
Hey
All versions after 10.8 rev 1347 has the problem.
I'm using VPinMAME-3.6-720-e4df859-win-x64

**Comment by toxieainc** [comment]
Okay, so inbetween beta5 and beta6 then, thanks!

**Comment by TchouK62** [comment]
You're welcome. If you need more tests I can do, just ask

**Comment by TchouK62** [comment]
hey @vbousquet I still have the bug in RC1. Is it a vpinmame problem instead of vpx ?

**Comment by GroniPinball** [comment]
Oh Nevermind...Just found the updated Sam.vbs

**Comment by TchouK62** [comment]
> Oh Nevermind...Just found the updated Sam.vbs

Where dis you fond that? That solved the bug?

**Comment by GroniPinball** [comment]
Yes the updated Sam.vbs solved the Scarecrow Crane Bug. 

https://github.com/vpinball/vpinball/blob/master/scripts/sam.vbs

**Comment by wiesshund** [comment]
@toxieainc @vbousquet 
Please undo this reversion, it is NOT a sam VBS error
It is a table script issue, the script needs updated
the SAM.VBS already has a contention for this


table script needs

Const cSingleLFlip = 0
Const cSingleRFlip = 0

that is all.

Technically only needs 
Const cSingleRFlip = 0

but the other hurts nothing since L isnt used either

**Comment by wiesshund** [comment]
ALL tables that have any conflicts with staged flipping do to use of said circuits simply need the offending circuit (one or both flippers) set to be disregarded.

And not all SAM tables have any conflict.

Const cSingleLFlip = 0
Const cSingleRFlip = 0

Or whatever combination suits the table but you dont normally have to specify the value of 1 so you only need to set the ones you want deactivated.

just throw it in top of script after
Option Explicit
Randomize
