### ISSUE TITLE
10.8.1: Transporter the rescue loses track of ball on drain

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1375]
**Describe the bug**

Tested with `VPinballX_GL-10.8.0-1836-43556db-Release-win-x64` (beta8)

When the ball drains a new ball appears in the shooter lane

Tested with `VPinballX_GL-10.8.1-1979-44a78e3-Release-win-x64`

When the ball drains nothing happens

**To Reproduce**
1. Get table and rom https://vpuniverse.com/files/file/7899-transporter-the-rescue-bally-1989-vpw/
2. Play
3. Let the ball drain
4. The game is stuck as it did not see the ball drain?

**Comment by Karl030167** [comment]
I can't reproduce your error. X.8.0 v1869 NonGL, table VPW 1.05
After every drain a new ball in shooter lane, all ok
Maybe try to reset your tsptr_l3 Rom (delete the .NV)

**Comment by francisdb** [comment]
@Karl030167 This is on a fresh install that did not have the rom/nvram yet.
`10.8.1`, you're using a `10.8.0` build

**Comment by Karl030167** [comment]
Ah, I see. You mentioned especially x.8.1
So this is only a bug report for x.8.1

**Comment by francisdb** [comment]
same issue as #1246
