### ISSUE TITLE
10.8.0 DX rev 1869 - Multiple versions of The Machine - Bride of Pinbot just crashes

### ISSUE THREAD

**Issue by Smilelikejoker** [vpinball/vpinball#1377]
**Describe the bug**
Multiple version of The Machine - Bride of Pinbot now just crashes VPX to desktop.  I've tried the following versions:
https://vpuniverse.com/files/file/12029-the-machine-bride-of-pinbot-williams-1991-vpw-mod/
https://www.vpforums.org/index.php?app=downloads&showfile=17599

I've tried everything I could think of to get them to load, but no luck.  It has been awhile since I tried playing the table so I'm not sure when the issue started.  It crashes in x32 and x64.

It is either a VPX issue or a VPinMAME issue.  I'm not sure how to pinpoint which though.

**To Reproduce**
1. Download one of the versions above.
2. Try and open.  It will crash while stuck on starting scripts.

**Expected behavior**
It should not crash to desktop.

**Screenshots**
N/A

**Crash dump**
The crash dump is too large to upload.  Mine is 1.7 gigs, and that is a fresh crash dump.

**Versions & Settings**
 - VPX: 10.8.0 DX rev 1869 x32 and x64
 - VPinMAME 3.6 SC rev 793 x32 and x64
 - Win 11 Pro
 - NVIdia 3080 TI - Latest driver
[VPinballX.zip](https://github.com/vpinball/vpinball/files/14036957/VPinballX.zip)

**Additional context**
167 tables with zero issues.

**Comment by toxieainc** [comment]
Can confirm, thanks!

**Comment by toxieainc** [comment]
Actually a PinMAME issue.

**Comment by toxieainc** [comment]
@vbousquet Crashes in core.c, core_write_pwm_output_8b, coreGlobals.physicOutputState[pos].integrator is 0.

**Comment by toxieainc** [comment]
Just to follow protocol, closing here and re-opening on pinmame.
