### ISSUE TITLE
FlexDMD error after loading table and saving

### ISSUE THREAD

**Issue by Dini64** [vpinball/vpinball#1378]
Games like Haunted Hotel or Nosferatu 1922 work fine when downloading them from VPF or VPU
When loading the game into VPX Editor pressing RUN everything works fine.
After Saving the Game and starting the game again the following error occurs (After saving without changed filesize reduces !!!)

![image](https://github.com/vpinball/vpinball/assets/154258238/3e2b126c-dd61-4db9-b6c5-66056c63f9ac)

Link to the game:
https://www.vpforums.org/index.php?app=downloads&showfile=16218

VPX Version: VPinballX-10.8.0-1836-43556db-Release-win-x64
VPMAME Version: VPinMAME-sc-3.6-797-0784ec2-win-x64

Occurs on Windows 7 and Windows 11

**Comment by Smilelikejoker** [comment]
What version of FlexDMD are you running?  This looks the old FlexDMD bug that was fixed with the following FlexDMD action:
https://github.com/vbousquet/flexdmd/actions/runs/6836823342

You must have a github account to get this action.

**Comment by vbousquet** [comment]
I will close it here since this is not a VPX bug but a FlexDMD one. Beside as Smilelikejoker this is likely already fixed

**Comment by Smilelikejoker** [comment]
@vbousquet On topic but also off topic.  This is a common bug people run into now.  Would it be possible, if you get a few minutes to spare, to add the latest FlexDMD action to the Released section on the github page?

**Comment by Dini64** [comment]
Sorry for the late reply!Thanks a lot It works nowThanks for your supportMartinAm 24.01.2024 um 17:15 schrieb Smilelikejoker ***@***.***>:﻿
What version of FlexDMD are you running?  This looks the old FlexDMD bug that was fixed with the following FlexDMD action:
https://github.com/vbousquet/flexdmd/actions/runs/6836823342
You must have a github account to get this action.
