### ISSUE TITLE
(Request) external storage

### ISSUE THREAD

**Issue by PsyVHS77** [vpinball/vpinball#1379]
I have problems with the web server so I want a ask a question can you add a external storage for android?
Thanks 👍

**Comment by francisdb** [comment]
A PR adding this should be on the way:
https://discord.com/channels/652274650524418078/1076655472846831667/1205425582226018354

**Comment by francisdb** [comment]
ping @YellowLabrador

**Comment by YellowLabrador** [comment]
I'm working on it, it's very close now. The enhancement will allow you to pick either internal storage or a SD card (if your device supports it).
