### ISSUE TITLE
(Request) Separate configuration settings for VPX vs. VPX GL

### ISSUE THREAD

**Issue by dphoba** [vpinball/vpinball#1382]
(Not sure if this request belongs here or with B2S?...)

It appears that there is only a single global configuration (Windows registry?) per table. 

Since there are situations where different settings could be desired in VPX vs. VPX GL, it would be advantageous if these two programs saved per-table settings independently. 

For example, with some VR tables it is necessary to have the DMD on the backglass so everything displays and is scaled properly, whereas in non-VR it could be preferable to display a larger backglass image and place the DMD on a third separate LCD screen.

Thanks in advance for looking,
Dino

**Comment by francisdb** [comment]
Pretty sure you can set the config file to use on startup

```
-Ini  [filename]  Use a custom settings file instead of loading it from the default location
```

**Comment by dphoba** [comment]
Thanks very much for the quick feedback!  I'll give this a try.
