### ISSUE TITLE
VPinSPA not working in 10.8 ... works fine in 10.7.2

### ISSUE THREAD

**Issue by Dini64** [vpinball/vpinball#1394]
Can't load SPA ...
Needed for Ghostbusters LE ...

**Comment by vbousquet** [comment]
Please fill in  a complete bug report using the template. There's nothing to be done without this

**Comment by toxieainc** [comment]
I would guess that this is mixing the old VPinSPA 32bit build with a 64bit VPX build, thus its failing/not available,
If this is the case, there is nothing we can do about this, as VPinSPA is not part of the PinMAME/VPX 'universe'.

**Comment by Dini64** [comment]
Hi toxie!

Thanks for the quick reply!
You are right. I think its this 32-bit 64-bit thing ...

Will create a VPX 32-bit group on my pincab!
Thanks a lot
Martin

Am Mi., 31. Jan. 2024 um 11:25 Uhr schrieb toxie ***@***.***>:

**Comment by Joey-2001** [comment]
GB works great with 64bit.
You have to add three registry entries.

Open cmd as administrator and insert each following line one by one.

reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v AppID /t REG_SZ /d "{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v DllSurrogate /t REG_SZ

**Comment by Dini64** [comment]
Hi
Thanks a lot for your reply, but it doesn't work:
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]
P.S. Also executed InstallVPinSPA and pressed: install
Still writing: "can't load SPA" ...
Martin

Am Mi., 31. Jan. 2024 um 23:10 Uhr schrieb Rajo Joey <
***@***.***>:

**Comment by MikedaSpike** [comment]
You properly had the reg commands not correct, as it works for multiple people.
Even gl version with vr is working (only later builds cannot close vpinsa correctly)

**Comment by Dini64** [comment]
Are these 3 commands correct:
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\CLSID{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v AppID /t REG_SZ /d "{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v DllSurrogate /t REG_SZ

**Comment by MikedaSpike** [comment]
No, you missed a slash behind clsid.. these are the correct ones:
`reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v AppID /t REG_SZ /d "{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}"
reg.exe ADD "HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}" /f /v DllSurrogate /t REG_SZ`

**Comment by Joey-2001** [comment]
I'm just wondering, why the last backslashes are gone in my posting. I think, I forgot them and want to edit the post.
But then I saw, they are there. It seems, GitHub delete them in all three lines.

**Comment by MikedaSpike** [comment]
Github also removed my 

> I'm just wondering, why the last backslashes are gone at all three lines in my posting. I think, I forgot them and want to edit the post. But then I saw, they are there. It seems, GitHub delete them in all three lines. But why? I test it and write \ followed by the {. After saving the \ is gone.

I had the same on Discord. Properly because \ is a closing tag within HTML

**Comment by Dini64** [comment]
Hi Mike!

Thanks a lot for your effort, but unfortunately it doesn't work with the
slashes either.
Strange! Running VPX 10.7.4 works fine with GB LE!

If you have any additional ideas let me know.
Also the VPinSPA test shows the DMD as it should!

Martin

Am So., 4. Feb. 2024 um 07:09 Uhr schrieb Mike ***@***.***>:

**Comment by MikedaSpike** [comment]
Hi Martin,

The VpinSpa setup is the 32 bit application. If that is working, that means that the 32 bit installation is fine.
The registry keys that are provided by Rajo Joey are just instructions to redirect the 64 bit calls to the 32 bit DLL.
after importing the registry keys you should run the 32 bit install again, to add extra keys by the DllSurrogate key

After adding the key's for the 1st time it should look like this :
Check the following in your registry:
Computer\HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}
![image](https://github.com/vpinball/vpinball/assets/48748234/1f8606ac-518b-4be7-a581-b497019526dc)

and
HKEY_CLASSES_ROOT\WOW6432Node\AppID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A}
![image](https://github.com/vpinball/vpinball/assets/48748234/32506e41-2528-4722-9cb7-dcf12fead0ed)

it will still gives a 'SPA cannot load' during Vpinball
run the InstallVPinSPA.exe as administrator and click Install and make sure it will give you a successful install (or something)

now your registry key for Computer\HKEY_CLASSES_ROOT\WOW6432Node\CLSID\{F389C8B7-144F-4C63-A2E3-246D168F9D3A} will have an inprocserver32 that is pointing to your 32bit vpinspa dll
![image](https://github.com/vpinball/vpinball/assets/48748234/e7d40326-f112-4760-b2c8-6ed92cdf220d)

That means the 64 bit is redirected to 32 bit and should work

if it is still not working, there must be something in your computer not working

**Comment by Joey-2001** [comment]
> Hi Martin,
> 
> The VpinSpa setup is the 32 bit application. If that is working, that means that the 32 bit installation is fine. The registry keys that are provided by Rajo Joey are just instructions to redirect the 64 bit calls to the 32 bit DLL. after importing the registry keys you should run the 32 bit install again, to add extra keys by the DllSurrogate key
> 
> After adding the key's for the 1st time it should look like this : Check the following in your registry: Computer\HKEY_CLASSES_ROOT\WOW6432Node\CLSID{F389C8B7-144F-4C63-A2E3-246D168F9D3A} ![image](https://private-user-images.githubusercontent.com/48748234/302093825-1f8606ac-518b-4be7-a581-b497019526dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDIzNjYsIm5iZiI6MTcwNzA0MjA2NiwicGF0aCI6Ii80ODc0ODIzNC8zMDIwOTM4MjUtMWY4NjA2YWMtNTE4Yi00YmU3LWE1ODEtYjQ5NzAxOTUyNmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEwMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNGRmNWY0OTBjZjQwNWE0ZWY0MjQ0NzI3YjA2YmE4NDJmNDg5OGM5ZDZjOTQyMTFjZjQ4MDljZTZlZDFiYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WUrfkzvZ5aNP-itJbMazZjFI3ACJNFuLR-CR4kNI-PY)
> 
> and HKEY_CLASSES_ROOT\WOW6432Node\AppID{F389C8B7-144F-4C63-A2E3-246D168F9D3A} ![image](https://private-user-images.githubusercontent.com/48748234/302093627-32506e41-2528-4722-9cb7-dcf12fead0ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDIzNjYsIm5iZiI6MTcwNzA0MjA2NiwicGF0aCI6Ii80ODc0ODIzNC8zMDIwOTM2MjctMzI1MDZlNDEtMjUyOC00NzIyLTljYjctZGNmMTJmZWFkMGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEwMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNDViNWQ0NmJmNjMzNTExNzgwY2Q4OTRlYjU0M2MwNTFlOTU1MzdjNzE0MmFiODQzOGQ4NDNlYmJlZmE1MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3JFhzcFWIPlZuKspsO7xaZWFcAdiQvFepruQCTQz8I)
> 
> it will still gives a 'SPA cannot load' during Vpinball run the InstallVPinSPA.exe as administrator and click Install and make sure it will give you a successful install (or something)
> 
> now your registry key for Computer\HKEY_CLASSES_ROOT\WOW6432Node\CLSID{F389C8B7-144F-4C63-A2E3-246D168F9D3A} will have an inprocserver32 that is pointing to your 32bit vpinspa dll ![image](https://private-user-images.githubusercontent.com/48748234/302094303-e7d40326-f112-4760-b2c8-6ed92cdf220d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDIzNjYsIm5iZiI6MTcwNzA0MjA2NiwicGF0aCI6Ii80ODc0ODIzNC8zMDIwOTQzMDMtZTdkNDAzMjYtZjExMi00NzYwLWIyYzgtNmVkOTJjZGYyMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEwMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWYzMDQ5NDkxZmVlMGZmM2JiMTA4YTUwOWQ1MGU1MGNmNmM1NzhjY2ZiZjk3NDIxODI5NWRhZTZiYzYyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uQi6AtffkfDa8ZSYBKfOSQDF2vLhBq_RHrTUaL0sE4)
> 
> That means the 64 bit is redirected to 32 bit and should work
> 
> if it is still not working, there must be something in your computer not working

Now your backslashes are also deleted. :-)

**Comment by toxieainc** [comment]
This is all pretty interesting actually. Cause back in the days i tried to do the same for VPinMAME 32bit and failed. I never got VPX 64bit to work with it in similar ways. The benefit for still making it work (at the moment) would be that one could use AT91 JIT code also with VPX 64bit.

(and luckily i couldn't get it to work back then, otherwise i would have never started to make PinMAME 64bit ready, which is more than useful today, e.g. libPinMAME :))

**Comment by MikedaSpike** [comment]
@toxieainc 
I know this isn't ideal, but vpinspa is only used for 1 table. And this quick fix is easy to implement. there is no more development on spinspa and I am happy that vpinmame is now 64 bit. Although AT91 JIT still needs to be fixed. I hope a developer can pick this up
Anyway good job on all you achieved the last view years on VP, PinMame and B2S

**Comment by surtarso** [comment]
any way to run this table on standalone? I tried everything with 1.0 and 1.2 version, even stripping down the vbs to bare minimum... I dont understand this Vpin"SPA" thing...
