### ISSUE TITLE
Medieval Madness Lunix Error Line 1, Character: 0, Description unavailable

### ISSUE THREAD

**Issue by Dodyr** [vpinball/vpinball#1396]
**Describe the bug**
All medieval madness tables don't work on Arch Linux, SteamOS to be more clear (playing on Steam Deck), unable to start with a strange error Runtime error: Line: 1, Character: 0, Description unavailable, see logs below
I don't know if it happends on other linux systems, but I didn't find information about that. If it is a problem on my end, please help me

**To Reproduce**
1. Tables directory - roms/vpinball/<table>
inside <table> there is a pinmame folder, inside of which is roms folder with rom file for the table
made that possible with editing VPinballX.ini (see below)
```
VPRegPath = ./
PinMAMEPath = ./
PinMAMEIniPath = ./
```
Followed that guide:
https://gitlab.com/es-de/emulationstation-de/-/blob/master/USERGUIDE.md#visual-pinball

2. Open terminal and write ./VPinballX_GL - play <any Medieval Madness table>
3. See error

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

Bug appears on all medieval madness tables, tested most recently on this table https://vpuniverse.com/files/file/9784-medieval-madness-mod-nfozzy-fleep-sounds-lut-11/
Tested as well on:
https://vpuniverse.com/files/file/5643-medieval-madness-skitso-mod/
https://www.vpforums.org/index.php?app=downloads&showfile=15354
https://www.vpforums.org/index.php?app=downloads&showfile=11664

**Expected behavior**
Table runs as normal

**Screenshots**
Don't see the need

**Crash dump**
Did not find

**Versions & Settings**
 - VPinballX_GL-10.8.1-1990-cc238f6-Release-linux-x64
 - Operating System: SteamOS 3.5.7
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.9
Kernel Version: 6.1.52-valve9-1-neptune-61 (64-bit)
Graphics Platform: X11
 - Processors: 8 × AMD Custom APU 0405
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405
Manufacturer: Valve
Product Name: Jupiter
System Version: 1

**Additional context**
[VPinballX.log](https://github.com/vpinball/vpinball/files/14114457/VPinballX.log)
[vpinball.log](https://github.com/vpinball/vpinball/files/14114458/vpinball.log)

**Comment by jsm174** [comment]
@Dodyr 

See here:

https://github.com/vpinball/vpinball/blob/standalone/standalone/vbscript.md

and here:

https://github.com/jsm174/vpx-standalone-scripts/tree/master/1455577933_MedievalMadness_Upgrade(Real_Final)

**Comment by francisdb** [comment]
Any time a table script fails when using vpinball standalone you can check https://github.com/jsm174/vpx-standalone-scripts to see if we already made a patch. We tend to do this for the most popular versions of tables. Feel free to report tickets over there if you think anything is missing.

**Comment by Dodyr** [comment]
Thank you so much! I appreciate that a lot!
