### ISSUE TITLE
in VR, on some tables, lights "oversaturate"

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1398]
**Describe the bug**
In VR, on some tables, lights get brighter and brighter the longer they stay on.

**To Reproduce**
Example table:
https://www.vpforums.org/index.php?app=downloads&showfile=16156

**Screenshots**
![2024-02-01 20_17_12-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/4abbd0d0-f4d5-4b73-90a8-76b86125f8ca)

**Versions & Settings**

 - VPinballX_GL-10.8.0-1874-4e92fd6-Release-win-x64 (4e92fd6)
 - Windows version 11
 - GPU and video settings if applicable - Quest 3, Steam Link for Quest

**Comment by apophis79** [comment]
@tweety231323 why did this issue get closed? I noticed the same problem on the latest build.
https://github.com/vpinball/vpinball/actions/runs/7755856960

**Comment by apophis79** [comment]
It seems the bug is related to playfield reflections. If you disable reflections for a visible walls, the issue goes away.

**Comment by tweety231323** [comment]
> @tweety231323 why did this issue get closed? I noticed the same problem on build 1879

I closed it, because it's a duplicate of issue #1228.

[https://github.com/vpinball/vpinball/issues/1228](url)
