### ISSUE TITLE
Opening image manager changes alpha mask of images

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1403]
**Describe the bug**
Table -> Image manager -> select an image
change alpha mask to 3
Closing image manager and opening again: now alpha mask is 3.000000
Closing image manager and opening again: now alpha mask is 3000000.250000
Later:
3000000618006035868680192.000000
3000000800721035918773300756480.000000
3000000677352573878739622736064151552.000000

**Versions & Settings**
 - VPX: 10.8.0 rev 1874

**Comment by toxieainc** [comment]
@tweety231323 Please verify with a new build..

**Comment by tweety231323** [comment]
@toxieainc Confirmed it fixed.
