### ISSUE TITLE
Something strange going on with Fireball XL5 using TonyMcMapFace

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1413]
10.8.0 RC1 windows GL 64

https://vpuniverse.com/files/file/18224-fireballxl5/ v 1.0.1

Screenshots below show the issue. Already with ReinHard there are some strange dark reflections. When switching to TonyMcMapFace the tower turns into a funky glitter.

![image](https://github.com/vpinball/vpinball/assets/161305/8c75d54f-a8ad-4b1d-bd1d-196b376e7c73)
![image](https://github.com/vpinball/vpinball/assets/161305/4bb709ff-00c3-47a6-815c-24868a62883a)

**Comment by vbousquet** [comment]
This table has an invalid normal map on object SpaceTower leading to incorrect shading. Just remove the normal map or check the "object space" option
