### ISSUE TITLE
After update from 10.8 beta 5 to RC1 very low volume pinMame

### ISSUE THREAD

**Issue by ghost** [vpinball/vpinball#1416]
All pinmame sounds are low in volume on the tables I tried. I only have WPC and Stern tables.
When I test the rom in pinmame itself the sound is in normal volume.

I have tried to change the sound setings wich are default on 2 way stero for me and default sound output.
Changing these settings did not change the volume in any way for me.

When I downgrade to beta 5 again volumes return to the normal volume.

**Versions & Settings**
 - VPX:  10.8 RC1 64bit
- pinmame 3.5
 - Windows 10 23H2

**Comment by pinballguy66** [comment]
I tried with your setup and the Stern tables I used, Lord of the Rings, Star Trek LE, and X-Men, all sounded the same using VPX 10.8 Beta 5 and VPX 10.8 RC1 64bit, running pinmame 3.5.  What Stern tables have you tried?

**Comment by vbousquet** [comment]
Without further informations after 6 months, and without succeeding to reproduce, I will close this issue. If there is still an issue on this, just tell
