### ISSUE TITLE
Pointing to a missing file in LoadVPM silently fails

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1417]
**Describe the bug**

Windows / 10.8.0 RC1 GL 64bit

I came across a table that required a specific non-standard vbs file to be loaded with `LoadVPM`. When the file was not installed in the correct location vpinball was not reporting that the file was missing.

Looking at the code there is this part that seems to do some error handling:

https://github.com/vpinball/vpinball/blob/65b50dbb640a4760583c81da3b943c74de688cb1/scripts/controller.vbs#L157-L163

However that "Unable to open" message never pops up. I suppose that `GetTextFile` returns empty string and does not throw an error if the file is missing?

This ends up causing other errors further down the script when things initialized in the not found script are missing. Which is confusing and could be improved with proper error reporting.

**Comment by jsm174** [comment]
I planned on doing this:

```
STDMETHODIMP ScriptGlobalTable::GetTextFile(BSTR FileName, BSTR *pContents)
.
.
.
   for(size_t i = 0; i < std::size(defaultFileNameSearch); ++i)
      if(GetTextFileFromDirectory(defaultFileNameSearch[i] + szFileName, defaultPathSearch[i], pContents))
         return S_OK;

   PLOGE.printf("Unable to load file: %s", szFileName);

   return S_FALSE;
```

Will this work for you?

**Comment by francisdb** [comment]
That would certainly help.

But we probably also want to fix this for windows users? They should see that MsgBox.

Wondering what use cases exist that do a GetTextFile and don't want an exception if the file does not exist.

**Comment by francisdb** [comment]
What does a `return S_FALSE;` end up like on the vbs side? How do you check that?
