### ISSUE TITLE
Corrupt flasher shadows on Scared Stiff since beta 6

### ISSUE THREAD

**Issue by superblobster** [vpinball/vpinball#1421]
This report concerns Mikcab's release of this table here:
https://vpuniverse.com/files/file/13544-scared-stiff-bally-1996-mikcab_mod/
(Same behavior also occurs in Bigus1's version that is based on the same table.)

When the blue flashers in the top right are going off, they cause corrupt-looking shadows.

I have tried a bunch of builds and determined that this behavior started between [Visual Pinball X 10.8.0 beta 5](https://github.com/vpinball/vpinball/releases/tag/v10.8.0-1347-3d585e7) and [Visual Pinball X 10.8.0 beta 6](https://github.com/vpinball/vpinball/releases/tag/v10.8.0-1786-588c765).
The latest RC1 release is affected as well.
It doesn't happen in beta 5 and older.

I have only seen it on this particular table, not sure if this should be considered a table bug or a VPX bug.

Turning off reflections, ambient occlusion, anisotropic filtering and anti-aliasing did not fix it.

RC1:
![scared stiff fucked](https://github.com/vpinball/vpinball/assets/60817163/7cb21fa2-9557-4da6-a65e-aef5838ff5b0)

Expected (beta 5 or older):
![scared normal](https://github.com/vpinball/vpinball/assets/60817163/527147f8-2387-4ce1-a3c3-4972471e7f71)

**Comment by vbousquet** [comment]
This is an overflow problem. These are difficult bugs to solve. The table push the flasher value very very high, relying on the hardware to clamp it but this clamping is not guaranteed (DirectX and OpenGL specs differs on this, allowing undefined behavior) and depends on how the rendering is done (which is likely the reason it appeared between 2 betas). I'm not sure VPX can handle all situations like this. I think the easiest solution would be to lower a bit the flasher on the table side

**Comment by superblobster** [comment]
I was avoiding changing the table, but I think I've figured it out.

I lowered the Transmit value of the lights F17t, F18t and F19t on layer 7 to 5000, 4000 and 5000 respectively (they were 50000, 40000 and 50000 before).
This improved the situation a lot, at least with Reinhard. Could probably lower them further.

I'm don't know VPX well, so if anyone knows a better tweak, please share.

**Comment by vbousquet** [comment]
Yes that's the value causing problems. They are way too high. I will close the issue for now as I think this is a table bug, not a VPX bug
