### ISSUE TITLE
10.8.1: disabling and enabling timer during tick causes timer to never fire again

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1427]
**Describe the bug**

Tested on Windows 64bit GL
This is a specific bug for 10.8.1
On 10.8.0 RC1 this works as expected

Used this table for testing
https://vpuniverse.com/files/file/5580-skyrocket-bally-1970-rosvezip/

Create a `Skyrocket (Bally 1970).vbs` next to the table with the following code

```vbs
option explicit
Randomize
ExecuteGlobal GetTextFile("core.vbs")
ExecuteGlobal GetTextFile("Controller.vbs")

Sub Table1_KeyDown(ByVal keycode)
	if keycode=StartGameKey then
        debug.print "enabling Timer with interval 500"
        SeqTimer.Interval=500
        SeqTimer.Enabled=True
	End if
End Sub

Sub SeqTimer_Timer
    Debug.Print "Timer run with Interval=" & SeqTimer.Interval
 
    debug.print "disabling Timer"
    SeqTimer.Enabled=False
 
    debug.print "enabling Timer with interval 100"
    SeqTimer.Interval= 100
    SeqTimer.Enabled=True
End Sub
```

1. Using `10.8.1`
2. Play the table
3. Enabel debug window by pressing `D`
4. start the game by pressing `1`

You will see following output and nothing else happens
```
Script.Print 'enabling Timer with interval 500'
Script.Print 'Timer run with Interval=500'
Script.Print 'disabling Timer'
Script.Print 'enabling Timer with interval 100'
```

However doing the same on `10.8.0` will give you this
```
Script.Print 'enabling Timer with interval 500'
Script.Print 'Timer run with Interval=500'
Script.Print 'disabling Timer'
Script.Print 'enabling Timer with interval 100'
Script.Print 'Timer run with Interval=100'
Script.Print 'disabling Timer'
Script.Print 'enabling Timer with interval 100'
Script.Print 'Timer run with Interval=100'
...
```

**Comment by francisdb** [comment]
Without the script you will see that this table no longer provides balls after the first drain. Caused by this issue.

**Comment by francisdb** [comment]
Probably introduced in fcf1a538dead9fcfbb2989d0d3964abc3b21e6bf

**Comment by vbousquet** [comment]
Thanks for the clean report, it helped to solve the issue (likely also solve other issues related to script hangs)
