### ISSUE TITLE
Visual Pinball X 10.8 what path are settings files ?

### ISSUE THREAD

**Issue by Augusto7743** [vpinball/vpinball#1434]
Thanks for reading my topic.
Visual Pinball X 10.8 save settings only in an path or in registry too ?
The path if using WINE is the path below ?
WINE/drive_c/users/username/AppData/Roaming/VPinballX/

Only want save my settings thus avoiding reconfigure in each WINE installation.
Have an nice day.

**Comment by francisdb** [comment]
https://github.com/vpinball/vpinball/blob/5d4ec6aef45294062e4640ececc9b4853ad55c96/txt/Changelog.txt#L99

On a sidenote, you might want to try vpinball standalone.

**Comment by Augusto7743** [comment]
Thanks for replying.
Standalone version not run in Ubuntu 20.04.6.
However I has saved the ini file.
Have an nice day.
