### ISSUE TITLE
A crash problem about fireball classic table on android

### ISSUE THREAD

**Issue by PsyVHS77** [vpinball/vpinball#1435]
I try playing this table call fireball classic by Bally on my android but is crash a lot time I boot this table can you fix this table ?
Thanks x3 👍

**Comment by jsm174** [comment]
We need some logs. Can you please get them via the web server or adb?

**Comment by PsyVHS77** [comment]
> We need some logs. Can you please get them via the web server or adb?

I Try adb but I don't know how is working
There are lots adb apps on Google play store I don't manage a getting work for myself ?

**Comment by francisdb** [comment]
Have you applied the patch?
https://github.com/jsm174/vpx-standalone-scripts/tree/master/Fireball%20Classic%20(Bally%201984)1.2

**Comment by jsm174** [comment]
You can get the logs from the built in webserver. adb isn't something you would install on the device. its a utility in the android sdk.
