### ISSUE TITLE
Missing warning window

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1449]
**Describe the bug**
A lamp is part of a collection.

When you select the lamp and delete it,
![2024-02-11 14_39_50-Visual Pinball -  !Pinball Lizard (Game Plan 1980)_build3_](https://github.com/vpinball/vpinball/assets/98708681/6fcb5c7f-ca89-46c4-8e19-b99fdb373116)
you will get this warning message.
![2024-02-11 14_39_32-Visual Pinball](https://github.com/vpinball/vpinball/assets/98708681/a6c95c5c-aca7-4b0c-93a4-c360bb04e193)

But when you select just the cross in the middle of the lamp and delete it,
![2024-02-11 14_39_58-Visual Pinball -  !Pinball Lizard (Game Plan 1980)_build3_](https://github.com/vpinball/vpinball/assets/98708681/4d0a72cd-ea02-4d4c-8353-7d2f3a373e97)
there is no such warning message.

**Expected behavior**
Show the warning.

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1887-7c2f156-Release-win-x64
 - Windows version 11

**Comment by jpsalas59** [comment]
This is also an old bug, from 10.6 and maybe older than that.

**Comment by tweety231323** [comment]
Any other old bugs we could add, so they get fixed?

**Comment by jpsalas59** [comment]
> Any other old bugs we could add, so they get fixed?

Not that I know. I have learned to live with these small errors :)

**Comment by jpsalas59** [comment]
Thanks :)
