### ISSUE TITLE
"Paste at" doesn't paste at

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1450]
**Describe the bug**
"Paste at" never pastes at the selected position, 
![2024-02-11 16_18_38-Visual Pinball -  !Pinball Lizard (Game Plan 1980)_build3_](https://github.com/vpinball/vpinball/assets/98708681/e509ded6-2430-483e-ae07-1880a68d7469)
but always to the upper left.
![2024-02-11 16_18_48-Visual Pinball -  !Pinball Lizard (Game Plan 1980)_build3_](https://github.com/vpinball/vpinball/assets/98708681/a69b4026-2965-4b5c-86b8-8bd4671d9c86)

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1887-7c2f156-Release-win-x64
 - Windows version 11

**Comment by tweety231323** [comment]
Any other old bugs we could add, so they get fixed?

**Comment by jpsalas59** [comment]
> Any other old bugs we could add, so they get fixed?

Not that I know. I have learned to live with these small errors :)

**Comment by jpsalas59** [comment]
Thanks! ;)
