### ISSUE TITLE
Window POV Player Y no longer represents real world distance from center bottom of playfield screen

### ISSUE THREAD

**Issue by SmedleyB** [vpinball/vpinball#1451]
**Describe the bug**
In earlier beta releases, the Player Y distance represented the real world measurement straight back (parallel to ground) from the center bottom of the playfield screen to the player's eye location. Many beta release ago (maybe a couple months back?) the behavior changed such that I had to start using a Player Y value of around -25cm to generate the same POV that had previously been generated with a value of -8cm. Player Z and Player X settings seem to work as usual.

**Expected behavior**
I'd really prefer the real world value from center bottom of screen could be used, which also matches the current documentation.

**Versions & Settings**
 10.8 RC

**Comment by vbousquet** [comment]
In fact, it's the opposite. It was never true to the real world and now it is but you need to calibrate your screen first. Please see docs or forums for help with this process

**Comment by SmedleyB** [comment]
@vbousquet I will review and take screenshots as needed. Would running the playfield in Landscape (Flipped) orientation in Windows 10 have an affect on the POV calculations in the more recent beta releases? And could that have been introduced after the Window POV calculations were updated as compared to the earlier beta releases?

**Comment by SmedleyB** [comment]
![auto no stretching](https://github.com/vpinball/vpinball/assets/117312732/416f5c2d-ec30-4f82-994b-642e6049cf67)
![auto stretch to fit](https://github.com/vpinball/vpinball/assets/117312732/14095648-5a6a-4fe0-a0b9-2ac49e57f595)
![vpx settings](https://github.com/vpinball/vpinball/assets/117312732/cb4b2bf0-f957-49e8-b966-51eb41fd6496)


@vbousquet  My settings are attached. I play on a 32" screen and have validated screen width and height measurements via the calibration table, I also confident my screen inclination is correct.

Note in both screenshots, if you focus on the flippers, I must use a Player Y of -25cm to achieve a POV you would normally associate with being almost directly above the bottom center of the playfield (I would think between 2-4cm would be my real-world player Y distance between center bottom of playfield and my eyeball location). What am I doing wrong?

I've also attached the 2 auto generate Window POV styles created when pressing the launch/plunge button. Note that while the no stretching POV looks good and centers the playfield appropriately and clips the apron, the stretch-to-fit auto POV squishes the table way too much on the Y axis. I have other tables, like VPW Police Force, where this is even more obvious in the auto stretch-to-fit POV.

**Comment by SmedleyB** [comment]
Hi @vbousquet, wondering if my above screenshots change your mind at all about potential unwanted behavior in the Player Y setting. I have confirmed with other users that they must use similar Player Y settings on a 32" playfield. Or if I'm doing something wrong, let me know, so I can update POVs how-to's I've been sharing.
