### ISSUE TITLE
all playfield lights are shifted under main playfield f14-tomcat only

### ISSUE THREAD

**Issue by keithhov** [vpinball/vpinball#1457]
F14 Tomcat (Williams 1987) wrd1972 1.0 

All playfield lights appear under playfield a few millimeters. 
Currently tested on 10.8.0-1879-e7ea030......has happened on all recent versions of beta, also occurs on 10.8.1-2038-0f9ee39.

This version is hard to find it is not on any of the main sites to download but here is the link https://drive.google.com/file/d/1H1Vw9DgsAgToYmk_t3u4tKqJrS7oWJAM/view?pli=1
![playfield](https://github.com/vpinball/vpinball/assets/146595499/1afb099c-72e2-4c21-8b57-0cfbad024f62)

**Comment by francisdb** [comment]
This is not really a vpinball bug but a table issue?

There's a newer version of this table where this has been fixed. I guess you'll have to ask [wrd1972](https://www.vpforums.org/index.php?showuser=95963) to share it.

![image](https://github.com/vpinball/vpinball/assets/161305/759cf06d-a3f7-4def-8cbf-7e0576135340)

**Comment by keithhov** [comment]
Thanks, i got the newer version and lights are normal now.  Looks like someone is working on finalizing the newer version.
