### ISSUE TITLE
Add Linux and MacOS versions to release page

### ISSUE THREAD

**Issue by rawdatafeel** [vpinball/vpinball#1461]
**Is your feature request related to a problem? Please describe.**
Apologies if I am looking in the wrong spot here, but was looking at the prereleases, https://github.com/vpinball/vpinball/releases, and it looks like MacOS and Linux aren't included here.

**Describe the solution you'd like**
I know you can grab the latest versions of these two platforms from the Actions tab but downloading from the actions tab requires a GitHub account. Adding these two platforms to the prerelease section would make it much more user friendly to download and set these up on non-Windows platforms :)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by toxieainc** [comment]
This is planned as we switch gears from 10.8.0 (which is still windows only) to 10.8.1.
