### ISSUE TITLE
Official Font and Logos ?

### ISSUE THREAD

**Issue by wlan4you** [vpinball/vpinball#1464]
Hello,

it is not realy a Feature Request.
I will ask,
is there a official Graphic Archiv from Visual Pinball ?
Which is the official FONT or Logo for it ?
Is there a Download Area where i can find it?
Or can you say me what Font are using hier?

Best Regards
Stefan

**Comment by toxieainc** [comment]
That would be https://avatars.githubusercontent.com/u/20977447?s=400&u=d514f488c5abf4c629732694d9612dc481fb93c8&v=4 (i hope you can access) or https://upload.wikimedia.org/wikipedia/en/c/c0/Visual_Pinball_X_logo.png
Official font we don't have. There are a lot of unofficial logos,etc out here, like the one on https://de.wikipedia.org/wiki/Visual_Pinball . But i don't know who did these.

**Comment by wlan4you** [comment]
![grafik](https://github.com/vpinball/vpinball/assets/60288714/a900f66e-d02d-434f-9504-88368c8d7a55)

above original Graphic

bottom selfmade Graphic

This two Fonts can it be:
Marketing Script for "**Visual**"
Its a freefont:
https://www.ffonts.net/Marketing-Script.font.download

ALBA for "**Pinball**"
Its a freefont:
https://www.ffonts.net/Alba.font.download

Thank you for the Links to the Pinball with the X
And thanks for the Rest of Information.
Maybe someone ask in the Future for the Fonts.

Best Regards

**Comment by toxieainc** [comment]
Thanks!
