### ISSUE TITLE
Bitdefender is detecting a virus under the file VPinballX_GL64.exe

### ISSUE THREAD

**Issue by aabramson** [vpinball/vpinball#1465]
After I tried to unzip the files from 10.8.0 release candidate 1, the bitdefender antivirus detected a virus with the following output:

Name of file:  VPinballX_GL-10.8.0-1873-bdd0673-Release-win-x64.zip 

Bitdefender Log:
Type: critical
Infected file inside of zip archive: VPinballX_GL64.exe
Virus name: Gen:Variant.Lazy.476837

![bitdefender antivirus](https://github.com/vpinball/vpinball/assets/40179992/04cd55ff-be53-4735-a71a-06004b6ecbcf)

I think it might be a false positive, but it's better to investigate deeper just to make sure.

**Comment by mazjohn** [comment]
Noticed same behavior here as described.  It happens on both the standard x64 and openGL executables

**Comment by toxieainc** [comment]
Definetly false positive. Could be that we still used UPX back then, don't remember (and that one triggers all kinds of false positives in some engines).
Always use https://www.virustotal.com/gui/home/upload to check with multiple engines.
