### ISSUE TITLE
Blurry Playfield texture when using supersampling

### ISSUE THREAD

**Issue by jueank** [vpinball/vpinball#1468]
Using 10.8.0 RC1, 64bit, GL version.
When using supersampling with a percentage below 100% (50% or 75%), the playfield texture is slightly shifted and looks blurry. That becomes recognizable when opening the 'F12' menu. In that case - for whatever reason - the playfield texture is unshifted (I assume) and is shown sharper and ultimately looks better. IMHO this should be the desired look during normal play.
Here is an example showing the difference: https://imgsli.com/MjQwODkx
The difference in the example looks very subtle, so you might think there is little reason to fix this issue, but when looking at a large cab TV (42"), the difference is very obvious.
With other tables (sharper playfield textures), the difference might even be bigger.

**Comment by Jayhay89** [comment]
I'd like to add that supersampling in general looks far more blurry and aliased compared to it's Direct X counterpart when over 100% (I have it at 200%)
