### ISSUE TITLE
Transparency of png files

### ISSUE THREAD

**Issue by cwscws** [vpinball/vpinball#1485]
If using a png file with transparency for a wall or primitive, certain objects under it are not displayed.

Can be reproduced on VPX 10.8.0 using DirectX or the Standalone Player using OpenGL.

<img width="263" alt="trans2" src="https://github.com/vpinball/vpinball/assets/5362135/4841797e-d85d-4dcd-8ae6-a69561dd8d1c">

**Comment by vbousquet** [comment]
As far as I can tell, that has always be true and is not a bug.

The solutions for that are to either use alpha testing (which I would discourage) or depth bias. The render backface is also of importance here (for 2 sided materials like plastic ramps). Finally, in 10.8, you also have the possibility to disable depth masking for transparent part with a dedicated check box.

I will close for now, tell me if I missed something

**Comment by cwscws** [comment]
Please remove that issue - it seems to be depth bias related
