### ISSUE TITLE
Dragon's Lair pupscreen issue with 10.8 

### ISSUE THREAD

**Issue by workerb0y** [vpinball/vpinball#1505]
Pup screens do not close when exiting the Dragon's Lair table (both versions). 
It exits the table, but continues to project the b2s and fulldmd image, it can only be closed manually in the Task Manager. 
With 10.7.4 it works properly.

**To Reproduce**
1. Open the table with any 10.8 betas after beta7 (I didn't tried it with an older version)
2. Run the game.
3. When table and pup loaded, exit the table.
4. See error: pup screens doesn't closed, vpx crashed /see attached crash.txt/ (I tried to attach crash.dmp but it's more than 1GB)

[crash.txt](https://github.com/vpinball/vpinball/files/14438136/crash.txt)

**Versions & Settings**
 - VPX: 10.8 beta rev1879 GL X64/X86
 - Windows version: Windows 10 Pro x64
 - RTX3070 8GB, graphics filters off, texture size 3172, frame pacing

[VPinballX.log](https://github.com/vpinball/vpinball/files/14438297/VPinballX.log)

**Comment by vbousquet** [comment]
Duplicate https://github.com/vpinball/vpinball/issues/1506
