### ISSUE TITLE
Pupscreen problem in several tables with 10.8

### ISSUE THREAD

**Issue by estivalet** [vpinball/vpinball#1506]
For any puppack they have like a video in the backdrop but plays in in the playfield or apron , vpinball won't exit cleanly(using q to quite not escape) as it's not closing pinup process as expected and hangs VP, force to close those pinup elements from task manager and have to use task manager to kill process for vpinball.

Few example tables:

- IronMaiden Legacy of the Beast PRO Tribute

- The Last Starfighter (1984)
 
- Johnny Mnemonic LE
 
- Pink Floyd (Pupversion)
 
- Dragon's Lair

...

 

It exist cleanly with vpinball 10.7 doe... odd
rather certain it's not pinup player 1.5 issue as it works with 10.7

**Comment by vbousquet** [comment]
Duplicate https://github.com/vpinball/vpinball/issues/1511
