### ISSUE TITLE
This New gl version of vpx app is getting crashing on android 

### ISSUE THREAD

**Issue by PsyVHS77** [vpinball/vpinball#1510]
I try play a table on this New version of the app but any time I launch a table it crash a lot ?

**Comment by francisdb** [comment]
You'll have to provide more info to be able to debug this:

- What table were you playing?
- Are you using any patch script?
- Does it crash during game or on startup?
- And if possible adb logs, not sure we have some docs on getting those @jsm174 ?

**Comment by francisdb** [comment]
@toxieainc can we mark this with label `standalone`?

**Comment by PsyVHS77** [comment]
> > @toxieainc can we mark this with label `standalone`?
> 
> Well I try launch any tables form big shot to pitbot but it never launch at all and the pinmame folder is missing on android?

And I used the vpx mobile version of standalone version of vpx

**Comment by jsm174** [comment]
@PsyVHS77 - Hello. I missed cherry-picking a PR from the 10.8.1 branch in regards to the android builds.

Can you please try the build from here: https://github.com/vpinball/vpinball/actions/runs/8111110845
