### ISSUE TITLE
[RC1] DX & GL crash to desktop on exit when videos on playfield

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1511]
**Describe the bug**
Several users have reported this table crashes 10.8 RC1 with both GL and DX versions. It happens every time you a table running videos on the playfield or apron.  This does not occur with 10.7 versions.

Confirmed with these tables:
- Iron Maiden Legacy of the Beast PRO Tribute
- The Last Starfighter (1984)
- Johnny Mnemonic LE
- Pink Floyd (Pup version)
- Dragon's Lair

**To Reproduce**
Load table that has a Pup-Pack that place videos on playfield or apron
Run table
exit table (Q in VPX)

VPX zipped here... https://filebin.net/ersby8qm93yql0ew/Dragon_s_Lair.zip

**Expected behavior**
Exit back to editor

**Crash dump**
ZIP attached with Settings, Log, etc

**Versions & Settings**
 - VPX: 10.8 RC1
 - Windows version 11
 - RTX2060

[Log-Settings-Crash.zip](https://github.com/vpinball/vpinball/files/14464076/Log-Settings-Crash.zip)

**More Info**

Multi-users have confirmed this is a consistent (happen 99% of the time) when using VPX Beta8 or RC1 
VPX 10.7 seem to -not- have this problem.

We believe this is also causing Pinup Popper apps/processes do not close.

-- When VPX crashed, instead of existing back to the editor, two PinUp processes must be manually killed using Windows Task Manager or right-clicked / closed manually in the Windows notification area (lower right on task bar)

-- When VPX exits back to the edit cleanly those same PinUp processes close on their own, as expected.

**Comment by nailbuster** [comment]
@vbousquet seems current workaround/solution is to call this at start of table1_exit on the vpx flasher capturing the pup.

Screen.TimerEnabled=false    'timer to capture/update the flasher with screen scrape.
Screen.VideoCapUpdate=""   'force vpx to dispose texture/flasher 

vpx 10.7 didn't need this, so I'll assume it's the freeing of the videocap texture that crashes VPX editor/player.  Setting videoCapupdate="" (blank) in tablescript forces the capture texture to be freed within vpx.
