### ISSUE TITLE
Out of stack space: 'cb' script error

### ISSUE THREAD

**Issue by keithhov** [vpinball/vpinball#1529]
Getting scrip error on any version of back to the future.

Runtime error
-------------
Line: 1
Out of stack space: 'cb'

VPX version  1909,1910,1911,1912,1913.... pinmane version 864

**Comment by vbousquet** [comment]
This is a table script bug. Latest release will tell you about it (it was silently ignored before, likely breaking fastflips)

**Comment by keithhov** [comment]
correct, fixed by delelting line as vpx pop up suggests.
