### ISSUE TITLE
Add build number and SHA7 to the file properties

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/vpinball#1530]
**Is your feature request related to a problem? Please describe.**
When testing a lot of builds from the actions and you do not know anymore which version did you just install.

**Describe the solution you'd like**
If the build number and SHA7 is added to the file properties, it is just a right click away.

**Describe alternatives you've considered**
Alternative solution would be to name the VPinball.exe with the version and build included in the name

**Additional context**
I tested it on a fork:

![image](https://github.com/vpinball/vpinball/assets/12571104/93cb9858-e285-46d4-823a-a4f4a7aba3a7)
build number included in the File version and build number and SHA7 included in the Product version

**Comment by vbousquet** [comment]
> It does look like the `.rc` files can handle C/C++ preprocessing directives?
> 
> Maybe they could be leveraged? If not I guess we'd have to do it via the CI.

I think that an include should do the job. At least the reference seems to tell so: https://learn.microsoft.com/en-us/windows/win32/menurc/preprocessor-directives

**Comment by JockeJarre** [comment]
What I tried in my fork was just to add an update to the workflow in the rc file: 

```
          perl -i -pe's/(VALUE "ProductVersion", "\d+, \d+, \d+, )0/${1}${{ needs.version.outputs.revision }}-${{ needs.version.outputs.sha7 }}/' vpinball_eng.rc
          perl -i -pe's/(PRODUCTVERSION \d+,\d+,\d+,)\d+/${1}${{ needs.version.outputs.revision }}-${{ needs.version.outputs.sha7 }}/' vpinball_eng.rc
          perl -i -pe's/(VALUE "FileVersion", "\d+, \d+, \d+, )0/${1}${{ needs.version.outputs.revision }}/' vpinball_eng.rc
          perl -i -pe's/(FILEVERSION \d+,\d+,\d+,)\d+/${1}${{ needs.version.outputs.revision }}/' vpinball_eng.rc
```

But I explicitly added the build number and the sha7,

**Comment by jsm174** [comment]
Yeh, if possible I would rather not do it from the github action, but directly in the rc file.

There are four rc's:

```
vpinball_eng.rc
vpinball_fre.rc
vpinball_ger.rc
vpinballres.rc
```

Maybe you could `#include "vpversion.h"` in `vpinballres.rc` before those the other ones, maybe you can update each one to use the constants, ie maybe something similar to 

```
VALUE "FileVersion", VP_VERSION_STRING_COMMAS
VALUE "ProductVersion", VP_VERSION_STRING_FULL_LITERAL
```

you may have to update `vpversion.h` to have a `#define` that fits what you need as well.

**Comment by jsm174** [comment]
@JockeJarre - your change is now in master and 10.8.1 branches.

If you could quickly test, than we can close this issue.

**Comment by JockeJarre** [comment]
Works! 
Thanks @jsm174
