### ISSUE TITLE
Goldeneye bug report with every 10.8.0 beta's (master) after 1904

### ISSUE THREAD

**Issue by joco77** [vpinball/vpinball#1536]
Hi

With Goldeneye VPW 1.0 release : https://vpuniverse.com/search/?q=goldeneye&quick=1&type=downloads_file
"Every 10.8.0 beta's (master) after 1904  vbs scripts(dont know which .vbs file) cause this: Goldeneye-> you start a game -> flippers hit up automatically and stays there....i figured out vbs scripts doing this and the last working is the ones what included in version 1904 10.8.0 beta. So it's bad after 1904+ versions"
Thalamus mentioned it's same with Apollo 13 too, so maybe related to sega2.vbs.
Thanks.

**Comment by vbousquet** [comment]
I just had a look : the bug is on the table side: it's missing the `vpmInit Me` in Table_Init. It is also defining `PinMAMETimer.Enabled = 1` which it should not. I will close the bug report as this must be fixed on the table side, not VPX/VPM

**Comment by keithhov** [comment]
@joco77 

I just copied script lines from another table and it worked,,,, copied from addams family... didnt play long but flippers work....hopefully tables plays in full until script is properly fixed. 
	
vpmInit Me
	With Controller
		.GameName = cGameName
		If Err Then MsgBox "Can't start Game " & cGameName & vbNewLine & Err.Description:Exit Sub
		.SplashInfoLine="The Addams Family by Bally, 1992"
		.Games(cGameName).Settings.Value("rol") = 0
		.HandleKeyboard=0
		.ShowTitle=0
		.ShowDMDOnly=1
		.HandleMechanics=0
		.DIP(0)=&H00
		.ShowFrame=0
		On Error Resume Next
		.Run GetPlayerHWnd
		If Err Then MsgBox Err.Description
		On Error Goto 0
	End With

**Comment by passionforpins** [comment]
All thats needed is to add the vpmInit me above the With Controller line as below. This way you maintain the proper table info
Sub GoldenEye_Init
	PinMAMETimer.Interval = PinMAMEInterval
	PinMAMETimer.Enabled = 1
	SatTop.IsDropped=1
	SatTop1.IsDropped=1
	SatTop2.IsDropped=1
	On Error Resume Next
	vpmInit Me
	With Controller

**Comment by francisdb** [comment]
```diff
--- ./Goldeneye (Sega 1996) VPW 1.0/Goldeneye (Sega 1996) VPW 1.0.vbs.original	2024-03-08 15:54:20
+++ ./Goldeneye (Sega 1996) VPW 1.0/Goldeneye (Sega 1996) VPW 1.0.vbs	2024-03-08 15:57:04
@@ -176,12 +176,11 @@
 
 
 Sub GoldenEye_Init
-	PinMAMETimer.Interval = PinMAMEInterval
-	PinMAMETimer.Enabled = 1
 	SatTop.IsDropped=1
 	SatTop1.IsDropped=1
 	SatTop2.IsDropped=1
 	On Error Resume Next
+	vpmInit Me
 	With Controller
 		.GameName=cGameName
 		.Games(cGameName).Settings.Value("rol")=0
```
