### ISSUE TITLE
Regression - No sound after BASS lifecycle commit

### ISSUE THREAD

**Issue by Nicals** [vpinball/vpinball#1540]
**Describe the bug**
Since 89e7ad877, I don't have any sound on any table under Linux.

It seems that all tables are affected.

**To Reproduce**
1. Build VPX starting from commit 936fef5e4
2. Start any table
3. Notice the sweet sound of silence

**Expected behavior**
I expect tables to play sound, either music and sound FX from the rom or sound fx from VPinball.

**Screenshots**
N/A

**Crash dump**
N/A

**Versions & Settings**
 - VPX: 10.8.1 since 89e7ad877
 - Debian Linux, was reported to by Somatik on MacOS (discord server / vpx-standalone channel)
 - [Log from 89e7ad877, sound muted](https://github.com/vpinball/vpinball/files/14537421/sound-mute.log)
 - [Log from 1b6ec74fb, with sound, same table](https://github.com/vpinball/vpinball/files/14537432/sound-works.log)

**Additional context**

This seems to be related to 89e7ad877. I run some tables with the commits around this one and got this:

  + 89e7ad877 No Sound
  + 936fef5e4 Did not compile due to syntax errors
  + 1b6ec74fb I do have sound

**Comment by jsm174** [comment]
fixed in https://github.com/vpinball/vpinball/commit/4b7b466b3570dd5e6b5094e8aabe566cc72fa315
