### ISSUE TITLE
Password protection for Locking tables

### ISSUE THREAD

**Issue by workerb0y** [vpinball/vpinball#1555]
I'm one of the admins of a virtual pinball challenge group. 
It would be a useful function for us if the Table Lock option could be protected with a password. 
With this, we could prevent table modifications of the kind that could affect the gameplay, and thus the possibility of cheating would decrease. 
The default Lock option would be passwordless, and the user (in our case, the admin) could set his own password when locking the table.

Could such an option be feasible?

Thank you in advance!

**Comment by toxieainc** [comment]
Did you try out the new tournament mode feature?
See https://github.com/vpinball/vpinball/blob/bbfa053097de888366a5128c9e5892fb1edf59f6/txt/Changelog.txt#L209

Cause what you suggest can easily be worked around by doing a recompile of VPX with the password feature disabled.
Plus in general, i don't like the idea of locking tables, it had been a feature in the past and it just annoyed people (on average).

**Comment by workerb0y** [comment]
Okay, maybe you're right that it could cause a problem. 
Thanks for the tip, I looked and managed to export the txt file.
But what can I do with this txt?
Can I read any information about the table settings from this? 
If someone changes anything in the script or the Preferences menu, does it show up here? For this reason, Lock Password could be practical, so we could be sure that no one has changed anything. Unfortunately, I don't know anything about this tournament setting.

**Comment by workerb0y** [comment]
Ok, thanks a lot for the advice and explanation!
The only problem I have with this is that the versions have to match for it to work properly. This might cause problems on the part of the users (many people don't, or just find it difficult to update, as I've experienced). For this reason, I think that a Lock Password option would be a simpler and better solution for us, but for the reasons you also wrote, we should discard this proposal.
