### ISSUE TITLE
Add support for defining playfield monitor screen inclination per table

### ISSUE THREAD

**Issue by SmedleyB** [vpinball/vpinball#1556]
Would you consider adding support for overriding the default screen inclination setting in VPX with a setting per table?
This would allow for cab users to add devices that raise or lower the angle of the monitor to match that of the real table or at least match the glass angle as defined by the table author via the top and bottom glass heights in the .vpx file.

Ultimately this could be in support of another TBD program that would read that glass angle from a .ini file or calculate it per the .vpx table dimensions and then automatically raise or lower a programmable linear actuator to change the screen inclination automatically.

**Comment by PG248** [comment]
What devices are you referring to? I've never seen a VPin that has a variable playfield monitor angle.

The angle of the playfield can already be set individually for each table via the top/bottom distance from the glass.

**Comment by SmedleyB** [comment]
@PG248 TBD = to be determined., doesn't exist yet. I'd rather have a perfect pov than a bunch of lights, although you could just install your LEDs at the max angle and only drop your monitor from there, never raise.

**Comment by PG248** [comment]
I understand. On a 2D display adjusting the angle of the screen to match the angle of the real playfield is probably the best way to reach the perfect POV.
I went another route. I use a 3D TV mounted almost parallel and close to the glass and create the illusion of different playfield angles with the 3D perspective. POV wise I can't see a difference to the real cab next to it.

**Comment by SmedleyB** [comment]
Closing - VPX .ini does allow for table-level override of screen inclination.
