### ISSUE TITLE
VPinballX_GL-10.8.0-476-x86 - DXGI error

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpinball#156]
Version: VPinballX_GL-10.8.0-476-x86 and older

Today I tried to start a VR-table with external backglass and the following error occurs.
![grafik](https://user-images.githubusercontent.com/35002625/197798963-7c741c1e-e177-4590-8ca8-da162401467e.png)

It belongs to "Disable B2S" in the settings for Keys, Nudge and DOF.
If I start the table with checked "Disable B2S" everything works fine.
If you uncheck it, the DXGI error happens.

This happens also in versions before 476.

**Comment by studlygoorite** [comment]
Been doing this for a while, v350 is the same....will not play VR tables that require the b2s (you get the error above). If needed, let me know and I will go back through every build to see where this issue started.

**Comment by vbousquet** [comment]
Should be fixed as v545
