### ISSUE TITLE
Material not applied correctly in GL version?!?

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#1571]
**Describe the bug**
In DirectX version the metal rails look fine. In OpenGL version they are black.

**To Reproduce**
Bigus1' Breakshot table:
https://www.vpforums.org/index.php?app=downloads&showfile=14361

**Screenshots**
![2024-03-15 23_16_55-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/38ed8cf8-7f21-49f1-ad7c-a36b33b0685d)
![2024-03-15 23_17_25-Visual Pinball Player](https://github.com/vpinball/vpinball/assets/98708681/89693f0e-7015-4918-a378-7e11415d1f29)

**Versions & Settings**
 - VPX: 10.8.0 [beta6 and rev 1923 tested.
 - Windows version 11

**Comment by vbousquet** [comment]
Table bug: it has an incorrect shininess level largely over 1
