### ISSUE TITLE
POV Settings Broken

### ISSUE THREAD

**Issue by BostonBuckeye** [vpinball/vpinball#1573]
In the latest version of 10.8 version 1932 the POV settings numbers can only be increased. When you press the left flipper button the numbers still increase instead of decreasing. This is in both 64 bit versions of GL and DX. Version 1931 is fine.

**Comment by DanRoid** [comment]
Also applies to standalone linux version 1933.

**Comment by vbousquet** [comment]
Fixed in latest

**Comment by BostonBuckeye** [comment]
Thank you very much!
