### ISSUE TITLE
VPX 10.8 VR not capturing B2S correctly shows it semi transparent.

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpinball#158]
**Describe the bug**
When running vpx in vr mode the b2s backglass is transparent.

**To Reproduce**
Run with B2S enabled and have the b2s file with the vpx table.

**Expected behavior**
Have it capture the B2S clearly

**Screenshots**
![20221022_104853](https://user-images.githubusercontent.com/23017535/198892331-b4b8d731-75e9-4b40-9882-10f627833917.jpg)

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions**
 10.8

**Additional context**

**Comment by vbousquet** [comment]
Should be fixed in v545
