### ISSUE TITLE
Big Bang Bar

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/vpinball#1582]
Big Bang Bar now bloomed out on the latest version.
![bbb](https://github.com/vpinball/vpinball/assets/115115011/4173b7a1-9f85-4396-90bc-c4e4f3e3f1e2)

**Comment by Loadedweapon** [comment]
could be something else as even 10.7 looks like that..

**Comment by Jasonh1981** [comment]
> could be something else as even 10.7 looks like that..

Did you figure out what is wrong? I'm having this issue as well.

**Comment by Loadedweapon** [comment]
Was Vpinmame has been fixed

**Comment by toxieainc** [comment]
Yes, please update to latest PinMAME builds..
