### ISSUE TITLE
Since the 1930 version - Tables Options/Point of View - axis offset impossible to adjust (too fast movement)

### ISSUE THREAD

**Issue by aerao** [vpinball/vpinball#1583]
**axis offset impossible to adjust (too fast movement)**

Hi!
Since the latest versions of VPX, it's impossible to adjust offsets (vertical and horizontal), you can't adjust to the mm. An instant press makes me move the axis 3-4cm.

Are there new button assignments to adjust more slowly? or is it just a bug? a problem with my personnal settings ?

THX!

**Comment by francisdb** [comment]
Is the speed related to some other setting like cabinet setup values? I have seen something similar in the past.

**Comment by aerao** [comment]
I've just gone back to the 1930 version, and I'm having no problems with the settings.
I reinstalled the 1934 version (RC2), I have the bug, axis adjustment is impossible.

**Comment by francisdb** [comment]
Must be related to #1569

**Comment by aerao** [comment]
ok thanks I hadn't seen that

**Comment by Meshuggah70** [comment]
in RC2 the speeds of the actual adjustments are fine for me . Its just the Horizontal and vertical offset speed a 1/4 frame per button push

**Comment by jueank** [comment]
I updated to 10.8 RC2 and I can confirm that adjusting values in F12 menu (y offset, 'window top z offset' and 'window bottom z offset') are impossible to dial in. Jumping always multiples of mm, even if you try to close the flipper contact of only for one hundredths of a second. I'm using cabinet mode, exclusive fullscreen.
In the longer term, it might be worth trying a different editing mode. e.g. a 'single step' (+/- 0.1mm with each flipper button press. the user has to release & press again for the next step) and a continuous mode (like now, keep changing the value while the flipper button is pressed)

**Comment by Meshuggah70** [comment]
> I updated to 10.8 RC2 and I can confirm that adjusting values in F12 menu (y offset, 'window top z offset' and 'window bottom z offset') are impossible to dial in. Jumping always multiples of mm, even if you try to close the flipper contact of only for one hundredths of a second. I'm using cabinet mode, exclusive fullscreen. In the longer term, it might be worth trying a different editing mode. e.g. a 'single step' (+/- 0.1mm with each flipper button press. the user has to release & press again for the next step) and a continuous mode (like now, keep changing the value while the flipper button is pressed)

For the most part the problems in RC2 were fixed in the very next  build release. everything else was fine and still the offset was an issue. this is what this ticket is for.. im on Build # 1940 now and either it has gotten better or I have gotten used to the touchiness of the offset adjustment..

**Comment by Denys06** [comment]
where have you download version 1940  please ?

**Comment by Meshuggah70** [comment]
It's on the GitHub page  under actions and it's the first "master" for 10.8
as of this morning. May be a newer now

**Comment by jueank** [comment]
@Meshuggah70 Thanks for the information. I updated to build 1940. I can also confirm that it's fixed for 'window top z offset' and 'window bottom z offset'. Setting 'y offset' is still very sensitive.
