### ISSUE TITLE
Goldeneye Sega VPW 1.0 Flippers Are Stuck in the UP Position

### ISSUE THREAD

**Issue by LukeImYourFasia** [vpinball/vpinball#1585]
**Describe the bug**

Goldeneye Sega VPW 1.0 Flippers Are Stuck in the UP Position

**To Reproduce**

1. Use goldeneye, I think any version but VPW for sure
2. Start Game
3. Shoot Ball
4. See flippers stuck in Up Position

**Expected behavior**
Flippers not stuck and ussable.

**Screenshots**
NA

**Crash dump**
NA

**Versions & Settings**
 - VPX: [10.8 RC1] Standard settings
 - Windows 10
 - GPU and video settings NA
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here) I'll drop it laters as its not related.
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**
This is related to the scripts file. If I copy an older version of the scripts folder  for example beta 8 of scripts the game works with no problem.
I use the same scripts folder for 10.7.4 and same problem happens.
I haven't done a diff yet but I'm sure a change in one of the recent scripts is the cause.

**Comment by Joey-2001** [comment]
Open the script. Add the following line in the table1_init section:

vpminit me

The stuck flippers also happens at some other Data East tables. It's always the missing line.

**Comment by francisdb** [comment]
duplicate of #1536

**Comment by Spacegoogie** [comment]
@Joey-2001  Thank you!
I was pulling my hair out.

**Comment by Mclaneinc** [comment]
What script please..Just starting off, looked in the scripts folder but no clue how or where you do it apart from using Notepad+

**Comment by Urkz** [comment]
Cheers for solution  i had this problem.

**Comment by Urkz** [comment]
> **EDIT: Sussed it out..All fine now...Its painful having to learn at my age :)**
> 
> What script please..Just starting off, looked in the scripts folder but no clue how or where you do it apart from using Notepad+
> 
> Apologies for a newbie question, but once I know I'll not ask it again..

When you launch VPX editor there is a box tab to click with a scroll symbol on it , the script in question is found when you click on that.
