### ISSUE TITLE
Crash/SIGSEV on table exit

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1591]
10.8.1 branch

```
PinTable::FireDispID vpinball_standalone_i_proxy.cpp:4162
EventProxyBase::FireVoidEvent eventproxy.h:14
Player::OnClose player.cpp:694
Player::FinishFrame player.cpp:2148
Player::OnIdle player.cpp:1949
VPinball::MainMsgLoop vpinball.cpp:1601
VPApp::Run main.cpp:1125
WinMain main.cpp:1366
main main.cpp:1401
```

![image](https://github.com/vpinball/vpinball/assets/161305/1ea9acd0-73c7-468b-a7ed-5861b04745cb)

**Comment by jsm174** [comment]
Standalone needs `g_pplayer` so it can fire the `DISPID_GameEvents_Exit`.

This issue was introduced in: https://github.com/vpinball/vpinball/commit/8de7cd89295368274921299bf69a20a0730b177a

It sets `g_pplayer` to `null` before the call to `FireVoidEvent`

Not sure @vbousquet if this would be okay for Windows, so I temporarily put `ifdef` around it:

https://github.com/vpinball/vpinball/compare/541932957656fab96fdde6e4448d6f4dba24e89b..f56b4b58d21adf63ffe5cef393b0526003ec16ee

**Comment by francisdb** [comment]
```
Renderer::IsUsingStaticPrepass Renderer.cpp:1264
Player::OnClose player.cpp:710
Player::FinishFrame player.cpp:2153
Player::OnIdle player.cpp:1954
VPinball::MainMsgLoop vpinball.cpp:1601
VPApp::Run main.cpp:1125
WinMain main.cpp:1366
main main.cpp:1401
```

![image](https://github.com/vpinball/vpinball/assets/161305/61b009d3-6924-4925-9601-8ed919751806)

**Comment by francisdb** [comment]
This was for `White Water (Williams 1993) v.1.2.vpx` 
https://vpuniverse.com/files/file/17705-white-water-williams-1993-v12/

But I have it with all tables

**Comment by jsm174** [comment]
@vbousquet  - this has to be an issue on windows too?

```
    if (m_detectScriptHang)
        g_pvp->PostWorkToWorkerThread(HANG_SNOOP_STOP, NULL);
#ifdef __STANDALONE__
   g_pplayer = nullptr;
#endif

   // Save list of used textures to avoid stuttering in next play
   if ((m_ptable->m_settings.LoadValueWithDefault(Settings::Player, "CacheMode"s, 1) > 0) && FileExists(m_ptable->m_szFileName))
   {
      string dir = g_pvp->m_szMyPrefPath + "Cache" + PATH_SEPARATOR_CHAR + m_ptable->m_szTitle + PATH_SEPARATOR_CHAR;
      std::filesystem::create_directories(std::filesystem::path(dir));

      std::map<string, bool> prevPreRenderOnly;
      if (!m_renderer->IsUsingStaticPrepass() && FileExists(dir + "used_textures.xml"))
      {
 ```
 
`IsUsingStaticPrepass()` also uses `g_pplayer`:

```
bool Renderer::IsUsingStaticPrepass() const
{
   return !m_disableStaticPrepass && m_stereo3D != STEREO_VR && !g_pplayer->m_headTracking;
}
```

**Comment by toxieainc** [comment]
Can confirm. The latter also happens e.g. on VPX 10.8.1 DX.

**Comment by francisdb** [comment]
Commit 9cd01e6
