### ISSUE TITLE
Standalone 10.8.1 - crash on exit (B2SPictureBox)

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1605]
Table:
https://vpuniverse.com/files/file/10011-wacky-races/
Backglass:
https://vpuniverse.com/files/file/13199-wacky-races-original-2022-b2s-with-full-dmd/
Patch:
https://github.com/jsm174/vpx-standalone-scripts/tree/master/wackyraces

```
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
B2SPictureBox::SetVisible B2SPictureBox.h:28
PictureBoxAnimation::LightGroup PictureBoxAnimation.cpp:311
PictureBoxAnimation::PictureBoxAnimationTick PictureBoxAnimation.cpp:255
VP::Timer::TimerCallback Timer.cpp:11
```

![image](https://github.com/vpinball/vpinball/assets/161305/d8105d8c-fab7-43dc-97c1-a18dc8187253)

**Comment by francisdb** [comment]
Still happens.
https://virtual-pinball-spreadsheet.web.app/game/6t0bWHR24a (DUNE)

**Comment by jsm174** [comment]
Can you try again please with the latest?

**Comment by francisdb** [comment]
Still same issue

```
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
Control::IsVisible Control.cpp:51
B2SPictureBox::SetVisible B2SPictureBox.h:28
PictureBoxAnimation::LightGroup PictureBoxAnimation.cpp:311
PictureBoxAnimation::PictureBoxAnimationTick PictureBoxAnimation.cpp:255
VP::Timer::TimerCallback Timer.cpp:11
```

**Comment by francisdb** [comment]
![image](https://github.com/vpinball/vpinball/assets/161305/1456f309-2d34-4553-a5ba-7f662a9903bc)

**Comment by jsm174** [comment]
new build in the pipeline, if you could check that out when its done..

**Comment by francisdb** [comment]
Process finished with exit code 0 👏
