### ISSUE TITLE
Batman 66 - PUP will not close out with RC2

### ISSUE THREAD

**Issue by WaRcLaWz** [vpinball/vpinball#1608]
**Describe the bug**
The Batman 66 table will not close out the PUP Pack videos on the backglass and DMD, and the music continues after the table closes in VPX. It works fine with all 10.8 versions including RC1, but stopped working in RC2.

**To Reproduce**
1. Run the Batman 66 table using RC2 32bit or 64bit
2. Quit the table
3. The PUP Pack continues playing

**Comment by DomiKamu** [comment]
From **Task Manager**, VPX's exe continues to run as background task (visible from **Details** tab).

**Comment by Joey-2001** [comment]
Can't confirm this. I play with the GL v1942. VPX and PupPack closes correct.

**Comment by vbousquet** [comment]
It's ok on my side as well. Note that if you are using PinballY, there is a bug on the way it handles the close message, so you need to diable the ESC key on Pinball Y for things to works correctly (PinballY kills VPX before VPX closes everything properly)

**Comment by vbousquet** [comment]
Without further informations, 2 testers with bug not reproduced, and one possible cause (PinballY) which has been solved (on PinballY and VPX side), I will close this issue. Just tell if it's still there
