### ISSUE TITLE
VPinballX_GL-10.8.0 x86 malware reported Win32:MalOb-IJ [Cryp]

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#161]
Since last week the x86 -GL release Avast has been throwing this warning and aborting the connection. I reported to toxie and vincent via vpforums and submitted to Avast for further investigation. Their response below shows it is an infected file;

Thank you for contacting Avast and reporting a false positive detection. I'm happy to help.

Along with the Avast virus specialist, we’ve confirmed that this detection is correct.

If you are the owner of the reported file or website and you want to change the detection to clean, feel free to contact us again for a new analysis as soon as it matches the [Avast Clean Guidelines](https://support.avast.com/en-in/article/Threat-Lab-clean-guideline).

Thank you for understanding.

I hope you have a nice day, and stay safe online.

Ondrej
Avast Customer Care Team

**Comment by jsm174** [comment]
Hello. Can you get the specific version where it started rather than last week?
It's much more helpful when trying to track things down.

FWIW, all the code is built here in the workflows and is not externally manipulated.

**Comment by passionforpins** [comment]
VPinballX_GL-10.80-472-2821e2a-Release-gl-win-x86

**Comment by passionforpins** [comment]
For what its worth the x64 downloads fine. Only the x86 version seems affected

**Comment by jsm174** [comment]
okay, that screen shot shows me that it's not `VPinball_GL.exe` but rather the `SDL2_ttf.dll`. I think SDL2 was recently updated in the repo. I will check around that time.

**Comment by jsm174** [comment]
Looking at the repo, `SDL2_ttf.dll` was updated 8 days ago [here](
https://github.com/vpinball/vpinball/commit/437d0d2d0497e522197bffce73e99ee5a90258f2)

That was build [459](https://github.com/vpinball/vpinball/actions/runs/3308334258).

Can you check if your avast catches that?

**Comment by passionforpins** [comment]
Yep. Avast stops the download of 459 with the same warning

**Comment by jsm174** [comment]
Okay, perfect. Thanks @passionforpins 

@toxieainc, @vbousquet  - Where do we get the latest SDL2 binaries from?

**Comment by toxieainc** [comment]
Please recheck

**Comment by toxieainc** [comment]
@jsm174 : https://github.com/libsdl-org/SDL/releases and https://github.com/libsdl-org/SDL_ttf/releases/

**Comment by passionforpins** [comment]
downloaded successfully with no warnings from Avast. all clean- thanks

**Comment by jsm174** [comment]
awesome. Thanks everyone!
