### ISSUE TITLE
Guns N Roses VPW - No lights when using RC2

### ISSUE THREAD

**Issue by WaRcLaWz** [vpinball/vpinball#1610]
**Describe the bug**
The Guns N Roses VPW table has no lighting when opened with 10.8 RC2.

**To Reproduce**
1. Open the Guns N Roses table using RC2 64bit
2. No lights

**Comment by dacstyle** [comment]
I have the same problem with release 1942.
Reverted to 1873 and lights works again.
I don't know exactly in which release the problems start.

**Comment by francisdb** [comment]
I can confirm this issue on 10.8.1, flashers work, no insert lights

![image](https://github.com/vpinball/vpinball/assets/161305/3f3b3344-91ec-4ac3-ade3-e2d33a67a2d0)

**Comment by vbousquet** [comment]
This is a known table issue. Not VPX
