### ISSUE TITLE
Question: Is it possible to import the exported VB script back into the VPX file?

### ISSUE THREAD

**Issue by syd711** [vpinball/vpinball#1614]
VPX supports to export the script via command line, but I did not find an option to import it back.
For my tool VPin Studio I got often ask if it is possible to change tables from remote.
This would be possible with the option to import the script back.

**Comment by francisdb** [comment]
[vpxtool](https://github.com/francisdb/vpxtool) can do that

```
vpxtool importvbs test.vpx
```

But I personally prefer to not mess with the original table file and keep the sidecar vbs

**Comment by francisdb** [comment]
> That sounds pretty cool. I forgot that that you build something like that. But what do you mean with sidecar vbs? So it isn't save to export from the original table and import with your tool? Or are you afraid that you have messed up the script?

No I can guarantee you can export and import with my tool without issues. Also export using vpxtool is [much faster](https://github.com/vpinball/vpinball/issues/814).

I personally like to keep the vpx file in it's original form and keep the modified `[tablename].vbs` next to it. In some place this is called a sidecar vbs. We use this a lot in vpinball standalone where quite some tables [need patches to run properly](https://github.com/jsm174/vpx-standalone-scripts).

**Comment by syd711** [comment]
Closing this issue - will use the vpxtool for this.
