### ISSUE TITLE
TrailStrength and BallTrailStrength methods not working, VPX error out when using.

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1615]
**Describe the bug**
Cannot get Trail intensity settings to work/set in script. VPX throws error using both documented here... https://github.com/vpinball/vpinball/blob/master/txt/CommandReference.txt

TrailStrength(int)

BallTrailStrength(int)

Command Reference has both of these listed in separate places... TrailStrength under variables // BallTrailStrength under changelog for 10.1

When trying to use in script (table init) I get these errors...

```
Object doesn't support this property or method: 'table1.TrailStrength'

Object doesn't support this property or method: 'table1.BallTrailStrength'
```

**To Reproduce**
I tried both methods inside table1_init in table script

table1.BallTrail = 100 
table1.BallTrailStrength = 100

**Expected behavior**
set values, via table script, per info from https://github.com/vpinball/vpinball/blob/master/txt/CommandReference.txt

**Versions & Settings**
 - VPX: 10.8 RC1 and RC2
 - Windows 11

LOG and INI attached in ZIP
[VisualPinball-RC2_Log_INI.zip](https://github.com/vpinball/vpinball/files/14806046/VisualPinball-RC2_Log_INI.zip)

**Comment by Ltek** [comment]
@francisdb would you be able to take a quick look at this and LMK if there is a workaround or a quick fix? Working on a table with MerlinRTP and Oqqsan and being able to set, in script at Init or dynamically (most desired), the largest ball trails we can is important to the theme. 
also related... https://github.com/vpinball/vpinball/issues/1616
and, ideally we'd like to make them larger than the current max allowed...  https://github.com/vpinball/vpinball/issues/1563

**Comment by francisdb** [comment]
Have you tried this?

```vbs
table1.BallTrail = 100
table1.BallTrailStrength = 100
```

https://github.com/vpinball/vpinball/blob/51e53475359ff2e36ac7b11cfd3f6eae8d4021d6/src/parts/pintable.cpp#L8707-L8735

This setting seems to be cached in the player so you probably need to restart the table to see it applied. Also it does not seem to be capped to 100 in that code.

https://github.com/vpinball/vpinball/blob/51e53475359ff2e36ac7b11cfd3f6eae8d4021d6/src/core/player.cpp#L133

But then this value is probably not saved unless the user goes to the tweak menu and saves with `start/1`?

The best fix would probably be applying this setting to the player on modification?

**Comment by Ltek** [comment]
Would you be able to change this to make the value settable in table script... and increase the strength? I'd be happy to test as I'd like to release the table soon. Table should go beta in a week or less.

As for the setting value... I can assure you I tested heavily and setting anything above '1' in the INI only shows the ball trail the same as '1'; even on the brightest white glowing ball (table has 15 glowing ball color options). 

I hope table settings/options would be exposed to table scripts, no matter where they are stored. If thye are not table authors cannot use existing functionality. Plus, the lack of consistency is challenging especially for us new authors... by default assume that if its documented, its available for use.  

In this case the author cannot control it but it exists... players must manually change the table's INI (most tables do not have a tweak menu) to get the tails to work. This ball trails are a key design feature for this theme (Tron). With Darkest Dungeon, Oqqsan had to create a very complex code set to mimic ball trails and ball glows because the built-in settings do not work as expected. His code doesnt work for my new table since DD had a very dark theme, Tron is very bright, and we are trying to build completely different code... we've been working on it for 2 weeks. We would not need it at all _**if**_ we can control built-in tails from inside the script and make them larger/longer/brighter.

**Comment by stevejones72** [comment]
How would the more global player settings for Ball Trails work with Ball specific settings? Would ball specific settings override player settings given the designer / scripter is deliberately asking for them to be rendered?

**Comment by Ltek** [comment]
> How would the more global player settings for Ball Trails work with Ball specific settings? Would ball specific settings override player settings given the designer / scripter is deliberately asking for them to be rendered?

I'm not sure I understand your question - please provide more detail.

The ask is to be able to set in the script - which it cannot be currently.

So it would act just like all other settings... order of precedence: VPX UI < Script defaults < User Settings (which only work when used by the script)

**Comment by stevejones72** [comment]
You phrased your answer much better than my question Ltek, yes I was trying to work out an order of precedence.

**Comment by Ltek** [comment]
@vbousquet thank you!
