### ISSUE TITLE
BallTrailStrength values are not working as documented in CommandReference

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1616]
**Describe the bug**
https://github.com/vpinball/vpinball/blob/master/txt/CommandReference.txt says 0 to 100

When using any value greater than 1 the strength is always 1

ball trail strength in IN -or- VPX's UI (under Preferences) will accept any value but ONLY any over 1 doesnt do anything different than setting to 1

**To Reproduce**
Set VPX Preferences to 1 and to any value above 1... see when playing the are identical
Set table's INI to 1 or any value above 1.... see when playing the are identical

**Expected behavior**
1. Please settle on and document what values are acceptable
2. use a field check in VPX UI (preferences) to ensure only acceptable values are allowed to be entered.
3. use INI check to change any  'out of range' value to the nearest acceptable value

**Versions & Settings**
 VPX: 10.8 RC1 and RC2

**Comment by vbousquet** [comment]
Command Reference is about vbs values, not the UI (and saved in ini) values.
It happens that the VBS property is a percent while the UI is a floating point value.
