### ISSUE TITLE
RC2 - Scripts folder breaks High Roller Casino

### ISSUE THREAD

**Issue by WaRcLaWz** [vpinball/vpinball#1618]
**Describe the bug**
After installing the VPX RC2 version the table named High Roller Casino will freeze after loading, and will crash with a syntax error on Line 1, even if the table is not actually running on RC2.

After some troubleshooting it was discovered that the Scripts folder provided in the RC2 update was the issue. When replacing the Scripts folder with the one from RC1 or from 10.8 beta 8, the issue resolves.

**To Reproduce**
1. Install RC2 by copy/pasting the exe, dll's, and Scripts folder
2. Run the High Roller Casino table using any version of VPX 10.7 or 10.8
3. After the ROM loads the table will freeze
4. Alt-Tab and find that the script crashed with a syntax error on Line 1.

**Comment by francisdb** [comment]
There have been fixes after RC2 for solenoid callbacks.

You could try a more recent build or just pick the latest `core.vbs` from https://github.com/vpinball/vpinball/blob/master/scripts/core.vbs

**Comment by vbousquet** [comment]
Just tested this version : https://www.vpforums.org/index.php?app=downloads&showfile=14586
with latest master build and it worked fine. Note that I also had the latest VPinMame.
I think this was solved by https://github.com/vpinball/vpinball/commit/dace567b070d078cc8b3b6354494f7a0cb31a111
I will close for now
