### ISSUE TITLE
Cactus Canyon Continued RC2 Issue

### ISSUE THREAD

**Issue by bismark-0610** [vpinball/vpinball#1623]
When running RC2, Cactus Canyon Continued (P-ROC edition) will not drop the ball into the shooter lane. Confirmed this behavior with several different versions of CCC until I reverted back to RC1. RC1 still works.

**To Reproduce**
1. Run CCC with RC2
2. Start game

Use the latest VPW version

**Expected behavior**
I expect the ball to come out to start play

**Comment by vbousquet** [comment]
Duplicate https://github.com/vpinball/vpinball/issues/1578
