### ISSUE TITLE
SIGSEGV in PluginHost::PluginInit

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1629]
10.8.1 branch standalone Linux x64

Fairy Favors 1.0
https://www.vpforums.org/index.php?app=downloads&showfile=18322
(downloaded whole dropbox folder, see table description)

Signal: SIGSEGV (Segmentation fault)

```
__gnu_cxx::__normal_iterator::__normal_iterator stl_iterator.h:1077
std::vector::begin stl_vector.h:871
PluginHost::PluginInit PluginHost.cpp:44
Server::Run Server.cpp:279
Server::Invoke b2s_i_proxy.cpp:300
IDispatch_Invoke oaidl.h:896
disp_call vbdisp.c:1943
do_mcall interp.c:784
interp_mcallv interp.c:811
exec_script interp.c:2606
exec_global_code vbscript.c:196
exec_queued_code vbscript.c:207
VBScript_SetScriptState vbscript.c:735
CodeViewer::Start codeview.cpp:1607
Player::Init player.cpp:1216
Player::OnInitialUpdate player.cpp:663
Player::CreateWnd player.cpp:562
PinTable::Play pintable.cpp:2570
VPinball::DoPlay vpinball.cpp:1050
VPApp::Run main.cpp:1122
WinMain main.cpp:1366
main main.cpp:1401
__libc_start_call_main 0x00007ffff4828150
__libc_start_main_impl 0x00007ffff4828209
_start 0x0000555555676065
```

**Comment by francisdb** [comment]
Sam issue on https://vpuniverse.com/files/file/19459-full-house-williams-1966vpx/

**Comment by francisdb** [comment]
Tried fixing this but giving up. Things are initialized/cleaned all over the place.

**Comment by jsm174** [comment]
Sorry, I thought on discord I said I would get this fixed.

I will do it tonight.

![Screenshot 2024-04-09 at 3 01 21 PM](https://github.com/vpinball/vpinball/assets/1197137/2aba4ff1-57d8-45cc-8700-ffc1552b1e26)

**Comment by jsm174** [comment]
I believe I fixed this in the most recent commits. Can you please test?

**Comment by francisdb** [comment]
Thanks @jsm174 Confirmed filed.
