### ISSUE TITLE
Frequent lag when hitting flip buttons

### ISSUE THREAD

**Issue by vync79** [vpinball/vpinball#1642]
**Describe the bug**
First fo all I am a big fan of the work you did with 1.8.x ! 

With VPX 1.8.0 RC2 I noticed a regression which does not seem specific to any given table.

There is now quite frequently an ~1 second lag when hitting the flips button (I would say happening 5-10 times during a ball) which makes a little difficult to play. 

I reverted back to 1.8.0 RC1 and the lag is gone.  (However with RC1 I had sometimes a  3-4 seconds black screen issue during the game which is no longer happening with RC2).

**To Reproduce**
Play any table... For example Tales of the Arabian Nights.

**Versions & Settings**
 - VPX: 1.8.0 Candidate 2 / OpenGL / Release mode / 32bits
 - Windows 11
 - GPU : Nvidia RTX4070 Ti

 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Comment by toxieainc** [comment]
@vync79 Please retry with VPX 10.8 RC3 and a recent PinMAME build, too (incl. updated scripts).

**Comment by vync79** [comment]
> @vync79 Please retry with VPX 10.8 RC3 and a recent PinMAME build, too (incl. updated scripts).

Thanks for the quick answer.
I did install the RC3 and also updated the VPinMame to the latest 3.6 x86 build available on GitHub.
It did significantly improve as I no longer encountered lags when hitting flipper buttons on TOTAN or Junkyard. 
However with Junkyard (not with TOTAN), there was a black screen for 3 seconds after every ball loss. Not really an issue preventing me from playing given it happens between 2 balls, but I never experienced this with former releases...

I will do some more testing with other tables tomorrow.

**Comment by WaRcLaWz** [comment]
Something to try: I experience a very similar issue with many tables, where the flippers will be laggy or sticky, and/or the table will stutter with low framerate. The fix for me has always been to right-click on the backglass, click the "Run as EXE" button, or whatever it is called, to disable that feature, then save and restart the table. I know it sounds counter-productive, but it fixes those issues for me on those tables. It's like a light switch, where everything will become super smooth and flippers will work beautifully.

**Comment by vync79** [comment]
I did some more testing and found that for any reason my windows pincab was not set to max performances as power option. Given that I am playing on a 4k playground @ 120fps, it most likely deserve max performances.
So I set it to max performances and here is what I observed:
1- the lags and black screen are no longer visible
2- if I start a table without first exiting fully VPX then it randomly creates issues like error popups at loading about textures not being loaded or lags during game. However when starting the same table after restarting fully VPX, it works fine.

So if noone else experiences lags or black screen with RC3 I suppose you may close this issue. 

For the point 2 above, do you think there are memory leaks or missing clean up in VPX when closing a table ?
