### ISSUE TITLE
Unable to Open/Edit Script for Eight Ball Deluxe in VPX 10.8.0 Rev 1947 64 Bit

### ISSUE THREAD

**Issue by bernarma** [vpinball/vpinball#1647]
When opening Eight Ball Deluxe Bally 1981 released by Bord in the VPX Editor, I am unable to open the Script and make changes to the variables. I am able to make changes on other tables and have been able to use v10.7 to edit the script.

Version: v10.8.0 Beta (Rev 1947), windows OpenGL 64 Bits

**Comment by bernarma** [comment]
![Screenshot 2024-04-10 103923](https://github.com/vpinball/vpinball/assets/6805182/e3f7831a-08ad-4904-ae0f-3b2341dd3a81)

You can also see that quite a lot of the options are greyed out / disabled.

**Comment by bernarma** [comment]
This is using 10.7 - see the options are all enabled.

![image](https://github.com/vpinball/vpinball/assets/6805182/9bb1f6ef-bd3d-4e77-a4c2-f866a329e3a6)

**Comment by Joey-2001** [comment]
I'm not at my PC, but I think, the table is locked, like many other tables from VPW or team members.
So go to the menu and unlock the table.

**Comment by bernarma** [comment]
You're correct. I never knew this feature existed. I'll withdraw the bug. Many thanks.
