### ISSUE TITLE
Flips stuck up

### ISSUE THREAD

**Issue by Moussounet** [vpinball/vpinball#1650]
Hi !

About the VPX 10.8 RC3 : 

With the table Golden Eye  [https://vpuniverse.com/files/file/10040-goldeneye-sega-1996-vpw-mod/page/2/?tab=comments#comment-19157](url) , at the beginning of a game, the flippers are always in the high position, and nothing happens when I press a flip button.
Some report the same bug with the Apollo 13 table, although I didn't notice this bug with this table.

**Comment by francisdb** [comment]
Duplicate of https://github.com/vpinball/vpinball/issues/1536

**Comment by mazjohn** [comment]
this issue is happening again on latest build of this post - vpminit me does not fix the issue on Stern Lectronimo. its already in the script.
