### ISSUE TITLE
Regression - 10.8.1 - standalone - Tabe window positioning

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1669]
**Describe the bug**

```ini
FullScreen = 0
WindowPosX = 
WindowPosY = 
Width = 1080
Height = 1920
BGSet = 1
```
Previously the table window was by default positioned in the center of my main monitor (`1`), now it's positioned on my secondary monitor (`2`).

I tried to correct this using `WindowPosX` and `WindowPosY` settings but these are not applied, this was already the case before (could be related to using Wayland as display server?). 
The `Width` and `Height` settings work.

This must be related to recent changes in window code. Going back to b6f255bed21861d27f5a42e8688aab57faef65b7 fixes the issue.

![image](https://github.com/vpinball/vpinball/assets/161305/0fbe5a26-ec54-4a6f-8b56-6c3aa03a5ef2)

**Comment by vbousquet** [comment]
Standalone was missing the window positioning, so I added it lately. It is now supposed to work like for regular builds. To select the output, you need to define the `Display` in your settings file. The window will be placed at the centered as a default. You can drag it like for windows and the position should be restored. Though, all of this is untested by lack of time and a linux machine to do so. Position of the main window is defined in the settings as `PlayfieldWndX` & `PlayfieldWndY` settings

**Comment by francisdb** [comment]
Setting `Display = 0` fixed the issue for me. I do wonder why the default is something else.
`PlayfieldWndX` and `Y` also works :+1: 

So all that's left is documenting the new fields in [Default_VPinballX.ini](https://github.com/vpinball/vpinball/blob/10.8.1/src/assets/Default_VPinballX.ini)

**Comment by vbousquet** [comment]
The default is to used the display defined as the `primary` display (the one which contains the logical coordinates 0,0). It seems is the other one on your setup. `Display` is already documented and has been there for years. The new window positioning are not stabilized yet (they are supposed to allow positioning of more than one output, this is in progress)

**Comment by francisdb** [comment]
One more issue

If I set `PlayfieldWndX =` it's considered 0 instead of not set. I actually have to remove the setting declaration. So adding a default empty value would break display-based positioning.

**Comment by francisdb** [comment]
> The default is to used the display defined as the `primary` display (the one which contains the logical coordinates 0,0).

Yes in my case the configured primary is the right display and the assumption that 0,0 is on the primary display is incorrect. Not a big deal though.

**Comment by vbousquet** [comment]
It's difficult for me to test this (don't have a linux setup at hand). If you have some time to do some stepping through https://github.com/vpinball/vpinball/blob/51b6f978a20defb553342f77b1afb476abac0dda/src/renderer/Window.cpp#L95 and the following lines, it may help to understand why it does not behave on Linux the same as other platform

**Comment by francisdb** [comment]
Never mind, I can't reproduce any more, must not have been on the last commit. All good.
Thanks for all the cleanup efforts.
