### ISSUE TITLE
Backdrop/glass elements off

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#167]
**Describe the bug**
Some tables (e.g. IT, and VPWs Machine Bride of Pinbot) backdrop displays are offsetted/weirdly scaled.

**To Reproduce**
Download mentioned tables from VPU.
Tested with GL.

**Versions**
 - VPX:  10.8.0 Revision 504
 - Windows 10

Thanks!

**Comment by studlygoorite** [comment]
FYI (with v504), I see no issue with It or Machine BOP's backglass through my headset the Meta Quest Pro :) but I do have troubles launching Machine BOP since it came out with several builds, it (It) launches half of the time and sometimes without ROM sounds.
