### ISSUE TITLE
regression - 10.8.1 - standalone - macOS HiDPI issues

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#1672]
```ini
FullScreen = 0
Width = 540
Height = 960
BGSet = 1
```

The table window is now rendered like this)

<img width="547" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/d6c97a86-9520-4dab-b562-620613e4c1e3">

Tweak UI is rendered correctly

<img width="547" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/8db8e5f0-71e5-45f5-b54f-9b99b4118130">

**Comment by vbousquet** [comment]
@francisdb I have just pushed a quick and dirty hack for this (as the real fix will be when we will mode to SDL3 which should not be too long now that its beta is out). Could you give it a try ?

**Comment by francisdb** [comment]
Seem to do the job

<img width="594" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/f356c8c5-8e6b-4462-80ff-478edc2363a1">

**Comment by francisdb** [comment]
@vbousquet there is one more issue, mouse input in the tweak menu is not translated from HiDPI. 

Want me to create a new issue?

https://github.com/vpinball/vpinball/assets/161305/ef8a5bf9-bbf2-4a9d-886c-ce89ccfa80c1

**Comment by francisdb** [comment]
All long fixed.
