### ISSUE TITLE
SCRIPT button / Menu Option greyed out

### ISSUE THREAD

**Issue by bele20097** [vpinball/vpinball#1695]
Trying to edit script for Spider-Man (VPW) to change rom name.

Script button and Menu option as not available. Tried RC3 64-bits, x86, debug and release versions. All exhibit the same problem. Tried RC1 versions with the same issue.

I am able to edit the script in VPX 10.7 but saving it then messes up with the file so this is not an option.

**To Reproduce**
1. Open VPX RC3
2. Load "Spider-Man Vault Edition (Stern 2016) VPW.xpx"
3. View -> Script
4. See Script option not available

**Versions & Settings**
 - VPX: 10.8.0 Beta (Rev 1947 (3b3f101) Open GL 64 bits
 - Windows version : W11
![image](https://github.com/vpinball/vpinball/assets/8573463/e754bae9-7016-4306-a46c-3f39440172d5)

**Comment by Joey-2001** [comment]
That's not a bug. The table is locked, like other new tables from VPW.
Unlock the table in the menu and you can edit the script.
