### ISSUE TITLE
Options Menu selection changes 10x too fast to use unless you are the Flash.

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1696]
Options Menu (F12 tweak menu) changing the selection inside a row/option (an array choice inside a given option) the change from selection-to-selection is 10x too fast, impossible to control when the array has a lot of options/choices.
Examples:
Day/Night
Table's Vertical position
large Author created lists (20+ selection choices - I have a table with multiple options that have 20+ in the array) .

Please fix, this is a huge issue not being able to even accurately set table adjustments.

**Versions & Settings**
 - VPX: 10.8 RC3
 - Windows 11

**Comment by Ltek** [comment]
@francisdb please look at this, its been a huge issue for a few RCs now. I cannot believe no one else has posted this prior to me. setting the options is impossible if there are many choices... like setting the playfield's vertical position, it shoots up/down, unlike horizonal which is nice an slow left/right

**Comment by francisdb** [comment]
I fear I'm not the person to ask, if I remember correctly there was an update to make these changes go faster over time. So short presses should not go over multiple values. I do have the impression that it's not working as it should. @vbousquet is this a known issue?

https://github.com/vpinball/vpinball/commit/0547502f9d6ad2fab3d6c801e84298522ffb57c6

Do you know any table that has many options in an array?

**Comment by Ltek** [comment]
> Do you know any table that has many options in an array?

the hyperfast changes are an issue with the built-in table coordinate adjustments (vertical specifically), not just my huge array *no pun intended ;-)

I have confirmed with others they have the same problem... not just my install.

**Comment by Ltek** [comment]
bump

**Comment by francisdb** [comment]
Mind sharing a small video of what it looks like?

**Comment by francisdb** [comment]
@Ltek has the table showing this issue been released?

**Comment by Ltek** [comment]
> @Ltek has the table showing this issue been released?

https://vpuniverse.com/files/file/20103-tron-neon-30/

Haven't tested it with anything newer than RC4 when it was built... been working on other tables since.

**Comment by vbousquet** [comment]
Fixed in 10.8.1

**Comment by vbousquet** [comment]
...and in 10.8
