### ISSUE TITLE
Unable to access settings options since 10.8.1

### ISSUE THREAD

**Issue by aerao** [vpinball/vpinball#1699]
Since I switched from 10.8.0 to 10.8.1 (no matter which version) I've noticed a problem:
The F12 shortcut key no longer works.
And when I'm in the table options, I can't access the odd options.

I only have access to options 2/4 and 4/4, and I can't get 1/4 and 3/4, which means I can't set the povs.
If I go back to version 10.8.0, no more problems.
If you have any ideas... Thx

**Comment by Ltek** [comment]
check your VPX settings in the UI... when I updated to 10.8 RC3 the 'Tweak' menu key "magically" changed on its own

**Comment by vbousquet** [comment]
10.8.1 is anywhere but stable and this type of problem is to be expected (should be fixed though).
