### ISSUE TITLE
Question: How to read key mapping values

### ISSUE THREAD

**Issue by syd711** [vpinball/vpinball#1717]
For my Java based pause menu, I want to read the key navigation from VPX.

I found the VPinballX.ini in the users' app data. But the stored values don't seem to match ASCII values.
Could you give me a hint how I can resolve these numeric values?

e.g.
LFlipKey = 42  (left shit key)

I C++ this would be **VK_LSHIFT | 0xA0 | Left SHIFT key**.

![image](https://github.com/vpinball/vpinball/assets/1169826/6d8f2818-9610-4d73-bb13-c6e73730c125)

**Comment by francisdb** [comment]
I believe these are DirectX scancodes.

**Comment by syd711** [comment]
Perfect, thank you Francis. That was I was looking for!
