### ISSUE TITLE
10.8 reporting image sizes 100s to 1000s times larger than true size

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1718]
Nealy all of the images I upload VPX 10.8 (any of hte RCs at least) show them many many times larger than reality. 
Example shown has multiple PNG and WEBP images under 2MB on my PC but 23.5mb in VPX?
or the extreme case (very first image in list), that image is 284k and VPX Image Manager says is 198MB!

I have tried deleting (not just re-importing) and import again new... same problem

![image](https://github.com/vpinball/vpinball/assets/1626802/543424f3-da52-4a56-a0e5-23e66347ef6d)

when I open the VPX archive I see files that are 2.6 GB in size... even the primitives' I have would never be that large. When I copy those to my PC they are 2.5 MB (not GB)

![image](https://github.com/vpinball/vpinball/assets/1626802/72ffb969-02ea-4971-b4ac-32387704665f)

**Comment by francisdb** [comment]
That's the raw decompressed size once the image is loaded in memory. Which is `width * height * 3` (or 4 if the image contains an alpha channel).

eg 8333 * 8333 * 3 = 208 316 667  or ~198 MB (208316667 / (1024 * 1024))

**Comment by Ltek** [comment]
Thanks for explaining. I thought it might be something like that (which is why I removed the [bug] label). So this begs the question on file type and on-disk size... does it matter? I'm trying to save everything as WEBP Lossless (see my feature request in VPXTOOL) but does that make a difference when running the table?

**Comment by toxieainc** [comment]
It can make a difference, yes.
Depending on file type and compression type, the tabke loading speed can vary, along with the image-quality effects of lossy vs lossless compression.
But apart from that, everything else is the same.

**Comment by Ltek** [comment]
> It can make a difference, yes. Depending on file type and compression type, the tabke loading speed can vary, along with the image-quality effects of lossy vs lossless compression. But apart from that, everything else is the same.

ok, I figured so, which is why I wanted to make most webp lossless. Hopefully VPXTOOL will get that bulk export/import and make it far easier/quicker to do! ;-)
