### ISSUE TITLE
VR Settings Missing

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#172]
**Describe the bug**

**To Reproduce**
1. Go to 'GL v509 or v510'
2. Click on 'the .exe'
3. Scroll down to 'over to preferences '

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions**
 - VPX-GL: v509 and v510
 - Windows version 10
 - GPU and video settings if applicable

**Additional context**

**Comment by studlygoorite** [comment]
Fixed in v514

**Comment by vbousquet** [comment]
@studlygoorite Thanks alot for your feedback. It's not that easy to look everywhere with all the changes!

**Comment by studlygoorite** [comment]
> @studlygoorite Thanks alot for your feedback. It's not that easy to look everywhere with all the changes!

Good to know, I get the feeling at times that maybe I am being a pain in the ass :) Thinking that you gents are aware of things and it's on the todo list, if you need anything specific looked at just let me know.
