### ISSUE TITLE
How do we add gamepads/Keyboards in Android Version

### ISSUE THREAD

**Issue by PeterTucker** [vpinball/vpinball#1728]
How do we add gamepads/Keyboards in Android Version?

**Comment by jsm174** [comment]
out of the box, it should detect xbox and playstation gamecontrollers on android.  bluetooth keyboards will work the same way, nothing special to do.

**Comment by PeterTucker** [comment]
Anyway to map 3rd party? I built my own pinball controller

**Comment by gjupp** [comment]
Did you build a bluetooth controller Peter or is it USB only?

**Comment by jsm174** [comment]
controllers and keyboards are usb or bluetooth. We run through SDL, so if supports it, should be good. Also, we do support gamecontrollerdb.txt on Android. see: https://github.com/mdqinc/SDL_GameControllerDB and https://github.com/mdqinc/SDL_GameControllerDB/blob/b1e4090b3d4266e55feb0793efa35792e05faf66/gamecontrollerdb.txt#L1725
