### ISSUE TITLE
Primitives : Imported animations are exhibiting 'glitches', although importing a single wavefront object appears to be fine.

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#1736]
**Describe the bug**
Creating an animation in Blender (4.1) and exporting it as a Wavefront object can sometimes result in glitches when imported into VPX 10.8. However, creating 31 primitives and importing the OBJ files to display them all together does not produce a glitch.

**To Reproduce**
1.Insert Primitve
2. Click on "Import Mesh"
3. click browse.
4. select Primitive with 001
5. make sure "Import animation sequence"is selected
6. run animation via endles

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
No, this is the test table. And we have it with a lot of animations already

**Expected behavior**
Importing all the OBJ files correctly without any glitch when importing them as animation

**Screenshots**
Creating an animation in blender (4.1) 
![bauer](https://github.com/vpinball/vpinball/assets/48748234/53b84fae-732a-4228-9303-6bf4024965dc)
export is as wave front object 
![image](https://github.com/vpinball/vpinball/assets/48748234/7d338caa-cf53-4629-bc05-9c9f21d4197e)
And import it into VPX 10.8 
![image](https://github.com/vpinball/vpinball/assets/48748234/076a31fe-ec85-47f3-a1b2-c2961c156180)
![image](https://github.com/vpinball/vpinball/assets/48748234/aa51ec02-6f83-496b-8909-e578dfdb5e2c)
could results (not always, but most of the times) into  this 
![bauer2](https://github.com/vpinball/vpinball/assets/48748234/0dd6fd12-d68c-4a7f-89b8-2c27866e137f)
When creating 31 primitives and import the OBJ files (and shows them all together) There isn't a 'glitch'
![image](https://github.com/vpinball/vpinball/assets/48748234/1a91901a-8011-4a39-9aba-9245821f37f7)

**Crash dump**
NA

**Versions & Settings**
 - VPX: 10.8.0 Beta 1954 - see GL and DX version

**Additional context**
Added zip with all 31 wavefront obj files : [Jack.zip](https://github.com/vpinball/vpinball/files/15446208/Jack.zip)
VPX with imported animation : [jackVPX.zip](https://github.com/vpinball/vpinball/files/15446218/jackVPX.zip)
VPX with all 31 primitives  : [jack_allPrimit.zip](https://github.com/vpinball/vpinball/files/15446214/jack_allPrimit.zip)

**Comment by toxieainc** [comment]
VPX at the moment cannot handle changing topology in the animation (e.g. different number of vertices or triangles, or different ordering). Maybe that's the problem here?

**Comment by vbousquet** [comment]
The bug looks to be that the order of the triangles change from frame to frame which is not supported.
I would guess that the original model has quads that are triangulated on the fly by Blender when exporting, leading to this.

**Comment by vbousquet** [comment]
Note: I have added a topology check on import that will report and fail the import if the topology is not the same for all the frames of the animation

**Comment by MikedaSpike** [comment]
Nice! Thank you, Vincent, that makes sense.
