### ISSUE TITLE
VPX 10.8.0 Beta 517 jaggy everything

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#175]
**Describe the bug**
It seems zero antialiasing happening. I'm in desktop mode and haven't changed any video settings from the last properly working version (.428)
50% super sampling, Quality FXAA, Bilateral CAS, Force anisotropic texture filtering
Windows 10 21h2, nvidia gtx 1060 6gb

**To Reproduce**
No need- just see pic attached

**Expected behavior**
all elements should be rendered with antialiasing

**Screenshots**
attached

**Crash dump**
no crashing. just ugly :)

**Versions**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable

**Additional context**
![hs2-ugly-vpx514](https://user-images.githubusercontent.com/52011304/200385101-7f6b49aa-bfad-41eb-9c6f-49f36455e59e.jpg)

**Comment by vbousquet** [comment]
Could you post a screenshot of your video settings ?

**Comment by passionforpins** [comment]
![vpx1080517-settings](https://user-images.githubusercontent.com/52011304/200395717-28540b19-6986-4261-8452-6182a4fb3606.jpg)

**Comment by vbousquet** [comment]
You have the supersampling set to 50% : it downsample everything (for performance on very low end systems) resulting to aliasing. It's the intended behavior

**Comment by vbousquet** [comment]
On the other hand, this option is really needed when the output resolution is fixed (like in VR where the resolution is defined by the device, not the user), and not really usefull otherwise (not to say it is misleading). Perhaps we could disable it for desktop usage and only keep it for VR ?

@toxieainc What do you think ? Do we remove it for desktop and only keep it for VR ?

**Comment by passionforpins** [comment]
Ok understood. Here it is with supersampling disabled and at 125%. Certainly better than 50% but still not great like with 10.7.2 final
![hs2-no-SS-vpx517](https://user-images.githubusercontent.com/52011304/200415554-79f12051-19e7-4742-b47f-9f1b98acfd0e.jpg)
![hs2-SS125-vpx517](https://user-images.githubusercontent.com/52011304/200415583-639797cf-856f-4c03-96a8-7b7a37bab9f3.jpg)

**Comment by passionforpins** [comment]
not a bug, just growing pains :) closing as issue

**Comment by toxieainc** [comment]
> @toxieainc What do you think ? Do we remove it for desktop and only keep it for VR ?

Maybe at least disallow <100% ? Might be less confusing then.
