### ISSUE TITLE
Runtime error ------------- Line: 1 Variable is undefined: 'FrameIndex'

### ISSUE THREAD

**Issue by mazjohn** [vpinball/vpinball#1751]
**Describe the bug**
after updating to latest10.8 build 1955, 10.7x tables are all giving the following error breaking backward compatability:

Runtime error
-------------
Line: 1
Variable is undefined: 'FrameIndex'

**To Reproduce**
just launch a 10.7x table.

**Expected behavior**
no crash leading to increased enjoyment level.

**Screenshots**
Runtime error
-------------
Line: 1
Variable is undefined: 'FrameIndex'

**Versions & Settings**
 - VPX: 10.7.3 Final Rev 395
 - windows  master build
 - 33 and 64bit both crash

first noticed after updating to build 1955 of 10.8. when i revert back to build 1954, the issue with 10.7x backward compatability and above error is resolved. I presume it must have something to do with the latest change involving frame index in build 1955???

**Comment by vbousquet** [comment]
Fixed in latest
