### ISSUE TITLE
Ability to resize the line number column in script editor to accommodate larger font size

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#1779]
**Is your feature request related to a problem? Please describe.**
Script/code editor line number column only shows 3 character width line numbers for some users depending on font choice/size resulting in visually incorrect line numbering past line 999. The quick and dirty solution is to reduce the font point size for default text in the code viewer options however this can result in harder to read text in the script itself depending on monitor size/resolution/eyesight.

**Describe the solution you'd like**
Line number column should auto adjust it's width to accommodate larger font size.

**Describe alternatives you've considered**
Ability for user to manually adjust the line number column width

**Additional context**
I would also class this as somewhat of a bug as well as feature request. There is a thread related to this issue at https://www.vpforums.org/index.php?showtopic=51839

**Comment by stevejones72** [comment]
![image](https://github.com/vpinball/vpinball/assets/45272774/fe66cf45-8545-4bba-aea3-56389343a801)

How about a 4 char wide width as a default?

**Comment by gjupp** [comment]
> ![image](https://private-user-images.githubusercontent.com/45272774/340570363-fe66cf45-8545-4bba-aea3-56389343a801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NTIzNTYsIm5iZiI6MTcxODc1MjA1NiwicGF0aCI6Ii80NTI3Mjc3NC8zNDA1NzAzNjMtZmU2NmNmNDUtODU0NS00YmJhLWFlYTMtNTYzODkzNDNhODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDIzMDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMWJjOTMxYmY5NjdjYTM4OTEyNGMzZjMxNGEzMjFiNjUyYjIzOWMxYjMxMmVjZTFlODI4NmVmMDA0NTQwYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EnCj1XfohEEg3Ntj257iSrNAoWiMaTkBTUeSXlK-kUw)
> 
> How about a 4 char wide width as a default?

Nice one. Have you tested that to see if an increase in the point size of the default text actually results in the column width increasing to accommodate, or is it a fixed pixel width?

**Comment by stevejones72** [comment]
![image](https://github.com/vpinball/vpinball/assets/45272774/7bb749bd-ab54-4bb3-9cab-eb165e19c3dc)

![image](https://github.com/vpinball/vpinball/assets/45272774/a5bf1786-7bfe-4bc7-85af-c2e7215b171a)

Like that?

**Comment by stevejones72** [comment]
It looks at the point size of the default font, also works out the number of characters required for the loaded script to keep it as small as possible.

**Comment by gjupp** [comment]
Awesome, thankyou.

**Comment by toxieainc** [comment]
Merged, closing then, right?
