### ISSUE TITLE
Crash when opening any preferences window (Windows 11)

### ISSUE THREAD

**Issue by ScaryG** [vpinball/vpinball#1793]
Since 10.8.1r2301, the Windows 64-bit versions (vanilla and GL) will hit an exception and crash on my Win11 machine when opening any preferences window.

The commit causing this is aad6278, "Update to 9.5.2", which is I think updating the Win32++ lib to that version.

The issue seems to be related to RTTI. You might notice that in the build logs we get this warning now:

`"D:\a\vpinball\vpinball\third-party\include\win32xx\include\wxx_dialog.h(749,40): warning C4541: 'dynamic_cast' used on polymorphic type 'Win32xx::CWnd' with /GR-; unpredictable behavior may result"`

Removing /GR- from the compiler options reenables RTTI, gets rid of the warning, and fixes the crash; however rather than submit that as a PR I'm just opening this issue in case there's a fix within Win32++ or the VPinball code you'd rather implement.

**Comment by vbousquet** [comment]
There are quie a few dynamic_cast in Win32++ (even before this update), and the standalone libraries also have quite a few. Beside the code is slowly moving toward more and more C++ language features. I think the solution would be to re-enable type information (so remove the GR-) and if it does not make the app grow too much just stay with this.

I will have a look later on
