### ISSUE TITLE
Cache corruption upon using LoadTexture

### ISSUE THREAD

**Issue by Lovinity** [vpinball/vpinball#1799]
**Describe the bug**
I just started using LoadTexture to load in QR codes from Scorbit. While it worked in-game, VPX 10.8 RC3 DX64 crashed on exit, and the table fails to play anymore (in VPX 10.8 RC3) without VPX crashing. 

I confirmed this bug by reproducing it on a blank table.

**To Reproduce**
1. Create a new table in VPX 10.8 RC3
2. Create a flasher on the table
3. In the table init function, use LoadTexture to load a PNG or BMP image into a name that does not currently exist in the Images manager
5. Assign the image to the flasher.ImageA
6. Play the table
7. LoadTexture works as intended, except the new image loaded in does not appear in the image manager (is it supposed to?)
8. Close the table and try playing it again; VPX crashes. You can no longer play the table anymore in VPX 10.8 RC3 no matter what you try, even if you manually add an image by the same name into the image manager or reset the flasher ImageA property back to <none>.

**Expected behavior**
The image loads into the flasher correctly, the new image appears in the Image manager, and trying to play the table again does not cause VPX crashes.

**Crash dump**
[Temporary link](https://file.pdstig.me/index.php/s/uMtYAZdxIlXvzp0)

**Versions & Settings**
 - VPX: 10.8 RC3
 - Windows: 11 22H2
 - GPU and video settings if applicable: AMD Radeon RX 6750 XT
 - If this bug report is for VPX 10.8+, please join your setting file: [temporary link](https://file.pdstig.me/index.php/s/FsDb3dZYYLoh7ul)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file: Tried this, have no idea where the log file is located

**Additional context**
Deleting the cache directory for the table in AppData/Roaming/VPinballX gets the table in a playable state again

Side note, may be a separate bug but sometimes Script errors with Description Unavailable if you try to LoadTexture on a name that already exists in the Image manager.

**Comment by Lovinity** [comment]
I've confirmed the issue is the presence of this item in the used_textures.xml file after using LoadTexture:

<texture filter="5" clampu="3" clampv="3" linear="false" prerender="false"></texture>

Removing this line from used_textures.xml makes the game work again, so the bug is that LoadTexture should not be adding this line in the XML.

**Comment by vbousquet** [comment]
Should be fixed now. Thanks for the clear description, it makes fixing things really easier!

**Comment by Lovinity** [comment]
Confirmed... it is fixed in 10.8 RC4. Thank you!
