### ISSUE TITLE
Corrupt file Loading 10.8.0 Rev 523 table in 10.7.2 Final 

### ISSUE THREAD

**Issue by retro27** [vpinball/vpinball#180]
**Describe the bug**
I have found if you save a table in 10.8.0 Rev 523, and try to open the table in 10.7.2 final. I'm getting a Pop up "This file is corrupt and cannot be loaded" If you reopen the file in 10.8.0 Rev 523 the table loads up and plays ok. Ive been testing and think the problem start at rev513

**To Reproduce**
1. Open  VPinballX ver 10.08.0 rev 523, load any table,
2. Save the table
3. Open VpinballX ver 10.7.2 Final and load the saved table
5.

**Expected behavior**
Load the table and play ok

**Screenshots**
![Screenshot 2022-11-09 202829](https://user-images.githubusercontent.com/16049569/200935213-40685721-193c-4279-bcd6-c9ba9988aac0.png)

**Crash dump**
No Crash Dump

**Versions**
 - VPX: 10.08.0 Rev 231
 - Windows version 11
 - GPU and video settings if applicable
 - Nvidia 3070 RTX, default settings

**Additional context**

**Comment by vbousquet** [comment]
Sadly the fix, doesn't fixed it...

**Comment by vbousquet** [comment]
Now this is good. Thanks for reporting, this was a really annoying issue with risk of loosing table creator work.
