### ISSUE TITLE
 3D Stereo Anaglyph Filter "Deghost" Changing Saturation Causes Render Issues

### ISSUE THREAD

**Issue by brewedenhell** [vpinball/vpinball#1815]
**Description:**
When adjusting the saturation in the 3D Stereo Anaglyph filter "Deghost" to values above 1.000000 (specifically tested at 1.300000), parts of the playfield render incorrectly and go black with noise artifacts. Changing the brightness setting does not affect this issue.

![image](https://github.com/vpinball/vpinball/assets/23454468/72d796de-37b9-4172-a6fa-df8dd7a201d1)

![Adams Family GL With satuation higher](https://github.com/vpinball/vpinball/assets/23454468/c1ec762b-1bae-44e9-b798-037aed11b4a8)

**Versions Tested:**

- VPinballX_GL-10.8.0-1975 RC4
- VPinballX_GL-10.8.0-1947 RC3

**Modes Tested**
Red/Cyan
Green/Magenta

**Comment by vbousquet** [comment]
saturation value over 1.0 are not supported so this is normal. The idea is to desaturate to avoid ghosting due to bad color separation of the anaglyph glasses
