### ISSUE TITLE
Back to the future VBScript bug

### ISSUE THREAD

**Issue by zack06007** [vpinball/vpinball#1818]
**Describe the bug**
The table doesn't functunning 
 

**To Reproduce**
1. Go to 'VPX 10.8 RC4'
2. Click on 'table back of the future (Data East 1990).'
3. See error

**Expected behavior**
With RC4 10.8 the table doesn't work

**Screenshots**
![Untitled](https://github.com/vpinball/vpinball/assets/8669357/74691741-c975-4a8f-823f-14f847005bd7)

**Crash dump**
table crash - return on desktop

**Versions & Settings**
 - VPX: 10.8 RC4
 - W11

**Comment by vbousquet** [comment]
As stated in the dialog, this is a table script bug

**Comment by zack06007** [comment]
Ok with v.1.0.5 (table) it's ok
Sorry
delete this thread :D
