### ISSUE TITLE
[Bug] Script Compile notification modal does not allow VPX Player to take focus

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1823]
If you are editing a script and run compile, then forget to close that modal window... VPX still allows you to run/start a table. BUT if you do, VPX player will not take focus - even if you try to force it.

IMO the best solution is one of these...

1) have that window not be modal, and just be a notification in the script editor window (best solution IMO)
2) have VPX force close the compile window if the VPX editor or player takes focus.

**Comment by vbousquet** [comment]
Duplicate https://github.com/vpinball/vpinball/issues/1698

**Comment by Ltek** [comment]
> Duplicate #1698

I forgot :)
