### ISSUE TITLE
FPS Limit on Android version

### ISSUE THREAD

**Issue by hendrickchan** [vpinball/vpinball#1837]
I just downloaded VPX for android and wow, it performs great. Anyway we can put a limit on the FPS to 60 or such? The fan on my device starts roaring after a minute or two of play. This might help battery life and keeping the device cool. Thanks!

**Comment by francisdb** [comment]
Edit `VPinballX.ini` and set `MaxFramerate = 60`

It should default to the display refresh rate but not sure that applies to Android.

**Comment by hendrickchan** [comment]
Thanks for the info. Will try this out.

**Comment by francisdb** [comment]
On linux `F11` shows fps, again not sure how to show it on Android

**Comment by hendrickchan** [comment]
My FPS on android is over a hundred, sometimes just below 200.
