### ISSUE TITLE
DMD window not showing ( scoreboard is not showing on android )

### ISSUE THREAD

**Issue by PsyVHS77** [vpinball/vpinball#1844]
I play pinball table's like black hole NBA fastbreak and wwf royal rumble but all tables does not showing the scoreboard on my android phone I try changing in the settings but no result the only table's of I play had have scoreboard are fss tables ( full single screen )
But not landscape table those not have scoreboard (DMD) can you fix this issue I like playing my favourite table black hole landscape mode with scoreboard (DMD) I hope this bug is fix for next version

Thanks. 👍

**Comment by jsm174** [comment]
This is not a bug. Visit the discord channel for help, or look at the documentation:

https://github.com/vpinball/vpinball/tree/standalone/standalone#workarounds

example: https://github.com/jsm174/vpx-standalone-scripts/blob/master/South%20Park%20(Sega%201999)%201.3/South%20Park%20(Sega%201999)%201.3.vbs.dmd.patch
