### ISSUE TITLE
[Bug] Flasher set to 100% Opaque still allows light / shadows though from other elements

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#1865]
Flashers when set to 100% Opacity still allow light through from other objects. 

Flashers are great for lighting -and- for displaying images   (side note: far better than Decals which are very limiting, I'm not sure why Decals exist ;-)

This bug forces me to create a wall under the Flasher to block the light. Is very annoying and requires a lot more work when just wanting a simple Flasher with an image on it to show clean, without shadows from other elements behind it.

**Comment by vbousquet** [comment]
This is not the bug but the way flashers were designed (not depth masking). This can't be changed or it would break all existing tables

**Comment by Ltek** [comment]
> This is not the bug but the way flashers were designed (not depth masking). This can't be changed or it would break all existing tables

understood.... maybe an FR to add a property (to not break existing tables) for 'Do Not Allow Light Penetration from Back-side" (some something like that?
