### ISSUE TITLE
Some tables not showing internal DMD in 10.8.0/10.8.1

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1867]
Maybe(!) related to the quirk seen in https://github.com/vpinball/vpinball/issues/1811, e.g. some Nascar table variants (not JPs one) do not show the internal DMD, although the script looks completely sane, and it shows perfectly fine in 10.7.X.

At least modifying the core.vbs to remove time fence and updatevisual does not make it work, so may also be another issue.
Also happens in both DX and GL.

**Comment by vbousquet** [comment]
It was bad draw call sorting between DMD draw and Sprite draw, so tables with a textbox "behind" the DMD textbox would end up with the DMD hidden behind.

Should be fixed now for both 10.8 & 10.8.1

**Comment by toxieainc** [comment]
Great, thanks (and confirmed)..
