### ISSUE TITLE
Filtering of backglass images non-optimal when using GL

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#1869]
E.g. taking JPs Nascar table, one can see artifacts/aliasing on the backglass (i tested 1920x1080) compared to the DX rendering.
I guess this is due to the texture not being sampled using mipmaps and/or some other filter param being off.

**Comment by vbousquet** [comment]
Is this 10.8 or 10.8.1 ?

**Comment by toxieainc** [comment]
Both..

**Comment by toxieainc** [comment]
Also 10.8.1 BGFX
