### ISSUE TITLE
Newer core.vbs script breaks P-ROC tables 

### ISSUE THREAD

**Issue by Yardl3y** [vpinball/vpinball#1875]
**Describe the bug**
P-ROC tables don't work with newer core.vbs script. The tables start with no errors but there is no ball put into the shooter lane. Problem has been confirmed by several people over at the VPU forums. 

**To Reproduce**
Play any P-ROC table with 10.8 RC4 and the included core.vbs script. No ball is shot into the shooter lane. To fix, revert to an older core.vbs script, I believe the one included with 10.8.0.889 and older will work.

**Comment by gdycaps24680** [comment]
https://github.com/vpinball/vpinball/issues/1578
