### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by rosagio** [vpinball/vpinball#1891]
Hello, first, thanks for your work
The android version of standalone version crash at start up since some version on my samsung s22+
misc: standalone builds for macos, ios, tvos, android, linux, and rpi #475
How can i fix it ? Thanks a lot
June version works well

**Comment by jsm174** [comment]
Hello. Can you clarify where the crash is, ie a table being launched or the app itself launching?

Can you look at adb to see if any exceptions are thrown?

**Comment by rosagio** [comment]
Hello the crash is immediatly after the installation during the first start and others
But before the choice of the vpx folder
Adb?

**Comment by bartdesign** [comment]
I have the same problem. It loads up. And you briefly see select vpx directory and the the app closes again. Relaunching or force closing doesn’t help. This is on a new android device. So i never ran a VPinball build before on this phone.

**Comment by jsm174** [comment]
Can you please test out the build here:

https://github.com/vpinball/vpinball/actions/runs/10311204701

**Comment by bartdesign** [comment]
This fixed my issues. Thank you!!

**Comment by rosagio** [comment]
Ok for me, Thanks 
😀

**Comment by jsm174** [comment]
Great! thanks for testing!
