### ISSUE TITLE
[Feature Request] 3D support with simultaneous Head tracking

### ISSUE THREAD

**Issue by StrangeCloudsVPin** [vpinball/vpinball#1892]
First I would like to say thank you so much for creating such an amazing piece of software. 

I would love to see the implementation of head tracking support with simultaneous 3D stereo enabled.

I know this is currently possible on a competing software. But it would be much more beneficial to see this working on what I believe to be the superior application.

**Comment by vbousquet** [comment]
Duplicate: https://github.com/vpinball/vpinball/issues/1730

**Comment by StrangeCloudsVPin** [comment]
I do not believe this is a duplicate request.

**Comment by vbousquet** [comment]
Sorry pointed to the wrong issue. The existing one is this one: https://github.com/vpinball/vpinball/issues/1376
