### ISSUE TITLE
[Question] nvram is not written without Controller.stop routine (?)

### ISSUE THREAD

**Issue by syd711** [vpinball/vpinball#1897]
This is rather a question than a bug (I assume):

For some tables, e.g. "Checkpoint (Data East)" I realized that the nvram is NOT written when the table exited through PinUP Popper. But a regular exit though VPX does write it. After adding the Controller.Stop method to the script of "Checkpoint", the issue is gone and the nvram is then written too.

What I don't understand: there are other tables like "Create from the black lagoon" which also don't have the "controller.stop" call, but the nvram is written anyway when exited through popper.

I wonder is you could help me clarifying this behaviour or is this something for the VPinMAME team to answer?

**Comment by toxieainc** [comment]
I'd guess that this is implementation depend on the machine/generation type. @gaston may know more.

**Comment by toxieainc** [comment]
actually his github is @volkenborn

**Comment by volkenborn** [comment]
No sorry, I cannot explain that difference in behaviour.

**Comment by syd711** [comment]
Ok guys, thank you for your quick responses! I will also try the VPinMAME then.

**Comment by francisdb** [comment]
Is it not because `Creature from the Black Lagoon` does not override `Table1_Exit` and therefore implicitly calls `Controller.Stop`

https://github.com/vpinball/vpinball/blob/c5179816cec8d657f8a2562e893e46d42f6ae11f/scripts/core.vbs#L2358

**Comment by francisdb** [comment]
fore reference: https://github.com/vpinball/pinmame/issues/300

**Comment by syd711** [comment]
So if a table defines "Table1_Exit", then this method should also call "Controller.stop" there?

**Comment by francisdb** [comment]
Mind that `Table1_Exit` might be called differently if the table was renamed.

The name is part of the gamedata.

https://github.com/francisdb/mfdoom.vpx/blob/02d0179b1f45a33782ef1026c4db1c25eef41c4e/MFDOOM/gamedata.json#L137

**Comment by syd711** [comment]
I see, thanks for the clarification and the quick response.
