### ISSUE TITLE
Metallica 180h ROM - Inserts Stop Lighting Up

### ISSUE THREAD

**Issue by Primetime5k** [vpinball/vpinball#1902]
**Describe the bug**
The 180H rom will stop lighting inserts as the game progresses. 

**To Reproduce**
1. Open Metallica and play with the 180H rom
2. Play for 20-30min

[If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.](https://vpuniverse.com/files/file/6058-metallica-premium-monsters-stern-2013-vpw-mod/)

**Expected behavior**
Inserts continue to light as required.

**Screenshots**
Video (I notice it starting aprox 30min in):
https://youtu.be/oeFtx4aB2Nc

**Crash dump**
NA

**Versions & Settings**
 - VPX: 10.8 1975 64bit / VPM 3.6.1044 (happens on earlier versions of both)
 - 10 Pro
 - 3070
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file
[VPinballX .log](https://github.com/user-attachments/files/16730558/VPinballX.log)

**Additional context**
NA

**Comment by jpsalas59** [comment]
I guess you are using the 64 bits version. So this is a vpinmame issue, not a VPX issue. Stern ROMS have problems with the vpinmame 64 bits version, due to a missing component which only exists in the 32 bits version emulations, the one called at91Jit. Just do a search for it, this is a known bug in vpinmame, not a VPX problem.

**Comment by Primetime5k** [comment]
Thanks, JP! That was the inital thought, but my understanding is that might not be the case. It uses a unique nodeboard that's not fully emulated. The team needs a firmware dump from the board for the path of least resistance.
