### ISSUE TITLE
Graphical distortion on flippers on Android VPX 10.8.0

### ISSUE THREAD

**Issue by hendrickchan** [vpinball/vpinball#1912]
I'm using a SD 8 Gen 2, android GL version. 

The flippers and some other moving items get distorted like this. Any help? Thanks in advance!

![Visual Pinball X Graphic Corruption in Game](https://github.com/user-attachments/assets/59e342c5-ea6c-45b4-ae08-c3b635e9bf54)

**Comment by jsm174** [comment]
Duplicate of https://github.com/vpinball/vpinball/issues/1710
