### ISSUE TITLE
Bug Proc Table CORE.vbs 10.8 candidate 4

### ISSUE THREAD

**Issue by Sebastiendelf** [vpinball/vpinball#1914]
Bonjour 
Je voulais vous reporter un problème sur le nouveau core.vbs qui se trouve dans le dossier scripts de la version 10.8.0 candidate 4 GL 64bits (même problème sur les versions anciennes 64bits jusqu'à la modification du script core.vbs), j'ai constaté ce problème sur les tables Proc qui fonctionne très bien en version 10.7.3. 32 bits sauf si je remplace le core.vbs par le celui de la version 10.8.0 GL 64bits candidate 4.
Lorsque je lance la table, elle s'ouvre mais quand j'appuie sur START, je n'ai pas de bille donc impossible de jouer.
Mon système est en cohabitation entre la version 10.7.3 32bits et 10.8.0 GL 64bits candidate 4, toutes mes autres tables vpx semblent fonctionner à ma connaissance.
Pour finir je dois mettre l'ancien core.vbs à la place du nouveau core.vbs, et les tables Proc refonctionnent en 10.7.3 32bits et en 10.8.0 GL 64bits candidate 4 (après modif du registre)
Par contre les dernières table comme la Golden Eye de la team VPW ne fonctionnent plus avec l'ancien core.vbs.
Désolé si je ne suis pas assez clair, ce n'est pas évident à expliquer.
Merci

**Comment by 3d2000s10** [comment]
https://github.com/vpinball/vpinball/issues/1578
