### ISSUE TITLE
Out of control tilt

### ISSUE THREAD

**Issue by curtiskam** [vpinball/vpinball#1948]
After downloading this weekend’s build, I get tilts for no apparent reason, and the screen just shakes continuously with no end until I click the exit table button. Hopefully I can attach a short video

**To Reproduce**
1. Launch any table
2. Start a game
3. Play for a while
4. Table will eventually tilt without being nudged. Tilt animation will not stop

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
Tilt should only happen when I nudge too hard, not just randomly. Tilt should lose the ball and end the animation, not hang my game 

**Screenshots**
Video attached 

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: 10.8.1 GL (2526)
 - Windows 11

**Comment by curtiskam** [comment]
[TableOverride]
ViewCabMode = 1
ViewCabScaleX = 0.736250
ViewCabScaleY = 0.734900
ViewCabScaleZ = 0.542253
ViewCabRotation = 270.000000
ViewCabPlayerX = 0.922055
ViewCabPlayerY = 0.000000
ViewCabPlayerZ = 741.947327
ViewCabLookAt = 5.000000
ViewCabFOV = 50.000000
ViewCabHOfs = 0.000000
ViewCabVOfs = 107.173462

**Comment by Jajogurec** [comment]
The same happens with x64 no GL version.

**Comment by vbousquet** [comment]
10.8.1 is a not yet stable version with breaking changes. Tilt simulation is part of them and you will need to adjust your settings to get it working (better than before)
