### ISSUE TITLE
Black Playfield

### ISSUE THREAD

**Issue by shaggy2dabs** [vpinball/vpinball#195]
![20221118_092157](https://user-images.githubusercontent.com/29291907/202726560-abf8ce16-b08e-4118-949a-a19767c3a795.jpg)
The latest 10.8 rev 580 when you push start on Batman 66  Playfield disappears works fine on official 10.7.2

**Comment by vbousquet** [comment]
Which version did you use ? Was it the latest ? This is supposed to have been fixed a few commit ago, but perhaps it is still there ?

**Comment by shaggy2dabs** [comment]
10.8 rev 580 x86

**Comment by passionforpins** [comment]
Can confirm on this game only so far with rev 580x86. I tried 5 other tables with no blacked out playfield. Same blacked out pf on Bat 66 with VPinballX-10.8.0-589-8661034-Release-win-x86.

Windows 10 home 64 21h2
nvidia GTX 1060 6gb
Desktop mode
![vpx-580-589-blackpf](https://user-images.githubusercontent.com/52011304/202860579-ea9aa1ad-1a3f-4a66-b778-a7dce8806c04.jpg)

**Comment by passionforpins** [comment]
Still a black playfield as soon as you start a game on batman 66 with 10.80.0 beta rev 599.

**Comment by vbousquet** [comment]
Should be fixed by https://github.com/vpinball/vpinball/pull/205/commits/0e5cc634152716660605dbf60b04b69fcd02b717
