### ISSUE TITLE
Standalone: keyboard support

### ISSUE THREAD

**Issue by symontyPBS** [vpinball/vpinball#1952]
Ability to use keyboards with ios / ipados

**Comment by jsm174** [comment]
no worries! 

There is a "Learn More..." in settings that takes directly to the faq:

![Screenshot 2024-10-17 at 12 08 06 PM](https://github.com/user-attachments/assets/3ea956a5-3987-4ec3-aeee-868016c105ec)

And at the bottom when no tables:

![IMG_D83D08A611D1-1](https://github.com/user-attachments/assets/1ba898f0-7ff7-4fd5-ada1-4cbcbf24fee9)

**Comment by symontyPBS** [comment]
Yeah it is listed as support on my version which confused me since I did not want to bother peeps.
