### ISSUE TITLE
standalone: ipad layout support in ios build

### ISSUE THREAD

**Issue by symontyPBS** [vpinball/vpinball#1953]
Present standalone version only supports iphone layout and does not use all ipad screen.

Tables work but in a limited fashion due to the missing layouts for the larger screen.

**Comment by AndreasLueck** [comment]
**iPad version – any update on timeline?**

Thanks for the great work on the iOS port – really impressive and a lot of fun! 
I’ve had the chance to try one of your iPad builds, and in several areas it already feels noticeably further along than the current iPhone App Store version. It’s only so uncomfortable to use it over the setapp installer… if I forget to update it every 7 days it’s gone again.

I think there are quite a few fans who have been quietly hoping for an official iPad release for a while now.
No pressure at all – just curious whether it’s still on the roadmap, or whether other things have taken priority for now.
Thanks and best regards From Germany
Andreas

**Comment by jsm174** [comment]
@AndreasLueck  - thanks for the kind words! We have a version in testflight so you don't have to install via altstore every 7 days. If you stop by our discord channel we can get you an invite. 

When 10.8.1 enters beta I will definitely be releasing a new version in the app store. Hopefully soon!

**Comment by AndreasLueck** [comment]
Sure, that’s two great pieces of news at once. Thank you!

A TestFlight version without the AltStore 7-day dance sounds fantastic. I’ll jump over to Discord right away and would be happy to get an invite.

And hearing that a new App Store version is planned for 10.8.1 beta just made my day. The sun literally just came up here, and now it feels like it came up twice. ☀️
