### ISSUE TITLE
Add easier ways to start a table in VR or Desktop

### ISSUE THREAD

**Issue by ChaosSlave51** [vpinball/vpinball#1954]
**Is your feature request related to a problem? Please describe.**
When switching between VR and Desktop you have to keep going to the settings. It takes many clicks and can't be controlled externally. There is an auto feature, but it doesn't work with OpenVR

**Describe the solution you'd like**
Below run table add "Run Table In Desktop" and "Run Table in VR"
Also add a command line element so a frontend could enable and disable VR at application start

**Comment by vbousquet** [comment]
This has already been implemented in 10.8 by moving all settings to an ini file and allowing to start VPX with a custom ini files through `-ini` command line option
