### ISSUE TITLE
Latest VPX 10.8 Master Error

### ISSUE THREAD

**Issue by Urkz** [vpinball/vpinball#1958]
I have made sure  "it isnt me" before i posted this , but the x64 version of the latest master i get a hidapi not found error.
Build 2000 perfect.

Cheers.

**Comment by toxieainc** [comment]
@mjrgh Any clue/hints?

**Comment by mjrgh** [comment]
What's your build configuration (platform, toolchain)?  It goes through the CI okay, so presumably the cmakelists.txt is correct and the library is in the repos.  If you're building on Visual Studio, you might just need to regenerate the .sln from cmake to get the library added to the build.

**Comment by Urkz** [comment]
Never had any issue with any other builds before , nothing changed for 2 years with my cabinet.

**Comment by mjrgh** [comment]
It's not due to a change in your cabinet, it's due to a change in the build. Did you try regenerating the .vcxproj from cmake?

**Comment by Urkz** [comment]
> It's not due to a change in your cabinet, it's due to a change in the build. Did you try regenerating the .vcxproj from cmake?

? Not sure what you are meaning.

**Comment by Urkz** [comment]
Dohhhhhhh, is this latest master only for table makers ?

**Comment by GHOSTfaceKILLr1974** [comment]
I was on VPX 10.8.0 beta (Rev. 1985 (c517981) 64bit) and Vpinmame 3.6.0.1104.064b52f (64bit). I updated to VPX 10.8.0 beta (Rev. 2007 (6ff5d45) 64bit) and I get hidapi64.dll missing error. I'm currently on VPX 10.8.0 beta (Rev. 2000 (5174ee2) 64bit) with zero issues.

**Comment by jsm174** [comment]
We need to get the cmakes files in master `CMakeLists_gl-win-x64.txt` / `CMakeLists_gl-win-86.txt` updated to also copy `hidapi64.dll` / `hidapi.dll`

ie:

```
   COMMAND "${CMAKE_COMMAND}" -E copy "${CMAKE_SOURCE_DIR}/third-party/runtime-libs/windows-x64/hidapi64.dll" "$<TARGET_FILE_DIR:vpinball>"
```

**Comment by Urkz** [comment]
Never had any issue till build 2007.

**Comment by jsm174** [comment]
Correct, @mjrgh or myself needs to update the cmake files as listed above. This will insure the hdiapi or hdiapi64.dll get copied into the version your downloading.

**Comment by toxieainc** [comment]
Ah, true, will do. Same for 10.7.4.

**Comment by toxieainc** [comment]
Oh wait, 10.8.0 is sufficient.. Done..

**Comment by jsm174** [comment]
thanks! sorry for not getting around to it earlier.
