### ISSUE TITLE
Visual Pinball X 10.8.0 Release Candidate 5 (2015-6f63503) Severe Starting Slowness Issue

### ISSUE THREAD

**Issue by Stevenoj27** [vpinball/vpinball#1962]
My PC is a 13th Gen Intel(R) Core(TM) i9-13900K (3.00 GHz) with a NVIDIA GeForce RTX 4080, running Windows 11

Up to Visual Pinball X 10.8.0 Release Candidate 4 everything has been working well.  

Starting with Visual Pinball X 10.8.0 Release Candidate 5 I have been getting Severe Slowness when starting both the VPX 10.8 application and then again when starting to play the table.   This happens with both the 32bit and 64bit versions GL and non-GL.  I tried with and without the backglass.  I also tested both rom, non-rom, flex, non-flex, Pinup, non-Pinup and have the same severe slowness with all.

Here is the step by step of what I been doing and seeing with Release Candidate 5.

- After Rebooting or Starting my PC the VPX applications start fine the first time.
- It then loads a table as normal.
- When Clicking Play Table, it hangs on Initializing Visuals for up several minutes.  This happens if I directly double click the table to play as well.  (With Release Candidate 4 it takes like 3 seconds to start the same table.)
- When the table finally starts it plays as normal, I get over 200FPS on the biggest tables.
- After playing and quitting the VPX application, it then takes several minutes for VPX to start-up again.  Then the same thing with trying to play the table it still takes several minutes to start.  (Rebooting allows VPX to start normally the first time but the tables always take several minutes to start.)

Not sure what else you need just let me know and I will supply it.

Thanks!

**Comment by Spacegoogie** [comment]
Was on RC4 also, Everything was perfect. Then decided to update everything to latest.
Last time I do that. So sick of myself fixing things that are not broken.
My rant on VPU on this.  ( https://vpuniverse.com/forums/topic/11015-updated-now-i-seem-to-have-table-exit-delay-and-puppacs-stay-open/#comment-83760 )

RC5  freezes loading tables, (never got it to load) then crashes. Went back to RC4, all is right again.
I also Updated VpinMAME yesterday  and tables would  no longer close instantly.
It now took 4-6 sec to close tables and pup packs were not  either launching, or closing!
I was pissed ( Why I had to vent to my fellow pinball brothers on VPU lol).

**Comment by BostonBuckeye** [comment]
> Was on RC4 also, Everything was perfect. Then decided to update everything to latest. Last time I do that. So sick of myself fixing things that are not broken. My rant on VPU on this. ( https://vpuniverse.com/forums/topic/11015-updated-now-i-seem-to-have-table-exit-delay-and-puppacs-stay-open/#comment-83760 )
> 
> RC5 freezes loading tables, (never got it to load) then crashes. Went back to RC4, all is right again. I also Updated VpinMAME yesterday and tables would no longer close instantly. It now took 4-6 sec to close tables and pup packs were not either launching, or closing! I was pissed ( Why I had to vent to my fellow pinball brothers on VPU lol).

Spacegoogle, I have the same issue brother. DMD tables won't close right away now. Then VPX either crashes or closes down. 

I have been experimenting with VPX 10.8.1 as well and the same issue occurs with it so maybe it is a VpinMAME issue.  I regularly update to the newest version of VpinMAME . The strangest issue I have is with 10.8.1. When I launch a table directly through the VPX app I only see a pitch black screen where the table should be. But when I launch a table running 10.8.1 in pinup popper the table launches fine. Doesn't make sense.

**Comment by Stevenoj27** [comment]
Finally believe I tracked down the culprit.  It was my iCUE software that was interfering.  So much for lighting up my keyboard and mouse.  I stopped the iCUE process and RC5 now works beautifully.  I start the iCUE process and it breaks VPX again.  I did a full reinstall of Windows and it the same exact problem.

**Comment by francisdb** [comment]
@Stevenoj27 great you found what was causing this. Can you please close the issue?

**Comment by BobVpin** [comment]
> Finally believe I tracked down the culprit. It was my iCUE software that was interfering. So much for lighting up my keyboard and mouse. I stopped the iCUE process and RC5 now works beautifully. I start the iCUE process and it breaks VPX again. I did a full reinstall of Windows and it the same exact problem.

I had the exact issue. With iCUE running, it hangs for ages, shutdown iCUE and it all works perfectly.
