### ISSUE TITLE
Apple M4 support? 

### ISSUE THREAD

**Issue by sjudkins** [vpinball/vpinball#2003]
Simple question... 

I know you guys support the Apple silicon, but what about the new M4 chip? It's "supposed" to be a real game changer as far as 3D graphics/gaming support for the Mac platform. Personally, I haven't dug into it yet (I've been a software engineer for 35+ years), just checking the temp in here to see if it's on your radar at all. 

Keep up the fantastic work everyone!

**Comment by francisdb** [comment]
Should just work. Vpinball runs fine on my M1 max on macOS. Some minor issues on Asahi linux on that same machine but getting better every day.
