### ISSUE TITLE
saving per table "Backglass View->Camera->Test Desktop active"

### ISSUE THREAD

**Issue by Ahriman0** [vpinball/vpinball#203]
**Is your feature request related to a problem? Please describe.**
The Problem is that there are many VR tables out there who need to start with "Test Desktop" active to show them correctly.
Now you cant use them together with for example VR Launcher because you have to activate "Test Desktop" manuel every time you start them. 

The Version i use:
VPinballX_GL-10.8.0-599-50cfc07-Release-gl-win-x64

**Describe the solution you'd like**
It would be nice when VPX_VR_GL 32/64bit could save this option (Test Desktop) per table so when you open the same table again this option is already activated if you saved it.

**Describe alternatives you've considered**

**Additional context**
![Unbenannt](https://user-images.githubusercontent.com/102740091/203622871-ea04d3a2-dddd-4bf4-afc5-e69d61fe1d4a.JPG)

**Comment by gear323** [comment]
Interesting.  I have this exact table and test Desktop is checked off every time I start it.    I unchecked it and saved the table and closed it and it is checked off again now.  Tried this a few times. 

Seems that maybe we used to be able to save the setting but in the current version we can't and it stays defaulted to whatever the last saved setting was when we could indeed save it.

**Comment by Ahriman0** [comment]
yes i tried your workaround but sadly no luck :/

> Interesting. I have this exact table and test Desktop is checked off every time I start it. I unchecked it and saved the table and closed it and it is checked off again now when I open the table again. Tried this a few times.
> 
> Seems that maybe we used to be able to save the setting but in the current version we can't and it stays defaulted to whatever the last saved setting was when we could indeed save it. I'm not 100% sure but seems like a possible new bug. I also see that If I change the setting to full screen that setting does not save either.
> 
> For now as a workaround, you may want to try to redownload the table as the default may go back to enabled for you.
> 
> Edit** I also tried changing the VR options to VR disabled and then save these settings and they also do not save so changing that does not have any effect.

yes i tried your workaround but sadly no luck :/

**Comment by studlygoorite** [comment]
I wonder if this is related to the same issue I am seeing. Trying to run a 120Hz playfield with 10bit monitor support. A warning pops up (which is great) when trying to run Congo by VPW that there may be artifacts if trying to run 10bit with SMAA enabled for a table. So going into the table user setting and changing Quality SMAA do default or disabled will not save, every time I boot the table up again the Quality SMAA setting is selected

**Comment by vbousquet** [comment]
10.8 (in alpha state, so unreleased yet) version adds the ability to swap settings on startup by providing a custom ini file. This is meant for this type of situation and should cover the need. Therefore, I will close the feature request
