### ISSUE TITLE
Standalone 10.8.0 macOS ARM64 - Ball hangs when you use a Xbox controller 

### ISSUE THREAD

**Issue by RoderickdeRuijter** [vpinball/vpinball#2032]
**Describe the bug**
When you shoot the ball with the Xbox controller the ball gets stuck. If you do the same using the keyboard 'enter' key there is no issue. As this is quite strange i recorded a video and included the log. To video shows the following, please ignore the double DMD as i had to use a windowed view to record the video.

**To Reproduce**
1. Start the table
2. Use the keyboard 'enter' key to release the ball and let it go as it does. not matter if you play or not.
3. Ball is saved and automatically released again
4. Ball 2, This time we use the xbox controller to release the ball and as you can see it gets stuck. If you give the table a nudge you can see it moving but i've not found a way to get it loose again.

I tried multiple tables like 
Pirates of the Caribbean MOD M.Roche.vpx -> table: Pirates of the Caribbean (Stern 2006)
TOTAN4k 1.5.vpx -> table: Tales of the Arabian Nights

**Expected behavior**
That you are able to release the ball with the Xbox controller. 

**Screenshots**
Created a video 
https://1drv.ms/v/s!Ah5kpnR2G3M3gq9uE-Wfo1Nr4T27Ow?e=OfJFHK

**Crash dump**
no crashes to be complete here is te log with some anonymization 
https://1drv.ms/u/s!Ah5kpnR2G3M3gq9vFtH2u3VrZU-aZw?e=8AHLmI

**Versions & Settings**
 - VPX: ARM 64 v10.8.0 Beta downloaded from the actions here
 - Windows version/ No Windows macOS 15.1.1 (24B91)
 - GPU and video settings if applicable: Apple M1 Pro
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 I only have some settings there regarding the screen resolution 
 
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**
no other information

**Comment by francisdb** [comment]
It could also be plunger/nudge being set up the wrong way in `~/.vpinball/VPinballX.ini`, try tweaking below values
```ini
; Nudge
LRAxis =
LRAxisFlip =
UDAxis =
UDAxisFlip =
PBWEnabled =
PBWNormalMount =
PBWDefaultLayout =
PBWRotationCB =
PBWRotationvalue =
PBWAccelGainX = 150
PBWAccelGainY = 150
PBWAccelMaxX = 100
PBWAccelMaxY = 100
TiltSensCB =0
TiltSensValue =
EnableNudgeFilter = 0
EnableLegacyNudge =
LegacyNudgeStrength =
; Plunger   
PlungerAxis = 5
ReversePlungerAxis = 
DeadZone = 2
PlungerRetract = 
```

There is also `~/.vpinball/gamecontrollerdb.txt` which could be related.
https://github.com/mdqinc/SDL_GameControllerDB

**Comment by RoderickdeRuijter** [comment]
Thanks! This change shifted the plunger control (shooting) from the left trigger to the right stick. This adjustment not only resolves the issue but also feels more logical overall.

Thanks @francisdb
