### ISSUE TITLE
Rendering broken on macos standalone after 51b2aac and SetVector assertion

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#2034]
As reported earlier, https://github.com/vpinball/vpinball/issues/2028, some tables have began to appear black on macos. After https://github.com/vpinball/vpinball/commit/51b2aac3320e81055f4755631ee03261ebf1dd1a it is now worse.

I know I've been neglecting macos builds as I'm trying to finish up the new android app, but I just made a debug build of 10.8.1.

I get the following assertion anytime I try to launch a table:

```
Assertion failed: (m_shader->m_stateOffsets[uniformName] != -1), function SetVector, file Shader.h, line 586.
[1]    32709 abort       -play
```

After commenting out 586, I was able to get it going, but, here is IJ as an example:

![Screenshot 2024-12-01 at 10 42 04 AM](https://github.com/user-attachments/assets/88d0cb0a-d343-49cf-ad33-e14317beab56)

After reverting [51b2aac3320e81055f4755631ee03261ebf1dd1a](https://github.com/vpinball/vpinball/commit/51b2aac3320e81055f4755631ee03261ebf1dd1a) and still commenting out 586, its much better:

![Screenshot 2024-12-01 at 10 48 37 AM](https://github.com/user-attachments/assets/ba1cbfe4-d158-4d88-bb50-f19dfb1478eb)

**Comment by toxieainc** [comment]
The black part issue should be better again, the assert i don't fully understand why that is triggered.  :/

**Comment by jsm174** [comment]
Thanks for look into this! I tried the newest version, but it's still the same.

**Comment by cwscws** [comment]
Can this be fixed for standalone 10.8.0, too?

**Comment by jsm174** [comment]
So I looked at this some more. Prior, we updated the pdata, and then copied. Now your updates are doing it directly. (Very cool, btw).

Anyway,

https://github.com/vpinball/vpinball/blob/e2f9e4383be66dc0a94c4cc0ab33351248647760/src/renderer/Shader.h#L600-L605

actually needs to be:

```
             if (n > 2) {
                if (p->z > 0 && p->z < FLT_MIN_VALUE) s->z = FLT_MIN_VALUE;
                else if (p->z < 0 && p->z > -FLT_MIN_VALUE) s->z = -FLT_MIN_VALUE;
                else s->z = p->z;
             }
             if (n > 3) {
                if (p->w > 0 && p->w < FLT_MIN_VALUE) s->w = FLT_MIN_VALUE;
                else if (p->w < 0 && p->w > -FLT_MIN_VALUE) s->w = -FLT_MIN_VALUE;
                else s->w = p->w;
             }
```

because we have to leave `s->z` and `s->w` to the value they are originally if `n < 2`, `n < 3`, etc.


As for the `assert` I can open up another issue, or maybe @vbousquet would know. The `uniformName` is `SHADER_spline2`

![Screenshot 2024-12-02 at 8 40 02 AM](https://github.com/user-attachments/assets/6ce7927f-ad3b-4b49-85f1-243d45306f6e)

**Comment by toxieainc** [comment]
Oh, d'oh, good catch! Thanks!

I just wanted to quickly fix this, as it could have had the potential to cause headaches at some later point in time (as it screwed the compiler over by claiming const correctness, but then breaking it). But seems i was a bit too quick  ;/

**Comment by toxieainc** [comment]
The assertion is also my fault, it doesn't lead to actual errors though. Will fix it.
