### ISSUE TITLE
How  to build VPX

### ISSUE THREAD

**Issue by Benforce** [vpinball/vpinball#2035]
Not a problem or feature request. Just a question how to build VPX from source. Apart from Visual Studio what extra frameworks and what commands/parameters for the make and build?  Or is it described in detail somewhere and I missed it?

**Comment by toxieainc** [comment]
Its super simplistic. Run 'create_vs_solution.bat' and then open the created sln+proj file. No cmake or other stuff needed.
Only if you want to compile the DX9 variant, then it may be that you have to install the Microsoft DirectX SDK.

**Comment by toxieainc** [comment]
I just created https://github.com/vpinball/vpinball/blob/10.8.1/make/README.md, too. Let us know if there is something missing, thanks..

**Comment by francisdb** [comment]
Might be good idea to put this in the main readme or at least reference it there.

**Comment by toxieainc** [comment]
Yup, indeed a good idea, done, thanks!
