### ISSUE TITLE
Added material does not show up in drop down until deselecting and reselecting an object.

### ISSUE THREAD

**Issue by a-bord** [vpinball/vpinball#204]
When creating a new material it is unable to be seen in the dropdown menu of the selected mesh until deselecting it and reselecting it.

1. Select a mesh
2. Create a new material
3. drop down the mesh's material menu

Ideally a new material shows in the drop down menu immediately.

 - VPX: 10.72 release
 - Windows 10

This was recently fixed in the image editor. It was the same problem. Hoping this can also be addressed.

**Comment by vbousquet** [comment]
Should be fixed by https://github.com/vpinball/vpinball/pull/205/commits/50592f883f02e067e3337e524b9b623f5f352b0b
