### ISSUE TITLE
Monster bash vpw, star trek nfozzy black squares

### ISSUE THREAD

**Issue by emgroom** [vpinball/vpinball#207]
Recently started playing vpvr and just trying out many tables. Have come across quite a few tables with black squares or missing textures. I've redownloaded these tables and still same effect.  The 2 in the title are rhe most prominent ones. Also have small flickering squares on most tables. Am using the latest 10.8 vpvr. 
![20221127_133417](https://user-images.githubusercontent.com/119262623/204160606-d5634d65-e7bd-467e-9dbf-fc8254e8d085.jpg)
![20221127_133354](https://user-images.githubusercontent.com/119262623/204160608-caff7735-dcb6-4c3a-92f1-27bd2fdde54d.jpg)
![20221127_133351](https://user-images.githubusercontent.com/119262623/204160609-d5355d6f-9602-4c5b-aec8-3876acaa8e30.jpg)

**Comment by vbousquet** [comment]
Could you use the "bug report" issue template ? It's very difficult for us to understand what is wrong and solve it without the requested informations.

**Comment by emgroom** [comment]
Apologies.  This is my first time reporting any issues on github so pardon my ignorance. 

**Describe the bug**
Black squares/missing textures completely blocking certain parts of playfield.  Most noticeable is monsterbash by vpw.  On the star trek enterprise by nfozzy when pop bumpers are being hit by ball it does the same.  I have also noticed random flickering squares while looking downwards at the lockbar as well for almost all tables.  

**To Reproduce**
Opening table with vpvr v10.8.0-323-f8c26fc

**Expected behavior**
No missing textures

**Screenshots**
Attached.

**Crash dump**
N/A

**Versions**
 - VPX: vpvr v10.8.0-323-f8c26fc
 -  32 bit
 - Windows version 10
 -GPU Rtx 2080ti, CPU AMD 5500, using Quest 2 headset through steam VR/Oculus app

**Comment by emgroom** [comment]
Ah. I will have to try later when I get home. I will report back

**Comment by emgroom** [comment]
Yep the 603 build completely fixed all of it!!  Thanks!
