### ISSUE TITLE
DMD Flashers no longer work after #2078

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#2080]
While playing with the new [embedded window code](https://github.com/vpinball/vpinball/pull/2078) #2078, I've been able to get DMDs embedded on iOS and Android. 

Textbox DMDs work, but Flasher DMDs now appear empty.

I added some test code to the flasher, just to confirm the dmd frame has valid data, and it seems good:
```
      {
         Player::ControllerDisplay dmd = g_pplayer->GetControllerDisplay(-1);
         if (dmd.frame == nullptr)
            return;
         const vec4 dotTint = dmd.frame->m_format == BaseTexture::BW ? color : vec4(1.f, 1.f, 1.f, color.w);
         g_pplayer->m_renderer->SetupDMDRender(0, dotTint, dmd.frame, m_d.m_modulate_vs_add, false);

         std::ofstream file(g_pvp->m_szMyPrefPath + "file.raw", std::ios::binary);

         if (file.is_open()) {
             file.write(reinterpret_cast<const char*>(dmd.frame->data()), 128*32*4);
             file.close();
         }
      }
  ```

![Screenshot 2024-12-30 at 7 48 20 AM](https://github.com/user-attachments/assets/aba95275-d6f0-4703-8bea-c61ec9bf5b9f)

**Comment by vbousquet** [comment]
Should be fixed in latest

**Comment by jsm174** [comment]
Tested and working great. Thanks @vbousquet !
