### ISSUE TITLE
Issue with Capture external DMD checkbox in VR options, when using a VPX table  (non VRRoom) with a B2s file

### ISSUE THREAD

**Issue by RGYsr** [vpinball/vpinball#215]
**Describe the bug**
In preferences- VR settings - Backglass / DMD Capture checkbox section.

If the Capture Backglass is checked, the Capture external DMD checkbox must be unchecked, or the backglass disappears after 1 second after loading. 

Tested on many different Non VRRoom tables.

**Versions**
VPinballX_GL-10.8.0-607-eabc079-Release-gl-win-x86
VPinMAME-sc-3.6-239-0a38627-win-x86 (same result with versions 3.4 and 3.5)
DMDext-v1.10.2-x86 ((same result with version 1.8.2)
Flexdmd V1.8
B2SBackglassServer-1.4.1-589cc4e-Release-win-x86  (same result with versions1.3.1.1) 

 - Windows 10 version 22H2 X64
 - Nvidia RTX 2080 ti
 - Intel I7 4790 4Ghz
 - 16gb RAM
 - Valve Index, & Steam

**Comment by RGYsr** [comment]
I just tried version VPinballX_GL-10.8.0-712-292e2b7-Release-win-x86 and the issue still exists. I have to uncheck the capture external DMD or the backglass and DMD will disappear shortly after loading. Gear 323 told me he doesn't have this issue but he uses the 64bit version.

**Comment by vbousquet** [comment]
This bug is the same as https://github.com/vpinball/vpinball/issues/238
Therefore I will add a link to the other issue report and close this one to have all feedback on the same issue
