### ISSUE TITLE
Primitive Animations

### ISSUE THREAD

**Issue by 3rdaxis** [vpinball/vpinball#216]
Seems the primitive animations get stuck after sometime unless a timer and "Stopanim" are used. Did some rudimentary testing on a blank table and imported a simple mesh with a simple animation and it worked fine until I let it run for about five minutes then it locked up. Put in a "stopanim" on a separate trigger and this would free it up but it would eventually get stuck again. 

This is happening on all of my tables with primitive animations, haven't tested anyone else's yet and this seems to be a 10.7.2 issue only.

**Comment by toxieainc** [comment]
So 10.8 and 10.7.0 don't show it?

**Comment by toxieainc** [comment]
Oh, and do you have a link to one of your tables that shows the issue?

**Comment by toxieainc** [comment]
Or for repro, which command do you use? PlayAnimEndless(float speed)?

**Comment by 3rdaxis** [comment]
Using Playanim that's it. Here is a link to the table. https://www.vpforums.org/index.php?app=downloads&showfile=14051

**Comment by 3rdaxis** [comment]
Also having issues with the flipper images. Seems that it's cutting them in half and blacking them out. launch the table and use the control keys to cycle throw the flipper images in game to see. Even if I replace the image it cuts it in half. Or look at image _flipper_white_black in the editor.

**Comment by 3rdaxis** [comment]
I=The animations worked in 10.7.0. I haven't tried 10.8 yet.

**Comment by toxieainc** [comment]
Somehow i fail to repro.
I downloaded the table, and made it so that the left flipper triggers the sub of a target hit. Works with all tested VPX versions (target wobbles each time i press the left flipper). What do i have to do exactly to make it fail with 10.7.2?

**Comment by 3rdaxis** [comment]
Um. When I launch the table in 10.7.2 and play it normally, the targets will wobble once maybe and the pop bumper ring primitives will get stuck as well. Maybe it's something on my end.

**Comment by toxieainc** [comment]
Okay, then i will try with normal gameplay.

**Comment by toxieainc** [comment]
As i still couldn't repro it, i poked at the code a bit and found a potential issue. Could you please try with https://github.com/vpinball/vpinball/actions/runs/3712894542

This also fixes the issue that primitive playback animation was dependent on the framerate.  :/
The fix now assumes that the original animation speed was tweaked at 60fps.

**Comment by 3rdaxis** [comment]
Is that 10.8?

**Comment by toxieainc** [comment]
Yes. Its enough to just copy the .exe (if you're using VPX via DX and not via OpenGL/VR), everything else is roughly still the same.

**Comment by 3rdaxis** [comment]
I can just drag the files in and let it over write? except the tables file of course...

**Comment by 3rdaxis** [comment]
Oh I see, nevermind. I'll try it now.

**Comment by toxieainc** [comment]
Yup. Just rename the 10.7.2 .exe and bring the new one in.
Leave everything else as is. This is not a general rule, but for now this applies to 10.8 beta.

**Comment by toxieainc** [comment]
> Also having issues with the flipper images. Seems that it's cutting them in half and blacking them out. launch the table and use the control keys to cycle throw the flipper images in game to see. Even if I replace the image it cuts it in half. Or look at image _flipper_white_black in the editor.

Unfortunately i also cannot repro this one. Could you please share your video settings?

**Comment by toxieainc** [comment]
..can repro the flipper image issue now. This is extremely weird. If one exports the image, everything looks good, but when loaded its ~2/3 black.

**Comment by toxieainc** [comment]
The latter is also fixed, can you please confirm all?
https://github.com/vpinball/vpinball/actions/runs/3725307259  has all the fixes  (pick release/x86)

**Comment by vbousquet** [comment]
@toxieainc I have just changed the way visual animations are processed. Now, they are performed once per frame, separately (before) from the rendering. It should not impact your change (since you have already tied the animation to be framerate independent) and it goes in the same direction (being frame rate independent, do not depends on visibility flags, avoid animation being updated multiple times due to multiple render call for example for normal + reflections rendering).

**Comment by toxieainc** [comment]
ping @3rdaxis for confirmation

**Comment by toxieainc** [comment]
@3rdaxis The fix will also be in the upcoming 10.7.3

**Comment by toxieainc** [comment]
..and its released

**Comment by 3rdaxis** [comment]
Hey Toxie, sorry i've been busy with Holiday stuff and family.

**Comment by toxieainc** [comment]
No prob

**Comment by toxieainc** [comment]
ping  :)

**Comment by vbousquet** [comment]
Just checked and this seems to be fixed. Also saw some successfull testing from VPW team, so I will close this for now. @3rdaxis Please just tell if there are still things to fix!
