### ISSUE TITLE
Ball vanishes within orb saucer

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#218]
**Describe the bug**
Instead of staying visible, the ball is not clearly rendered (=on top) of the orb saucer in JPs TOTAN.
Works fine in 10.7.2

**To Reproduce**
1. Go to vpforums, dload JPs TOTAN
2. I used both DX & GL for testing this

**Versions**
 - VPX: 10.8 rev 614

**Comment by passionforpins** [comment]
confirmed. Same in 10.8.0 rev 608 too. 10.72 366 shows fine.
