### ISSUE TITLE
VR-GL v619 and Beyond Don't Work (for me)

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#220]
**Describe the bug**
VR-GL v619 and beyond all crash with GL Errors

**To Reproduce**
Try any build after v618, I receive 4 GL errors and one PinDMD3 error on every table. After clicking off the errors the VR-GL is shut down.

**Comment by toxieainc** [comment]
Could you please retry with the latest build? Otherwise we'd need the exact GL errors.

**Comment by studlygoorite** [comment]
> Could you please retry with the latest build? Otherwise we'd need the exact GL errors.

Just tested VR-GL (64bit) v628 and have the same errors, sorry it's not a PinDMD3 error


![error](https://user-images.githubusercontent.com/87738258/207652905-bba4c9e1-782f-46d4-97fd-bac4534ca137.PNG)
![error1](https://user-images.githubusercontent.com/87738258/207652931-216f7074-3d2a-4339-9274-9de1522625f7.PNG)
![error2](https://user-images.githubusercontent.com/87738258/207652943-33b078cd-c1ef-48b2-aadf-fc13e7db8053.PNG)
![error3](https://user-images.githubusercontent.com/87738258/207652956-017999c3-d1a1-4cc5-a9dd-9af7ff993018.PNG)

**Comment by studlygoorite** [comment]
I should note that I don't have a "D" drive :)

**Comment by toxieainc** [comment]
That helps, thanks. The D: drive message just points to the drive where the original source files were stored, so it seems like the github actions build stores them there.  ;)

**Comment by toxieainc** [comment]
Fixed, thanks!
