### ISSUE TITLE
Case sensitive filenames

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#231]
For the standalone builds, some operating systems have case sensitive filenames. 

For example, on the runtime side, many scripts reference `Controller.vbs`, but it's stored in the repository as `controller.vbs`. Other examples: (`bumperbase.bmp`, `bumperCap.bmp`, `bumperring.bmp`, `bumperskirt.bmp`)

On the compile side for example `SDL2` is `SDL2` and not `sdl2` (`inc/sdl2`)  (ex. `#include <SDL2/SDL.h>`)

I'm not sure the ultimate solution to this problem for runtime (an alias list, something that checks the directory first against all lowercase), but I figured it would be good to document when thinking about the future.

**Comment by jsm174** [comment]
In standalone, I've temporarily renamed `controller.vbs`, which doesn't look like history has been lost.

`git mv -f controller.vbs Controller.vbs`

**Comment by jsm174** [comment]
I've found a few tables that reference it as `controller.vbs`, so I will just put a shim in place:

```
STDMETHODIMP ScriptGlobalTable::GetTextFile(BSTR FileName, BSTR *pContents)
{
   char szFileName[MAX_PATH];
   WideCharToMultiByteNull(CP_ACP, 0, FileName, -1, szFileName, MAX_PATH, nullptr, nullptr);

#ifdef __STANDALONE__
   if (!_stricmp(szFileName, "controller.vbs")) {
      strcpy(szFileName, "controller.vbs");
   }
#endif
```

**Comment by EarBiteR** [comment]
On Linux if you are using ext4 (most do) then you might try below which enables insensitivity on folders you mark as such:

For existing filesystems:

tune2fs -O casefold /dev/sda1

This doesn't automatically make the whole filesystem case-insensitive – each directory has to be marked so individually:

chattr +F ~/.wine

Then stuff that works fine on windows being insensitive and fails on Linux BEING case-sensitive might work without any code changes!

from https://superuser.com/questions/290480/case-insensitive-partition-under-linux

**Comment by francisdb** [comment]
@jsm174 can this be closed now that most of this stuff now works case-insensitive?

**Comment by jsm174** [comment]
I think so, there are still a few places I didn't copy it over yet. Probably need to research, flex, wmp, etc.

As for WINE, all the code fixes put in place for this wouldn't make a difference, since they aren't technically using standalond.
