### ISSUE TITLE
Ramp visibility cannot be changed via script anymore

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#233]
**Describe the bug**
There are some tables that set VPX ramp visibility via script. Some moving ramps uses this. This is not working anymore and it has worked fine in 10.6 and 10.7.

**To Reproduce**
1. Make a ramp (ramp123)
2. Start game with F5
3. Open debugger
4. Call ramp123.visible = false
5. --> Ramp will not disappear

**Expected behavior**
Ramp visibility should changeable via script like in previous VPX version

**Versions**
 - VPX: 10.8 rev 650
 - Windows 10
 - Any Nvidia or Intel

**Comment by vbousquet** [comment]
I don't think anything changed in the behavior of ramps in 10.8. I made a few tests and in my test, they behave the same in 10.7.2 and 10.8.

Ramp visibility is always taken in account but they are staticly rendered (so not updated) if their material is not active. So to be able to toggle visibility of a ramp, you have to set its material to active.

I have checked this on 10.8 (with the new live debugger :) ) and it is fully working, so I will close this issue. Tell me if I missed something and I will reopen
