### ISSUE TITLE
VR Blackglass not loading since 10.8.0 rev513

### ISSUE THREAD

**Issue by retro27** [vpinball/vpinball#238]
**Describe the bug**
Since 10.08.0 rev 513- Fix building DX9 shaders #65, B2S backglass has stopped working. I get a clear back ground when in VR, (see attached image)  The last working build was 10.8.0 rev 510, 

On the Current build 10.8.0 rev 672
If I disable the Capture External DMD and leave Capture External Backglass enabled, the the Backglass capture works ok.
But cant get both to run at the same time.

**Expected behavior**
Both Capture External backglass and Capture External DMD to work at the same time.

**Screenshots**
Please see attached
![IN VR](https://user-images.githubusercontent.com/16049569/209868062-a781282b-94d4-4929-8d7c-5c174a4e40cf.png)
![VR settings](https://user-images.githubusercontent.com/16049569/209868078-b43b01d0-2cef-410f-84e8-df04a5834fe0.png)

**Versions**
 - VPX:  10.08.0 rev 513 - problem started,
 - Windows 11 Pro 22H2
 - Nividia 3070 RTX, 
 - CPU 11th Intel i7-11800H

**Comment by Krystm** [comment]
Same issue (PizzaTime) on 669

**Comment by Krystm** [comment]
Still present on 697.  Seems can get one or the other. Tested Pizza Time / Harry Potter. Tables with single like Iron Maiden / GOTG / Stranger Things all work great.

**Comment by Krystm** [comment]
Ok, so I did some more testing and I figured out at least my issue. The DMD and Backglass have to be on separate monitors. Not sure why but adjusted pup settings and separated the dmd and back glass and everything is working as it should. I think this is still a bug as 510 and prior I could run it all one one monitor. Tested with 609 and then 698 just now.

**Comment by retro27** [comment]
Thank for testing, I tried the same, I got the backglass working, if the backglass was setup on a 2nd display.
I tried running both DMD and backglass on a single display and I get the problem. of it only showing 1 of the 2.

I tested VP 10.6.0 and I don't have any problems, both DMD and backglass work ok on a single display

**Comment by Krystm** [comment]
I found another interesting issue today and as I’m writing didn’t think to to test it but I certainly can. While the seperate monitors did fix the capture of both dmd and backglass, I noticed that as soon as I started the table the videos stuttered in VR, table ran fine and no issues just video stutter. So I moved the dmd from my 3rd monitor to my playfield monitor and left the backglass on the backglass monitor, and the stutter disappeared. I may try putting all the pup in the play field monitor and see if that works, not sure it’ll matter but at least should help with replication of the issue.

**Comment by vbousquet** [comment]
Latest pre-alpha version (build 1085) have a fix for this.
@retro27 @Krystm Could you give it a try and tell us if this solved it for you ?

**Comment by retro27** [comment]
Hi I've just testing v1093, still not working. The B2S is working when I have both options selected, but not pickup the DMD Extension. I have also noticed with in the DMD screen its picking up the bottom of the B2S screen. very odd.

Pictures of my settings  and screen captures
![Screenshot 2023-05-13 111420](https://github.com/vpinball/vpinball/assets/16049569/1876d401-6a59-4ce4-b19b-7556a545a0aa)
![Screenshot 2023-05-13 112222](https://github.com/vpinball/vpinball/assets/16049569/70bfa48a-82d3-4987-b3d7-bf008412431a)

**Comment by vbousquet** [comment]
I tried to solve this better. Could you test the latest 1098 build ? This time, I hope it should be good

**Comment by retro27** [comment]
HI vbousquet just tried 1112 build both B2S and Pup are now working from a single display in VR
Thank you again for your great work.
![Screenshot 2023-05-16 083341](https://github.com/vpinball/vpinball/assets/16049569/003d03c7-e493-4b24-bb12-de0709ce4e8a)

**Comment by toxieainc** [comment]
Thanks for the verification!
