### ISSUE TITLE
Missing DMD Score with v10.8.0-694-ef6c106

### ISSUE THREAD

**Issue by coreduo0099** [vpinball/vpinball#244]
on the 3 screen dmd score display, no score is displayed on Phantom Of The Opera (Data East 1990) 3 Screen.zip 1.0  from vpforums

**To Reproduce**
1 run table from 7.x and notice score is there
2 run table from 8.x and notice score is not there

**Expected behavior**
DMD scoring should work

no issues yet with any other full dmds, so perhaps it is an issue with the 2013 dmd code?

**Comment by vbousquet** [comment]
Please could you fill up the issue with the information requested in the template (version,...). Without these informations, there is no way to understand and solve the problem

**Comment by vbousquet** [comment]
Just try it without any additional information and could not reproduce. The table does not include a DMD in the display so it is very likely a PinMame / Freezy DMD configuration problem, not linked to VPX itself. Therefore, I will close the issue for now
