### ISSUE TITLE
What is Visual Pinball correct file to use ? the exe installer or the compressed file ?

### ISSUE THREAD

**Issue by Augusto7743** [vpinball/vpinball#248]
In
https://github.com/vpinball/vpinball/releases
have the information

If you want to install Visual Pinball from scratch, please download and install https://github.com/vpinball/vpinball/releases/download/v10.7.2-366-f94da1e/Main.Download.Installer.-.VPX72setup.exe first.
Then overwrite the contents of the Visual Pinball folder with the 10.7.3 archive.

Using the installer is created registry keys for Visual Pinball components ?
Trying use Visual Pinball from compressed file without exe installer works in same way as the exe installer ?

Only trying understand what is the correct and better way to use Visual Pinball.

Have an nice week.

**Comment by toxieainc** [comment]
It depends.

The installer basically is a convenience thing. It also not just includes VPX, but also other programs like PinMAME, B2S, FlexDMD, etc.
So if you never had anything installed, then the installer is the way to go.

When updating from older VPX versions, the smaller zip (pick the x86 release build) can simply be used to overwrite everything that already exists in the Visual Pinball folder.

**Comment by toxieainc** [comment]
But the zip also works on its own. So if you just want to give Visual Pinball a quick try, just unzip it somewhere, and try the builtin simple example tables.

**Comment by Augusto7743** [comment]
If only running VPX and Vpinmame in an simple computer using only an display monitor is required B2S are FlexDMD ?

**Comment by toxieainc** [comment]
In my opinion, on a desktop/laptop, one only needs Visual Pinball X, VPinMAME and FlexDMD. Optionally also PUP, but only few tables require it.
Nevertheless, the installer still is the best option if trying out VP for the first time.

**Comment by toxieainc** [comment]
As no other feedback/questions here, closing
