### ISSUE TITLE
Script editor should warn about duplicate sub definitions 

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#25]
I've seen it too often that author may accidentally add similar code twice in a project. In these cases VPX is not giving an error or warning, and the table will use one or another version that is in code. This happened lately when one author was updating the table to use different light fading code. 

Example:
```vbs
Sub init_lights
   Debug.Print "first"
End sub

Sub init_lights
   Debug.Print "second that should be warned"
End sub
```

It would be really nice to get some exclamation for these accidents when table is started. Or add an editor option that will make these exclamations visible, as this can possible break some table releases that has this problem.

**Comment by toxieainc** [comment]
I added a simple test that should hopefully catch these.
Unfortunately the current VP script parser isn't really capable to properly analyze such errors, and also to output them, so i improvised a bit and duplicates are shown as a tooltip as the script editor comes into focus.
