### ISSUE TITLE
F6 to change POV settings makes VPX to close

### ISSUE THREAD

**Issue by Thazoot** [vpinball/vpinball#250]
When trying to enter POV settings by pressing F6, on many tables, VPX closes immediatly.

**Comment by toxieainc** [comment]
Should be fixed now, please retry with latest build.

**Comment by Thazoot** [comment]
Hi toxie, thanks. Just a question. I'm pretty new in the github universe.
I'm unable to find the latest build. It looks like it's the same version
(saying latest update is on the last week). I use this one:[image:
image.png]

**Comment by Thazoot** [comment]
Sorry, made a little mistake. I use the release version, not the debug

**Comment by toxieainc** [comment]
Its in the 'Actions' Tab above, for example: https://github.com/vpinball/vpinball/actions/runs/3866203184
(x86 release is needed)

**Comment by Thazoot** [comment]
Thank you very much. This is fine now. Thanks for the lesson :)
