### ISSUE TITLE
10.8.0 GL x86 Bam Headtracking 

### ISSUE THREAD

**Issue by mobutu16** [vpinball/vpinball#255]
**Describe the bug**
Bam tracking previously opened, working fine in FP. Box BAM headtracking checked. VP opens, can play with any table but dont detect headtracking so no 3D movement done and impossible to open BAM menu.
When you press Q to quit, VP hangs and close task needed.

**To Reproduce**
1. Update latest BAM dll
2. Open Bam Tracker
3. Open Vpinball_gl.exe v 10.8.0 694 x86
4. Checked BAM headtracing option
5. Open table, works fine but w/o any headtracking son not 3D movement is done.
6. Cannot close .exe with Q key

**Expected behavior**
Detect BAM tracker

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions**
 - VPX: 10.8.0 694 x86
 - Windows version: 10 pro
 - GPU: nvidia 1660

**Additional context**

**Comment by IdolCrasher** [comment]
I have this problem!  I can run Future Pinball just fine with headtracking.  I am able to run the newest 10.8.0 PinBall_GL 32 bit.  I can play VPX tables just fine, but the headtracking does not engage.  I have the headtracking checkbox checked, and I have BAM running successfully before I launch.  Please help.

**Comment by punkie909** [comment]
i remember by patching this line of code, i got kinect headtracking working. it looks like this condition was always true and it never got to the headtracking part.

```
diff --git a/pin/player.cpp b/pin/player.cpp
index adc6a6f..241e4cb 100644
--- a/pin/player.cpp
+++ b/pin/player.cpp
@@ -5482,7 +5482,7 @@ void Player::Render()
    } 
    else
 #endif
-   if (m_dynamicMode)
+   if (m_dynamicMode && !m_headTracking)
    {
       m_pin3d.InitLayout(m_ptable->m_BG_enable_FSS, m_ptable->GetMaxSeparation());
    }
```

but take this with a grain of salt, as this was still on the old vpvr repo on commit [76bf273](https://github.com/vpinball/vpvr/commit/76bf27320ec751cf9b3be3fecbfefdaf6ee7b1f3), since then I haven't tested my head tracking setup and I did not test what else it breaks.

**Comment by IdolCrasher** [comment]
Does this mean the issue has a fix?  I am hopeful  :)  I'm not really sure how to compile and use the source code, so I guess I have to wait for a release with the fix.

**Comment by vbousquet** [comment]
You can download the beta build from here: https://github.com/vpinball/vpinball/actions/runs/3962007715

**Comment by mobutu16** [comment]
Tested rigjt now Vincent.

Thanks a lot Vincent,

Although  BAM headtracking is working right now is not possible to configure the Axis, you need to do this configuration into BAM menú, the BAM Key to open is on the Bam.cfg file.

If we cannot open BAM on play, it will be impossible to configure X, Y and Z axis.

Need a call to open this BAM menu

**Comment by punkie909** [comment]
wasn't it that you'd need to configure everything in FP, take the cfg from there and use it in VP? or did this change?

**Comment by toxieainc** [comment]
> Although BAM headtracking is working right now is not possible to configure the Axis, you need to do this configuration into BAM menú, the BAM Key to open is on the Bam.cfg file.
> 
> If we cannot open BAM on play, it will be impossible to configure X, Y and Z axis.
> 
> System creates a BAMViewSettings.xml , changed some Scales, nothing happens
> 
> Need a call to open this BAM menu

@mobutu16 Can you please file this as a separate issue/request?
