### ISSUE TITLE
Enhancement: Add Display Resolution to table-level options

### ISSUE THREAD

**Issue by SmedleyB** [vpinball/vpinball#257]
**Is your feature request related to a problem? Please describe.**
With current state of VPX, resource demands can vary greatly from table to table. Setting the refresh rate via VPX's Display resolution dropdown when in Fullscreen mode has been key to me finding optimal performance for a table. For example, some tables run with very smooth movement when set to 2k 165hz resolution. For other, more demanding tables, I must lower the refresh rate to the 2k 120hz entry in VPX to maintain the smooth movement. I would like to be able to set the resolution & refresh rate on a table by table basis so I can avoid changing it in main VPX settings every time before playing a new table.

**Describe the solution you'd like**
Display resolution dropdown should appear next to other video options on the table, and allow for a setting that defaults to your overall VPX setting. 

**Describe alternatives you've considered**
I've tested many graphics driver and VPX video option combinations, I find limiting the refresh rate via VPX to be key to getting optimum performance for a given table.

**Comment by vbousquet** [comment]
10.8 (in alpha state, so unreleased yet) version adds the ability to swap settings on startup by providing a custom ini file. This is meant for this type of situation and should cover the need. Therefore, I will close the feature request
