### ISSUE TITLE
VPVR 10.8 - Some flashing lights in a few tables  shows a black spot on the screen

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#258]
**Describe the bug**
Some flashing lights in a few tables  shows a black spot

**To Reproduce**
Tables that has the issue : 
Tee'd Off (Gottlieb 1993) 2.0.3.vpx (rothbauerw, dark)
VR ROOM Fish Tales (Williams 1992) VR v1.2.3.vpx (Bigus1 - VR Room by Rawd)
Launch both games with rev 713 and you see that some flasher will give black spots

**Expected behavior**
Flashers should just blink and not give a black spot (not natural)
rev 603 works fine

**Screenshots**
Hard to create , but here are 2 from teed off, table FT has the same
![1](https://user-images.githubusercontent.com/48748234/212677038-bcc74fb8-2ebb-40b6-875a-48ddda66c638.png)
![2](https://user-images.githubusercontent.com/48748234/212677044-20480679-f7c3-43a9-a2f2-902319f7a715.png)

**Crash dump**
NA

**Versions**
 - VPX: VPinballX_GL.exe 10.8.0 rev 713
 - Windows version 11 (22h2 build 22621.1105)
 - GPU and video settings if applicable RTX3080 
Settings:
![image](https://user-images.githubusercontent.com/48748234/212677913-5d333104-4a0e-4f1f-a761-40807981dc1e.png)

**Additional context**
NA

**Comment by Thazoot** [comment]
Same issue with above named table (Teed of and Fish tale) but also have it with Indiana Jones Stern 2008 (Bigus1 2.0 version. I use VPX 10.8 rev 717 
![indi](https://user-images.githubusercontent.com/63427471/214224828-c41fe743-96cd-46b8-839c-af61d082c8e2.jpg)

**Comment by Gigalula** [comment]
Don’t forget to include your setting from nvidia control panel to help coders to reproduce the bug sometime it’s only video setting.

**Comment by studlygoorite** [comment]
Issue continues with v738 (64bit) on Apollo 13
![Screenshot (159)](https://user-images.githubusercontent.com/87738258/215144358-041898f0-a3f0-44da-8b97-eeb369129f44.png)

**Comment by dj-casey** [comment]
hi any updateon this ? Issue still exists on lastets version

**Comment by zack06007** [comment]
Same problem with 10.8 for Fish Tales!

**Comment by vbousquet** [comment]
This bug should be solved in latest builds (900+).

@MikedaSpike @studlygoorite Could you confirm that everything is all good now and that I can close the issue ?

**Comment by studlygoorite** [comment]
> This bug should be solved in latest builds (900+).
> 
> @MikedaSpike @studlygoorite Could you confirm that everything is all good now and that I can close the issue ?

Thanks, I tested again with v887 64bit that I had installed and the issue was fixed. I then loaded up v905, the issue was still solved but I had no DMD with Apollo 13, tried v904 and the same, no DMD. Loaded up v900 64bit and my DMD was back :) So v904 and 905 break my DMD. I have a PinDMD3 in my cabinet and run VR from my cabinet if that helps.

**Comment by MikedaSpike** [comment]
> This bug should be solved in latest builds (900+).
> 
> @MikedaSpike @studlygoorite Could you confirm that everything is all good now and that I can close the issue ?

Thanks @vbousquet  I tested this morning 906. And the flashes are working, but same as @studlygoorite mentioned, The DMD is not displaying anymore.
During VR, I switch from real DMD to virtual (as I can't get it to work if my real DMD is enabled), and during gameplay it flashes a couple of time green, but nothing more
Close this issue and create a new one for the DMD ?

**Comment by vbousquet** [comment]
I moved the new issue to https://github.com/vpinball/vpinball/issues/353 and closed this one
