### ISSUE TITLE
10.7.2

### ISSUE THREAD

**Issue by a-bord** [vpinball/vpinball#263]
10.7.2 and 10.8 Image Manager will not export large image files.

1. Go to Image Manager
2. Find a large image file (i.e 4096 x 8192)
3. Hit Export
4. Nothing happens
5. Repeat for small file from same import path and you get a finder window to place your file.

![image](https://user-images.githubusercontent.com/90645800/213729882-de60687f-01e9-4d82-b624-4ea078c7cb49.png)

 - VPX: 10.7.2 Final (Revision 366 (f94da1e), 32bit) also 10.8 beta
 - Windows 10

**Comment by toxieainc** [comment]
@a-bord I just tried to repro this by importing a 8192x4096 file to the example table, then saving, closing, reopening and exporting. That worked.
So can you please provide a repro file to me?

**Comment by toxieainc** [comment]
@vbousquet Seems like we have to handle this case all over the place then, also now that we are not-only-windows-anymore?

**Comment by vbousquet** [comment]
I think so yes. On a side note, this one was coming from a VPX file modified outside of VPX (by the lightmapper I created here: https://github.com/vbousquet/vpx_lightmapper), so it was mainly an external bug, but VPX should be able to handle gracefully both separators in the whole codebase
