### ISSUE TITLE
mouse cursor hidden, why?

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable

**Additional context**

**Comment by vbousquet** [comment]
This is caused by this commit: https://github.com/vpinball/vpinball/commit/dc78d27d3b83251d93b3fa796f7a1d3a8303156d

**Comment by toxieainc** [comment]
Hmmm.. Will recheck/evaluate.

**Comment by JorgePedro65** [comment]
That´s right, it is cause by the dc78d27 commit. Please find a solution because I don´t want to hide mouse cursos after exiting a game. Thanks so much.

**Comment by toxieainc** [comment]
Fixed
