### ISSUE TITLE
Mouse loses focus after game, cannot use editor 

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#270]
**Describe the bug**
To add to what JorgePedro65 reported the mouse has now lost focus after a table is run so the editor cannot be used, nor even closed easily.
**To Reproduce**
1. open any table and run it in play mode
2. Exit game and you'll se the mouse is behind the editor
**Expected behavior**
When exiting a game back to editor one should be able to use the mouse to perform any editing functions

**Versions**
 - VPX: VPinballX-10.8.0-726-dc78d27-Release-win-x86 and 736
 - Windows 10 22H2 home 64
 - Nvidia GTX 1060 6gb driver 528.24

**Comment by RGYsr** [comment]
Same here, mouse cursor disappears when hovering over editor
