### ISSUE TITLE
No DMD in VR on latest version of VPX 8 Beta (743) GL

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#273]
**Describe the bug**
Latest version of 10.8 beta.  No DMD on tables anymore.  (not using the capture feature)

**To Reproduce**
Try to play a VR ROOM table.  I tried 5 tables including T2 and Fishtales for example. 

**Expected behavior**
I would have a DMD in VR

**Screenshots**
I can get a screenshot if needed but its the VRROOM table and the DMD is missing.   I do hear the ROM audio, can insert coins and can start table and play. 

**Crash dump**
No Crash

**Versions**
10.8.0 Beta Rev 743

**Additional context**

UPDATE 1 - Went to 10.8 732 and the backglass issue and the DMD issue not happening there.   (have the missing mouse cursor issue though on this version)
UPDATE 2 - Went to 10.8 738.  Mouse issue resolved and does not have the missing backglass or DMD issue that is in 743
UPDATE 3 - Went to 10.8 743 again to confirm I'd get the issue and indeed the DMD is missing and the backglass is missing on some tables again as expected. 
UPDATE 4 - installed 741 and this version also has the issue with the missing DMD on all tested tables and missing backglass on some tables
Final Update- Looks like the [Cleanup IndexBuffer](https://github.com/vpinball/vpinball/actions/runs/4029326008) update is where the issue started.  I now reverted back to 738 as that is the last playable version for now until the issue is resolved.   Hope this testing was helpful.

**Comment by toxieainc** [comment]
Thanks for nailing down the exact commit, this is always the most helpful! So up to @vbousquet then.  ;)

**Comment by vbousquet** [comment]
Thanks for this very good report. It helped me a lot and with the precise informations I was able to locate the bug. It's (hopefully) fixed now. @gear323 Could you confirm that everything is back to normal ?

**Comment by gear323** [comment]
@vbousquet  I can confirm that you have fixed the issue in 751.    Thanks for fixing this bug so quickly. 

Testing and reporting issues is the least I can do for all the work you guys do.   

Thanks again
