### ISSUE TITLE
Backglass missing in VR on latest version of VPX 8 Beta (743) GL

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#274]
**Describe the bug**
Backglass is missing on some tables in VR  (Capture external backglass disabled)
**To Reproduce**
For example, try fluppers Whirlwind table

**Expected behavior**
Backglass would be shown

**Screenshots**
I can create a screenshot if needed but this should be super easy to reproduce.  I do hear the ROM audio, can insert coins and can start table and play. 

**Crash dump**
does not crash

**Versions**
10.8 Beta (743)

**Additional context**
UPDATE 1 - Went to 10.8 732 and the backglass issue and the DMD issue not happening there.   (have the missing mouse cursor issue though on this version)
UPDATE 2 - Went to 10.8 738.  Mouse issue resolved and does not have the missing backglass or DMD issue that is in 743
UPDATE 3 - Went to 10.8 743 again to confirm I'd get the issue and indeed the DMD is missing and the backglass is missing on some tables again as expected. 
UPDATE 4 - installed 741 and this version also has the issue with the missing DMD on all tested tables and missing backglass on some tables
Final Update- Looks like the [Cleanup IndexBuffer](https://github.com/vpinball/vpinball/actions/runs/4029326008) update is where the issue started.  I now reverted back to 738 as that is the last playable version for now until the issue is resolved.   Hope this testing was helpful.

**Comment by toxieainc** [comment]
Thanks once more. @vbousquet for vis

**Comment by vbousquet** [comment]
Thanks also for this very detailled report. SHould be fixed now. @gear323 Could you confirm that everything is back to normal ?

**Comment by gear323** [comment]
@vbousquet  I can confirm that you have fixed the issue in 751.    Thanks for fixing this bug so quickly. 

Testing and reporting issues is the least I can do for all the work you guys do.   

Thanks again
