### ISSUE TITLE
MeshBuffer update crashes Shadow Skitso MOD

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#279]
**Describe the bug**
The version i tested should match this one: https://drive.google.com/drive/folders/1s4IJmejEySuyMV1Q4x6VYm8TBMrxlE0V
Previously there were special checks in place to prevent grouped primitives to crash during the initial setup phase, maybe the same has to be done, too, for the new code path(s).

**Comment by vbousquet** [comment]
Just had a look, and I ported a bug :) It's (hopefully) fixed now.
This 'MeshBuffer' change is somewhat too big. It makes it difficult to be sure there are no side effect. I will keep testing

**Comment by toxieainc** [comment]
No problem. I will just assist by reviewing and testing. Good that you tackle this stuff and make things cleaner, etc.
