### ISSUE TITLE
Cannot move flasher or primitive realtime via changing it's position with a command.

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#28]
- flasher19.height = 300 <enter> -> this should move flasher height, but nothing happens. One needs to click on the table to let it run, flasher moves, but has also probably turned off by the game script.
- Workflow example from 10.6: 
    1. Call some flasher sub that is normally called via solcallback
    2. flasher and light objects tied to that solenoid are lit to full intensity and the scene is paused. 
        (internally this means that flashlevel value is set to 1, flasher timer is started and first round of the timer is ran; meaning that objects are set visible and their intensityscale and opacity is at flashlvl.)
    3. While in this state, one can easily adjust the position and intensity for each object.
        light001.bulbhaloheight = 43 'maybe works?
        flasher001.amount = 90
        flasher002.height = 230     'not working anymore; worked in 10.6
        flasher002.rotx = 23        'not working anymore; worked in 10.6
        flasher002.roty = -90       'not working anymore; worked in 10.6
        primitive13.z = 125.4
        primitive13.rotx = 56

This has made it almost impossible to adjust insert lights and multi object flashers via debugger. I need to take the table back to 10.6 to be able to adjust and position them.

**Comment by iaakki** [comment]
We've discussed this one a bit with authors and it seems this is one of the biggest issues that makes authoring hard in 10.7. I'm sure fixing this must be super complex. I guess this has happened because of some optimisation into player or something? 

Best example where this is giving issues is adjusting Flupper flasher domes. In 10.6 you could just call the flasher sub and then adjust the position for each light element that got lit. Yes they lit immediately when you call the sub.

In 10.7 no lights get lit when calling a flasher timer sub. You must click on game so that timer starts looping. Then you click debugger immediately and that way one can stop the timer and see the lights. Then you use editor to move for example bulb halo height, but yet again the game is not updating. You need to click on game to make it update, and the flash has faded off already, so you call it again and immediately click on game and then debugger. Adjusting these flasher domes perfectly takes several iterations in 10.6. In 10.7 it just takes 5x more time atm.

**Comment by toxieainc** [comment]
Yes, thanks, its next on my todo list to investigate what happened.

**Comment by toxieainc** [comment]
I just tested this with the current trunk version (https://github.com/vpinball/vpinball/suites/5737320761/artifacts/190154841) and it works for my tests.
Could you please check that one?

**Comment by toxieainc** [comment]
Okay, got it now, thanks! Can repro..

**Comment by iaakki** [comment]
Any guesses are you able to fix it? This really makes editing super painful.

**Comment by vbousquet** [comment]
Commit https://github.com/vpinball/vpinball/commit/862b6a5aef5ebdf9f0e40fe6d973f06297d0276b should (at least partially) fix this.

The behavior it implements is the following: when in pause mode (so debug also), the player will continue to render but suspend physics, animation, audio and input. This allows to tweak properties that do not depend on these to get visual feedback (visibility, position,... but not light state for example)

@iaakki could you give feedback on this to see if it's ok and if we close this issue or not ?

**Comment by vbousquet** [comment]
This is now fixed, so I will close this issue.
