### ISSUE TITLE
backdrop lights make black spots vpx 10.8 beta x86 (desktop)

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#282]
**Describe the bug**
Lights used to simulate a backglass burn black spots when lit on Playboy (Stern 2002) v1.1.vpx
**To Reproduce**
Start VPinballX-10.8.0-662-c02e8f9-Release-win-x86 or later
Load Playboy (Stern 2002) v1.1.vpx and enter play mode
Start a game in desktop mode and watch the simulated backglass upper left of screen. 
When rollovers are made the lamps will flash and leave a black spot

**Expected behavior**
lamps should not leave black spots behind
**Screenshots**
attached

**Crash dump**
NA

**Versions**
 - VPinballX-10.8.0-662-c02e8f9-Release-win-x86 or newer. It seems to begin with this version. Version 649 and prior does NOT do this.
 - Windows 10 22h2 home 64
 - Nvidia GTX 1060 6GB
**Additional context**
![playboy-spots](https://user-images.githubusercontent.com/52011304/215367301-7ea0f1a8-a03b-4d5c-a1d2-f54101e7f157.jpg)
![playboy-backdrop-lamps](https://user-images.githubusercontent.com/52011304/215367497-8dc21068-05be-4450-a57f-bcb53760cb8a.jpg)

**Comment by vbousquet** [comment]
I will close since this should be fixed in latest build. Please tell us if you are still facing this bug
