### ISSUE TITLE
Playfield missing

### ISSUE THREAD

**Issue by drinkcristal** [vpinball/vpinball#284]
I am trying to use the 10.8 version of VPX both in VR and non-VR. When running old and new tables, the playfield artwork is invisible (transparent).

The same tables running in 10.7.3 or earlier are fine.

I have tried the last few releases of 10.8 in both VR and non-VR and the outcome is the same

My set up is:
![image](https://user-images.githubusercontent.com/108242910/215975718-1fe9d1c1-2724-4498-b7ec-ebb130ed09b3.png)

It is a ROG ASUS laptop with the latest Nvidia drivers

I have tried re-downloading tables to no effect.

**Comment by vbousquet** [comment]
Could you fill the issue template ? Without the requested information, there is no way we can understand and eventually help you

**Comment by drinkcristal** [comment]
I assume you are referring to the template questions listed in the new bug report request. If I have misunderstood, sorry and please direct me to where I may find a template

**Describe the bug**
Loading and playing games in vpx version 10.8, the playfield is not visible and is transparent. Version 10.7.3 is fine as well as earlier versions

![playfield](https://user-images.githubusercontent.com/108242910/216007155-3d6b0ced-e6c0-450e-89ef-98aa71a99e62.png)


**To Reproduce**
Steps to reproduce the behavior:
1. Open Vpinball.exe (VPinballX-10.8.0-775-639a05c-Release-win-x86)
2. File open any table (in my case it was captain fantastic but I have tried multiple games)
3. Play table
4. No errors but the table playfield is not visible (as in attached screenshot)

**Expected behavior**
Playfield should be visible

This is the appearance in 10.7.3

![image](https://user-images.githubusercontent.com/108242910/216008002-ff4b682a-caff-41df-ba80-364eaf73fc03.png)


**Screenshots**
Provided

**Crash dump**
No crashing. The game runs as normal except no playfield is visible

**Versions**
See my original post for my set up

**Additional context**
None to add.

**Comment by vbousquet** [comment]
Yes, these informations are very important to understand. Thanks for filling it. I will have a look when I get some time off

**Comment by vbousquet** [comment]
@drinkcristal I have been testing with quite a lot of different setup and was never able to reproduce this bug. Could you have a try with the latest version (at least version 874) and a freshly downloaded table to check if you still have the issue on your side ?

**Comment by drinkcristal** [comment]
Thank you for looking into this. I will try the latest version as soon as I can (I am just in the middle of moving apartments ;-) )

**Comment by vbousquet** [comment]
Just made some more testing with the latest rendering code and the different version of captain fantastic's table. EVerything seems fine, so I will close this issue for now. Please reopen it if you are still experiencing problems.
