### ISSUE TITLE
Walls not Displaying Images VPinballX_GL

### ISSUE THREAD

**Issue by Lizarddddd** [vpinball/vpinball#286]
Walls are not displaying images when playing table.

I have tried Big Bang Bar, cyclone, and Eight Ball. These three tables use walls for the plastics and are not showing the images on them.

Using VPinballX_GL-10.8.0-775-639a05c-Release-win-x86.zip on W11 With nvidia gtx3070.

**Comment by vbousquet** [comment]
I think this was fixed v776 therefore I will close it for now.
Please tell us if the bug is still present and we will reopen it
