### ISSUE TITLE
 FileObj.FolderExists  (ERROR)

### ISSUE THREAD

**Issue by Gigalula** [vpinball/vpinball#288]
ERROR VBS example line :

	If Not FileObj.FolderExists(UserDirectory) 

All table with this line now stop on error. Noticed from VPX 10.8 build 742 to 780

build 717 to 741 tested to work fine.

Tested with  ("win x86 32bit build") all tested in VR mode

Robocop (Data East 1989)_drakkon(VRX8)(mod_1.2).rar   <-- with B2S file
Operation Thunder (Gottlieb 1992) (10.8) 1.4.zip
Laser Cue (Williams 1984) w VR Room 2.0.0.vpx.zip
Monte Carlo (Premier 1987) (10.7) 1.6.zip

only few example of tables tested.

Also Table that crash and force close VPX 
"TimeLord2.0.2.1.zip"

MORE INFO:

Tested all version up to 741 without issue.
The problem start with build 742 and Up

**Comment by toxieainc** [comment]
@Gigalula Can you please verify on your setup with the latest build that this is really fixed for you, too? Thanks!

**Comment by Gigalula** [comment]
> @Gigalula Can you please verify on your setup with the latest build that this is really fixed for you, too? Thanks!

Yep all good with latest build concerning this bug on my side. Thanks ... 

My personal dream for my cab is to see the headtrack fixed to be playable bahhhh we can always dream right LOL.

Thanks again for the quit fix like always your the man.

**Comment by toxieainc** [comment]
The headtracking is already tracked as an issue, right? Maybe you could contact ravarcade on that?
Unfortunately i have no experience at all with that code..
