### ISSUE TITLE
VR Table Rec, Table Up, and Table Down settings disappear when going in  Key. Nudge, and DOF menu. 

### ISSUE THREAD

**Issue by Rascal5688** [vpinball/vpinball#289]
**Describe the bug**
I noticed the three key assignments In the VR Options menu for Table Rec, Table Up, and Table Down, become unassigned a lot. Gigalula gave me a hint as to when it happens. Any time you go into the Keys, Nudge, and DOF setting menu, even if you just go in and Cancel, the VR settings for these three keys get lost. 

**To Reproduce**
1. Go to VR Options and do Button Assignments for Table Rec, Table Up, and Table Down.
2. Click on OK to save.
3. Now open the Keys, Nudge, and DOF options menu and just click Cancel.
4. Now if you go back into VR Options you will see the buttons are unassigned again.

**Expected behavior**
It should not clear these key assignments.

**Versions**
 - All GL 10.8 versions

**Additional context**
It seems like when leaving Keys, Nudge, and DOF, keys are saved from that dialog form, but somehow wipe keys set for VR. Maybe these keys should be moved to Keys, Nudge, and DOF and protected from getting overwritten.

**Comment by vbousquet** [comment]
Hi! This bug was supposed to be solved by this commit: 639a05ce5044662e8290e80b943f76ce0c0ea19f
Could you confirm that you did check with the absolute latest version of VPX ?

**Comment by Rascal5688** [comment]
I will check now, thanks. Just downloaded 779. You are correct my friend, it is indeed fixed, sorry for the report.
