### ISSUE TITLE
Quick Access File Name Lengths

### ISSUE THREAD

**Issue by Sixtoe** [vpinball/vpinball#29]
Quick access filename/structure now truncated to 75 digits, meaning you cannot see what version you're loading if your file structure extends beyond that.

**Comment by toxieainc** [comment]
We are aware of this one, but no clue where this gets truncated within the Win32++ code that we're using..  :/

**Comment by toxieainc** [comment]
Found it now. I always searched for the wrong length there. It was overall 80.  :/
