### ISSUE TITLE
Frank Thomas' Big Hurt, flashers not correct

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#294]
![217435432-70906bf0-2acd-4159-9ff6-b7d2d6db7dfd](https://user-images.githubusercontent.com/81928693/217962627-2e53ff6c-2220-4da7-ad7a-db9a7d69ccb7.jpg)
![217435432-70906bf0-2acd-4159-9ff6-b7d2d6db7dfd](https://user-images.githubusercontent.com/81928693/217962672-0b2741ab-296b-4cab-b196-b67b0440ab27.jpg)
[VPinballX-10.8.0-635-63b095e-Release-win-x86](https://github.com/vpinball/vpinball/suites/9933993097/artifacts/480822496)
This is the latest one that works for me. The flashers are distortioned from 636 until last.

**Comment by vbousquet** [comment]
Hi ! Could you fill the issue report with all the informations ? This would help to understand/reproduce. A link to the table causing problems would help as well

**Comment by JorgePedro65** [comment]
https://mega.nz/file/vAwTiQAS#6zMrx5K_AjDgQqwh7xggVzqgCaPe3M2kRORV3e8xuE4

This is the link for the table. Thank you so much.

**Comment by vbousquet** [comment]
@JorgePedro65 Could you have a try with the latest build and report if things are still broken or if they are fixed now ? There were some changes that may solve your problem

**Comment by JorgePedro65** [comment]
I've just tried the latest build 805 and the problem was solved. The flashers are correct now. Thank you so much.
