### ISSUE TITLE
Portrait mode won't display the DMD (via dmddevice.dll) to VR (GL version) when virtual DMD is on playfield screen

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#295]
**Describe the bug**
I'm using a hybrid cabinet for VR and 'normal' play.
When switching to VR, I disable all my screens except the playfield.
I set the  playfield to portrait mode.
When launching VPinballX_GL.exe with a pinmame table, the DMD is blank. (I use vpinamme with external DMD)
Virtual DMD is show on the playfield.
When rotation screen to landscape mode, and launching the same table, the DMD is visible in VR as well.
Rotating screen to portrait again and enabling a 2nd screen, move the virtual screen to the 2nd screen, the DMD will be shown in VR as well.

**To Reproduce**
1. set playfield screen to portrait
2. Move virtual DMD from 2nd screen to playfield screen
3. Launch any table that uses a pinmame rom or flexdmd screen within Visual_pinball_GL
4. DMD will not be visible.
5. Rotate screen to landscape mode and relaunch the table, the DMD is visible in VR
6. Move screen to portrait and move virtual DMD to (for example) backglass screen and relaunch table, the DMD is in VR as well

**Expected behavior**
Portrait mode  with 1 screen should show the virtual DMD in VR as well when virtual DMD 

**Screenshots**
Landscape mode with virtual DMD on playfield screen (working in VR)
![landscapetmode_Virtualonscreen](https://user-images.githubusercontent.com/48748234/218648054-c176d360-b926-4ec8-bd93-1bf39a32eb6c.png)
portrait mode with virtual DMD on playfield screen (not working in VR)
![Portraitmode_Virtualonscreen](https://user-images.githubusercontent.com/48748234/218648142-309edc28-e495-40a3-a362-581d65a25864.png)
Portrait mode with virtual DMD on backglass screen (working in VR)
![Portrait_withDMDonBackglass](https://user-images.githubusercontent.com/48748234/218648272-7d9c49e7-6e2f-4b56-b08a-a99a58c309aa.png)

**Crash dump**
NA
**Versions**
 - VPX: VPinballX_GL.exe 10.8 rev 784
 - Windows version : Windows 11 22h2 build 22621.1105
 - Pinamme 3.5
 - GPU and video settings if applicable
![Schermafbeelding_20230214_064119](https://user-images.githubusercontent.com/48748234/218649788-9fda0351-6182-4ae4-843b-745de3fa14ed.png)
![Schermafbeelding_20230214_064029](https://user-images.githubusercontent.com/48748234/218649827-27bc2561-9447-4404-8333-e886ead5137a.png)
![Schermafbeelding_20230214_063910](https://user-images.githubusercontent.com/48748234/218649861-1201ddcd-f57c-496f-b56e-f6eb02f81529.png)

**Additional context**
Unchecking "Use external DMD (dll)" within Vpinmame shows the DMD within VR as well in portrait mode on single screen  (but without the colors)

![Schermafbeelding_20230214_065513](https://user-images.githubusercontent.com/48748234/218651998-57a34075-bcf5-4ffd-97c8-a1649296adb4.png)

**Comment by vbousquet** [comment]
This issue is very likely the same as https://github.com/vpinball/vpinball/issues/238
So I will reference this report in the other report and close this one to have only one place to follow the fix (not yet done).

Thanks for the detailed feedback !
