### ISSUE TITLE
TimeLord crashes when starting

### ISSUE THREAD

**Issue by slydog43** [vpinball/vpinball#296]
the table Time Lord (Original)(2022)(RusstyT, JP Salas, Gedankekojote97, Peter Moritz, Outhere)(2.1)
crashes when I try and start the table with 10.8 but works fine with 10.7.3

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

[crash.txt](https://github.com/vpinball/vpinball/files/10734513/crash.txt)

**Comment by vbousquet** [comment]
Please fill in the issue form because without it there is no way we may understand and/or reproduce your problem

**Comment by toxieainc** [comment]
I also thought that this was fixed recently. Did you try with the latest 10.8 build(s)?

**Comment by vbousquet** [comment]
Yes, the bug was identified here: https://github.com/vpinball/vpinball/issues/291 and I thought I fixed it here: https://github.com/vpinball/vpinball/commit/2590f96864a37158084cba5c1e54e38436ec1c8d

That was why I need a complete issue report to see if this si the same thing or another problem

**Comment by vbousquet** [comment]
@slydog43 Without any news, nor being able to reproduce, and having a fix already pushed for this bug, I will close for now. Please give us more informations if the bug is still hapenning for you.
