### ISSUE TITLE
Missing mouse pointer 

### ISSUE THREAD

**Issue by sverrewl** [vpinball/vpinball#297]
The mouse pointer seems to become hidden too easily now, and you can't really use dips switch menus or debugger in that you don't know where the pointer is. This seems to be a bit intermittent, in that I manged to get it to work, once, but, while experimenting, it disappeared again and I was not able to get it back. Sometime it seems to come to view as you press eg. 'D' for debugger, but, most of the time, not. 

**To Reproduce**
1. Load a table. Let it start, press 'D', no mouse pointer, so it is almost impossible to use the dialogue box.

**Expected behavior**
The mouse should be there :)

**Versions**
 - VPX: 1.8.0 Beta 783 - currently latest build.
 - Win10 21H2 19044.2486
 - NVidia RTX 3080

**Additional context**
If you enable the external dmd, you will see the mouse pointer - moving over it. Except for that, it won't show. This is by the way, tested on desktop with one monitor 2560x1440 windowed fullscreen.

**Comment by toxieainc** [comment]
Should all work again as expected now. Note that one also needs to update the scripts.
