### ISSUE TITLE
Standalone - VBScript Engine - space required after ampersand (&)

### ISSUE THREAD

**Issue by GeorgeMcMullen** [vpinball/vpinball#298]
When testing tables with the latest build on MacOS from the standalone branch, I would come across the following errors:

```
2023-02-15 04:18:19.881 ERROR [15417931] [CodeViewer::OnScriptError@1181] Script Error at line 2489 : 0x600003d13488
2023-02-15 04:18:19.881 INFO  [15417931] [CodeViewer::AppendLastErrorTextW@3949] Compile error: Line: 2489, Character: 19, VBS_UNKNOWN_RUNTIME_ERROR
```

This particular error came from JP's Space Cadet v4.vpx

The workaround is simple. Upon extracting the VBS and editing it, it was a simple case of changing lines to that there was a space after the &. For example changing:

```
DMD CL(0, "HIGHSCORES"), "1> " &HighScoreName(0) & " " &FormatScore(HighScore(0)), "", eNone, eScrollLeft, eNone, 2000, False, ""
```

to:

```
DMD CL(0, "HIGHSCORES"), "1> " & HighScoreName(0) & " " & FormatScore(HighScore(0)), "", eNone, eScrollLeft, eNone, 2000, False, ""
```

I presume this works using the standard VPX and that this error is actually caused by the VBScript Engine. If you'd like me to file a bug with VBScript Engine, please point me to the appropriate location.

**To Reproduce**
1. Use a build from the standalone branch
2. Try to play JP's Space Cadet
3. See error, table will not load

**Expected behavior**
Game plays with no problems.

**Versions**
 - VPX standalone on MacOS

**Comment by GeorgeMcMullen** [comment]
Haha cool. I've seen other VBSE errors. If opening new tickets here is appropriate, let me know, I'll post as I find them and troubleshoot them.

**Comment by jsm174** [comment]
I see what's happening in this case. 

In vbscript, you can represent hex numbers with `&H`, ie: 

`Array("DIP 1",&H000000001,"DIP 2",&H00000002)`

This particular variable just happens to being with an `H` (`&HighScoreName`) so it is getting confused.

> If opening new tickets here is appropriate, let me know, I'll post as I find them and troubleshoot them.

I will open an issue where we can just dump all VBS errors into instead of one off tickets. (I know most of the errors so far as I now test with about 27 tables)

**Comment by jsm174** [comment]
https://gitlab.winehq.org/wine/wine/-/merge_requests/2214/diffs

**Comment by jsm174** [comment]
This has been merged into Wine and in the latest standalone tree.

Closing.
