### ISSUE TITLE
DIPs - hex literals too long (ALI, s4, s6, s7)?

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#306]
While working on the standalone port, I ran into a wine vbscript issue where it was failing because of hex literals being too long.

Wine vbscript only allows for 8 places, where real vbscript appears to be more forgiving. 

I can submit a patch to wine, but I'm wondering if maybe there is a typo in a few of the scripts, (specifically ALI, s4, s6, s7)

![Screenshot 2023-02-21 at 8 23 36 AM](https://user-images.githubusercontent.com/1197137/220356519-1f99e8bb-d13a-4920-a22c-ba6d4e4aa60c.jpg)

Are these really supposed to be `&H00000001` instead of `&H000000001`?

**Comment by toxieainc** [comment]
@volkenborn to the rescue

**Comment by volkenborn** [comment]
Huh???
No idea. I think right digits should do it. :)
