### ISSUE TITLE
10.7.8 - Quit to Editor doesnt bring editor in focus - still minimized on task bar

### ISSUE THREAD

**Issue by derwin12** [vpinball/vpinball#309]
Can others confirm? Update to 10.7.8 and working on a new table, I hit play then esc quite to editor. The play screen closes but it doesn't bring the editor back up. I have to go down to the start bar and bring it back up in the window.

Note to that Help About still shows me 10.7.3 final but I am pretty darn sure this is the 10.7.8 from here/github. (jan 29)

**Comment by toxieainc** [comment]
Version of 10.8 is correct, so you must be using something else apparently: https://github.com/vpinball/vpinball/blob/master/vpversion.h#L4 https://github.com/vpinball/vpinball/blob/master/vpinball_eng.rc#L2921 https://github.com/vpinball/vpinball/blob/master/dialogs/AboutDialog.cpp#L27

**Comment by derwin12** [comment]
Sorry getting numbers mixed up .. using 10.7.4 Beta .. but I see that is still really just a 10.7.3 zip/binary.
![image](https://user-images.githubusercontent.com/4643499/220999272-be756e7a-8595-4fce-9c7b-1106fcd8256d.png)

**Comment by toxieainc** [comment]
True.. This one was outdated..

**Comment by derwin12** [comment]
Let me see if this issue still hits me in 10.8 - or I might just rollback as it is a bit annoying ;-)

**Comment by derwin12** [comment]
Rolled back to 10.7.3 minimal and it is still doing it .. so something obviously (or not so obvious on my end) .. I will have to track it down.
