### ISSUE TITLE
Element Detail Level in .ini?

### ISSUE THREAD

**Issue by cwscws** [vpinball/vpinball#312]
I do not know if the is a bug or it should be a feature:

In VPX Windows version you can set the degree of the Element Detail Level with a slider in the video prefs (and in the table option, too).

I was told this is the Alpha Ramp Accuracy in the .ini file - it this true? If yes, why a different name? If not, how to set this via the ini-file.

**Comment by jsm174** [comment]
I will defer to @toxieainc and @vbousquet, but I see that:

```
CONTROL         "",IDC_ARASlider,"msctls_trackbar32",TBS_AUTOTICKS | TBS_TOP | WS_TABSTOP,155,338,191,18
.
.
.
LTEXT           "Elements Detail Level (decrease = performance)",IDC_STATIC,163,330,156,8
```

That slider controls `AlphaRampAccuracy` which would be the `<AlphaRampAccuracy></AlphaRampAccuracy>` node in the `VPinballX.ini` file:


```
   const size_t alphaRampsAccuracy = SendMessage(GetDlgItem(IDC_ARASlider).GetHwnd(), TBM_GETPOS, 0, 0);
   SaveValueInt(regKey[RegName::Player], "AlphaRampAccuracy"s, (int)alphaRampsAccuracy);
```

From your screenshot:

![Screenshot 2023-03-01 at 1 40 38 PM](https://user-images.githubusercontent.com/1197137/222234524-646e0a05-aa1b-4a47-ba5a-6902cbe204e4.jpg)

**Comment by toxieainc** [comment]
Yes, this is true.
This weird naming is due to legacy reasons. Back in the VP9 days, only dynamically rendered ramps were affected by this setting, thus the name. We decided to generalize it to more elements after that.
