### ISSUE TITLE
Bug Report - Beta Version v10.8.0-775-639a05c

### ISSUE THREAD

**Issue by Jwkramer61j** [vpinball/vpinball#319]
**Describe the bug**
Environmental Emmission changes in F6 mode do not physically change the displayed light level, but do save with the POV file (and show up correctly when table is launched)

**To Reproduce**
1. Load Table
2. Press F6
3. Go to Environmental Emmission screen
4. Change table brightness levels - nothing on screen changes.

**Expected behavior**
The light level should go up/down when it is changed

**Screenshots**
n/a

**Crash dump**
n/a

**Versions**
 - VPX: 10.8.0-775-639a05c (64 bit)
 - Windows version: Windows 10
 - GPU and video settings if applicable: GTX1060

**Additional context**
n/a

**Comment by vbousquet** [comment]
Could you check in latest (823+) ? I think this is already fixed

**Comment by Jwkramer61j** [comment]
> Could you check in latest (823+) ? I think this is already fixed

I do not see that in the repository. Am I missing something?

**Comment by vbousquet** [comment]
Here it is: https://github.com/vpinball/vpinball/actions/runs/4373551899

**Comment by Jwkramer61j** [comment]
You are correct - this issue no longer occurs in the latest beta release. Thanks so much for the link to D/L.
