### ISSUE TITLE
Built-In 3d issue with 10.8 betas

### ISSUE THREAD

**Issue by workerb0y** [vpinball/vpinball#320]
The built-in 3d effect does not work properly in the 10.8 beta revisions.
I have been using the anaglyph 3d effect in vpx for a long time, with amber-blue glasses. When I tried the 10.8 rev375 version at the end of last year, I already noticed that it was not working well and since then it has been like this with every new 10.8 beta update. I tried with rev775 and 783, same issue. The colors on the screen change according to the given setting (amber-blue), but the image is not separated into two, so the spatial effect is not created. No matter how I set the Separate and ZPD values in vpx, the view always remains the same (there is no spatial effect, only the colors change).
There is no problem with the previous vpx versions, it works correctly with both (x86 and x64) versions of the latest 10.7.4 final.

My current configuration is:
Intel i5-10400f CPU, 16GB 3200mhz RAM, sata SSD drive, NVidia RTX3070 8GB GPU, Windows 10 Pro x64. 
32" playfield 2k 144hz, 22" fullhd b2s screen, 10.1" 1366x fulldmd via USB.
VPX 10.7.4 final (x86 & x64), VPinMame 3.6 beta 353, B2sServer 2.0, FlexDMD v1.9, Lucky latest dll's, Popper 1.4.6

Thanks

**Comment by vbousquet** [comment]
The anaglyph rendering should be fully functional both for OpenGL and DIrectX (I just checked no latest build).
OpenGL has a (far) better rendering for this with real stereo and depth. You may need to adjust your settings:
![image](https://user-images.githubusercontent.com/2796036/230704493-360ec7f3-6700-4ea6-9882-492004eda803.png)

Also, you may check that you did not disabled it using the F10 shortcut. I will close for now, please comment if it's not ok yet for you

**Comment by workerb0y** [comment]
In the case of the normal (non-GL) version 10.8, if I turn the 3d effect on and off with the F10 button, only the colors change, the image does not slide apart, so the spatial effect is not created. It doesn't matter what I set to the Separate and ZPD values in the settings you mentioned.
The spatial effect works with the 10.8 GL version, but since I use it in cab mode (I don't have vr glasses), it's a bit difficult for me to use that version.
It works correctly with all of the previous versions up to and including the latest version 10.7.4, only the normal (non-GL) 10.8 beta does not work correctly.

**Comment by vbousquet** [comment]
Version 1030+ has been updated regarding this issue. Could you give it a go and see if this is ok for you ?

**Comment by workerb0y** [comment]
Yes, of course, but please, send me a link, I can't find v1030 anywhere. Thanks!

**Comment by workerb0y** [comment]
Thanks, I tried it. And at the same time, I realized how much of a jerk I was. 
While on previous versions (10.7.3, 10.7.4) the ZPD value of 0.65-0.8 was suitable for me and provided a satisfactory 3d effect, on versions 10.8 (and now it seems on previous versions as well) values below 0.5 give the same 3d effect. Unfortunately, I only just found out about this, so I apologize for wasting your time unnecessarily! Since I used 10.8 at the same ZPD value (0.7) as previous versions, the image splitting was so minimal that it was almost unnoticeable. That's why I thought the 3d effect wasn't working properly. Once again, I apologize and thank you for devoting time to the problem!

**Comment by workerb0y** [comment]
Sorry, it's me again! :)
I just noticed after updated vpx 10.8 from rev1166 to rev1189, the 3d anaglyph effect is much better with the 1166 version. 
I reported some 3d issue earlier what later turned out I only need to reduce the ZPD value from 0.65-0.8 to 0.3-0.5. After that change with the rev1166 the spatial effect was really good, better than ever. But now with the rev1189, again just like with the 10.7.4 versions, I need to set the ZPD around 0.65-0.75 for a good spatial effect but the final look much worse like with the 1166 was. 
Maybe you change something about it since the rev1166?

**Comment by workerb0y** [comment]
Thanks for the advice, I tried it. The 3d effect of the GL version is indeed better, but even that falls short of the rev1166 normal version. Something has changed since rev1166 in the normal version, because of which the normal version rev1189 does not give such a good spatial effect. I will try to find the best settings later, but so far it seems that the 3d effect of the rev1166 normal version is the best for me.

**Comment by workerb0y** [comment]
Meantime I found the latest (rev1241) version and it's the same like rev1166 was, so it's perfect, creating a really good spatial effect. Thanks again!
