### ISSUE TITLE
Text info too small in Interactive Mode on CAB

### ISSUE THREAD

**Issue by Jwkramer61j** [vpinball/vpinball#326]
When making changes in Interactive mode, the new screen display is very, very small on a 43" 4K cabinet monitor, and all the way up by the backbox (upper left corner of playfield). The only way to see it is to stand on the side of the cab, and then its hard to reach the buttons to make changes.

**Describe the solution you'd like**
The display needs to be bigger so it can be read from the front of the cabinet.

Currently running version 10.8.0-823

I can provide a photo if needed.

**Comment by vbousquet** [comment]
Hello ! The text should be sized according to your Windows display settings: it takes in account your DPI settings, so it should be the same size as would be any other desktop application on your computer. Is it the what you get (get the text size of other desktop app) ?

It seems like a "normal" behavior for an editor (the "live" editor) but perhaps are you referring to other things like FPS or camera mode which are less like a desktop app but more like an in-game thingy ?

A photo would sure help to better understand the problem and what solution could be added.

**Comment by Jwkramer61j** [comment]
I attached examples. The code changed recently. The file named "OLD" shows how the text appeared previously (this is on a 4K display (set to 100% font size as required). The file named "NEW" is how it appears now. Notice that for one thing the text has moved from the lower left to the upper left of the screen. In addition, it is way smaller. On a CABINET this makes it all but unreadable - especially on a 4K display of any size (mine is 43").

![new-way](https://user-images.githubusercontent.com/95442216/225883597-1134847c-ad66-4bb2-975d-73aef72a24ef.JPG)
![old-way](https://user-images.githubusercontent.com/95442216/225883624-9a842866-90a4-40e5-bcce-950acfc30736.JPG)

Thanks!

**Comment by vbousquet** [comment]
I have just wrapped up a new version, with bigger text, placed at the bottom left (near the player). Could you confirm that it is alright now ?

**Comment by Jwkramer61j** [comment]
Will do. Thanks!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Vincent Bousquet ***@***.***> Date: 3/17/23  18:05  (GMT-05:00) To: vpinball/vpinball ***@***.***> Cc: Jim Kramer ***@***.***>, Author ***@***.***> Subject: Re: [vpinball/vpinball] Text info too small in Interactive Mode on CAB (Issue #326) 
I have just wrapped up a new version, with bigger text, placed at the bottom left (near the player). Could you confirm that it is alright now ?

**Comment by Jwkramer61j** [comment]
PERFECT!
![20230317_193200](https://user-images.githubusercontent.com/95442216/226069718-23bb791a-33f0-4dc1-aca1-640c27c1e6ca.jpg)
