### ISSUE TITLE
BBB flippers not working in VR with (VPX GL 10.8.0 build 881 X64)

### ISSUE THREAD

**Issue by Gigalula** [vpinball/vpinball#336]
**Describe the bug**

Big Bang Bar flippers not working in VR with (VPX GL 10.8.0 build 881 X64)

Tested and work with build 880 and 807  X64

**Comment by Gigalula** [comment]
I will test it again later but I already tested many time before the issue report. Was myself surprise will even test new version if present and get back to you later

**Comment by Gigalula** [comment]
Yep you were right I did a full re-installation of my Visual Pinball from start to end including 64bit and now everything seem to work fine up to build 900.... 

Sorry so many strange behavior since few weeks that I tought it was maybe time to restart the pinball drive from scratch to ensure nothing was corrupted. So now I presume yes soomething else was giving issue. Thanks for your help and Sory for the false alert my intention was legitimate and for sure not to dirsturb you my friend.  Even If I would like to know what was my issue honestly but I guest we will never know LOL.

BTW since build 817 you probably changed something because I cannot access anymore F11 menu to reach BAM menu. I can see in this version that you have on screen menu selection but no mouse available to select and other build after was even worst no more menu on screen so maybe you are doing something new hopefully ;)

You can see here why I love BAM in the cab:
https://www.youtube.com/watch?v=im4IFLyAXYs


Regards

**Comment by vbousquet** [comment]
In game menu is indeed changing. So far, what is being done for keyboard shortcut is:
- F11 => simply toggle FPS
- ESC / Q => Show splash menu (Resume / Live Editor / Legacy Debugger / Quit)
- Q long press => Quit
So no big change regarding how it used to behave.

Everything more advanced (BAM menu, video/audio settings, table inspection, renderer inspection, live editing,...) are moved to the live editor to allow to add more advanced stuff with live feedback, without bloating the UI for everyone

**Comment by Gigalula** [comment]
Both version....Hooo nice to ear that my friend :)  BTW can you make sure to call the BAM menu with  standard BAM key? 

Bon ok ont y va avec un peu de Français pour bien finir le tous. (La touche Juste au dessus du TAB) et surtous a ne pas noublie  que le fichier XML est très important il garde nos paramètre individuel par table et par le fait même les paramètres par défaut qui font en sorte d'avoir moins de manipulation a recalibrer pour tables suivante.

Merci de tous les effort et l'énergie déployer a rendre VPX et BAM tellement captivant.

Salutation Robert

**Comment by Gigalula** [comment]
> Both version....Hooo nice to ear that my friend :) BTW can you make sure to call the BAM menu with standard BAM key?
> 
> Bon ok ont y va avec un peu de Français pour bien finir le tous. (La touche Juste au dessus du TAB) et surtous a ne pas noublie que le fichier XML est très important il garde nos paramètre individuel par table et par le fait même les paramètres par défaut qui font en sorte d'avoir moins de manipulation a recalibrer pour tables suivante.
> 
> Merci de tous les effort et l'énergie déployer a rendre VPX et BAM tellement captivant.
> 
> Salutation Robert
