### ISSUE TITLE
Cannot Select Game Type - GoldenEye 007

### ISSUE THREAD

**Issue by Jwkramer61j** [vpinball/vpinball#338]
**Describe the bug**
In the latest beta release (10.8.0-885) the ability to select the game type at the beginning of GoldenEye 007 no longer works (tried both 32 & 63 bit EXE's). I tried it with the 823 build and it works fine in both 32/64.
(doesn't work in 862 build either)

**To Reproduce**
Table Used: https://vpuniverse.com/files/file/10040-goldeneye-sega-1996-vpw-mod/
ROM Used: https://vpuniverse.com/files/file/619-gldneyezip/
Start Table
When "Select Game Type" appears, flippers do nothing.

**Expected behavior**
Flippers should select "Novice" or "Regular" when pressed

**Screenshots**
![007-Startup](https://user-images.githubusercontent.com/95442216/226369377-28d42b3b-3d13-4839-8f29-9c37fcaba727.JPG)

**Versions**
 - VPX: VPinballX-10.8.0-885-1219137-Release-win-x86, VPinballX-10.8.0-885-1219137-Release-win-x64 
 - Windows 10 Pro

**Comment by baegi82** [comment]
I had the same problem with this version. The solution was to delete the nvram file. After that everything worked again.

**Comment by Jwkramer61j** [comment]
> I had the same problem with this version. The solution was to delete the nvram file. After that everything worked again.

tried that, did not fix the issue. Did you get this to work with the version referenced in the bug report?

**Comment by Jwkramer61j** [comment]
This is now working (tested in build 906).
