### ISSUE TITLE
Altsound/pinsound not working properly

### ISSUE THREAD

**Issue by pacleary** [vpinball/vpinball#343]
Altsound/pinsound only comes out left channel only. Default rom sounds play normally. Reverted back to 10.7.3 and altsound/pinsound works.

**Comment by toxieainc** [comment]
Which exact 10.7.4 beta build do you use?

**Comment by vbousquet** [comment]
Altsound / Pinsound are driven by PinMame so I think this bug report does not relate to VPX at all. Beside, Altsound has just been rewrote. Without any further feedback, I will close this issue for now

**Comment by zack06007** [comment]
Altsound don't functionning on 10.8 beta 8 - i try with Whitewhiter table - option altsound 1 but now i haven't music & sound
Now i use option 0 with rom sound
It's normal?
