### ISSUE TITLE
No table works with the new 10.8.0 v888, because of the new core.vbx

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpinball#345]
**Describe the bug**
I have installed the v888 of 10.8.0.
After that no table can be started. 
As error message is displayed:
Can't open core.vbs.

I see that some changes have been made in the file.
If I take the old core.vbs again, the tables work. Also with the core.vbs in 10.7.4.

**To Reproduce**
Copy the scripts from the v888 in the vp folder and start a table.
![Core1](https://user-images.githubusercontent.com/35002625/226902079-54101a2a-b4df-418d-abf7-722189f099a4.jpg)

**Comment by Joey-2001** [comment]
It seems, that it was corrected in the newer version.

**Comment by jsm174** [comment]
@Joey-2001 - 888 was a vpx "standalone" build and I do have to fix something I broke in `core.vbs`.

Only grab versions from the CI that are not titled with `misc: standalone builds for macos, ios, tvos, android, linux, and rpi`

**Comment by Joey-2001** [comment]
Thanks for the info. Good to know.
