### ISSUE TITLE
Cannot use "Find" in script editor while game is running. 

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#35]
**Is your feature request related to a problem? Please describe.**
Hitting crtl + f and nothing happens. Luckily I can copy the script to other editor in this state, but it would make it easier to have only one editor.

**Describe the solution you'd like**
Make script window to be searchable while in game

**Describe alternatives you've considered**

**Additional context**

Version 10.x

**Comment by fuzzelhjb** [comment]
The script editor isn't supposed to work when the player is running. The editor should be disabled when the player is running.
Changing the script while playing won't have any effect on the running game.

**Comment by iaakki** [comment]
Yes but I use that script view to see all the code the table is running. I then copy paste snippets to debugger side editor to do tweaks. Example: I see that some object is too dim, I use search to find its full name and DL control from script, then my snipped can be: 
Debug.print pInsertNum79.blenddisablelighting
10
pInsertNum79.blenddisablelighting = 15

I thought it would be quite easy to add the find dialog call in there. Find actually works if you have left the find dialog open when you start the table..
