### ISSUE TITLE
Missing DMD in VR

### ISSUE THREAD

**Issue by vbousquet** [vpinball/vpinball#353]
Followup of previous issue https://github.com/vpinball/vpinball/issues/258 : "I then loaded up v905, the issue was still solved but I had no DMD with Apollo 13, tried v904 and the same, no DMD. Loaded up v900 64bit and my DMD was back :) So v904 and 905 break my DMD. I have a PinDMD3 in my cabinet and run VR from my cabinet if that helps."

So th issue is linked to one of the latest commit:
https://github.com/vpinball/vpinball/commit/aef2311ad60383c0663cf27125e2ef9a3498ec7d
https://github.com/vpinball/vpinball/commit/66d803f33eea2c49896d59df528d1d2b9a6870ea
https://github.com/vpinball/vpinball/commit/1cd6f3cc81eeaee1876f6eb751a9ebaea35d6285
https://github.com/vpinball/vpinball/commit/d2ab9b04fb51d544c3a2d7795d799b4483cef7a2

**Comment by studlygoorite** [comment]
Unfortunately, still no DMD for me with v908 or v912 64bit

**Comment by vbousquet** [comment]
Sorry then, I closed it wrongly (always a bit difficult for me, since I don't have a VR set). I need to investigate further (I'm making somewhat heavy changes to the internals in order to reach a playable speed on mobile devices and prepare for some more advanced rendering techniques). Thanks for the patience

**Comment by vbousquet** [comment]
Ok, in fact, I just forgot a little thing. It should be good now. If you could have a try in VR with this latest build and confirm this is all good, this would be really nice !

Build : https://github.com/vpinball/vpinball/actions/runs/4520150299

**Comment by studlygoorite** [comment]
> Ok, in fact, I just forgot a little thing. It should be good now. If you could have a try in VR with this latest build and confirm this is all good, this would be really nice !
> 
> Build : https://github.com/vpinball/vpinball/actions/runs/4520150299

You dan man!! All is good thanks again and let me know if you "ever" need anything tested.
