### ISSUE TITLE
Add more columns into "search/select element" dialog 

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#36]
**Is your feature request related to a problem? Please describe.**
At the moment there is: name, type, layer, image, material
I'd feel having more colums that one could sort would improve table authoring a lot. 

**Describe the solution you'd like**
New columns I feel would greatly improve the feature:
- Collection
- Collidable
- Visible
- TimerEnabled
- TimerInterval
- DepthBias
- StaticRendering
- ReflectionsEnabled

**Describe alternatives you've considered**
Columns could be customizable too.

**Additional context**
At the moment we must check these values manually, by going through each of the objects we have layed on the table. It is quite a task

Version: 10.x

**Comment by gjenning** [comment]
I would also like the ability to see and sort the "Physics Material" selected for a element on the table, if there is one.

**Comment by iaakki** [comment]
Oh yes that too. For me this sounds like it would be great to have configurable colums. Even one additional column that one could swap what to see in sorted list.

**Comment by toxieainc** [comment]
This is now implemented (except for the Collections, i hope @fuzzelhjb can please implement that part), please let me know if something is weird or misbehaving.

**Comment by fuzzelhjb** [comment]
Sorry I won't add this feature request. Main reason not to add this is that it's really a pain to implement this and hard to maintain.

**Comment by toxieainc** [comment]
Then closing. Please reopen if something is still fishy.

**Comment by iaakki** [comment]
So did the whole improvement got rejected or only the collections part?

**Comment by toxieainc** [comment]
Only the collections part of it. The rest can be already tested if you download e.g. https://github.com/vpinball/vpinball/suites/5639788314/artifacts/184199686

**Comment by iaakki** [comment]
You guys are the real MVPs. Thanks! That collection thing can be easily reworked in development. 
1. Filter objects using this new select element system
2. Select the element you want into some collection -> just make a new collection and rename. Easy.

**Comment by gjenning** [comment]
I think since collections is not being populated, which I am fine with, it should be removed from the search/select elements view.  All the other stuff is perfect and will be very very helpful.  Thanks again for all of your hard work.

**Comment by iaakki** [comment]
Finally decided to jump into latest version. Running rev 120 now and it looks lovely! But! Sorting with Depth Bias could be improved a bit. As now it is sorting them as Strings; not numbers. They will go in order -100, -7000, -90, 0, 1, 199, 2, 20000, 30,300, etc. It would be way much better if the sort order would be correct.
