### ISSUE TITLE
FLEX DMD in latest VPX 10.8 builds give "Character: 4 Asked to load a bitmap from a resource of type Unknow"

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#361]
**Describe the bug**
Using  10.8 rev 922
When launching for example "Bone Busters Inc. (Gottlieb 1989)_Bigus(MOD) 2.0" and enable the FLEX DMD that scutters created, I receive error : "
Runtime error
-------------
Line: 1258, Character: 4
Asked to load a bitmap from a resource of type Unknow
"
This is with GL and normal vp version. Older revision like 603 or VP 10.7.3 work correct
The line that fails  "AddActor FlexDMD.NewImage("Back2", "VPX.DMD_Background2")
			

**To Reproduce**
1. 'Use build 922 of VP 10.8. (Vpinball.exe or vpinball_gl.exe)
2. Open file https://www.vpforums.org/index.php?app=downloads&showfile=15331
3.Hit F5 or press play

**Expected behavior**
No errors. VP script should launch and internal Bitmaps should be loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/48748234/227846883-a9fb46ba-e056-4360-aee5-95ba71beeae8.png)

**Crash dump**
NA

**Versions**
 - VPX: 10.8.0 rev 922 . Gl and regular version
 - Windows version 11 22H2, latest updates
 - GPU and video settings if applicable : RTX3080 , nvidia driver, but don't think that is relevant (let me know to post screenshot)

**Additional context**
As it is working with older revision and latest release of VPX, my assumption is that this is not a FLEXDMD issue, but a VPX (but @vbousquet is working on both :D  )

**Comment by Jeanpierrepinball** [comment]
Hello, to give additional context if it may help, I'm also encountering this error but only on the 64 bit recent versions of VPX GL (I tried v885 and v924), for some flexdmd tables but not all. 
Tables that give the error : The Matrix (on Line: 2076), Monkey Island, TimeLord...
Tables that work fine with the same VPXGL versions are : Three Angels, The Goonies...

Under VPX "regular" 64 bit v775 , these tables crash when opening with an error message "instruction at 0x0000(...)1400E297 employs memory address 0x0000000000(...). Memory state cannot be read"

When opening The Goonies or Timelord with VPX GL x86 (v510) they run fine. 
With VPX GL x86 v510, The Matrix and Monkey Island display the error "capture:received DXGI_ERROR_WAIT_TIMEOUT" after a few seconds

**Comment by Gerhard-BL** [comment]
FLEX DMD in latest build give "Character: 4 Asked to load a bitmap from a resource of type Unknow"
Version 10.8.0 beta 824 64bit is working
![vpy10 8](https://user-images.githubusercontent.com/122221417/229606592-95ba9129-ca8c-4ff7-8f48-c27760e17189.png)

**Comment by MikedaSpike** [comment]
Confirmed that this is fixed in latest version
