### ISSUE TITLE
Crash to desktop when starting table, VPinballX_GL.exe running on Intel HD 4000 gpu (openGL 4.0 capable only)

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#364]
**Describe the bug**
Crash to desktop with no error code when attempting to start any table from within editor. Table will load into editor ok but crashes shortly after pressing Play then gets to "Preparing Table - Initialising visuals" stage (consistently advances two bars into the initialising stage and then crashes).

Older 2012 model i7 laptop with only HD4000 video, this GPU is only capable of openGL 4.0 and I suspect is the issue.

**To Reproduce**
Open table file into editor
Press play (or F5)
Table crashes to desktop with no error message.

**Expected behavior**
Should not crash to desktop or provide error message.

**Crash dump**
Crash report VPX GL rev925 (5081c03)
============
Process: VPinballX_GL.exe
Reason: 0xC0000005 - EXCEPTION_ACCESS_VIOLATION at 0023:00000000
Attempt to read from 0x00000000
Thread ID: 0x583C [22588]

Call stack
==========
00000000  (0x3F800000 0x0E1D6900 0x00000001 0x0019e418)
0063C1FA VPinballX_GL.exe (0x0E1D6900 0x00001907 0x00000578 0x11b7d0e0)
006359B4 VPinballX_GL.exe (0x0000881B 0x0000041A 0x1195CA90 0x1195cac0)
005D01EB VPinballX_GL.exe (0x00000001 0x00000020 0x1195D4FC 0x00000000)
005D0532 VPinballX_GL.exe (0x00000001 0x00000578 0x0000041A 0x00000020)
005659E3 VPinballX_GL.exe (0x0042E300 0x00562F88 0x0000C272 0x1195ca90)
00562F88 VPinballX_GL.exe (0x0000C272 0x1195CA90 0x0042E300 0x0019f15c)
0042FBC3 VPinballX_GL.exe (0x0000C272 0x00000000 0x00000000 0x000207f8)
00572B64 VPinballX_GL.exe (0x0000C272 0x00000000 0x00000000 0x0000c272)
0042E357 VPinballX_GL.exe (0x0042E300 0x000207F8 0x0000C272 0x00000000)
751380AA USER32.dll GetClassLongW + 0x7AA (0x0042E300 0x00000000 0x0000C272 0x00000000)
75135E1A USER32.dll DispatchMessageW + 0x24A (0x0019F148 0x006706E4 0x0019F114 0x00000000)
75127F00 USER32.dll DispatchMessageA + 0x10 (0x0019F114 0x00000000 0x00400000 0x002d7000)
006706E4 VPinballX_GL.exe (0x00000000 0x00000001 0x002D7000 0x00811414)
0065EA0E VPinballX_GL.exe (0x00400000 0x00000000 0x033C3FEB 0x00000001)
006A1F40 VPinballX_GL.exe (0x002D7000 0x755500E0 0x0019FFDC 0x770f7bbe)
755500F9 KERNEL32.DLL BaseThreadInitThunk + 0x19 (0x002D7000 0x151F6C25 0x00000000 0x00000000)
770F7BBE ntdll.dll RtlGetAppContainerNamedObjectPath + 0x11E (0xFFFFFFFFFFFFFFFF 0x77118D05 0x00000000 0x00000000)
770F7B8E ntdll.dll RtlGetAppContainerNamedObjectPath + 0xEE (0x006A1FC4 0x002D7000 0x00000000 0x78746341)

Environment
===========
Date/time: 29/3/2023, 14:38:00:31
Number of CPUs: 8
Processor type: 586
System: Windows 10 (10.0 19045)

Memory status
=============
Total Reserved: 104536K (102M) bytes
Total Commited: 393040K (383M) bytes
Total Free: 3696664K (3610M) bytes
Largest Free: 2095040K (2045M) bytes

Registers
=========
EAX=11B7D770 EBX=11CE5734 ECX=0019E038 EDX=00001902
ESI=11CE56F0 EDI=0000881B EBP=0019FFEC ESP=0019FFE4 EIP=770F7B8E
FLG=00010286 CS=0023 DS=002B SS=002B ES=002B FS=0053 GS=002B

Mini dump saved successfully.

**Versions**
 - VPX GL rev925 (5081c03)
 - Windows 10
 - HD 4000 GPU, this is only capable of openGL 4.0 maximum and could be source of crash?

**Additional context**
[crash.txt](https://github.com/vpinball/vpinball/files/11096430/crash.txt)

**Comment by vbousquet** [comment]
Could you run a debug version of VPX and post the crash.txt ?
It should give us a more meaningful crash.txt

Beside, does the DirectX 9 version of VPX runs on this computer ?

**Comment by gjupp** [comment]
Debug version attached.

I should also mention that this laptop is also meant to have a discrete nvidia GT650m GPU, however this GPU is faulty and no longer detected in Windows or even in BIOS level tests. Hence I am currently running it with the HD4000 only. Generally quite a stable PC aside from the eventual loss of the discrete GPU which had caused crashes in the past. 

DirectX 9 version of VPX works including the latest 10.8 rev925 (generally poor performance at 1080p for cabinet fullscreen mode but desktop mode playable for less resource hungry tables).


[crash.txt](https://github.com/vpinball/vpinball/files/11100382/crash.txt)

**Comment by vbousquet** [comment]
I would say that the OpenGL version needs OpenGL 4.3 at least. This will change when moving to a more portable architecture but for the time being, this crash is in fact expected. I will close the issue for the time being.
