### ISSUE TITLE
Apron Missing

### ISSUE THREAD

**Issue by CainArg** [vpinball/vpinball#368]
**Describe the bug**
Can't see apron image running 10.8.0. rev925 x64... wich loads ok with versions 10.8.0. rev775 x64 and x86 and also 10.7.4 rev400 x64 and x86

Table:
Wolf Man (Peyper 1987) Goldchicco 2.0 32assassin
https://vpuniverse.com/files/file/7729-wolf-man-peyper-1987

V.1 (IDSA 1986) Goldchicco 2.0a 32assassin
https://vpuniverse.com/files/file/7677-v1-idsa-1986/

**Comment by vbousquet** [comment]
This should be fine in latest build:
![image](https://user-images.githubusercontent.com/2796036/230704690-b28aaf0e-be6d-4463-8ca3-530213d31d9c.png)

I will close for now. Please comment if you're still experiencing issues.
