### ISSUE TITLE
DMD mirror gives "interlaced" screen with VPX_GL (all 10.8 version I tested)

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#369]
**Describe the bug**
This issue was brought under my attention by Gigalula as I just started to use VPX GL since 10.8 beta
When the DMD is mirrored with VPX GL to VR  , the DMD has some kind of interlaced screen (pixels jumping around, like an old 50hz tv and record it on 29fps. Not sure how to describe it)
But when using 10.6.0 (rev 3275) GL version, the DMD looks smooth within VR
So I hoped this could be fixed within 10.8 as well

**To Reproduce**
1. Open a table that uses a mirrored DMD with version 10.6.0 (rev 3275) Gl version and look at the DMD within VR
2.  Open a table that uses a mirrored DMD with version 10.8.0 (any rev)  Gl version and look at the DMD  within VR
3. You will see a distortion in the 10.8 GL version that wasn't there in 10.6

**Expected behavior**
I wasn't expecting much, but when I checked 10.6, I expect a smooth DMD instead of distortion (or interlaced stripes) in it

**Screenshots**
Not good to see on screenshot or video.
But created a video (but can't get the resolution set to high) https://youtu.be/sdFqiqxgldU

**Crash dump**
no crash

**Versions**
 - VPX: [e.g. 1.8.0 Final Revision 925 (a01daaa), 32 & 64bit - ]
 - Windows 11 22h2 latest patches
 - GPU and video settings if applicable RTX 3080:
 
![image](https://user-images.githubusercontent.com/48748234/229435326-ae3b6138-16b9-4838-8231-28c415f088c6.png)
![image](https://user-images.githubusercontent.com/48748234/229435104-9523f3db-2cd6-45a2-940b-3cb34c02e976.png)

**Additional context**
When zooming in, the DMD looks fine (No distortion or interlaced, but standing in front of the cab it does)
I noticed this with flasher lights on the back box as well. From close it looks good, but a bit further away it gets the same effect as the DMD screen.
My opinion is that when it is further away, lights, won't be displayed correctly anymore.
DMD screen looks better when unchecking "Capture External DMD" , but don't have the benefits of colored roms

**Comment by vbousquet** [comment]
This part of the code has received a few fixes lately. Could you check with the latest version (build 1106+) if you still have this problem (I could not reproduce on my side, everything was working well) ?

**Comment by MikedaSpike** [comment]
Checked with 1109, but still the same

**Comment by toxieainc** [comment]
@MikedaSpike Some more things happened in the meantime for all that code, could you please test again?

**Comment by MikedaSpike** [comment]
Just checked, but still the same.
Even tried to add the new commands to the flashers like .DMDWidth , .DMDHeight , .DMD  didn't make any difference.
The capture of the external DMD isn't 'smooth '
