### ISSUE TITLE
Selecting multiple objects may bug the Options view

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#37]
**Describe the bug**
Options view may stop showing the correct options when selecting multiple objects. Although selected objects are having same type.

**To Reproduce**
1. Doing edits to few similar light objects for example. 
2. Select 10 light objects while keeping Shift pressed
3. You will see light option values properly in Option panel
4. Select one primitive (by accident)
5. Click primitive again to unselect it
6. --> Options panel becomes empty and it is not showing the Light Option values anymore.
(7. Repeat and avoid selecting some other object type)

**Expected behavior**
Group of selected object option values should be always shown, when selected objects are having same type.

**Screenshots**

**Crash dump**

**Versions**
 - VPX: 1.7.0 Final Revision 367 (e242d7c)
 - Windows version: 10

**Additional context**

**Comment by fuzzelhjb** [comment]
fixed
