### ISSUE TITLE
Rotated rubbers not showing as rotated when running

### ISSUE THREAD

**Issue by jpsalas59** [vpinball/vpinball#373]
**Describe the bug**
Rotated rubbers, acting mostly as rings in a wire ramp are not showed rotated when running the table.

**To Reproduce**
Just run the attached "wireramp and rings" table

**Expected behavior**
They worked fine in 10.7.4 but not in 10.8 nor the GL version.

**Versions**
 - VPX: latest 10.8 925
 - Windows version 11
 - GPU: Nvidia GTX 3080

**Additional context**

[ wireramp and rings.zip](https://github.com/vpinball/vpinball/files/11178483/wireramp.and.rings.zip)
![rings](https://user-images.githubusercontent.com/81420627/230602043-fa4df923-66b7-470e-8182-a3e79b7ecfd3.png)

**Comment by jpsalas59** [comment]
Excellent! :)

**Comment by vbousquet** [comment]
My pleasure !

@jpsalas59 DrFlyTrap found a little issue in your (great !) version of Attack from Mars: https://github.com/vpinball/vpinball/issues/371
This is something that has changed in 10.8 and I think the only solution is on the table side (not VPX) ; you would need to either uncheck the visibility flag of Wall0001 (which was not visible anyway in previous version of VPX) or assign it a full black material to get correct rendering. If you could include it in the next update that would be great!

**Comment by jpsalas59** [comment]
I'll do that on my AFM table :)
