### ISSUE TITLE
Reopen issue #370 F-14 Tomcat

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#377]
Please tell me how can I share the file with you.

**Comment by vbousquet** [comment]
You can do a private message on VPForum: https://www.vpforums.org/index.php?showuser=46212

**Comment by vbousquet** [comment]
I have re-opened the original issue to keep everything in a single place : https://github.com/vpinball/vpinball/issues/370
I will close this one, and continue the discussionon the original issue
