### ISSUE TITLE
Rubbers rendering at hit height vs. visual height

### ISSUE THREAD

**Issue by rothbauerw** [vpinball/vpinball#381]
**Describe the bug**
In build 814 of VPVR rubbers are rendered using the hit height set in the editor instead of visual height.

**To Reproduce**
1. I noticed this on TAF by gk5.  When the slings fire, the animated rubbers appear above the slings because the hit height is set at a value over 100 vp units.

**Versions**
 - VPX:  10.8 GL build 814

**Comment by jsm174** [comment]
I think I've noticed this in standalone a while ago?

![Screenshot 2023-04-10 at 11 05 43 AM](https://user-images.githubusercontent.com/1197137/230928825-583e2991-e834-4f86-a29b-6de67d9d2105.jpg)

**Comment by rothbauerw** [comment]
Yep, that's it.  Thanks for the screenshot.

**Comment by vbousquet** [comment]
This should be solved in v953 available here: https://github.com/vpinball/vpinball/actions/runs/4672174707
Please tell me if it's ok for you so I can close this issue or investigate further
