### ISSUE TITLE
10.8-943 VPVR does not render VP lights in one eye

### ISSUE THREAD

**Issue by rothbauerw** [vpinball/vpinball#382]
**Describe the bug**
VP lights are not rendered for one eye when using 10.8-943

**To Reproduce**
1. Open any table that uses VP lights.
2. Preview both eyes.
3. One eye will render VP lights, the other will not.

**Screenshots**
![VR_10 8-943](https://user-images.githubusercontent.com/76694094/230939268-204e8201-0a24-43c6-bbd3-7f32886b7664.png)

**Versions**
 - VPX: 10.8 GL Revision 943

**Comment by vbousquet** [comment]
This should be solved in v953 available here: https://github.com/vpinball/vpinball/actions/runs/4672174707
Please tell me if it's ok for you so I can close this issue or investigate further
