### ISSUE TITLE
Wireforms rendering incorrectly in Blood Machines 2

### ISSUE THREAD

**Issue by jsm174** [vpinball/vpinball#389]
Using Blood Machines 2 as a test, the wireforms seem to be rendering outside the table.

![Screenshot 2023-04-16 at 1 04 36 PM](https://user-images.githubusercontent.com/1197137/232328567-68f7f975-7f10-4eb1-a277-dfebfb435676.jpg)

This is happening in standalone, but I did see it happen on the Windows side as well.

The ball seems to sometimes be visible outside the table as well:

https://user-images.githubusercontent.com/1197137/232328968-f9819396-cea9-468e-b7a4-fc55a8a3843d.mp4

**Versions** 
 - VPX GL 964
- Standalone / Windows

**Comment by vbousquet** [comment]
Fixed in v988, thanks to https://github.com/vpinball/vpinball/commit/20b155d1a262b8448aab70b2261c087236764fb4
