### ISSUE TITLE
Harry Potter (Orbital) and Star Wars Bounty Hunter crash on startup

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#390]
Crash on startup for both tables (both run perfectly on 10.7.3)

Crash.dmp too large to upload after crash (2 GB)

**Versions**
 - VPX: 10.8.0 rev775 (639a05c)
 - Windows version: Windows 11 home 22H2 OS: 22621.1555
 - GPU and video settings if applicable: GTX 1060 / 1080x1920, SS 200%, Bilateral CAS

**Additional context**
[crash.txt](https://github.com/vpinball/vpinball/files/11243074/crash.txt)

**Comment by vbousquet** [comment]
The latest beta is 964. Could you try and check if it crash as well ?

**Comment by Jayhay89** [comment]
> The latest beta is 964. Could you try and check if it crash as well ?

Could you send me a link to the latest build? Can't find it

**Comment by Jayhay89** [comment]
> The latest beta is 964. Could you try and check if it crash as well ?

Both now launch with 967 beta, but there is a lighting issue with SW Bountyhunter:
![image](https://user-images.githubusercontent.com/86264211/232343507-baf60582-445a-4c59-897c-cf31a37e16ef.png)

**Comment by vbousquet** [comment]
Hi ! Just tested with latest (v972) version and I think this is fixed. I will close for now (just comment/reopen if it is still broken for you)
