### ISSUE TITLE
10.8.0-964 x64 | Batman 66 | Flippers lighting up/flickering

### ISSUE THREAD

**Issue by DrFlytrap** [vpinball/vpinball#393]
**Describe the bug**
The flippers seem to be reflecting a light or acting as one.

**To Reproduce**
1. Launch table
2. Point eyes at flippers :):)
![B66FlipperError](https://user-images.githubusercontent.com/123576665/232344546-72d0d3a2-46f7-41a1-9762-e5d3ad5672db.png)

**Versions**
 - VPX: 10.8.0-964 Open GL beta (also happened in v775)
 - Win 10
 - NVIDIA GTX 2080 Super

**Additional context**

**Comment by DrFlytrap** [comment]
I should add, they flash dynamically as if triggered by or reflecting one of the lights.

**Comment by passionforpins** [comment]
confirmed with non-GL versions of 10.8 x64-964 and 10.8 x86-964 as well. 10.74 x86 and x64 ok

**Comment by vbousquet** [comment]
Revision 972 fix this bug. Thanks for reporting !
