### ISSUE TITLE
Table and Environment Move When You Move Your Head In VR

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#399]
**Describe the bug**
Same as the title....Table and Environment Move When You Move Your Head In VR.

**To Reproduce**
Just load a table in VR (Oculus for sure) and any little head movement will move the table and room.

**Versions**
 - VR-GL: Issue started just after v925 (v925 is good), note from v937 to v958 tables did not render in VR (black screen) so hard to say if the issue started here but from v958 to present the issue persists.

**Comment by gear323** [comment]
I have the same experience on Valve Index with Steam VR.   .925 is the last version that does not have the issue.  The latest versions makes you feel drunk since the room is moving slightly along with the headset.   Definitely motion sickness inducing.

**Comment by studlygoorite** [comment]
Closing this issue as it has been fixed in v999
