### ISSUE TITLE
Junk Yard

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#40]
**Describe the bug**
Flashing lights and the ball cannot be seen.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions**
 - VPX: 10.7.1
 - Windows version
 - GPU and video settings if applicable

**Additional context**

**Comment by freezy** [comment]
This is the repository of Visual Pinball, the software. For table issues, please contact the table author.
