### ISSUE TITLE
Transparency bug - Guardians of the Galaxy 

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#405]
Describe the bug
Ball is invisible when under plastic ramps (ball shadow is still visible)

To Reproduce
Launch table from VPX

Versions
VPX: 10.8.0 beta revision 988, 64 bit
Windows version 11 (22H2)
GPU GTX 1060

**Comment by Jayhay89** [comment]
Looks like similar rendering issues on Game of Thrones (VPW) also.

**Comment by vbousquet** [comment]
Is it true with version 990 ? There was a huge & stupid mistake in v988, so I quickly pushed a little fix but without that much time to test

**Comment by Jayhay89** [comment]
Excellent, all rendering issues seem to resolved with 990. Will close
