### ISSUE TITLE
D3D error on certain tables with 10.8 beta 980

### ISSUE THREAD

**Issue by SingingGorilla** [vpinball/vpinball#414]
When trying to play certain tables with the current 10.8 beta, I get the following error from VPX: Fatal error D3DERR_INVALIDCALL (0x8876086c Invalid call) at D:\a\vpinball\vpinball\Shader.cpp:432

I've seen this happen on several tables including Bank-a-ball, Scuba and Lariat.  So far, it looks like the common thread is that they are all tables by Loserman, so I guess it's probably related to something he used as a template.

Also I've confirmed this happens on both the x86 and x64 versions of VPinballX-10.8.0-980-aedf6dc.  If it helps, I reran VPinballX-10.8.0-808-612c4ea, which is the only prior 10.8 beta version I've used and the problem does **not** happen there.

**Comment by vbousquet** [comment]
980 had quite a lot of bug. Does it happens also for 1003 ?

**Comment by SingingGorilla** [comment]
I don't see a 1003 build available.  The latest 10.8 beta I see is still 980.

**Comment by vbousquet** [comment]
It's here: https://github.com/vpinball/vpinball/actions/runs/4829547030
You need a GitHub account to download it

**Comment by SingingGorilla** [comment]
Thanks.  I DL'ed 1003 and I can confirm that the issue does not exist anymore in that version, at least on the 4 tables I tried: Bank-A-Ball, Scuba, Lariat and Psychedelic.
