### ISSUE TITLE
new bug since the new "aedf6dc" release with light inlets under the playfield, the circle around it became transparant instead of black

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#416]
In the latest VR version of 10.80: "v10.8.0-980-aedf6dc" a new bug occured that didn't happen with the previous version: "v10.8.0-775-639a05c" (also VR, exactly the same settings).

In VR in the new VPW Tommy table(I have the last release installed): https://vpuniverse.com/files/file/10193-the-whos-tommy-pinball-wizard-data-east-1994-vpwmod/

The bug is that the "circle" around the round light inlets in the playfield(don't know how to call it exactly), such as the huge "SHOOT AGAIN" and the "Special" had normally a BLACK circle around it. Now this circle is gone and became 100% transparant, so it shows the "wooden floor" under the table... Which ruins the immersion in VR.

I hope that it can be fixed in the next 10.80 beta. Thank you in advance!

I didn't test other tables yet with this new version, Tommy is the only table that I tested so far so it could probably happen in other tables too.

**Comment by passionforpins** [comment]
Confirmed same insert borders are transparent in todays  v1010 release as well but also in 10.7.4. The table author likely expected a black background be used so didn't bother to draw the borders with an opaque material. Pic attached with bright green background so you can see all inserts are affected
![tommy-10 8v1010-trans-lenses](https://user-images.githubusercontent.com/52011304/235258670-725ca8b7-3911-4633-ba4a-8b07f13de20f.jpg)

**Comment by TurboHenk** [comment]
> Confirmed same insert borders are transparent in todays v1010 release as well but also in 10.7.4. The table author likely expected a black background be used so didn't bother to draw the borders with an opaque material. Pic attached with bright green background so you can see all inserts are affected ![tommy-10 8v1010-trans-lenses](https://user-images.githubusercontent.com/52011304/235258670-725ca8b7-3911-4633-ba4a-8b07f13de20f.jpg)

But this changed recently with the latest 10.80 and 10.74 release. It didn't happen in the previous VR 10.80 release/build and also not in the lastest 10.72 VR version (before they removed VR, since 10.74 isn't available in VR yet, so the 10.7x VR release is pretty dated now).

So clearly a recent bug. Thank you for adding the image, this makes it even more clear. I went back to the previous release in the meantime, hoping that they bug will be easy to fix for the team.

Thank you in advance!

**Comment by passionforpins** [comment]
I only run in desktop mode so no GL or VR. I also just tested this table in 10.7.2 x86 and same exact results. I then tested the previous version of this table, 1.0, and again same transparent borders around all inserts as in the picture I posted.

**Comment by TurboHenk** [comment]
> I only run in desktop mode so no GL or VR. I also just tested this table in 10.7.2 x86 and same exact results. I then tested the previous version of this table, 1.0, and again same transparent borders around all inserts as in the picture I posted.

Without VR they probably expected that the background is black. So there is a difference between the VR and non-VR(as with most tables, the room gets added, the bottom got to made black etc.).

But for the VR version they clearly added something that created the black surroundings around the inlet lights on the playfields, because on the previous 10.8 / 10.72 GL / VR builds; the issue was not there.

So that part has been bugged now; the VR part that made it black. So what it exactly is, is up to the dev team but the issue is not in the table itself, because it ran fine in VR in the previous GL / VR releases, somehow an element that prevented this got "hidden" by the new release.

**Comment by vbousquet** [comment]
I have tried to solve this in a general way (not that easy, since supporting transparency of the playfield is one of the main new features of 10.8). The fix is available starting with version 1019. It looks good to me but I can't test in VR. Could you give it a try and share if it is ok for you ?

**Comment by TurboHenk** [comment]
> I have tried to solve this in a general way (not that easy, since supporting transparency of the playfield is one of the main new features of 10.8). The fix is available starting with version 1019. It looks good to me but I can't test in VR. Could you give it a try and share if it is ok for you ?

Thank you. We compiled the latest code and it works again(it's black/not transparant) BUT with one flaw: when you look half way the table; then the black same insert borders in VR become pixelated(so in the first half/closest half of the table the insert borders look sharp/perfect, but ~second half not/pixelated/blocky). When I move my head a bit forward; the pixelation disappear/the far away insert borders(that get closer when moving my head towards them) get sharper. 

So it seems that some strange/ugly "level of detail" is going on with the insert borders in VR now. I remember that this was also the case for the old 10.60 VR/GL release, the same insert borders were also very pixelated/low resolution in VR(even worse). But with the previous 10.80(the last release that worked without the transparancy issue(~1 month ago release?)) this "level of detail issue" was not really there. I could still see it, but it was not super low res at distance that it was really distracting, as it is now and was in 10.60.

Is there a way to turn the level of detail changes off for the insert borders? So that they stay stable all the time? There is close to zero performance benefit of this level of detail behaviour I think, but the visual downgrade is big.

Second issue that happened with the new compile release in the same Tommy table (should be an other report but I'm not 100% if 10.80 is the cause, but I still mention it here): The propeller sound(mechanical sound of the plane) in the Tommy table gets stuck and at the same moment: the flippers don't work at all anymore (but the pluner still do, and when I look at notepad, the flippers still give correct output). This happened also once with the previous 10.80 release, but not more then once. Now it happened 3 times in a row so Tommy is still not playable with 10.80 x64 in VR(not sure if/don't think that VR has anything to do with this).

Second difference with the previous 10.80 release(from ~1 month ago, release v10.8.0-775-639a05c): the table now with the latest compile starts with the playfields lights OFF. With v10.8.0-775-639a05c, it started with the playfield lights ON. (if I look on youtube video's the playfield lights should be on at the start, so I think that it was accurate with the 10.80 release: v10.8.0-775-639a05c).

This all with the latest VPinmame beta x64 and the last 10.80 x64 version/compile of the last code and the latest VPW Tommy release 1.2.1.

Good luck with the development. I hope that the issues could be tracked down and solved! Thanks!

**Comment by vbousquet** [comment]
I have checked again this bug and I think it's gone. Maybe some table will have some light leak around inserts because they were not fullt designed for VR but this should go better now since 10.8 handles playfield transparency fairly better, allowing table authors to make nicer inserts. I will close for now, please comment if there is really a bug left here

**Comment by passionforpins** [comment]
still has transparent insert edges in dx-desktop mode 10.8.0 rev 1214. Must be the table because it shows exactly the same in 10.7.4 x32 or x64 dx (non-GL)
![tommy-10 8v1214-trans-lenses](https://github.com/vpinball/vpinball/assets/52011304/469fa561-8822-4257-8535-d35e1c6c2b49)
