### ISSUE TITLE
Script editor: Add "Go to definition" link to right click menu

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#42]
**Is your feature request related to a problem? Please describe.**
It is common that you copy paste code and then need to go to some Sub where to paste the snippet. If "go to definition" was available, one could carry that snipped easier to the Sub. Now one need to hit CTRL + F, copy paste that target Sub name to search, select desired snippet lines, copy, hit find, paste.

It would also make jumping around the code much easier. You come up with same variable, and you need to find where it is defined; just easier to right click

**Describe the solution you'd like**
In script editor, Hover over a word, right click, hit "Go to definition" -> profit

**Describe alternatives you've considered**
Probably some other IDE/editor might support this.

**Additional context**
![image](https://user-images.githubusercontent.com/86254776/155697499-171f0ee7-aa6f-4bce-8b3f-abe64d3d3c51.png)

**Comment by toxieainc** [comment]
Unfortunately this is a major PITA as Scintilla does not allow for custom entries in the context menu.. Would a keyboard-shortcut/menu-entry also do the trick?

**Comment by iaakki** [comment]
Those are fine too. Especially keyb shortcut. There's never enough of those. 😊
