### ISSUE TITLE
Playfield lights issue

### ISSUE THREAD

**Issue by fernandojconti** [vpinball/vpinball#425]
**Describe the bug**
There are some issues with lights in playfield with tables as Star Treck LE.

**To Reproduce**
1. Go to 'File -> Open -> Star Trek LE (Stern 2013) v4.vpx'
2. Click on 'Play Table'

**Expected behavior**
Table should be loaded with correct lights values

**Actual**

Some lights have too much bright and can't be changed.
![Untitled](https://user-images.githubusercontent.com/65995729/235377988-d48930ab-2d7f-409d-b243-6785fd1e624e.png)

**Versions**
 - VPX: 1.8.0 Beta (Revision 980 (aedf6dc) 32 & 64 bits
 - Windows 11 x64
 - Nvidia 3060Ti / Drivers version 531.68

**Comment by vbousquet** [comment]
Version 980 is an old pre-alpha build. Does this happens with recent build (1019+) ?

**Comment by fernandojconti** [comment]
I don't know. Version 980 is the latest that I can get access to so far from here: https://github.com/vpinball/vpinball/releases

**Comment by vbousquet** [comment]
The latest can be found in action tab (they are updated very often since 10.8 is in pre-alpah state). You need a github account to download fro there: https://github.com/vpinball/vpinball/actions

**Comment by vbousquet** [comment]
I have tested and can confirm that this is ok with latest build. I will close the issue for now
