### ISSUE TITLE
BAM x y z scale settings and save for tables in VPX 10.7 and 10.8 with use of VPinballX_GL.exe

### ISSUE THREAD

**Issue by mandermannen** [vpinball/vpinball#426]
Hello,
I really like the head tracking with kinect 2. But in VPX 10.7 and 10.8 beta (VPinballX_GL.exe) i miss a gui for adjusting and saving the x y z scale settings (like in future pinball). Do i overlooked something? I hope you can fix this. With te right subtile scale settings, the table really comes more alive.

Greetings,
Emiel

**Comment by vbousquet** [comment]
There is a menu for that, it's in the live editor, in the preference menu

**Comment by mandermannen** [comment]
Thank you so much, i found it, its working!! The only thing is, how can i close the live editor? And to hide the left and right window settings in the live editor? i want to adjust the image in a fullscreen setting.

Greetings

**Comment by vbousquet** [comment]
Latest version (1028+) has a direct access to the BAM settings from the main menu, with fullscreen feedback. Therefore, I will close the issue for now

**Comment by mandermannen** [comment]
Thank you! Where can i find this version 1028+? I only see version [VPinballX_GL-10.8.0-980](https://github.com/vpinball/vpinball/releases/download/v10.8.0-980-aedf6dc/VPinballX_GL-10.8.0-980-aedf6dc-Debug-win-x64.zip)

**Comment by vbousquet** [comment]
https://github.com/vpinball/vpinball/actions (with an account)
