### ISSUE TITLE
Question on Pinball Outhole Call and Documentation

### ISSUE THREAD

**Issue by arhanjain** [vpinball/vpinball#43]
Where can I find the call for when the game detects the pinball has fallen into the outhole? Just to clarify, this is what I mean by the outhole: 
![image](https://user-images.githubusercontent.com/43100506/157540893-5a9bc477-3eef-422a-b725-8ec5520a5039.png)

I want to know what is called when a ball in play has fallen past the flippers.

Additionally, is there any documentation of some kind that I can use to understand where to find certain things? It's been very hard to find certain calls and understand what some functions do without reading all of the code that defines them.

**Comment by jsm174** [comment]
The ball goes into a trough.  

Some good information about how troughs work is at: https://docs.missionpinball.org/en/latest/mechs/troughs/

The table's script (VBScript) will usually simulate a trough via [cpvmTrough](https://github.com/vpinball/vpinball/blob/b95312b74060e26325fbdfb857163a82f763ed61/scripts/core.vbs#L864) or [cvpmBallStack](https://github.com/vpinball/vpinball/blob/b95312b74060e26325fbdfb857163a82f763ed61/scripts/core.vbs#L864) in [core.vbs](https://github.com/vpinball/vpinball/blob/master/scripts/core.vbs). 

That said, those are not the only ways to do it. Since it is scripted, it can be done an infinite amount of ways.

**Comment by arhanjain** [comment]
Sorry I phrased the question badly - I meant to ask where is the function in the C++ code that is called when the ball falls into a trough/gets past the flippers.

**Comment by freezy** [comment]
As @jsm174 said, there isn't. It's done through the table script.

**Comment by arhanjain** [comment]
ah ok, i see. is there any way for me to quickly find out about things like this through some sort of documentation, rather than creating issues?

**Comment by toxieainc** [comment]
Some is still in here: https://github.com/vpinball/vpinball/blob/master/scripts/vbsdoc_outdated.html
Some here: https://github.com/vpinball/vpinball/blob/master/txt/Scripts.txt
(as for scripting)

**Comment by toxieainc** [comment]
Apart from that, looking at a 'slim' table script, like the ones by JPSalas for example, may enlighten you how it all works.

**Comment by arhanjain** [comment]
Sorry to reopen this issue - I had a question real quick regarding this topic. Can I receive some guidance on the communication between C++ and VBScript? 

From what I could gather, I believe codeview.cpp is handling the communication between VBScript and C++, but I may be wrong. 

I'm trying to understand how this communication tracks out. Does C++ call all these VBScripts once at the start? Do the VBScripts run in parallel? How is C++ receiving data to interact with the game accordingly? 

I greatly appreciate y'all taking the time to read and answer my questions.

**Comment by toxieainc** [comment]
What is happening is basically that the script can call VPX-API calls via COM.

And the core of VPX will also trigger certain script functions the other way round, for example if a wall or primitive is hit with a ball, or if a gate is crossed or a hittarget triggered.
These functions can be found in the respective files (search for STDMETHODIMP), e.g. to set a light state: https://github.com/vpinball/vpinball/blob/master/light.cpp#L1054

Then, there are also timer script functions that will be executed every X milliseconds by the VPX core.

And on top of that, PinMAME also comes into play which offers certain triggers (like lamps on/off, solenoids being triggered, etc) via the core.vbs interfaces (or more directly via COM, depending on what one needs to do).

**Comment by arhanjain** [comment]
@toxieainc Thank you so much! That was super helpful - the information on looking for STDMETHODIMP functions was exactly what I needed. Thank you guys for being so open to answering questions.
