### ISSUE TITLE
selecting BAM head tracking in VPinballX.exe and VPinballX_GL.exe

### ISSUE THREAD

**Issue by mandermannen** [vpinball/vpinball#439]
I noticed that when i select head tracking in the video preferences that in both VPinballX.exe and VPinballX_GL.exe the option is selected (or deselected). But i want to play the tables in VPinballX.exe with no head tracking and in VPinballX_GL.exe with head tracking. Is there some way to select and save the head tracking on/off setting per table? Or maybe save this with the VPinballX.exe head tracking off and with VPinballX_GL.exe head tracking on? Hope you can help me

**Comment by vbousquet** [comment]
VPX supports headtracking for both DirectX and OpenGL and the settings are shared, so this is the intended behavior.
For the time being, you can create different settings file (ini file) and run specifying the settings you want with -ini on the command line. Perhaps, this could be managed from a front end like PinballY.

**Comment by mandermannen** [comment]
Thank you for your fast respons! In which directory do i place this ini file and what command should it says to (de)activate bam tracking? Maybe i'll try the forums of pinup popper how to activate thess setting with the launchscript. Im not much of a programmer....

**Comment by vbousquet** [comment]
VPF should be the place to get some help on this, keeping in mind that this is a pre-alpha, unpublished feature :)

**Comment by mandermannen** [comment]
Thank you! I found this new BAM head tracking feature in vpx great!  I started a new topic on the forums about it, maybe they know how
