### ISSUE TITLE
All Collections are not displayed under "Add/Remove Collection" when you have over 33 collections

### ISSUE THREAD

**Issue by gjenning** [vpinball/vpinball#44]
**Describe the bug**
When a table has a large number of collection, like over 33 collections, all of the collections are not displayed to the end user when they right click on a object and and select "Add/Remove Collection"
**To Reproduce**
1. Add more than 33 collections to a table
2. Right click on a object and goto "Add/Remove Collection"
3. Some of the collections will not be in the list

**Expected behavior**
I would expect to see all of the collections displayed, even if the list has to wrap and show to the right

**Versions**
 - All versions of vpx
 -

**Comment by toxieainc** [comment]
Okay, i'll remove the limit. Which table has more than this amount, so i could test how it looks?

**Comment by gjenning** [comment]
I have created a quick example table that has over the maximum number of displayable collections. 

https://drive.google.com/file/d/1C96FBwhwlbMh1e7Lvjp5EPiz599V-SFY/view?usp=sharing

If this does not work let me know and I can get you a even better example but will have to send it to your privately.

Thanks for all of your help with this.  Also I don't know if it would be difficult to do, but it might be nice to have the collections the object is in to show first in the list.  Not sure if you can sort on that field before the list is displayed in the dropdown bar.

**Comment by toxieainc** [comment]
Thanks.. I removed the limit..

**Comment by fuzzelhjb** [comment]
The limit was done by intention because without a limit you really need a high resolution to display the whole context menu.

**Comment by toxieainc** [comment]
Yup, absolutely. Thats why i made it multi column now (32 entries each column).

**Comment by iaakki** [comment]
This is great! When doing original tables, you easily get tens of collections as one uses light sequencers. My current project is having 52 collections. Light sequencers, Fleep sound integration, NF physics etc all uses these.

**Comment by gjenning** [comment]
I have tested this and it works perfectly.... Thanks so much for this....
