### ISSUE TITLE
Allow user to adjust vertical position of POV menu to accommodate real apron.

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#444]
**Is your feature request related to a problem? Please describe.**
Some users are now adding physical aprons to their cabinets to increase realism, the physical apron obscures the bottom left and right corners of the playfield screens to a certain extent.

I have had a report from a friend that when these users wish to edit the POV, the POV settings menu is partially obscured by the apron making adjustment difficult. This is perhaps less of an issue in 1080p as the majority of the settings text is further up the screen but more of a problem at 4K where I suspect the menu text is smaller and takes up less vertical height away from the bottom edge of the screen.

**Describe the solution you'd like**
Allow user to customise position of POV menu so it is moved upwards away from the apron and again becomes visible.
![vpxmenu](https://user-images.githubusercontent.com/95056536/236720010-0afd6694-5ea3-4ed4-9d37-2fe94a451188.jpg)

An example of a real apron being used is at https://youtu.be/6OE6wWCisNE?t=818

**Comment by DonkyKong69** [comment]
2nd that, Would be great
