### ISSUE TITLE
External Tables & Roms with Visual Pinball built from source

### ISSUE THREAD

**Issue by AniAggarwal** [vpinball/vpinball#45]
I'm trying to get this table (https://www.vpforums.org/index.php?app=downloads&showfile=15087) to work with Visual Pinball X that I've built from source. 
I also have the zip file of this ROM (https://www.vpforums.org/index.php?app=downloads&showfile=931)

However, the program built from source isn't able to locate the file and errors. I believe it is still looking in the C:/Visual Pinball directory.
How do I go about getting this table to work with the program built from source and look for files under different directories?

**Comment by toxieainc** [comment]
Does the normal installed package work?

Cause VPX does not come with PinMAME, which is the needed component for emulation (i.e. to 'handle' the ROM part).

**Comment by AniAggarwal** [comment]
What is the normal installed package? I don't understand what you mean.
If you are asking if the included pinball table works, that would yes.
If you are asking whether my own table works using the pre-built installation, that works as well.

**Comment by freezy** [comment]
If you want to play a PinMAME-enabled game, then you need to install PinMAME as well. It's automatically installed if you use the [installer](https://github.com/vpinball/vpinball/releases/tag/v10.7.0-367-e242d7c). If you just build VPX from source, you probably don't have PinMAME at all. 

So you'll need to install PinMAME and configure it where to look for the ROM binaries (setup.exe). It also registers the COM library that VPX will be using. Only then, running the ROM-based game will work.

Where your VPX file is located is irrelevant, however.

**Comment by AniAggarwal** [comment]
That worked, thanks!
