### ISSUE TITLE
Performance Issues since latest update (Blood Machines VPW)

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#450]
**Describe the bug:**
Inconsistent performance and stutter since last few builds.
Blood Machines is the best example)
Runs flawlessly on 10.7.4
I'm nowhere near being GPU or CPU bound, but constant dips below 60fps whilst Vsync is on.

**To Reproduce:**
Launch table from VPX

**Screenshot of issue:**
![image](https://user-images.githubusercontent.com/86264211/236822938-355cc656-86e0-44f7-bf32-284373bf8824.png)

**Versions:**
VPX: 10.8.0 beta revision 1062, 64 bit
Windows version 11 (22H2)

**Comment by vbousquet** [comment]
Could you hsare your setting file ?

**Comment by Jayhay89** [comment]
*I have turned SSR and Ambient Occlusion off for this table

**Comment by Jayhay89** [comment]
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11466534/VPinballX.zip)

**Comment by Jayhay89** [comment]
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11466554/VPinballX.zip)

**Comment by Drybonz** [comment]
I agree that there seems to be some degradation in performance, as I'm now noticing ball stutter in tables that played perfectly in earlier 10.8 builds and also 10.7.  I've tried reducing/turning off some of the common culprit settings, but it hasn't helped.  I'm on 1138, but started noticing this a couple days ago.

**Comment by vbousquet** [comment]
Latest build (1214 available from action tab with a github account) should solve this problem (even giving better performance than before on my system). Beside, in you settings, you should set the sync mode to adaptive sync (set it to value 2). This will give better results. I will close for now, please comment if you are still encountering problems

**Comment by Drybonz** [comment]
Performance has improved over the last few builds.  I bumped my video settings up a bit more (with adaptive sync also) and tested with 1214.  It seems to be playing really well now.
