### ISSUE TITLE
Broken ball reflections in latest 10.8 build

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#456]
Describe the bug:
Ball reflections seem bugged. (see comparison images below between 10.8 (rev1077) and 10.7.4

To Reproduce:
Launch any table from VPX

Screenshot of issue:
10.8
![image](https://github.com/vpinball/vpinball/assets/86264211/6cb90b8d-17b0-4d16-8793-fee4759b145c)

10.7.4
![image](https://github.com/vpinball/vpinball/assets/86264211/45fb60f8-55be-4e21-98a8-53d94c521dc5)

Same table, same settings (HDR Ball)

Versions:
VPX: 10.8.0 beta revision 1077, 64 bit
Windows version 11 (22H2)

**Comment by vbousquet** [comment]
Could you fill in the bug template ? Especially to understand this bug, I would need:
- The precise version between DirectX or OpenGL
- The settings file (VPinballX.ini)
- Are you using a custom ball or is it the default one ?
- Also could you point ot the table version used on the screenshot ?

**Comment by Jayhay89** [comment]
Direct X 10.8 64bit (rev 1077) with the issues.
Direct X 10.7.4 64bit (Rev 404) and any build previous to this is fine.
Swords of Fury (Bord) although any table produces the same results
I don't have a .ini file in my visual pinball folder.
I'll attach the ball image in question below

**Comment by Jayhay89** [comment]
Direct X 10.8 64bit (rev 1077) with the issues.
Direct X 10.7.4 64bit (Rev 404) and any build previous to this is fine.
Swords of Fury (Bord) although any table produces the same results
I don't have a .ini file in my visual pinball folder.
I'll attach the ball image in question below

**Comment by Jayhay89** [comment]
[old_ass_eyes_ball.zip](https://github.com/vpinball/vpinball/files/11446677/old_ass_eyes_ball.zip)

**Comment by vbousquet** [comment]
It would be easier for me if I could have your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here). This allows to replay the same table with the same settings and save a lot of time. Could you share it ?

**Comment by Jayhay89** [comment]
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11465089/VPinballX.zip)

**Comment by vbousquet** [comment]
The latest (build 1088 available here: https://github.com/vpinball/vpinball/actions/runs/4961189272) should fix it. Could you have a try ?

**Comment by Jayhay89** [comment]
Much Improved
