### ISSUE TITLE
VR GL-10.8.0-1078 VR still not correct

### ISSUE THREAD

**Issue by thekronke** [vpinball/vpinball#458]
Don't know if this report is here right. 
It's mainly for the user vbousquet (hi). I'm testing the new VR changes and would like to give feedback.
VR Table Height and and Y settings doens't match the older version and the head position tracking doesn't work in this version.
(using hp reverb g2 on steamvr)

**Comment by gear323** [comment]
I have the same issue in 1084.  I can't even see a table anymore just a floor and 6DOF headtracking no linger works. Only 3dof works

**Comment by vbousquet** [comment]
This should be fixed in the latest alpha build v1085 available here: https://github.com/vpinball/vpinball/actions/runs/4952866770

Could you give it a try and report if this is ok for you ?

**Comment by thekronke** [comment]
It's fixed in v1085. Thanks. 
There is now a performance impact when capturing backglass.
