### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by AniAggarwal** [vpinball/vpinball#46]
I would love it if there was a Linux port of this as I'm using this library. 
I'm not particularly well versed in cpp or vbscript but I'm open to try to help make this happen.

Maybe working with wine or proton would make this easier?
I've tried some things with wine and with just building on Linux but run into the issue of not having `windows.h`.

**Comment by toxieainc** [comment]
I don't really get your statement "i'm using this library". Which library? VPX is a whole application.

And it apparently works as-is via Wine already, according to multiple users that tried this in the past.

**Comment by AniAggarwal** [comment]
Thanks for the prompt reply. 
I'll look into the VPE project, thanks for the pointer.

I somehow deleted part of my sentence when I posted. I was originally trying to say:
I would love it if there was a Linux port of this as I'm using this library for reinforcement learning which means I need to build form source. 
I assume no one has gotten build from source working via Wine or similar?

**Comment by toxieainc** [comment]
I don't know if anybody ever tried that. And i personally have no clue about that.  :/
So compiling on a windows-VM is no option? Or are your libs that you use (for RL) Linux-only?

**Comment by AniAggarwal** [comment]
I tried compiling on a Windows boot but I keep running into dll dependency errors.
After copying over all the dlls and resolving each error, I got stuck on trying on the dll dependencies for libzmq.
Have others gotten this to work?

While my the RL libs are not Linux only, most of our dev team is on Linux and we are deploying on Linux. Additionally, some of the hardware we are using doesn't interface as well with Windows.

**Comment by arhanjain** [comment]
> After copying over all the dlls and resolving each error, I got stuck on trying on the dll dependencies for libzmq.

I can't speak for other dependencies, but just wanted to add that the ZMQ dependency isn't part of code that shipped with Visual Pinball. I think it should be fixed by installing cppzmq with a C++ package manager (check out vcpkg here - https://github.com/microsoft/vcpkg)

**Comment by toxieainc** [comment]
I have no clue how you guys get stuck on these dependencies. Cause from all i know (and my personal experience), it should be enough to just have a standard VS install with the usual windows SDKs and the DX SDK.
And i don't even know where this libzmq dependency would come from, its also not explicitly mentioned for the github actions.  :/

**Comment by toxieainc** [comment]
Also with the dependency walker i see no trace of zmq.

**Comment by arhanjain** [comment]
@toxieainc Sorry about the confusion. The ZMQ is definitely not a part of the Visual Pinball repository. It's part of some custom scripts written for Reinforcement Learning which I think @AniAggarwal confused with the VPinball scripts. No issues with this repository on that end :)

**Comment by EarBiteR** [comment]
There is a Linux standalone version available now. If that works for you maybe close this issue?
