### ISSUE TITLE
Expose more overrides in .pov (or as additional default overrides) as optional collection-wide overrides

### ISSUE THREAD

**Issue by theissdev** [vpinball/vpinball#490]
When maintaining collections, sometimes I stumble upon table values that are only accessible via the table panes, but would like to use as "starting points" across all tables (env emission in this case). A lot of the currently exposed values I can automate across all tables with a python script as it's just xml.

Was wondering if we could allow the table lighting pane exposed and saved in POV files for overrides.

**Comment by Drybonz** [comment]
I would like to see these as possible default values in the video settings (such as default ball, etc) which could be overrode in the table editor settings (again, like the ball image).  It seems like there a lot of settings that would benefit from a default.  Not sure if this would be better than storing in the pov files, but a similar end result.  What do you think?

**Comment by theissdev** [comment]
I would be cool w/ a default override as well (basically the same thing). Ultimately, I'd like a way of saying "use this value across all tables except for these ones", just for more table-specific values is all.

**Comment by vbousquet** [comment]
The new settings system should allow all this since it offers:
- app settings, eventually overriden by table settings,
- a setting section that overrides table properties (TableOverride).
Everything is in ini files so easily parsable in any language/third party tool (no more mixed registry/xml/internal table settings)
