### ISSUE TITLE
Add Variable that can be called from VPX and VPVR to determine what ide is being used in script

### ISSUE THREAD

**Issue by gjenning** [vpinball/vpinball#51]
**Is your feature request related to a problem? Please describe.**
Currently when hybrid tables are released, a user has to go into the vb script and set a flag saying that the game is going to be played in vr.  It would be nice to have a way for a developer to determine if the ide is vpx or vpvr.  If the table is vpvr then VRRoom settings would be applied.  This would work similar to desktop/fullscreen settings when the game starts up.

**Describe the solution you'd like**
Have a global variable that could be read in the tables vb script to determine if the user is in VPX or VPVR.

**Comment by sverrewl** [comment]
Doesn't that exists already ?? -c1 ... -c9

**Comment by gjenning** [comment]
That would require the user the pass in a custom parameter at the command line, I was hoping that a variable like VPBuildVersion which is available to the core.vbs script could be created and exposed to the developers so that we could manage these settings while limiting user interaction.

**Comment by toxieainc** [comment]
I would guess that you're also not just interested in VPX or VPVR, but also rather if VPVR is running in VR or 'normal 2D', right?

**Comment by gjenning** [comment]
I think that is correct.  Sorry for not being very clear.

I was hoping that since Visual Pinball (this project) and VPVR seems to be built off of the Visual Pinball code base.  It would be nice for the application to expose a way for developers to know which engine they are using in the vpx script.  This way if the table is being run in 2D mode via Visual Pinball then developers could script the table to disable VR effects.  This would also be true if the same table is being run in 3D mode via VPVR then developers could scirpt the table to enable the appropriate VR Effects. 

So this change would have to definitely be implemented in both the Visual Pinball and VPVR repos 

Is that more clear?

Thanks again for taking the time to review this request.

**Comment by toxieainc** [comment]
Its available now in both VPX and VPVR via 'RenderingMode' (global script call, 0 = 2D, 1 = Stereo3D, 2 = VR)

**Comment by gjenning** [comment]
Sorry I think I misread your comment previously.  I took "Its available now " as something that was currently already in the system.  I saw that you pushed a commit 3 hours ago into the system, so it must only be in the latest build.  Thanks for implementing this change it will be very helpful in the future.
