### ISSUE TITLE
Per Table Custom .ini

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#512]
Please allow for custom .ini files to make it possible for tables to launch with settings other than the default .ini.  For example "Gorgar.ini" (named the same as the table file) would allow the game, Gorgar, to launch with custom settings.

There would be many possible scenarios when this would be useful.  For example, you could set a PuP table to launch in windowed mode, while your default is exclusive fullscreen, to avoid the problems PuP has in fullscreen.  A user with low computer specs could set certain tables to launch with various heavy-use settings disabled for better performance... etc.

Thank you for considering this suggestion.

**Comment by vbousquet** [comment]
This has been implemented in 1307.
You can add a little file with just the override you want. For example:
```
[Player]
syncmode = 0
```

**Comment by Drybonz** [comment]
Thanks, vbousquet for adding this feature.  Should we add this file in the tables directory, or in the appdata folder with the main .ini file?  Also, should we name the file the same as the .vpx file name?

**Comment by Jayhay89** [comment]
@Drybonz 
Have you figured out the correct way to implement this and where the .ini file should reside?
