### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#516]
Some minor typos VPX 10.8 Beta 2:

In adjust camera mode:

Viewport X Strech
Viewport X Strech

Correct English spelling is "stretch".

********************************

Properties/Table/User/Elements Detail Level/Use this slider instead of defaul

Correct spelling "default"

********************************

Properties/Table/User/Night->Day Cycle/Use this slider instead of defaul

Correct spelling "default"

VPX 10.8 Beta 2

**Comment by vbousquet** [comment]
Fixed! Thanks
