### ISSUE TITLE
The Last Action Hero (Data East 1993)  VPW V1.1 incompatible with 10.8 x64 - crashes on two systems(VR and non VR) with the same error: nvoglv64.dll

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#521]
I have tested The Last Action Hero (Data East 1993)  VPW V1.1 on 2 different systems:

One system with Windows 11 and 3080 and 2D(non VR) setup.
One system with Windows 10 and an 4090 and VR+Reverb G2.

So 100% completely different setups the only similarity is Nvidia.

The Last Action Hero (Data East 1993)  VPW V1.1 table (recent table at VPuniverse) **ALWAYS** crashes with 10.8 beta 2 x64 (from releases page) and also with the latest x64 compile from yesterday after ~1 to 15 minutes playing. This on both computers, after playing for a short while it always crashes with exactly the same error in the Windows logs. 

No specific settings, everything on default  settings (reinstalled the table even multiple times(to make sure that there are no script/table changes, everything is 100% stock/default), nothing matters).

The error is:
Naam van toepassing met fout: VPinballX_GL64.exe, versie: 10.8.0.0, tijdstempel: 0x64739846
Naam van module met fout: **nvoglv64.dll**, versie: 31.0.15.3203, tijdstempel: 0x64674342
Uitzonderingscode: 0xc0000005
Foutmarge: 0x0000000000fffd23
Id van proces met fout: 0x441c
Starttijd van toepassing met fout: 0x01d99194d5e6c47b

Other logbook item:
P1: VPinballX_GL64.exe
P2: 10.8.0.0
P3: 6460aa4c
P4: nvoglv64.dll
P5: 31.0.15.3203
P6: 64674342
P7: c0000005
P8: 0000000000fffd23 

Edit: I want to add that it's rock stable on 10.72

**Comment by vbousquet** [comment]
Does it works with the DirectX version on (at least one of) your setup ?

**Comment by TurboHenk** [comment]
> Does it works with the DirectX version on (at least one of) your setup ?

Thank you for your quick reply. Good question, we tested the DirectX version and it's rock stable.

So it's going wrong with the GL version only.

**Comment by vbousquet** [comment]
Could you file in the complete bug report template ? This will give us more insights (settings,...)

**Comment by TurboHenk** [comment]
> Could you file in the complete bug report template ? This will give us more insights (settings,...)

Thank you for you reply.

Just to be clear: I normally play VPX on my own VR cabinet, that's system 2 I described (Windows 10 and an 4090 and VR+Reverb G2). It crashed here, but I was not sure if it was because of my system/settings/configuration or because of a bug in VPX GL 10.8.

So because I wanted to make 100% sure that the crash is not because of one of my settings/system. So I asked a friend to install VPX with 100% default settings/default installation on his system and with a clean new download from vpuniverse of the table. He normally doesn't play VPX on that system, so it's a 100% default clean installation with literally nothing changed. I forgot to mention, we both use different nvidia drivers too(I even tried multiple versions), so different Windows version(10 vs 11), different GPU generation(3080/4090), different drivers, everything different except the VPX 10.8 versions.

And the crash on his system was equal as I described, exactly the same as on my system. After a couply of minutes playing the table it crashes with the exact same error in the Windows logbook: VPinballX_GL64.exe crashed on nvoglv64.dll.

Just to make sure that my own installation is stable, I played for 10-12 hours in a row VP 10.8 x64 on my system with ~20-30 other VPX tables: not one single crash. If I play The Last Action Hero (Data East 1993) VPW V1.1 (clean/new download from VPuniverse) in 10.8 with the latest beta 2 release or with the compile from 2 days ago it always crashes the same way within 1 to 15 minutes, always and on both systems. 

So it must be very easy to reproduce for you too IF you have an Nvidia card, because I was only able to test it with Nvidia cards. It must crash with that table with 100% default/stock settings and a new download of that table from VPuniverse.

Please let me know what more information you need and how I can supply it, because I really want to help to get this issue solved.

**Comment by vbousquet** [comment]
This should be fixed in build number 1214 (available from the action tab with a github account). I will close for now, please comment if it is still crashing on your side.
