### ISSUE TITLE
Multiple GL Errors 

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpinball#522]
Rev: 925 64bit  and the last three revisions: 

Getting GL error 0xFFFFFFFF unknown in
Shader.cpp:1204
Fatal Error: Vertex Shader compliation of 
BasicShader.glfx:basic_without_texture_failed!

Then get InitPin3D error code: 80004005

Getting the same shader issues with DMD, nolight, bulb_light

Running Windows 10, on a pimax using steam.

**Comment by vbousquet** [comment]
You have an installation problem. Please do a clean (re)install

**Comment by psiomicron** [comment]
I did that. Older versions work fine tho.

**Comment by Jseph** [comment]
Recently ran into the same issue today and it was caused by some shader files that were either missing or the wrong version. Copying over all the contents of the release zip and overwriting the old files got it working.
