### ISSUE TITLE
Visible black seam in balls that use environment emission image instead of ball image.

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#525]
**Describe the bug**
If a ball has no defined ball image and instead uses just an environment emission image as defined under the lighting tab, the ball appears to have a visible black seam (black line).

Problem does not occur if a ball image is instead selected at  "Properties/Table/Visuals/Ball/Ball Image" or if "overwrite ball image" is selected in graphics settings.

**To Reproduce**
Check recent Stingray table by Bord at https://vpuniverse.com/files/file/14533-stingray-stern-1977/

Problem also occurs in Default new table with it's included environment images.

![ballseam](https://github.com/vpinball/vpinball/assets/95056536/f84080a4-8271-42ff-9a58-38dfe0a19277)

**Versions & Settings**
 - VPX: 10.8 Beta Rev 1189 32 Bit
 - Windows version 10
 - HD 4000 GPU
 - Will supply ini if requested.
 
**Additional context**
Seems to be a new issue with 10.8 as Bord's Stingray table ball looks ok in 10.7.2

**Comment by toxieainc** [comment]
@vbousquet Clamp mode on one axis should be changed to wrap/repeat i guess, if this mode is enabled.

**Comment by apophis79** [comment]
This issue still exists, only more subtle now. See image capture from bord's Stingray. Picture is show with Spherical Map unchecked, but you can see the seam with it checked also. I am using VPX: 10.8-1240 64 Bit
![image](https://github.com/vpinball/vpinball/assets/74864015/7745b855-bfa4-4e27-bfba-d20e4054ef96)

**Comment by Smilelikejoker** [comment]
Hey @vbousquet I think I just encountered this issue, or very similar, on the latest action (1248).  I'm not sure if it is the same thing, but I noticed it on the Fish Tales table I have.
![fish tales](https://github.com/vpinball/vpinball/assets/102932021/7a4c28f9-b743-45ae-9f1d-a79ea5bdd867)
I also found this same weird white line/cloud on the Attack From Mars table I have.  I've started going through more tables and will advise if I find more if needed.  It doesn't seem to be on many tables from initial searching.

Here are my settings:
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11718772/VPinballX.zip)
VPX 10.8 DX (x32 and x64) Revision 1248
Win 11 Pro Ver 22H2
NVidia 3080TI Driver ver 535.98
HDR enabled in Windows and TV
![settings](https://github.com/vpinball/vpinball/assets/102932021/00c7fb9b-8364-44c6-855d-3228d5979d38)

Some things I've tried thus far:
- Adjusting camera views - No effect
- Disable ball lighting - Actually made it more noticeable (that's what caught my eye)
- Disable ball trails/motion blur - No effect

Please let me know if you'd like for me to investigate this further and run the issue through whatever paces I can think of.  That is if you need me to lol.  I've only found it on 2 tables atm though.  If you need me to, I can move this to its own bug tracker for you.

I'll be standing by...
Smiles

**Comment by vbousquet** [comment]
Yes, could you move it to a dedicated bug since I don't think it has anything to do with the original problem. This looks like a table specific thing. Could you add the links to the tables that are causing these white lines ?

**Comment by Smilelikejoker** [comment]
I've already found out how to fix the issue and why I couldn't find it on many tables lol.

I'll move to a new bug.
