### ISSUE TITLE
Some DMDs No Longer Show In VR

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#526]
**Describe the bug**
As per title, some DMDs no longer show in VR. Note, after going through all builds to find where this started, VR-GL v1010 64bit is good and then the DMDs no longer work in v1013 64bit. So it looks like v1013 (Fix Building For Older System) broke something. 

Tables affected so far that have the issue reported by me and others.... AC/DC by VPW and Bugs Bunny's Birthday Ball by Wrd1972
Update, reports (that I can confirm) of TOTAN and TOM also have the DMD issue.

 

[VPinballSettings.txt](https://github.com/vpinball/vpinball/files/11593396/VPinballSettings.txt)

**Comment by studlygoorite** [comment]
Another update to this, I just found that if I change my DmdDevice.ini to read "virtualDMD enabled=true" then these DMDs will show, I never had to do this before :) but maybe there is a way with the new DmdDevice.ini settings file that I can set all of my VR tables to run with virtual DMD enabled and all of my VPX table to have it disabled and use my PinDMD3? I know I can put an exception in the .ini for the ROM to use the virtual DMD but is there a way to make it global...for all VR tables?  Unless things get reverted back :)

**Comment by vbousquet** [comment]
This is not a bug then; the DMD is captured from the virtual DMD. This whole thing is a hack that will have to evolve one day but for the time being this is how it is done. VPX does not manage this part, perhaps with your front-end of choice ?
