### ISSUE TITLE
No mouse except in dmd window 10.8 rev 1194

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#527]
**Describe the bug**
Loss of visible mouse cursor except in dmd window

**To Reproduce**
Open any table ( I run in desktop mode) 
Wiggle the mouse. It will not be visible unless you manage to move it into the dmd window.
The problem is if the F1 pinmame options menu is needed you cannot use the mouse to make any changes since teh cursor is invisible

**Expected behavior**
Mouse cursor should appear any time the mouse is moved

**Screenshots**
NA

**Crash dump**
NA

**Versions & Settings**
 - VPinballX-10.8.0-1194-09cd252-Release-win-x86 and x64
 - Windows 11 22h2
 - Nvidia GTX 1660 Super 6gb
 -
**Additional context**

[VPinballX.log](https://github.com/vpinball/vpinball/files/11593598/VPinballX.log)

**Comment by wiesshund** [comment]
is exclusive fullscreen mode enabled?
that usually kills off the mouse cursor

**Comment by passionforpins** [comment]
No. I never use exclusive full screen in desktop mode. The problem still exists today with 10.8.0 beta 1273.
Open and run any game and hit F1 t bring up rom options and you see no way to click anything in the F1 menu. I have to use keys to navigate that menu. The mouse cursor ONLY appears in the dmd/score display or b2s full dmd window. 
The mouse DOES appear in the escape screen but not the F1 menu.
See pic attached. Cursor only in the purple box area.
The mouse does work as expected in all versions of 10.7
![no-mouse-10 80beta](https://github.com/vpinball/vpinball/assets/52011304/37ba2a58-29c2-4406-abc1-dd4070cd1fc2)

**Comment by wiesshund** [comment]
that is odd, i cant reproduce it except by enabling forced fullscreen, which would be expected.

![image](https://github.com/vpinball/vpinball/assets/8684777/5b551e77-cc8d-4032-b880-7ed0acc4fdbb)

**Comment by wiesshund** [comment]
well, mouse seems to not capture in a screen shot, but i definitely have a mouse and can click things

**Comment by passionforpins** [comment]
![10 8-vid-options](https://github.com/vpinball/vpinball/assets/52011304/797ccd1e-e702-4a46-ae1e-e2ae1741826f)

**Comment by wiesshund** [comment]
very funky

You might need to post a bit more about your system, it might help the devs look into it
os version  and build, gpu, driver version, anything else you think may be helpful

this is the dx9 build and not the GL build?

**Comment by passionforpins** [comment]
I always do. It's in the initial report above. as you see yes its the DX versions.  thanks wiesshund

**Comment by jasoncross** [comment]
I can verify that I have the same issue. Also windowed fullscreen.

**Comment by toxieainc** [comment]
Did you guys also update the scripts recently? Cause if the PinMAME menu is brought up, the mouse cursor will reappear due to the script changes.

**Comment by wiesshund** [comment]
> Did you guys also update the scripts recently? Cause if the PinMAME menu is brought up, the mouse cursor will reappear due to the script changes.

seems to work fine.
I have most recent build and DO have the accompanying scripts.

**Comment by passionforpins** [comment]
Lord have mercy. Remember ol' Bruce in Road Warrior? "All this time..." 
I feel like an idiot :) Thanks @toxieainc ! Works as before. scripts. whoda thunk it :)

**Comment by TruestSin** [comment]
Where do we get these scrips? Also where exactly do I place them?

**Comment by TruestSin** [comment]
I'm having the exact same issue.

**Comment by wiesshund** [comment]
> Where do we get these scrips? Also where exactly do I place them?

You get them from the beta zip
and they go in the scripts folder, replacing ALL of the existing.

**Comment by TruestSin** [comment]
Perfect thank you I will do this tonight. Can't wait to try it.
