### ISSUE TITLE
Flasher Issue - Lights showing the edges of all the flasher boxes - Not present in 10.74

### ISSUE THREAD

**Issue by Smilelikejoker** [vpinball/vpinball#529]
**Describe the bug**
Table - White Water 1.1 by flubber1.  In 10.8 (32bit and 64bit), there is an issue with the way flashers are working.  Exactly what is wrong, I do not know.  However, it is not present in 10.74 (32bit and 64bit).  Basically the flashers are bright enough to show the edge lines of the flasher boxes.  In the screenshot, you can see what is basically a line that is running to the left of the left rail and other flasher box edges.  

**To Reproduce**
1. Download White Water version 1.1 (easy to find) as this is the first table I've seen with the issue.
2. Switch to desktop view or FSS view.  A solid black desktop background will help you see the lines better.
3. Run the table in the latest 10.8 to see the issue.  You should see the line to the left of the left rail.  Pay attention to how the line flashes to be able to find its matching flasher.  It is several flashers while the game is idle and while playing.
4.  Then run the table in 10.74.  The issue is not present.

**Expected behavior**
We should not seen flasher box edges.  The expected behavior is observed in 10.74.

**Screenshots**
For the screenshot, I went into the live editor to turned on some of the other flashers so you can see the issue on more of them.

**Crash dump**
N/A

**Versions & Settings**
 - VPX: 10.8 Revision 1198.  Tested against 10.74 Revision 404.
 - Windows 11
 - NVidia 3080TI Driver version 531.61
 - Setting file attached
 
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11594638/VPinballX.zip)

![flasherlines](https://github.com/vpinball/vpinball/assets/102932021/ac15c0db-37f5-4174-bcc5-9aaaaeb32112)

**Additional context**
I do not know if this is happening on other tables.  Again... This is the first table I've seen this issue on.

**Comment by gjupp** [comment]
Issue appears to be related to vertically rotated flashers, it appears that we may be seeing a refracted image of the flasher texture along the top edge of the flasher surface?

![whitewater](https://github.com/vpinball/vpinball/assets/95056536/598b31d3-5d15-4d68-b051-ce5cc2fbc389)
