### ISSUE TITLE
The old DXGI error is back

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpinball#543]
**Describe the bug**
The old DXGI error is back again in all new versions I have tested (till v1214 64bit); VR table conversions with external backglass.
See this issue:
https://github.com/vpinball/vpinball/issues/156

**Comment by MikedaSpike** [comment]
not sure if it is only me, but if I uncheck  Capture b2s in the settings, I still get the error.
If I uncheck  "capture DMD" I don't get the error
I both are checked and add a b2s file, I don't get the error (even if the table doesn't use a b2s file)

**Comment by studlygoorite** [comment]
> **Describe the bug** The old DXGI error is back again in all new versions I have tested (till v1214 64bit); VR table conversions with external backglass. See this issue: #156

For me v1085 does not have the DXGI error but then going to v1097 the error appears, with the limited testing I did.
