### ISSUE TITLE
3d on sometimes won’t remove writing from screen 

### ISSUE THREAD

**Issue by Painterboy21** [vpinball/vpinball#552]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
**Additional context**

**Comment by vbousquet** [comment]
The bug report is empty. Closing

**Comment by julianmrodri** [comment]
I believe this might be the issue I describe here: https://github.com/vpinball/vpinball/issues/665
