### ISSUE TITLE
Batman 66 lights to bright can’t dim

### ISSUE THREAD

**Issue by Painterboy21** [vpinball/vpinball#553]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
**Additional context**

**Comment by passionforpins** [comment]
@Painterboy21 you didn't fill out anything in the bug report template. What version of VPX? Vpinmame? If you were reporting on vpx 10.8 betas you should also include your settings file. What video card? memory? Windows version?
I just ran batman 66 in vpx 10.7.4 final, rev 410 32 and 64 bit bit and its fine. The issue does still exist in 10.8 beta 1217 but it's already been reported as an issue. 
You can really help Vincent and the team here though by filling out the bug report template

**Comment by Smilelikejoker** [comment]
@passionforpins Odds are this is related to issue 538 in which Vincent just fixed a few hours ago.

I just tested the fix and can also confirm that the Batman 66 table, along with the F-14 table, bright light issue is fixed in 10.8.0 rev 1240/1241 x86 and x64.  Vincent is a coding beast! lol

**Comment by Painterboy21** [comment]
Awsome work. I’ll keep testing as I’m doing a new build and slowly adding tables so I will report if I need anything. Where is the new version now of 10.8 beta 2 Will say tables are loading so much better x64 Sent from my iPhoneOn 7 Jun 2023, at 06:16, Vincent Bousquet ***@***.***> wrote:﻿
Closed #553 as completed.
