### ISSUE TITLE
"VPinballX64" Conflicts with Windows Default App

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#556]
**Describe the bug**
After "VPinballX64" naming started for VP executable, there are conflicts with VP opening as the default app in Windows. 

**To Reproduce**
Double-click on a .vpx table file and the editor will open without any table loaded.

**Expected behavior**
In the past, double-clicking the .vpx file would open the editor with the table loaded and launch the game.

**Versions & Settings**
 - VPX: Any version after the .exe is renamed to VPinballX64
 - Windows 11
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
**Additional context**
We had some discussion about this on the VPF forums 10.8 beta thread.  We found this problem can be fixed by simply changing the .exe name back to VPinballX, but it appears that there are maybe registry entries that don't like the .exe being named differently and wanted to let you guys know about it.  I should add that changing the default app through Windows does not fix this.  Thanks for taking the time to read over this.  :)

**Comment by Smilelikejoker** [comment]
To add additional context and information on this.
What brought this up was the fact that we could no longer double click a table to open it directly.  Double clicking results in opening the VPX editor and another window to choose a table.  Before the exe name change, double clicking a table directly would instantly load / start the table.

There is an easy fix to this problem, but it underlines something that needs to eventually be addressed.  There are no registry entries that reference the new naming of the exe's.  All registry entries still point to VPinballX.exe for the opening of tables.  Additionally, there isn't any registry entries that separate the x32 and the x64 exe's from each other.

At some point, I think we're going to need something along these lines:
- At .bat file included with the download that changes and/or adds the needed registry entries.  This sounds like it would be the quickest to achieve.  However, it does somewhat go against simplicity for users.
- An installer for 10.8 that does the same thing.

**Comment by wiesshund** [comment]
this is normal and is not a VPX issue
windows can only have shell entries for one app to handle a file when double clicked

**Comment by vbousquet** [comment]
Indeed, this is not exactly a VPX issue but an installer issue. VPX does not create file association, this is the task of the installer. If you have multiple installs or if you have different naming, then this must be adjusted accordingly. I will close since there is nothing to do on the VPX side
