### ISSUE TITLE
VPinMAME Rom sound volume quite low

### ISSUE THREAD

**Issue by Scottacus64** [vpinball/vpinball#564]
I installed VPinballX_GL-10.8.0-1189-a038732 on my cab and I am running VPinMAME 3.6 both 64 bit versions.  In games with rom sounds (like MM) I could not get the sound levels to raise up very high.  I had the in game coin door sounds to their highest level, my primary Windows sound levels at 80 and the vpx table properties Sound Effects Volume and Music Volume both set at 100.  PinVol was disabled during testing as well.  I rolled back to 10.7 and the rom volumes with these same settings were loud enough to hurt my ears ;)

Just posting to let you know of my experiences.

Scott

**Comment by toxieainc** [comment]
Is this also happening with newer 10.8 versions?
What about 10.7.4?

**Comment by Scottacus64** [comment]
The ROM volume works perfectly in 10.7.4, which I rolled back to.  I have not tried it in any other version of 10.8 other than listed above but can do so.

**Comment by vbousquet** [comment]
I think this may be linked to the BASS output I enabled as default for a while and finally reverted due to all the bugs that arised. I'm not seeing any bug with latest builds (which do not entirely rely on BASS). @Scottacus64 Could you give it a try and tell us if it looks good for you ? This way I would flag it as a Bass bug and would not keep it in the 10.8 release path

**Comment by Scottacus64** [comment]
I'll give it a try tomorrow and report back here, thanks!

**Comment by Scottacus64** [comment]
The ROMs now play with good volume levels in VPinballX-10.8.0-1271-71581f5-Release-win-x64, thanks!

**Comment by sverrewl** [comment]
Experience the same issue. Stand-alone pinmame test VPinMAME-sc-3.6-616, sound is loud and great, VP 10.7.4 - build 140, same. 

Latest VP build PinballX-10.8.0-1504 ( all version 32bit/64bit Dx9/GL ) has very low sound, almost non existent.

Tested table Embryon (Bally 1981) w VR Room v2.0.1.vpx - that uses embryond rom.

**Comment by toxieainc** [comment]
This is extremely confusing @sverrewl, cause by now we reverted what caused this original issue, so all should be back to normal since July.

**Comment by sverrewl** [comment]
YES, I know it is. Just tested now @toxieainc / @vbousquet  - with older 10.8's. I don't have a huge archive and at some point. VP would just crash on Win7 64bit.

Latest working I've got is VPinballX-10.8.0-775, then I have a longer period where it would not run at all. (1271 to 1311 I've got archived and are able to test) From 1311 and up, including latest has this issue on my end.

**Comment by sverrewl** [comment]
@toxieainc / @vbousquet 

Ok, now I've tested the exact same environment ... pinmame, vp, table, rom. 
This on a newer desktop machine running Win10. Everything seems to be OK then. Weird stuff, I will try to investigate further, though, not sure what to look for.

**Comment by sverrewl** [comment]
@toxieainc / @vbousquet 

I seem to have found a work-around. All sound modes is broken, except 'Standard 2 Channel', when ... Primary Sound Driver is choosen. I change this to my Speakers Real-Tech and it seems at least for this game to have resolved the issue. I will report back if this changes.

**Comment by toxieainc** [comment]
@sverrewl What sound mode do you otherwise use?

It may be related to the problem that was reported here: https://github.com/vpinball/pinmame/issues/155

Does it happen e.g. for both a WPC (e.g. MM, AFM, TAF) and a SAM (e.g. TWD, MTL, ST)?
Cause the latter machines are Stereo, WPC is Mono output.

**Comment by sverrewl** [comment]
@toxieainc 

I use 7.1 surround. And, you are right. tried two wpc and two sam's. SAM doesn't have this issue. :+1:

**Comment by toxieainc** [comment]
..please test/verify..  :)
