### ISSUE TITLE
1256 GL Build issue Rendering 3 views 

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#567]
With the latest 1256 GL build the right eye seems to be rendered ok but the left eye has a split screen and a two eye view in one eye.  

Obviously not currently playable with this issue.   

Valve index 
Build 1256 
Windows 11
Steam VR 
Nvidia 3090

**Comment by gear323** [comment]
I can confirm that 1259 resolves this issue

**Comment by vbousquet** [comment]
In fact, I have not completely finished the fix. The problem was that with the latest cleanups it broke Stereo + SMAA. Now the stereo part is ok but the SMAA in stereo is still wrong. This will be fixed in the near future
