### ISSUE TITLE
Flipper sounds missing half of the time

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#572]
Let me know if you don't want bug reports about tables behaving differently in 10.8 vs 10.7.

**Describe the bug**
When testing `JP's Captain Fantastic (Bally 1975) v4.vpx` on 10.8 (latest build) the flippers seem to be missing sounds when interacted with rapidly.

I don't see this on 10.7.x

**To Reproduce**
1. Get `JP's Captain Fantastic (Bally 1975) v4.vpx`
2. Run the table
3. Insert coin
4. Start game
5. Go mad on the flippers

**Expected behavior**
Correct flipper sounds

**Versions & Settings**
- VPinballX_GL-10.8.0-1259-8a86dca-Release-win-x64 and 
- VPinballX_GL-10.8.0-1260-40783b9-Release-macos-arm64

**Comment by francisdb** [comment]
I can confirm this is fixed but I guess it still matters for standalone @jsm174

**Comment by jsm174** [comment]
Just curious, did you test with the example table? if you smash the buttons there you hear it. I wonder if it's scripting related instead of BASS?

**Comment by francisdb** [comment]
I only saw it with a few tables. I'll append more to this ticket if I encounter them.

**Comment by rothbauerw** [comment]
I'm testing 10.8 1256 and when you savie a file, is corrupting the settings of the sound files.  It setting the volume adjustment to -1 on many files and thus you can't hear the sounds.

**Comment by rothbauerw** [comment]
The above appears to be fixed in 10.8 beta 3

**Comment by jsm174** [comment]
This seems to be an issue as reported in https://github.com/jsm174/vpx-standalone-scripts/issues/63

> I was testing Lost World (Bally 1977) 4.0.1
> https://www.vpforums.org/index.php?app=downloads&showfile=12941
> You can clearly hear that a lot of the bumper sounds just don't play. Same for the flippers when flippering fast.
> 
> Somehow I think this is mostly with JPSalas tables.
> 
> This is a remaining issue from earlier but BASS was reverted on master
> https://github.com/vpinball/vpinball/issues/572

So just to clarify, VPX non standalone does not use BASS for playing WAV's. VPX standalone does use BASS for playing WAV's. 

If you try standalone with the example table, the flipper sounds seem to be there as rapidly as you can press.

Most other tables, they are not. I think we need to take a look at the vbscript to see what the difference is.

**Comment by francisdb** [comment]
Just build a win GL x64 with `ONLY_USE_BASS` and the same issue is noticeable there. So we should fix this on the master branch.

**Comment by toxieainc** [comment]
Still needs a new BASS-only special build and testing

**Comment by francisdb** [comment]
@toxieainc what's left to do here?

**Comment by toxieainc** [comment]
I hope nothing. As the dust settles with VP 10.8 we should re-evaluate all BASS related bugs then. I think @droscoe also wanted to look into sound code refactoring.
