### ISSUE TITLE
UI display issue in editor

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#576]
Properties boxes do not scroll down far enough to see all properties, depending on a persons resolution.
1080p and lower definitely.

For example you pick a light, and you can not see the location or surface dialog areas
it wont scroll down that far.
You have to either move or squich the layers dialog or pull the lights dialog loose and stretch it
You may even need to stretch it off screen.

**Comment by vbousquet** [comment]
Fixed by https://github.com/vpinball/vpinball/commit/aa96e1bc314ceffa1e39f50fb92ebb44627c3019
