### ISSUE TITLE
lamps below table when show bulb is enabled

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#577]
if you set a light to show bulb, the bulb is below the surface.
Unsure if this is a bug or undocumented intended change
You have to go to the Z position and raise it by about 30 to have the bulb display correctly

Unsure if this messes with halo height?

**Comment by vbousquet** [comment]
This is not a bug but a feature :)

The z of the light is the z of the light source. The bulb is aorund and blow it so this is entirely normal.
