### ISSUE TITLE
10.8 beta 3: UI panels with scroll bars cannot be scrolled down completely

### ISSUE THREAD

**Issue by wizballpin** [vpinball/vpinball#583]
**Describe the bug**
In VP 10.8 beta 3, Some UI elements are hidden because using the scroll bar does not scroll the UI panel to the bottom fully.

**To Reproduce**
1. Load any table or create a new table.
2. Select a Light object.
3. Move the scroll bar of the bottom of the Visuals tab of the Properties panel.
4. Despite the scroll bar being all the way at the bottom, the content at the bottom of the Visuals tab is not shown.

**Expected behavior**
The content at the bottom of the Visuals tab should appear if the Properties panel scroll bar is scrolled down.

**Screenshots**
<img width="961" alt="scrollbug" src="https://github.com/vpinball/vpinball/assets/136901869/7826d0fa-894a-4dcf-8e11-ec30f9a0ec9b">
(Note how the Properties tab cuts off at "Raytraced ball shadows")
<img width="961" alt="scrollbug2" src="https://github.com/vpinball/vpinball/assets/136901869/e90413a9-275e-4566-af10-8c7124a5558b">
(The position and surface fields only appear if the Properties panel is resized)

**Versions & Settings**
 - VPX: 10.8.0 Beta (Revision 1271, 64 bit)
 - Windows 10
 - Windows UI scale is 150%
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
[VPinballX.zip](https://github.com/vpinball/vpinball/files/11778933/VPinballX.zip)

**Comment by toxieainc** [comment]
Similar to #576
