### ISSUE TITLE
VPinballX_GL: Setting Keybinds/Controls

### ISSUE THREAD

**Issue by lshprung** [vpinball/vpinball#586]
Following the [guide for the VPinballX_GL (standalone branch)](https://github.com/vpinball/vpinball/blob/standalone/standalone/README.md), I am having trouble figuring out how to set custom controls (i.e., mapping the flipper controls to keys besides left and right shift). Not sure if this has been implemented yet.

**Comment by jsm174** [comment]
If it's configurable on the Windows version via the ini file, it should be the same on the standalone.

**Comment by lshprung** [comment]
Can you direct me to which file that is?

**Comment by jsm174** [comment]
> Can you direct me to which file that is? My Windows installation does not seem to have any VPinballX.ini file.

It should be in the preferences folder with 10.8. You have to edit it via the web server in the mobile apps.

**Comment by francisdb** [comment]
I personally find I hard to know what to enter in those fields as the defaults are not present.

```
; Keyboard input mappings
disableesc = 
lflipkey = 
rflipkey = 
ltiltkey = 
rtiltkey = 
...
```

**Comment by jsm174** [comment]
Yes, without a keyboard entry dialog, I agree its difficult to know.

The settings are all based on DirectInput `DIK` values, see [here](https://gitlab.winehq.org/wine/wine/-/blob/master/include/dinput.h#L470-607).

So for example to change the left flipper key to `A`:

```
lflipkey = 30
```

I added a small chart to the readme, here: https://github.com/vpinball/vpinball/tree/standalone/standalone#keyboard
