### ISSUE TITLE
GUI bug, layers pane.

### ISSUE THREAD

**Issue by sverrewl** [vpinball/vpinball#59]
There is a minor, mostly annoying bug with the new layers feature. Load a table, Disable the top "Layers" by un-ticking. All layers is disabled, just like you want. However. Visually, all layers in the layers pane except for "Layers" and the first "Sub layer" is disabled in the selector. You will have to click every layer twice in order to update their status to become correct.

1. Open up any table. Go to layers pane. Unselect Layers.
2. Watch the sub layer's status. You would expect that they are visible, but, they are in fact disabled.

All that is needed to fix this problem is to update the layers beyond the first one to become visually disabled, because that is what they actually are.

![159_layers_bug](https://user-images.githubusercontent.com/1965649/168427686-9e77bb31-5def-4f9f-bdd4-e4ad20325731.PNG)

**Versions**
 - VPX 1.7.1 Beta (Revision 159 (8923eb4 32bit)
 - Windows 10 64bit

**Comment by fuzzelhjb** [comment]
fix in [https://github.com/vpinball/vpinball/releases/tag/v10.7.1-160-d0f0a6c](url)
