### ISSUE TITLE
Field of View Behavior in Legacy Camera/Light Editor

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#594]
**Describe the bug**
After using "camera" mode on a table for the first time, using "legacy" mode on other tables... Field of View has a strange behavior that has not happened in the past.  There is unwanted horizontal positioning of the table, as well as adding a diagonal slant to the table.  (I use desktop mode)

**To Reproduce**
Adjust Field of View in the legacy mode of the interactive camera/light editor.  This was after using the "camera" mode, instead of "legacy" mode for the first time.  This was after having .pov files and auto.pov saved for all my tables.

**Expected behavior**
Old Field of View adjustment behavior that added a tilt back effect, but no horizontal movement of the table or slanting of the table (a diagonal slant from top to bottom).

**Versions & Settings**
 - VPX: 10.8 build 1271
 - Windows 11
 - GPU 3050
[VPinballX.log](https://github.com/vpinball/vpinball/files/11886490/VPinballX.log)
 
**Additional context**
Has using the "camera" mode changed my .pov files and ability to use "legacy" mode as I have in the past?

**Comment by vbousquet** [comment]
I'm not sure to understand your report.

The expected behavior is the following:
- legacy mode: just like in previous version
- camera/window mode: just like stated in the docs

As far as I can tell, it does just that on my tests. If it is not, then I would need some screenshots and better description of what has been done as well as the POV file to get a chance to reproduce.

**Comment by Drybonz** [comment]
Hi vbousquet, I saw your comment and was going to make a video of what was happening, but I am now unable to reproduce.  I had deleted .pov's for tables with problems, and started new ones, so I'm guessing this has fixed the problem for me.  Please feel free to close this and if I run across this again, I will try to give you better information in the future.  Thanks.

**Comment by vbousquet** [comment]
Just for information, you were right, there was a bug there. I finally found it and fixed it in latest build

**Comment by Drybonz** [comment]
Hi vbousquet... thanks, I'm glad you were able to find it, and sorry I didn't have more info to help out.
