### ISSUE TITLE
Release 1265 BROKE Pimax Crystal's mirror in VR

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#605]
Until version VPinballX_GL-10.8.0-1261 the mirror image of VPX still worked properly(I see the table normally rendered on the mirror screen)

Every version after this(so since VPinballX_GL-10.8.0-1265 GL: move to layered rendering instead of split viewport)  the mirror image of VPX is broken: It's VERY zoomed in, the table is simply not visible anymore in the mirror image, it shows ~10-15% of the image. It's zoomed in that far.

I tested ~10 versions after 1261(including the latest version) and they all had this issue. But strangely enough the mirrored window got a bit bigger with later versions but the issue is exactly the same: it shows a strange zoomedin image instead of the whole/what you see in the VR HMD.

I'm using Pimax Play V1.13. It happens with SteamVR/OpenVR and also with OpenXR/PimaxXR.

So something clearly went wrong with "GL: move to layered rendering instead of split viewport".

I hope that this can be fixed, because it makes playing pinball together impossible.

Hereby the link of the picture, then you see exactly what goes wrong since the change " GL: move to layered rendering instead of split viewport"

https://imgur.com/a/TLYAi9P

**Comment by vbousquet** [comment]
With all the latest changes, do you still have this bug (no way to reproduce on my side since I don't have a PiMax) ?

**Comment by TurboHenk** [comment]
Yes, and as I also noted with my other bug reports, please stop assuming that only Pimax has issues: https://github.com/vpinball/vpinball/issues/605

I just report everything faster than the majority here.

Please look at the changes of what's changed between: 1261-1265 GL so that you can fix it.

Thank you for the great development.

**Comment by vbousquet** [comment]
I will close and follow up in https://github.com/vpinball/vpinball/issues/978 since these are duplicates

**Comment by TurboHenk** [comment]
Thanks but it's not fixed here. So I have to open the closed issue again but I cannot reopen #978 so I try to open this one by posting it here (not sure if it works, if it doesn't I have to add the bug report again?)

See attached screenshot:

![notfixed](https://github.com/vpinball/vpinball/assets/132104433/23d4bcb7-8736-4673-bb83-8c3b3b6b10e6)
