### ISSUE TITLE
D3DERR_invalid  when set to Frame facing

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#609]
**Describe the bug**
Testing in cabinet mode 
When setting the settings to the new option "Synchronisation mode" and put it on "Frame facing", gives an  error  when visual player is starting 

Using 10.8 64 bit (DX9 and GL)  rev 1294

**To Reproduce**
1.Open VPinball64.exe or _GL 
2.  Go to Prefreences-> video settings
3. Set  Synchronisation mode to Frame facing
4. close and relaunch Vpinball64.exe
5. Open a table and launch th eplayer

**Expected behavior**
Shwoing a normal player where actually can play

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/48748234/0ad0a0fa-fad8-4057-869e-35922bcc907f)

**Crash dump**
[vpinball.log](https://github.com/vpinball/vpinball/files/11933016/vpinball.log)

**Versions & Settings**
 - VPX: 10.8 64 bit (DX9 and GL)  rev 1294 (and rev 1297)
 - Windows version W11 22h2
 - GPU and video settings if applicable RTX 3080 
 - If this bug report is for VPX 10.8+
[VPinballX_ini.log](https://github.com/vpinball/vpinball/files/11933043/VPinballX_ini.log)

**Additional context**

**Comment by passionforpins** [comment]
I'm running 1302 from today Mike, dx version and no problems at all so far. I just ran JP's new Totan v5vpx8 and my lord its glorious and smooth as hot melted butter when frame facing is on. Of course i'm only on desktop

**Comment by wiesshund** [comment]
@MikedaSpike 

Actually, it crashes if you pick anything but vertical sync
even picking no sync gives me same crash you report.

this is in rev 1303 even
Frame Pacing, Adaptive sync and No Sync all give same results

Line 1457 for rev 1303

Unfortunately logging doesnt give me anything because the logging terminates immediately when it crashes
which is immediately on launch
[VPinballX .ini.log](https://github.com/vpinball/vpinball/files/11939775/VPinballX.ini.log)

**Comment by wiesshund** [comment]
@MikedaSpike 
Update

It only crashes when exclusive fullscreen is enabled
Not that it makes it any better but

**Comment by passionforpins** [comment]
aha. thats probably why it didn't crash for me since I run desktop DX and never exclusive full screen.  All good helping Vince narrow this down.

**Comment by wiesshund** [comment]
Cant run in 10bit color either
I may need to open a new ticket for that though
![image](https://github.com/vpinball/vpinball/assets/8684777/13a75b1c-2f11-4b5a-95ff-7528c7044660)

**Comment by vbousquet** [comment]
This should be fixed in 1305. Could you give it a try and confirm I can close ?

**Comment by wiesshund** [comment]
Is fixed in 1307
i didnt get to try 1307 because 1307 already came over top of it
