### ISSUE TITLE
Enable 10bit color option crashes VPX DX9 version

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#614]
**Describe the bug**
Enable 10bit color option crashes VPX DX9 version

**To Reproduce**
1. Go to video prefs
2. Click on Force 10-Bit monitor support
3. See error screenshot

**Expected behavior**
For VPX to run in 10-Bit color

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/8684777/56609f84-c0a5-4bf9-8d12-e43ff9a34bdb)

**Crash dump**
does not create one

**Versions & Settings**
 - VPX: 10.8 1303
 - Windows version 11
 - GPU and video settings if applicable 10bit is enabled
 
[VPinballX.ini.log](https://github.com/vpinball/vpinball/files/11940206/VPinballX.ini.log)

 
**Additional context**
[Add any other context about the problem here.]

**Comment by vbousquet** [comment]
This should be fixed in 1305. Could you give it a try and confirm I can close ?

**Comment by wiesshund** [comment]
This is fixed, tested in 1307 since that was latest build.

Also fixed is the crashing when changing sync methods with exclusive full screen

But something new broke, i should open a new ticket i guess?

Setting to no sync, which should result in VPX being able to overrun monitor sync instead results a drop in FPS
But only the DX9 build, GL build does exactly what youd expect, run FPS in excess of vsync

**Comment by vbousquet** [comment]
This should be fixed in 1308
