### ISSUE TITLE
No Sync option not working in 10.8 1307 DX9 version

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#618]
**Describe the bug**
No Sync option not working in 10.8 1307 DX9 version.
Instead of just allowing FPS to run to the GPU max, the FPS drops to a weird number, 64.9, and they remain there

**To Reproduce**
1. Go to video prefs
2. Click on Sync dropdown
3. Choose no sync
4. Start table and press F11

**Expected behavior**
FPS to just run wild to the GPU's max, whether in sync with monitor or not

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/8684777/8491830c-bdf8-4ec4-905b-3818687fd4d3)

**Crash dump**
No crash

**Versions & Settings**
 - VPX:  10.8 rev 1307 DX9
 - Windows version 11
 - GPU and video settings if applicable
 FSAA - Use application settings
 Anisotropic 16x
 enable vsync - Use application settings

[VPinballX.ini.log](https://github.com/vpinball/vpinball/files/11941050/VPinballX.ini.log)

 
**Additional context**

**Comment by vbousquet** [comment]
Fixed in 1308

**Comment by wiesshund** [comment]
10.7.3

![image](https://github.com/vpinball/vpinball/assets/8684777/9be430a8-a744-4015-af8b-1a476c17c799)

**Comment by wiesshund** [comment]
oh hell LOL
ok will retest in 10.8 1308

**Comment by vbousquet** [comment]
Sorry you did not see the message on the other issue. But these clean issue help a lot, so thanks for them !

**Comment by wiesshund** [comment]
eh i dont like to toss other issues into other tickets anyways

to hard to work like that if issues become separate things to fix etc

and yep 1308 fixed this :)
