### ISSUE TITLE
Objects can end up on wrong layer with this sequence

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#62]
**Describe the bug**
After you fixed this https://github.com/vpinball/vpinball/issues/49, there is a possible work flow that sends your objects to wrong layer.

**To Reproduce**
1. Select an object, that is on layer 5 for instance. 
2. Create new layer, rename it, click next to it to apply the name (enter key doesn't seem to apply it.)
3. Notice that after this click, the new (last in list) layer is still selected
4. Click the "assign selected elements to selected layer", meaning the finger button on top of the layer panel.
5. Object in not going to that last (new) layer that was looking like it was selected
6. --> Object ended up on the layer that is first in the list in layer panel

**Expected behavior**
Object should have been moved to selected layer. This is probably some sync issue that the UI shows wrong layer as selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/86254776/170009095-1dadeb5d-948e-40ce-9435-f03308dc713f.png)
object ended up on layer_11, not on test layer.

**Versions**
 - VPX: 1.7.0.1 Final Revision 162 64bit

**Comment by fuzzelhjb** [comment]
fixed with [https://github.com/vpinball/vpinball/releases/tag/v10.7.1-164-487d9d6](url)
