### ISSUE TITLE
FPS Cut In Half When Using External DMD (VR)

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpinball#623]
**Describe the bug**

When I load up a VR table that uses an external DMD I get 45fps instead of 90fps. Deselecting "use external DMD" fixes the issue but then we cannot get color DMDs with Freezy. 
II have tested with new Freezy 2.0.3 and 2.0

**Versions & Settings**
 - VPX: Any VR-GL after around v1271/1291 64bit
 - Windows version 10 Home 22H2
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
[VPinballX.log](https://github.com/vpinball/vpinball/files/11984091/VPinballX.log)

**Additional context**
Going back to GL v1071 (approx) and there is no issue, tables play smooth at 90fps.

 To recreate the issue load up a table like Indianapolis 500 (Tasty Wasps) with the new VR-GL and VR disabled if no headset. Set DmdDevice.ini to virtual DMD=true and VPinMAME set to use external DMD you should see bad fps. Then if you deselect use external DMD all is good.

**Comment by vbousquet** [comment]
@studlygoorite This should be better (I hope fixed) in the latest build I just pushed.
Could you give it a try and tell me if it's good ?

**Comment by studlygoorite** [comment]
> @studlygoorite This should be better (I hope fixed) in the latest build I just pushed. Could you give it a try and tell me if it's good ?

Dude!!! it's fixed, thanks man!!
