### ISSUE TITLE
PUPPack based tables crash in GL/VR since 10.8.1293

### ISSUE THREAD

**Issue by BazzaLB** [vpinball/vpinball#627]
**Describe the bug**
Starting from build 1293 (10.8), VPInballX_GL (32 bit) crashes on any table that uses a PUP Pack video. PUP starts, but as soon as the video goes to load, it then freezes and VPX exits without error. Build 1292 works perfectly fine. All other versions after 1293 also have this issue.

**To Reproduce**
1. Open any table that uses a PUP Pack (eg Batman 66)
2. Start Table for VR
3. See PUP backglass displays and you get audio, but when video goes to play, game freezes, audio stutters and then VPX exists without error. PinupPlayer remains running in Task manager.

**Expected behavior**
Table plays with PUP video on backglass without crash to desktop

**Screenshots**
N/A

**Crash dump**
none found

**Versions & Settings**
 - VPInballX_GL 10.8.1293 onwards 32 bit
 - Windows 10
 - 11900K / RTX4090
 - 
 
**Additional c
[VPinballX.log](https://github.com/vpinball/vpinball/files/11988687/VPinballX.log)
ontext**

**Comment by vbousquet** [comment]
Fixed in latest (with the ability to move/resize captured windows as well)
