### ISSUE TITLE
[VPinballX_GL-10.8.0-1314] Tables with PuP videos crash briefly after loading in VR

### ISSUE THREAD

**Issue by gssjr** [vpinball/vpinball#638]
**Describe the bug**
Tables with PuP videos crash briefly after loading in VR. I tested with Total Nuclear Annihilation and Batman 66 as those are currently the only two tables I have with PuP packs.

Was working in 10.8-beta3 with everything else the same.

Another time I managed to load the table after closing the pupplayer and everything ran fine without the pupvideo.

**To Reproduce**
1. Launch TNA in VR (environment listed in section below)
2. A few seconds after loading the table, it starts to freeze/hyper stutter and then crash out of VPX

**Crash dump**
[crash.txt.log](https://github.com/vpinball/vpinball/files/12046619/crash.txt.log)
[crash.zip](https://github.com/vpinball/vpinball/files/12046648/crash.zip)

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1314 Windows-Release-x64
 - Windows 11
 - VPinMame 3.6
 - PinUp 1.4.6.6
 - dmdext 2.1.2
 - b2s 2.0.2
 - [VPinballX.log](https://github.com/vpinball/vpinball/files/12045539/VPinballX.log)

**Comment by studlygoorite** [comment]
I had this issue but it was fixed with v1317

**Comment by gssjr** [comment]
Tried build 1333 thanks to @studlygoorite making me realize I can grab unreleased builds and confirmed working again.
