### ISSUE TITLE
Sounds assigned from table to backglass do not play

### ISSUE THREAD

**Issue by RichardL64** [vpinball/vpinball#64]
If you assign a sound, using the sound manager, to backglass - e.g. move the knocker sound to play from the backglass rather than table - when run in F6 or F5 mode from the editor it will not play.

**To Reproduce**
Edit a sound in the sound manager - click on the 'backglass' option,
Run the table via F5 -  the sound will not play
Run the table via command line - i.e. a front end - the sound will play

**Expected behaviour**
Sounds assigned to the backglass should play in all modes.

**Versions**

VPX: 10.7.0 Final (Revision 367 (https://github.com/vpinball/vpinball/commit/e242d7c93fd8c427c4a3d4852277b7f088c883c3) 32bit)
Windows 10

**Comment by sverrewl** [comment]
It's a long standing but. Save the table, EXIT completely; and it is just fine.

**Comment by vbousquet** [comment]
I have just pushed a fix for this. Could you confirm that it is now working as intended ?
