### ISSUE TITLE
Game view problem after Live View used

### ISSUE THREAD

**Issue by apophis79** [vpinball/vpinball#642]
**Describe the bug**
The game does not look correct after using the Live Editor then resuming the game. Background looks grey, Live Editor cube (upper right) still showing, Table Info data still showing, etc.

**To Reproduce**
1. Open any table. Run the table.
2. Once running, hit Esc and click on Live Editor
3. Once in Live Editor, hit Esc and click Resume Game
4. Once back in the game view, notice how it is not correct.

**Expected behavior**
Game view should be normal after clicking Resume Game.

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/74864015/863ff9e4-9e13-49a9-b143-ba3f1d6f7276)

**Crash dump**
N/A

**Versions & Settings**
 - VPX: 10.8.0 Beta (Revision 1332 (b10f82a), 64bit) DX
 - Windows 10

**Comment by jsm174** [comment]
I noticed the same thing in Android, and later on Mac. I believe the problem started with https://github.com/vpinball/vpinball/commit/2b3838a47287edab294d73d1defed7b5b3c4b45d 

https://github.com/vpinball/vpinball/assets/1197137/7db6a1f7-a4b3-4b27-bb6b-7cb711bf5a6b
