### ISSUE TITLE
Bally EE tables don't work in 10.8 beta 1333

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#643]
I upgraded from 1314 to 1333, Bally EE tables don't work anymore (Fathom, Xenon, etc..). The playfield is static, without any plastics and flippers, and no lighting. The game does boot in the background and displays are working. I tried both x86 and x64, same issue. I reverted to 1314, everything was OK again.

**Comment by passionforpins** [comment]
Confirmed on other tables as well. Here's just two more. Hauntfreaks Slayer (2022) and Balutito's Killer Klowns Hurricane reskin (2023) both running 10.8 beta 1332. They did work up to 1314.
![killerklowns-10 8-1332](https://github.com/vpinball/vpinball/assets/52011304/be627f5c-ab79-4b66-bf40-aad5656b35d2)
![slayer-hauntfreaks-10 8-1332](https://github.com/vpinball/vpinball/assets/52011304/9539b03c-43f4-462c-9993-df939c3bb74c)
[VPinballX.log](https://github.com/vpinball/vpinball/files/12065017/VPinballX.log)

**Comment by passionforpins** [comment]
another of hauntfreaks tables in 10.8 beta 1332 x64 DX.
![hf-yf-10 8x64-1332](https://github.com/vpinball/vpinball/assets/52011304/ba2b0470-afdc-446a-b777-8ce931399396)

**Comment by francisdb** [comment]
As far as I know `Killer Klowns` does not run on standalone. Is #647 a dupe?

**Comment by passionforpins** [comment]
No, not a duplicate. My bug report is not regarding the standalone versions

**Comment by Crrispy** [comment]
Hello, yes, Windows 11 22H2 with latest updates.

**Comment by vbousquet** [comment]
This is a duplicate of https://github.com/vpinball/vpinball/issues/647 so I will close here and follow in Issue 647
