### ISSUE TITLE
Materials not displaying correctly in VR

### ISSUE THREAD

**Issue by DGrimmReaper** [vpinball/vpinball#649]
**Describe the bug**
Big Bang Bar
The metal on the cabinet (rails, lockdown bar, legs, etc) are just a dull grey.

**Versions & Settings**
VPX GL 10.8 64bit Revision 1335

**Comment by TurboHenk** [comment]
I can confirm this but it's dull "white" here I think instead of grey. 

And also the energy wall outlet(VR room element) is white(has textures on it normally).

Went back to a release for ~2 month's ago which didn't have this issue.

**Comment by vbousquet** [comment]
I was not able to reproduce in latest version 1367. Could you have a try and see if the latest fixes did solve your problem ?
If not, could you post a screenshot and a link to the table ?

**Comment by DGrimmReaper** [comment]
Its still not showing incorrectly in 1367.  I was able to find the build that broke it.  It was working fine in 1319 and then broke in 1322.
![Screenshot 2023-08-24 125734](https://github.com/vpinball/vpinball/assets/41349426/ea643fd4-5cf5-4c8c-83b8-ef7d90100801)
![Screenshot 2023-08-24 130227](https://github.com/vpinball/vpinball/assets/41349426/4b2d9f27-acc8-4876-acf9-223884b85bcb)

**Comment by vbousquet** [comment]
I was not able to reproduce on latest builds. It looks like missing textures (memory problems ?). Does it always happens or only after a few games ? I have also made quite a lot of updates to the rendering since this report. Could you give a try to the latest build (the ones from the action tab) ?

**Comment by DGrimmReaper** [comment]
Tested 1438 and still not displaying correctly.

**Comment by DGrimmReaper** [comment]
This could be a table issue.  I was able to resolve by unchecking Unshaded Additive Blend under the primitives in CabLit.  I will inform the VPW team.

**Comment by DGrimmReaper** [comment]
Table Issue.  VPW will include in their next update to the table.
