### ISSUE TITLE
Mouse cursor disappear if you happen to use Debug editor along live editor.

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#652]
**Describe the bug**
Mouse cursor just vanishes if you are in Live Editor and then you need to make some script calls. You exit from debug editor and you really cannot use the Live editor anymore as you cannot see the cursor.

**To Reproduce**
1. Go to 'live editor'
2. Click on 'D'
3. Exit debugger
4. --> no cursor

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: VPinballX64_r1335.exe
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
**Additional context**

**Comment by passionforpins** [comment]
I wonder if it's related to #527 Need our mouser cursor back!

**Comment by iaakki** [comment]
Yeah probably same. Pretty much every legacy action you do ends up in lost cursor.

**Comment by toxieainc** [comment]
Should be fixed with next build.
