### ISSUE TITLE
vpx 10.8 exit

### ISSUE THREAD

**Issue by krusso222** [vpinball/vpinball#654]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 
**Additional context**

**Comment by krusso222** [comment]
hi when i use 10.8 beta after i play a table vpx does not exit like previous versions did is there a setting im missing   thanks

**Comment by vbousquet** [comment]
The issue is mostly incomplete and yourpost on VPF as well. I will close since there is nothing that can be done with the information given here
