### ISSUE TITLE
Fps Limiter not working as expected..

### ISSUE THREAD

**Issue by EianAtDawn** [vpinball/vpinball#657]
Hi,

Fps Limiter under video graphics options in later versions 10.7.2 and 10.7.3 doesn't seem to work.
I tried setting 60 80 120 140 but fps remain uncapped as shown using F11. 
Under table properties Fps Limiter setting is set to -1 (default) but even when I set this to anything above 60 I get the same result.

I can of course cap fps using RTSS but limiting fps using game engine is always preferred as it introduces no additional latency.

Btw I'm using a GeForce 1060 (531.41 Driver version) with an 180HZ g-sync monitor on a windows 10 OS.

*
I just tried 10.8.4 Beta version as well and I'm getting a bit different but still inconsistent results..
I'm getting around 10% less frames than the cap setting.
For example capping to 160 gives around 140 capping to 100 gives around 90.
Also changing synchronization mode doesn't seem to make much of a difference except for frame pacing,
which shows 0 latency when pressing f11.
On a VRR capable monitor NO SYNC should give the least latency
and if GPU is capable of reaching the capped fps, frames should be paced equally.
I also tried both Fullscreen exclusive and windowed mode.

For VRR monitors (GSync / Freesync) the best option is to set a cap a bit lower than the maximum monitor's refresh
and set NO SYNC as sync mode. 
This should give stable frame rate with negligible latency.
For example capping to 140 with NO SYNC should give 140 fps without latency..
But in this case the option doesn't seem to work as expected. Am I missing something? 

Sorry for the long post.

Cheers

**Comment by vbousquet** [comment]
I have been testing the sync options in a variety of situations and could not reproduce any of the bugs you describe here.
Note that VPX has no support for GSync / FreeSync and that VPX is not supposed to work well with external synchronization like RTSS.

Regarding the precision of the syncing, I confirm that it is not precisely bound to the max value and should stabilize somewhat below (so 139 for 140 is not a bug but the expected result).

Without more precision, I will close for now. If you still encounter problems with the latest build (from action tab), without RTSS and without expecting tearing sync (GSync/Freesync) please comment with more info to better understand

**Comment by EianAtDawn** [comment]
![image](https://github.com/vpinball/vpinball/assets/99512697/537ba6cb-1005-4d86-b9f7-3878312ca817)
![Untitled-1](https://github.com/vpinball/vpinball/assets/99512697/5cdf1013-0821-49fd-83db-feb84235ca4f)

Happy new year!!

New computer fresh windows 11 installation..
Asus TUF 4070
Geforce drivers 537.58 (latest stable) set to the default settings..

No other software running and now limiter just doesn't work..
Again tried various rates and all the settings described to my original post..


Really strange noone else have reported this..
Every other limiter in many games I've tried work as expected..

**Comment by EianAtDawn** [comment]
I just figured that if I set the frame limiter above my monitor's refresh rate then the limiter works as expected..
If though it is set bellow my monitor's refresh rate (180) it does not work.

Again this is not preferred when aiming for the least possible latency and smooth experience..
I won't go too deep here since there are other sources that cover this in more detail
but the best configuration when using a vrr monitor is to
limit the fps via the game engine at about 5 percent bellow monitor's maximum refresh rate provided that the GPU is able to easily achieve this frame rate. If CPU/GPU is the bottleneck then the limiter must be set about 10 - 20 frames (depends on fluctuation) bellow average achievable fps the .

Example 1:
Monitor: 180hz (VRR)
Avg fps:  250
Best limiter setting: 170 

Example 2:
Monitor: 180hz (VRR)
Avg achievable fps: 150
Best limiter setting: <130

There are a few other methods that mitigate the latency issue without having to manually configure (low latency mode, adaptive, fast sync...)  but this one is the best for the lowest latency possible while achieving the smoothest experience.
Also this applies to VRR monitors only.

So it would be great if you could please add an option to be able to limit the fps even when bellow the monitor's refresh rate.

By the way this is the best Pinball simulator there is so thank you..
