### ISSUE TITLE
Leprechaun King, flashing lights so intense

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#664]
Hello, when I play Leprechaun King, the flashing lights are so intense. It occurs on the latest VPinballX-10.8.0-1345-6fc48d3 x86 and X64. Please find a solution.

I have a 4K laptop NVIDIA 3080ti. Thanks in advance.

https://github.com/vpinball/vpinball/assets/81928693/3d00a946-20f8-4838-911e-7d0b55e50955

**Comment by wiesshund** [comment]
only the 64bit?
cause should look the same 32 or 64, the renderer is the same.

Kind of looks like the table lights need updating since 10.8 does lighting differently.

**Comment by JorgePedro65** [comment]
Not only 64bit, it looks both 32 & 64bit.

**Comment by wiesshund** [comment]
Ok makes more sense then.

The author probably needs to update it for the new lighting.
Some old lighting hacks simply don't work anymore, and you have to update the table lighting.

**Comment by vbousquet** [comment]
Just tried the table in 10.7 and 10.6 and it looks just like that. I don't think there is a bug here but the table is made like that.
