### ISSUE TITLE
3D Message in 10.8 shows in middle of playfield and stays forever (> 4 seconds)

### ISSUE THREAD

**Issue by julianmrodri** [vpinball/vpinball#665]
Hi, I noticed in VPX 10.8 the message sign that says "3D Stereo is enabled but currently toggled off..." shows in the middle of the playfield and stays there for a very long time. This is quite annoying in my current setup as it shows with every table I load in my cabinet, right in the middle of the playfied.

In previous versions it was showing on top of the playfield and only for a few seconds. It is my understanding it should only be there for 4 seconds at most based on the code ein 10.8 but that is not happening in many cases.

Is there a way to restore that sign to the way it behaves in 10.7? Can I do something to prevent that for showing?

Thank you very much!
Julian

**Comment by wiesshund** [comment]
Turn off 3d anaglyph in vpx video prefs and it wont display at all

**Comment by julianmrodri** [comment]
> Turn off 3d anaglyph in vpx video prefs and it wont display at all

Thanks!. But would I still be able to switch to 3D by clicking F10? Because I do have a button in my cabinet to switch to 3D.

**Comment by julianmrodri** [comment]
![image](https://github.com/vpinball/vpinball/assets/56316686/ccfeba6a-a005-40ef-996c-b909cc3812f2)
this is what Im referring to, been playing this table for more than 10 minutes and still there!!

**Comment by julianmrodri** [comment]
Thanks will try it out!
