### ISSUE TITLE
S11 alternate machine translation to support tables like grand lizard

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#666]
Hey guys, it looks like Williams S11 and Grand Lizard's implementation of S11 is a bit off the norm

Grand Lizard (See manual Page 13, left side, from flipper power supply)
That is showing 1 staged flipper (No idea why only one of the two is staged but i did not design the machine)

SW 47 and 48 actually activate solenoids
VPM display is a bit flaky on that ROM, but they do in fact activate these.

 SolCallback(sURFlipper)
 SolCallback(sULFlipper)

but S11 has no switch definitions for the staged flips
I am not sure what other S11 tables deviated to do this?

I made a modified S11.vbs, called it S11g.vbs (because Grand lizard)
https://drive.google.com/file/d/1I8RCXIE9qVLunIVVXzdIICNwbPiSrUHS/view?usp=drive_link

here it is implemented in grand lizard
https://drive.google.com/file/d/1GF_p3UZsP7_fkaMjDMOr_fO3r8DjNFmW/view?usp=drive_link
(table script only)

Is this something we would want to add to official vpx scripts?

You can't add it to the normal S11 because the staged switches are used for other things
Such as Elvira's top lane rollovers.

**Comment by toxieainc** [comment]
Added, thanks a lot!!

**Comment by wiesshund** [comment]
@toxieainc could we perhaps not name it S11_Grandlizard ?
S11a or something?

Solar Fire will use it also.
People might get confused about using it?

![image](https://github.com/vpinball/vpinball/assets/8684777/ac47d4b8-c943-4432-9a1c-a47cf3915fb4)

![image](https://github.com/vpinball/vpinball/assets/8684777/1f2744f3-4682-4310-a756-4722935d62a7)

**Comment by wiesshund** [comment]
Oh crap wait
Solar fire is S7
Damn it, now i have to figure out another one.

**Comment by wiesshund** [comment]
the machine uses flipper button SW-1010A-13 
that is the dual staged flipper button

Can Gaston by change help me identify the switch number?

https://i.imgur.com/543kZ7c.png

https://i.imgur.com/CvrQjaH.png

**Comment by toxieainc** [comment]
Thats why i asked if more machines could use it. If yes, then we should rename it. If not then we will go with the specialized name, i'd say.
@volkenborn for the question above about Solar Fire.

Thanks for the investigations!

**Comment by wiesshund** [comment]
@toxieainc 
Sorry, not having staged flips myself it takes a bit to set up to do it
plus i never pay attention of if a machine has them or not.

Highspeed is Sys 11
I will look at it when i can and see if this works for it as well.

**Comment by wiesshund** [comment]
@toxieainc You're gonna hate me.
I will probably eventually have a number of these to submit.

But, not today!
LoL

**Comment by toxieainc** [comment]
No problem, take your time. Any improvement is appreciated, don't worry about having to do multiple iterations.

**Comment by wiesshund** [comment]
@toxieainc sorry, nothing happening here yet
I am waiting for the community to at least tell me what controllers the affected tables use.
It's some 150 individual tables, and i dont have time to run about looking for and downloading 150 tables, just to read 1 line from the script.

**Comment by wiesshund** [comment]
@toxieainc 
Attached is my work on the machine translations (No alternately named translations)
as well as table script examples of employing staged flips simply and logically.

[Staged Flipper Work-.zip](https://github.com/vpinball/vpinball/files/12612989/Staged.Flipper.Work-.zip)

End user of course needs to map their staged flipper buttons in vpx
and enable them in vpmkeys.vbs, but that part is nothing new.

I do not think there are any more possible machines

**Comment by toxieainc** [comment]
..i'm actually stupid, yes, just saw that they are mapped by default to the normal flipper buttons

**Comment by wiesshund** [comment]
its controlled by VPMKeys.vbs

default is stagedflipper key = flipperkey

So if you dont set it as staged control there, you never know a thing

Now in an original table or one using script forced staging as a work around for lack of VPM support, like data east
user just maps flips and staged flips to same keys in vpx dof nudge keys prefs

So at no time ever is one forced to have staged buttons
