### ISSUE TITLE
Allow VPX to save the keyboard mappings for Custom 1 2 3 4 and add 2 new custome keys named StagedL StagedR

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#667]
VPX does not presently save the keyboard mappings for buttons custom 1 2 3 or 4
it will save joykeys but not the keyboard mappings.

Why is this needed?

It allows the buttons mapped there to be sent to vpinmame directly as the keycodes

Presently the only way to do this is
manually edit VpinballX.ini (or registry in 10.7)
insert the key scan codes
Save file (or close regedit)
open vpx, pick the controller button numbers in dof/nudge prefs
click ok

If you try to map keyboard keys in the UI, they are not saved when you click OK (never have been)
try it, you will see that they vanish and are never saved.

Why is this needed?

go to %appdata%vpinballx
open vpinballx.ini
do find joycustom

edit those entries like so

joycustom1key = 22
joycustom2key = 23
joycustom3key = 24
joycustom4key = 25

this is U I O and P

save file and close notepad

open vpx
open dof/nudge prefs
set the 4 custom keys to ANY 4 buttons
click OK

CLick FIle > New Table
open table script
go to line 43

Sub Table1_KeyDown(ByVal keycode)

add a line below it

ScoreText.Text=KeyCode

launch table

press the 4 buttons you picked above
notice that vpx reflects the sending of the associated keyboard keys
these keys will be sent to vpnmame and so can be assigned in VPN keys
No joy2key type software required, or changing of controller from gamepad to keyboard emulation

Reason for asking for 2 additional custom keys is so that staged flippers could be done, without removing the ability to
setup a 4way stick for baby pacman or granny and the gators.

**Comment by toxieainc** [comment]
On it, i hope everything will work as expected in the end..

**Comment by wiesshund** [comment]
It will.
If the inputs exist in the UI, and they UI allows saving them as keyboard keys
then they will return a keyboard value when a controller button assigned to same functtion is pressed.

And then if they are given internal variable names, like all the other buttons are
an original table author could make use of them as well

**Comment by toxieainc** [comment]
Please test and let me know if i screwed stuff up or if it doesn't work as expected, as said, didn't have much time but wanted to unblock you

**Comment by wiesshund** [comment]
Ok, I will check it out later todayOn Aug 16, 2023 2:14 AM, toxie ***@***.***> wrote:
Didn't have much time, but i hope(!) that this should do the trick.
It should save the 4 keys properly now, and adds 2 new script calls:
StagedLeftFlipperKey
StagedRightFlipperKey
(these can also be configured in the UI)

**Comment by toxieainc** [comment]
I hope i didn't break things. The input code evolved into a rather messy state over the last 20 years.   :/

**Comment by wiesshund** [comment]
For functionality sake this does not matter

But perhaps for your sanity later, it should

The following settings

joystagedlflipkey = 0
joystagedrflipkey = 0
stagedlflipkey = 37
stagedrflipkey = 38

Are being saved in the INI under the header
; Counters decremented after each run

Should be
; Keyboard input mappings
stagedlflipkey = 37
stagedrflipkey = 38

and
; Joystick input mappings
joystagedlflipkey = 0
joystagedrflipkey = 0


It may not affect functionality, but may throw a wrench in your organizational sanity later?

Will test more later, a bit busy with work at the moment.

What are the script calls for custom key 1 2 3 and 4?

**Comment by wiesshund** [comment]
staged flipper key calls work
keyboard bindings do save as reported above

What are key calls for the customs so i can test those also?

Will have to grab a controller later and verify controller function

**Comment by toxieainc** [comment]
I just looked that up in the original commit over a decade ago.. The intention was really to just map some keyboard key to some joypad input. So no special call for that.

Thanks!

**Comment by wiesshund** [comment]
@toxieainc could we add them?
they could be used in an original

**Comment by wiesshund** [comment]
@toxieainc 
Can we add variables for the 4 customs?
I have run across at least 1 user who wants to do an original table that will have an arcade type mini game
like baby pacman or caveman or granny and the gators
and that needs a script variable for the keys

custom1key
custom2key
custom3key
custom4key

?

Or what ever seems appropriate
they exist in keymapper, just need a script variable

**Comment by toxieainc** [comment]
will do hopefully so tomorrow, thanks for the reminder!

**Comment by toxieainc** [comment]
Should be good now, please test and let me know if it works as expected for you, thanks!!

**Comment by wiesshund** [comment]
What are the variable names?
I tried JoyCustomKey1 and JoyCustom1Key and Custom1Key and CustomKey1
not recognized (undefined error)

**Comment by wiesshund** [comment]
![image](https://github.com/vpinball/vpinball/assets/8684777/859578fe-7259-4abe-b3f3-784092c6f7d8)

**Comment by wiesshund** [comment]
This seems it should work but, does not?

![image](https://github.com/vpinball/vpinball/assets/8684777/d2d5234f-95c8-4b4c-a892-b378179731ea)

**Comment by wiesshund** [comment]
OH! Ok
If Keycode = JoyCustomKey(1)
ok have to use them like that

Yes they work.
I am driving a flasher and a prim around the table

Useless example but hey, it works

**Comment by wiesshund** [comment]
May want to notate it like that when doing the official commands doc or what not

**Comment by toxieainc** [comment]
The index is noted in the CommandReference already  ;)
Thanks for verifying!

**Comment by wiesshund** [comment]
close ticket :)

another one bites the dust

Unrelated but why can vpx not read the POV/HAT/Dpad inputs
I know that would be a totally separate thing, was just curios on why it does not?

**Comment by toxieainc** [comment]
don't remember.. most likely because back in the days this was not a thing yet?!

**Comment by toxieainc** [comment]
also see https://github.com/vpinball/vpinball/issues/547

**Comment by toxieainc** [comment]
and https://github.com/vpinball/vpinball/issues/210

**Comment by wiesshund** [comment]
yea i know we have tickets to add some new functionality, which makes sense, i was just always curious on the Dpad
since it has existed as long as direct input has, and of course xinput has never existed without it.

I realize pincab controllers will not have it of course, as those have their origins in the usb arcade controllers from way back in the early MAME days, which have always adhered to strictly plain buttons and 2 pairs of analog axis

It does make sense to add shoulder triggers as a digital input if possible
They SUCK as a plunger axis, their axis throw is too short and too flakey in 90% of the controllers made, even real Xbox ones
But accepting any amount over threshold as simply button ON would work well
In DInput mode they work exactly like that (the controller itself, not VPX)

Of course you know what works really good?
cut the positive trace to the shoulder triggers
bridge it to that of the thumbstick buttons

Want to start a vpin gamepad modification service?
we might make enough profit to split a junior cheeseburger

**Comment by toxieainc** [comment]
In principle we should just move completely to let SDL handle all the inputs, as it will just map it under the hood to whatever is 'modern' and supported by the OS/Controller.

AFAIR the old DX input we use(d) does not separate dpad and analog stick or something.

**Comment by wiesshund** [comment]
dInput was unfairly killed by MS LoL

XInput supports maximum of 4 axes, 10 buttons, 2 triggers and 1 8-direction digital pad per controller, Max 4 controllers per machine, and two rumble motors of limited manipulation

DirectInput supports 8 axes, 128 buttons, and mulitple full-range POV, unlimited controllers per machine, 2 rumble motors with control of various sine wave modulations, full support of forced feedback via h-bridge controlled devices, typically but not limited to, stepper motors.

i know, off topic.

not sure what we currently use under the hood or what it's implementation was based off of
wish i could be more helpful there.
Axis wise it tends to understand enough of them.
Button wise, it seems to only understand the ones that define themselves as button in the event (best guess?)
whereas those will normally identify their event as DPAD (number) and POV (number)
maybe it was only written to look for button events?

**Comment by wiesshund** [comment]
wonder if this is useful though SDL is probably a better long term solution

https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee418634(v=vs.85)

**Comment by toxieainc** [comment]
i opened #790 to bundle up feature requests/ideas on that topic
