### ISSUE TITLE
"Light Emission Scale", "Light Range" and "Light Height",not saved in POV

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#668]
**Describe the bug**
If I set the 'Light Emission Scale', "Light Range" and "Light Height" through the 'Adjust camera' dialog for and I save the POV, the next time it launch the table, this setting is set to default again.

**To Reproduce**
1. Open table and run with player
2. hit Q and select "adjust camera"
3. Change value of "Light Emission Scale', "Light Range" and "Light Height" and hit the start button to save
4. pov file is created, relaunch table and the value is back to normal

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
Expect this settings to be written into the <customsettings> section of the pov

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Comment by droscoe** [comment]
Hi Mike,
Just for giggles, Try exporting the POV instead.  This was an issue with 10.7 as well.  Exporting the POV manually preserved more settings than simply saving the table.  Could be a holdover

**Comment by MikedaSpike** [comment]
thanks @droscoe , I tried that as well, but that didn't  work as well.
manually writing POV has the same export as export via 'Live editor' and is missing the  'Light Emission Scale', "Light Range" and "Light Height",
