### ISSUE TITLE
With Frame Pacing on, unable to start Blood Machines or Iron Man in Beta4

### ISSUE THREAD

**Issue by toddsay** [vpinball/vpinball#669]
**Describe the bug**
Using 10.8 Beta4, I am unable to start two tables:
- Blood Machines 2.0: "Coin" works (registers a credit), "Start" clicks but fails to begin a game.
- Iron Man Vault Edition (Stern 2010) VPW v1.0: "Coin" makes noise but does not register a coin. If I press "7" to add a credit and press "Start", the ball fails to advance into the channel and I get script error "Subscript out of range: 'Cor.ballvelx'".
- Using Beta3 I do not have these issues.

After much discussion below and some great troubleshooting by @Mrtr32, we learned these problem only occur when Video Synchronization is set to "Frame Pacing".

**To Reproduce**
1. In Video/Graphics Options, set Video Synchronization to "Frame Pacing"
2. Double-click either of the tables to load them in VPX
3. Press the "coin" button
4. Press the "start" button
5. Game fails to start

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
https://vpuniverse.com/files/file/9847-blood-machines-vpw-original-2022
https://vpuniverse.com/files/file/12116-iron-man-vault-edition-stern-2014-vpw-edition

**Expected behavior**
"Coin" button should register a credit
"Start" button should begin the game

**Versions & Settings**
 - VPX: 10.8.0 Beta (Revision 1314 (0f002da), 64bit)
 - Windows 10
 - .ini file attached if needed
[VPinballX.log](https://github.com/vpinball/vpinball/files/12288137/VPinballX.log)

**Comment by passionforpins** [comment]
I just tried both tables in desktop mode with VPinballX 10.8.0 rev 1345 -x86 and -x64 (DX only), VPinMAME-sc 3.6 rev483 x86 and x64. Both coined up and played perfectly with colored dmd (vpin) and pup packs.
My system windows 11 home, 32gb, 13th gen I7, nvidia GTX 1660 super 6gb.

Maybe try a newer beta version? I believe it's at 1348 now but 1345 working ok for me.

**Comment by toddsay** [comment]
Thanks [passionforpins](https://github.com/passionforpins). I just tried build 1348 and had all of the same issues. Running the exe from build 1271 I do not have these issues. But I can't explain why you had success, so it sounds like there are other factors at play. I'm also running with pup packs. But my VPinMAME version is 3.6-369 (latest released, I think, not sure if that might matter here). Windows 10, 12gb, 3rd gen i5, 1660ti.

**Comment by Mrtr32** [comment]
Tried **Whirlwind 4K** from Flupper and VPX8 1271 build without success
Can't add coins and can't start the table

**Comment by passionforpins** [comment]
Hate to say it but, again, working just fine for me with 10.8 x64 (dx) rev 1345

**Comment by Mrtr32** [comment]
Tried only VPX 10.8 x86 version
I'm running on Windows 7 Pro 64 bits, 32 GB of Ram, GTX 1660 Ti 6 GB
VPinMAME-sc-3.6-483-88b80ab-win-x86
Tried all VPX 10.8 Beta 2 to 4 without success
Thanks!

**Comment by Loafmeister** [comment]
Pardon my butting in, but it sounds like the old focus issue. Try it again and if coin or start doesn’t work , then press alt-tab to ensure the vp playfield is primarily at the front then try again

**Comment by passionforpins** [comment]
works ok in 10.8 1345 x86 too
![whirlwind-10 8-1345x86](https://github.com/vpinball/vpinball/assets/52011304/5fb5be83-7586-4054-a669-f5835bdbd0b3)

**Comment by toddsay** [comment]
It doesn't seem to be a focus issue (tried alt+tab, but also I do get coin/start SSF sounds so the presses seem recognized).

I'm running the latest 64-bit builds now (VPX 1348, VPinMAME 3.6-483), but still having the same issues. This is odd.

I did try that Whirlwind 4k table though, and did not have any problems there.

**Comment by studlygoorite** [comment]
With these tables try double clicking the VPinballX.exe and close the tables folder that automatically opens, then choose "file" and "open" and choose your table there. Worth a shot :)

**Comment by wiesshund** [comment]
tried both tables and the whirlwind but also can not replicate

They all ran as intended

**Comment by Mrtr32** [comment]
@wiesshund

Do I need to install VPX8 from scratch or I can simply extract VPX8 x86 files to my VPX7 x86 folder?

**Comment by Mrtr32** [comment]
After testing intensively VPX8, the table issues come from the **Maximum Framerate** parameter in the **Videom/Graphics options**
With the previous VPX versions I always limited the FPS to 1 to make the table faster for playback
In VPX8 limiting the FPS to 1 slowdown the table considerably and make it unplayable.
This is the reason why VPINMAME don't interact properly with the table

Currently the solution is to leave the **Maximum Framerate** at the **0** value.

**Comment by toxieainc** [comment]
Thanks for finding the issue. @vbousquet should be able to fix this regression when he's back.

**Comment by wiesshund** [comment]
In VPX 10.8 max framerate is not used to enable Vsync anymore
Vsync has its own dropdown box to enable it, so if you set Max Framerate to 1, you are going to get a result you do not want.
It should be at 0 or the actual FPS you want to lock it to if that is less than sync for some reason.
(Id not recommend locking under sync)

I do not see as there is anything to fix here?
It is working as intended

![image](https://github.com/vpinball/vpinball/assets/8684777/dcbec991-75bd-4cbf-a8bd-1c60979241a4)

**Comment by wiesshund** [comment]
> @wiesshund
> 
> Do I need to install VPX8 from scratch or I can simply extract VPX8 x86 files to my VPX7 x86 folder?

rename vpx 10.7 exe to something like vpinballx-10.7.3.exe
then just unzip beta into existing folder

**Comment by Mrtr32** [comment]
@wiesshund
Thanks for the tip, realy good to know!
In VPX7 limiting to 1 give me a smoother ball mouvements
at 0 the ball move by step on some tables

**Comment by wiesshund** [comment]
What did you set vsync to?

**Comment by wiesshund** [comment]
![image](https://github.com/vpinball/vpinball/assets/8684777/d3e10af6-8c7d-4319-88e4-e0859ff0414b)

**Comment by wiesshund** [comment]
ran blood machines 2.0 fine on laptop
as fine as laptop is capable anyways

**Comment by Mrtr32** [comment]
This is my current settings
![Screenshot 2023-08-10 140256](https://github.com/vpinball/vpinball/assets/87276333/4d0a1863-6542-44b8-8d3a-e2e973800e93)

**Comment by wiesshund** [comment]
change from no sync to frame pacing

**Comment by wiesshund** [comment]
![image](https://github.com/vpinball/vpinball/assets/8684777/a03e4ab5-0e57-4d6a-a8a1-bc327a619990)

testing in this version, on an extremely less than optimal machine to boot

**Comment by Mrtr32** [comment]
Tried frame pacing without success
No Vertical settings in VPX8 give me the same smooth ball mouvement as in VPX7 with FPS limits option to 1

**Comment by toxieainc** [comment]
> In VPX 10.8 max framerate is not used to enable Vsync anymore Vsync has its own dropdown box to enable it, so if you set Max Framerate to 1, you are going to get a result you do not want. It should be at 0 or the actual FPS you want to lock it to if that is less than sync for some reason. (Id not recommend locking under sync)
> 
> I do not see as there is anything to fix here? It is working as intended

I think at least catching 'nonsense' values and warn (or clamp them) would make sense still to avoid this kind of weird behavior.

**Comment by toddsay** [comment]
Thanks @Mrtr32 for tracking this down! I was doing some testing too but hadn't hit on anything useful.

In my case, I had that setting as "Frame Pacing" / 60 / 1. Changing those values to 0/0 did not fix my problem (just testing the Blood Machines table for now). But when I turned off frame pacing and went back to "No Sync" the problem vanished.

**Comment by wiesshund** [comment]
what fps does vpx show it is rendering at

**Comment by wiesshund** [comment]
> > In VPX 10.8 max framerate is not used to enable Vsync anymore Vsync has its own dropdown box to enable it, so if you set Max Framerate to 1, you are going to get a result you do not want. It should be at 0 or the actual FPS you want to lock it to if that is less than sync for some reason. (Id not recommend locking under sync)
> > I do not see as there is anything to fix here? It is working as intended
> 
> I think at least catching 'nonsense' values and warn (or clamp them) would make sense still to avoid this kind of weird behavior.

the Max FPS is still useful.
If one has say a 140hz monitor, and lets say one has an RX550 GPU
it wont attain 140fps, some wont be able to reach sync.
What it will attain is a wildly bouncing FPS rate (depending on the table of course) which will lead to the table looking like it runs like crap.

In which case, limiting the max FPS to 60fps will stop things from bounding around like that and making the table play badly

**Comment by toddsay** [comment]
Oh absolutely. And if there weren't videos involved I'd be able to exceed 60fps (on my 60Hz monitor).

**Comment by wiesshund** [comment]
> Between my barely adequate system specs and the light videos running in those pup packs, looks like I'm not hitting the 60 cap for these tables:
> 
> Blood Machines: 58, slowing to high 40's at times Iron Man: 54, slowing to mid 30's at times
> 
> But turning off sync did fix all of my problems here.

bummer frame pacing is not working for you, but i am not sure why?
your video driver is not overriding anything is it?

i cant suggest nvidia settings as i dont have a working nvidia gpu here, so i cant look at those.

PUP is entirely CPU driven, so it does up CPU load, no bearing on GPU though, but slowing down CPU can prevent it from feeding the GPU fast enough.
Higher the pup content resolution, higher the CPU load when decoding the content(even if playing back to a 720p screen).

I can usually speed those VPW tables some by deleting the entire VR room, objects assets and script
and then resizing the large image sheets to 4k or less in resolution.

I dont run the PUPs though, i throw the PUP packs and the PUP code in the trash.
when pinmame emulates spike2, i will worry about displaying a pup like display

**Comment by wiesshund** [comment]
> Oh absolutely. And if there weren't videos involved I'd be able to exceed 60fps (on my 60Hz monitor).

Not a lot of point in exceeding the monitor's refresh rate
wasted heat power and gpu cycles as it is work that wont be seen, or if seen while be sheared due to out of sync.

Great for benchmarking or messing with settings etc, not so great though for normal playback.

If frame packing screws the pooch for you, does straight vertical sync also mess things up?
as if monitor is 60hz it would limit fps to 60hz as well, without having to manually define a max fps

**Comment by wiesshund** [comment]
if frame pacing and vsync both fail to work properly
it may be helpful for devs to know GPU in use, GPU driver version and GPU driver settings

**Comment by toddsay** [comment]
Actually yes. It turns out I did have the frames limited to 58 on the GPU settings. With that off, I'm able to hit mid 60's, sometimes over 70, on Iron Man. And a bit over 100 on Blood Machines.

PUPs are another topic, yeah. That embedded vlc player is not efficient (new versions are _way_ better but not supported there). On some tables that player uses over half my CPU, making the table laggy and CPU-limited.

Vertical sync and adaptive sync both work for me. It seems to only be a regression with Frame Pacing, as I didn't have the issues in Beta3. But honestly I wasn't sure which type to choose there, was just trying to choose the newest or lowest overhead type. I think any sync method will be fine for me.

**Comment by wiesshund** [comment]
@toddsay 
Ugn damn, i wonder what happened to frame pacing
AND
I wonder why it has 0 effect on my laptop?

Or is this one of those things where not having a GPU is actually an upside?
Im going to try it on my desktop.

Is frame pacing working badly on other tables also, even if not as bad?

**Comment by wiesshund** [comment]
Seems to possibly be less bad on AMD but i tried on desktop, and something has noticeably been lost.
FPS is still high, blood machines runs at 200 fps without batting an eye if vsync is set to none, without turning any graphics down.

but frame pacing seems to be a bit off as previously it was acting flawless, now, at least what i tested on blood machines, it is adding a slight stutter to the ball most noticeable at mid table.
Not horrid, but noticeable enough.

Bummer :(

**Comment by wiesshund** [comment]
> But honestly I wasn't sure which type to choose there, was just trying to choose the newest or lowest overhead type. I think any sync method will be fine for me.

When it is fixed, frame pacing is best, lowest flipper reaction latency.
When it is working the internal latency is so low that you are really only limited by controller latency and physical button lag.
Not that i am remotely good enough at pinball to know but

**Comment by vbousquet** [comment]
After reading all this, I don't think there is a bug or regression here. The old sync parameter was split in 2 to be more easy to understand and allow more options. Now, in 10.8, the maximum framerate actually does what it says : it is the maximum framerate, so setting it to 1 leads to 1 frame per second (making thing unplayable). The sync option is now verbose instead of a number. 0/1/2 have been replaced by No Sync / Vsync / Adaptive Sync / Frame Pacing (new one).

To be more user friendly perhaps we could discard values that are not sensible (any max frame rate below something like 10 FPS will be unplayable) ?

On a side note, you are stating that frame pacing needs to be fixed but it is unclear to me what is not working with it. From my tests (and on my cab), it is just working as intended but I may be missing something

I will close for now the issue since as far as I can tell, it runs as expected

**Comment by toddsay** [comment]
@vbousquet That's not what I was seeing. Since Beta 4 I was unable to press start on the games in question. They'd make a clicking sound but just wouldn't start at all. That was with Frame Pacing and a max framerate of 60. I also tried 0 (which I think means unlimited?), with the same results. I never set that value to 1 (although another user mentioned doing that).

If I use any other method besides Frame Pacing, the start button works as expected. And using the Beta 3 version I can start the games even with Frame Pacing on.

**Comment by wiesshund** [comment]
rev 1351 is a bit better but frame pacing is not working as well as it did previously, in the build where you fixed
vpx being stuck liked to an odd refresh rate, frame pacing worked great afterwards.
Now it kind of lags is the best way i can describe it.

It should normally give the best results.

I would have to go look through the closed issues to see what build that would have been

(No have mave max fps set to nothing)

**Comment by wiesshund** [comment]
Found it
https://github.com/vpinball/vpinball/issues/618
Rev 1308

Frame Pacing was working awesome in that build.

**Comment by vbousquet** [comment]
Ok, but I just don't understand what is not working right now. On my side it's wiorking just perfectly. If you could describe it on another issue (this one is quite long and messes multiple subjects, making things difficult to follow/understand), this would be wonderful

**Comment by vbousquet** [comment]
@toddsay I have just fixed a major issue with frame pacing regarding timers. Could you have a try with version 1357 and tell me if you're still having the issue you described for BloodMahcine & IronMan ?

**Comment by Mrtr32** [comment]
@vbousquet

Sorry for my misunderstood of the new vsynch features changes

For an unknown reason, I was tested VPX 8 build 1347 with the previous DMDEXT 2.2.0 betas version and experiencing a lots of ball stutters issue on the most demanding tables including Blood Machines.

After updating
VPX8 to 1353 bulid (Latest)
DMDext to 2.2.0 Final build (Latest)
VPinMAME-sc-3.6-495 build
Using the **Frame Pacing** option

All is working very well on my test computer and my cab without any ball stutters issues on all the tables including the most demanding ones like Blood Machines.

I think this ticket could be closed.

Thank you very much for your excellent work.

Much appreciated

**Comment by vbousquet** [comment]
No problem, regards !

**Comment by toxieainc** [comment]
> To be more user friendly perhaps we could discard values that are not sensible (any max frame rate below something like 10 FPS will be unplayable) ?

I used 24 now, as it seems like the lowest value where one could still find some artificial argument for.

**Comment by toddsay** [comment]
Thanks @vbousquet! Indeed these problems are fixed by the latest builds. 🎉 

Just a note: Using Frame Pacing the reported FPS is roughly 10 lower than the number I get from VSync, but I haven't determined whether playability is better or worse so I'll probably stick with Frame Pacing for now.

**Comment by wiesshund** [comment]
Seems ok?

fps/latency counter sometimes flashes red when the stats it is reporting are better, rather than worse than expected
but i am not 100% certain by what criteria it flashes red, so that may be meaningless?

seems to work fine now though

FPS number matches sync rate

**Comment by wiesshund** [comment]
@toxieainc even 24 is somewhat hideous? sort of resembles stop motion animation?
I think the lowest refesh rate i have seen in use is 40hz used by some laptops as an alternate sync rate?
most stuff will be 60 or better?
