### ISSUE TITLE
Allow loading of image files straight from filesystem

### ISSUE THREAD

**Issue by iaakki** [vpinball/vpinball#671]
**Is your feature request related to a problem? Please describe.**
There are many use cases where it would be meaningful to load image files straight from filesystem. Currently if you want to show some texture in a flasher or primitive, one needs to bundle the image into VPX file. This prevents making dynamically scalable VPX projects, such as photo viewer or direct Scorbit integration. Scorbit support is now done using pup-system, just because of one QRCode image and there is a slow workaround implemented into Blood Machines that can load this image into VPX flasher. 

**Describe the solution you'd like**
Way to load image into VPX flasher or primitive straight from filesystem. One could build a proto library or music library with playlist features with album art etc. Currently all the album art would be needed inside the vpx file; at would be a lot more versatile, if those images are fetched straight from filesystem.

**Describe alternatives you've considered**
So BM uses this to get the QRCode into a VPX flasher https://github.com/iaakki/VPXQRView. It is really slow and buggy way to do it. Would not work with larger amount of images.

**Additional context**
I'm not sure why this has not been implemented previously? Maybe there is some reason I haven't through about?

**Comment by wiesshund** [comment]
have you tried creating a filesystem object and loading an image from there?

**Comment by francisdb** [comment]
Can we also consider standalone on mac/linux here where you might end up with *nix file paths using different separators.

**Comment by Lovinity** [comment]
> have you tried creating a filesystem object and loading an image from there?

This only works for BMP files. Any other file type needs converting to BMP first, which requires an external library or tool like ImageMagick.

**Comment by vbousquet** [comment]
Added in latest (LoadTexture method from global scope)

**Comment by mpcarr** [comment]
LoadTexture takes two params, imagename and filename. Presently the imagename isn't being used as the name for the texturecache, therefore the image never loads. The only way to use this is by supplying an empty string to loadtextue, that way the filename of the image is used as the imagename. e.g.

LoadTexture "", "C:\vPinball\testimage.png"
Flasher001.ImageA = "testimage"

PR with fix: 

https://github.com/vpinball/vpinball/pull/1226
