### ISSUE TITLE
Subwoofer not working?

### ISSUE THREAD

**Issue by wimpie3** [vpinball/vpinball#673]
I have a 7.1 audio setup. While I can hear sound coming from all the speakers while playing a VPX table, the subwoofer does not seem to produce any sound.

Set the VPX output to 7.1 audio.

**Expected behavior**
Subwoofer should produce sound.

**Versions & Settings**
 - Windows VPX 1.7.3

**Additional context**
Subwoofer DOES make a sound in the Sound Panel from Windows.

**Comment by vbousquet** [comment]
This is not a bug but a question of configuring. You will get better support on the community forums like in vpforums. I will close for now then
