### ISSUE TITLE
Exit of Visual player (if loaded with -play), doesn't close Visual Pinball editor

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#682]
**Describe the bug**
When launching a game directly from the gui or command line with -play, it doesn't close the editor when exiting the player.
When I use -play with 10.7.x and exit the player, it also closes the editor as well.
I normally star ta game with -extminimized (also added to the registry) and noticed I had 35 instances of VPlayer.exe open after a afternoon.

**To Reproduce**
1. Double click a VPX file
2. press Q to get the menu
3. press q again to quit the editor
4. Vpinball.exe editor is still open

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
When using the -play, I expect that the editor will close as well

**Screenshots**
NA

**Crash dump**
NA

**Versions & Settings**
 - VPX: [e.g. 1.8.0  beta Revision 1360 (bcd46562), 64 bit - see *Help - About*]
 - Windows 11 22hs
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**

**Comment by vbousquet** [comment]
I just tested it on VPX 10.7.3 and VPX 10.8 and did get the same result:
- if I run with ```-play test.vpx```, the table exits to the editor
- if I run with ```-minimized -play test.vpx```, the table exits to Windows (closes the editor)

I did not spot any difference in the behavior of the 2 versions of the app. Could you be more precise because I don't seem to understand where is the bug.

**Comment by MikedaSpike** [comment]
Let me check tomorrow. 
On 10.8 the editor was still open when exit a table. 10.7.3 was working fine

**Comment by MikedaSpike** [comment]
Thansk @vbousquet 

You are absolutly right. _ play leaves the editor open in 10.7.3 and 10.8 (sorry for the confussion)
When I use -minimized it closes indeed the editor.
But -extminimized leaves the editor open within 10.8
Running the -extminimized in 10.7.3 it will close the editor on exit table

**Comment by vbousquet** [comment]
Thanks for this very clear explanation. It should be fixed now (and allowed to also fix another bug)

**Comment by MikedaSpike** [comment]
thanks Vincent. I really appreciate all your work you did with the 10.8 release.
