### ISSUE TITLE
Record total number of plays per table with a view to implement progressive playfield wear

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#687]
There's been talk over the years of simulating playfield wear over time. A table with a high play frequency might start showing signs of wear/dirt layer on the surface of the inlanes and outlanes for instance.

I was thinking the first step in this idea would be if a file was incremented with the total number of plays for each table, persisting even after the table is closed. Script could then possibly check the counter in this file and if count is greater than X, simulate a gradual wear/grime layer on the playfield over time.

Not sure if the nvram already contains total plays and if so could it already be used for this purpose?

Any feedback?

**Comment by toxieainc** [comment]
Small addon: Modern machines would also allow to fetch the amount of total plays via NVRAM, e.g. https://github.com/vpinball/pinmame/blob/cc4986a97d92d80ab492b2bd3d921e3bf5bb35f5/release/whatsnewVPM.txt#L140
The difficulty is to find out the location in there, though, as only few machines are documented (see link above).

**Comment by gjupp** [comment]
Thanks @vbousquet and @toxieainc for the feedback.
