### ISSUE TITLE
Pupflasher not working and no Music play in "VPinballX_GL-10.8.0-1367-fc71d22-Release-win-x64"

### ISSUE THREAD

**Issue by Ahriman0** [vpinball/vpinball#691]
**Describe the bug**
I opened the table in "VPinballX_GL-10.8.0-1367-fc71d22-Release-win-x64" and the TV-pupflasher doesn't work, nor does the background music play. But if I open the table in "VPinballX_GL-10.8.0-1367-fc71d22-Release-win-x86" everything works, the background music plays and the TV pupflasher works too.

Table: "Stranger Things 4 LPE (Tuga & Nesta78 Limited 4K Edition) 2.5.vpx" 
little tablefix:
under layers, the double "pupflasher001" must be deleted, but that doesn't change anything about the problem described
Link: https://mega.nz/file/i7g3UIiQ#yu1qT_ALIAk4VhSK7SHHR70j_2AKznGiaXF2xkn72eg

Pup-Pack: "Stranger Things 4 Puppack" TeamTuga
Link: https://vpuniverse.com/files/file/15020-stranger-things-4-puppack/

**Expected behavior**
The Pupflasher and the Background music should work in VPX-GL 64bit too.

**Versions & Settings**
 - VPX: "VPinballX_GL-10.8.0-1367-fc71d22-Release-win-x64"
 - "VPinballX_GL-10.8.0-1367-fc71d22-Release-win-x86"
 - Windows 10 Pro 22H2 64bit
 - Intel(R) Core(TM) i7-7700K, 32GB RAM, RTX 3080TI

**Additional context**

[VPinballX.log](https://github.com/vpinball/vpinball/files/12434258/VPinballX.log)
[vpinball32bit.log](https://github.com/vpinball/vpinball/files/12434298/vpinball32bit.log)
[vpinball64bit.log](https://github.com/vpinball/vpinball/files/12434300/vpinball64bit.log)

**Comment by vbousquet** [comment]
The report shows that you have a problem with the other parts of your setup (B2S, PUP) when using x64 version, not VPX. I will close. You may find help on forums like VPForums or VPUniverse
