### ISSUE TITLE
DirectX9 rendering not working with old PC

### ISSUE THREAD

**Issue by KrakenByteKraken** [vpinball/vpinball#693]
DirectX9 version is not rendering all elements in my old PC, the tables show partially in black. It happens from the first 10.8 I tried, VPX beta 3 (VPinballX-10.8.0-1271-71581f5-Release-win-x64) to last build (VPinballX-10.8.0-1367-fc71d22-Release-win-x64).

![imagen](https://github.com/vpinball/vpinball/assets/117071087/c410e67e-4867-4cae-beb4-cce011e371d4)

Istead, it works perfectly, without any bug, in OpenGL flavor (VPinballX_GL-10.8.0-1367-fc71d22-Release-win-x64) and also fine in previous version 10.7.4 beta (VPinballX-10.7.4-410-08587fa-Release-win-x64).

![imagen](https://github.com/vpinball/vpinball/assets/117071087/453d3281-4106-4e3c-be69-0d623808490f)

I'm asking me if it could be a drivers problem because this PC runs with an old AMD Radeon HD 6870 GPU and stays with the last published driver because there is no support from 2015.

![imagen](https://github.com/vpinball/vpinball/assets/117071087/24b1a5b8-29b4-466d-af15-674ce917fb61)

In the other hand, the PC of my cab with a RTX 2080 SUPER runs all VPX versions at 4K resolution flawlessy.

**Comment by toxieainc** [comment]
Could you please post the video settings for both 10.7.4 beta and 10.8.0 beta?

**Comment by KrakenByteKraken** [comment]
Of course, I do. I hope this can help. I supose they're so similar settings:

**10.7.4 beta video settings:**

![imagen](https://github.com/vpinball/vpinball/assets/117071087/abff35eb-16ca-44df-8890-bc1807176762)


**10.8.0 beta video settings:**

![imagen](https://github.com/vpinball/vpinball/assets/117071087/e7a5e0a3-5b94-4a5c-aa97-0552d4b24288)

I also tried other values in the 10.8.0 playfield reflections section with the same sad results, and with 'force exclusive full screen mode' nothing to do either.

**Comment by toxieainc** [comment]
Playfield reflections would have been my guess, yes, but as you already tried these.. ..
Then most likely this is due to VPX.8 using more 'modern' concepts than VPX.7 in DX9, which maybe that old Radeon driver still had bugs with?

**Comment by KrakenByteKraken** [comment]
I bet it's something like that, yeah. Okay, thanks anyway.

So I'll play OpenGL version 10.8.0 on this old computer, at least until that part of their old drivers keeps working.

**Comment by DanRoid** [comment]
Don't you need to select Alternative Depth Buffer processing for AMD graphics cards?

**Comment by KrakenByteKraken** [comment]
I tried, thanks for the idea, but unsuccessful with same results.

**Comment by KrakenByteKraken** [comment]
Finally, it works in DX11 throughout the new **VPinballX BGFX64** flavor (VPinballX_BGFX-10.8.1-2602-484830d-Release-win-x64), so I close this issue.

![VPinballX BGFX64](https://github.com/user-attachments/assets/c12253b5-e688-4258-9b8e-754d0cfeeade)

I'm happy because **DirectX 11** gives me better performance that previous **DirectX 9**, an oldie now, but I'll try it also with **DirectX 12** when it becomes available.

Thank you to all involved in this amazing hobby, you guys are awesome!!!
