### ISSUE TITLE
Add confirmation message after saving POV in Adjust Camera mode

### ISSUE THREAD

**Issue by KrakenByteKraken** [vpinball/vpinball#694]
The new Adjust Camera Mode menu is amazing and I also love the new 'Window' view feature but, please...

Could you add a confirmation message that appears after pressing the save key to know that the POV file is perfectly stored?

It could be simply something like 'POV is exported, press any key to continue' showed in the display, and then all we'll be in peace and calmed because the hard work is saved and we know it's OK.

In the same way, if you consider, it could be interesting add other messages after pressing the other options like:

- Default POV values reseted, press any key to continue.
- Old POV values restored, press any key to continue.
- POV is exported, press any key to continue.

**Comment by gjupp** [comment]
Good idea, I noticed the same thing today when saving the POV and had to go an manually check the folder to see if it had actually saved.

**Comment by bele20097** [comment]
Good idea. This would be a geat feedback for the user, I am never sure it is saved so I end up hitting START multiple time.

**Comment by KrakenByteKraken** [comment]
Thankyou! 👏👏👏👏😀

**Comment by bele20097** [comment]
Awesome. Thanks to all ;-)
