### ISSUE TITLE
Alt Tab to view windows F1, F2, etc.

### ISSUE THREAD

**Issue by aerao** [vpinball/vpinball#697]
Hello!
I don't know if it's a bug or not, but I didn't have this problem on VPX versions 10.8b3 and 10.8b4.

When the table is launched, **since the update to beta 5**, when I press F1-F2, F4...., the windows don't appear, I have to alt tab to see them.

I've tried checking the "force exclusive full mode" box in VPX, but it doesn't change anything, it's even worse.
=> I'm still forced to alt-tab, and despite the apparent window, the mouse no longer interacts with the window. It's as if (the window) were still behind the table.

Thx

**Comment by aerao** [comment]
> make sure you update the scripts. That fixed the mouse missing in the F1 menu for me.

Would it be possible to know how to update the scripts please?
I can't figure out where to find them.
THX

**Comment by francisdb** [comment]
They should come with the download of vpinball.

**Comment by aerao** [comment]
> They should come with the download of vpinball.

I had already replaced all the old files with all the files contained in the Vpx8b5 .zip file, and it doesn't change.
If I do the same thing again, using the VPX8 beta 4 version, the problem disappears and the windows are displayed correctly.

I don't have this problem when I upgrade to beta 5.

**Comment by francisdb** [comment]
Now that I think about it I had the same issue yesterday on my cab, but I think F1 showed the dialog and then F2 did not show it any more. Wonder if I was starting the table through popper or not.

**Comment by vbousquet** [comment]
The keyboard should bne good now. The only problem you may have is pop up not being displayed in front of VPX if exclusive mode is used or when using OpenGL (this one depends on system setup and is tracked in another issue). Therefore I will close for now. Just tell us if it's still not ok for you
