### ISSUE TITLE
POV editor resets previously saved "Window" POV settings

### ISSUE THREAD

**Issue by bhamscott** [vpinball/vpinball#698]
**Describe the bug**
In the 64bit VPX DX and GL builds, once you have created a custom .pov for a table, if you then later try to do a live edit on the POV (for example, by clicking "Q" and selecting the "Adjust Camera"), the POV editor, once open, appears to not recognize the previously saved values.

**To Reproduce**
1. Go to 'Open a table and click Play'
2. Click on 'Q', make menu selection to enter the live POV editor and choose "Window' to create a new POV. Once done changing the settings to your liking, click the "Start" button to save the pov and then Exit from the POV editor and resume the table, or close the table, it does not matter here.
3. Repeat Step 1 and 2 and notice that the POV settings you previously saved are no longer recognized. For example, the table resets to 120% scale.
4. After step 3 if you close the table **without saving any values** (via Start button), it does appear that when you reopen it to play, your prior POV settings from step 1 are still there, its just that the POV editor does not apparently recognize that you have a .pov file or prehaps if it does it incorrectly parses that file.

The bug appears in almost every game I have tested. It does not appear to be specific to a game or games. For example, I tested Batman 66, GOTG, The Simpsons Pinball Party, to name a few and each of these tables were subjected to the bug.

**Expected behavior**
Once you have saved a POV for a given table, you may want to go back and tweak one or more settings for that POV. You should expect the POV live editor to respect those settings each time you open it.

**Screenshots**
Can provide if needed

**Crash dump**
The bug does not cause the program to crash.

**Versions & Settings**
 - VPX: 64bit Beta 10.8 revision 1347 (DX), 1370 (DX and GL)
 - Windows 11 Home
 - Nvidia RTX 3070 Ti FE. CPU is Ryzen 5 3600, MB is MSI Mortar, 16mb Ram
 - Settings log file is below
 
**Additional context**
I've observed the bug beginning in 64bit version 10.8 beta release 1367 through current. I have not tested 32bit versions.

**Comment by bhamscott** [comment]
[VPinballX.log](https://github.com/vpinball/vpinball/files/12457249/VPinballX.log)

**Comment by bhamscott** [comment]
@vbousquet is this a valid defect or perhaps I'm just doing it wrong?
PS: Amazing work on the 3D Stereo updates. Opens up a whole new means to enjoy the hobby.

**Comment by bhamscott** [comment]
Apparently this is how it was designed to work.

**Comment by vbousquet** [comment]
I have been testing the POV tools (F6 or live UI) and they both behave as expected. There used to be a bug with accessing the camera edit from the LiveUI and I think this is what you are refering here. Anyway, it is solved now.
