### ISSUE TITLE
Anaglyph 3D support for Trioviz Inficolor glasses.

### ISSUE THREAD

**Issue by gjupp** [vpinball/vpinball#709]
Currently we have an inbuilt 3D option for Magenta/Green and Green/Magenta however it is my understanding that Trioviz Inficolor glasses use a slightly more muted variation of these colours in their lenses and hence the existing options lead to ghosting. The lens orientation of Trioviz is magenta on left eye and green on right eye.

Whilst it may be too much work to add the full extent of the inficolor system (the reshade/Depth3D options for inficolor seem very extensive), it would be beneficial if we could please have a more closely matched 3D option for the colouring of these glasses.

It's possible that the colour values are exposed for viewing in the SuperDepth3D.fx shader file if the information proves difficult to otherwise find. Or perhaps a conversation with Blueskydefender (Depth3D coder) regarding the topic might prove fruitful. Ivite for Discord channel for Depth3D at https://discord.gg/pzdqKWEb  (expires 7 days).

Trioviz do seem to offer excellent colour reproduction, the best of all anaglyph 3D glasses in my opinion. They are also brighter than others and the physical quality of the genuine glasses seem good. They also fit over eye glasses.

Perhaps a per eye adjustment for colour tint/saturation might be useful but I'm not really sure exactly. I'm also not sure if the existing saturation option helps as I'm unable to test GL VPX at this stage.

**Comment by DanLShane** [comment]
I'll add my +1 to this request.  The Trioviz glasses are the most comfortable anaglyph specs of the dozens I own, especially wearing over my prescription glasses. As stated in the above request, the full-color pass-thru far exceeds any other 2-color format (except perhaps Colorcode, though it's much too dark to be practical). If the anaglyph crosstalk/blur was improved, it would be virtually perfect as an affordable way to render 3D for extended play.

**Comment by bhamscott** [comment]
I have the Trioviz magenta/green glasses. I was having good results on builds before 1381 using the magenta/green profile with both deghosted and dubois filters.
However, now with version 1381, the profile has gone kinda wack. Some filter combinations actually appear to reverse the Z depth! I'm sure this can be resolved but its kinda a mess at the moment for those of us who love the wide color gamut of the Trioviz glasses.

**Comment by bhamscott** [comment]
@DanLShane I completely agree with your comments. The color spectrum of the Trioviz glasses is excellent, but with the GL 10.8 it just comes at the expense of whatever term you want to use for fringing, crosstalk, or blur. Its basically misalignment of the stereo overlap.
Dial that in and the Trioviz glasses rock with VPX 10.8 GL

**Comment by gjupp** [comment]
> @DanLShane I completely agree with your comments. The color spectrum of the Trioviz glasses is excellent, but with the GL 10.8 it just comes at the expense of whatever term you want to use for fringing, crosstalk, or blur. Its basically misalignment of the stereo overlap. Dial that in and the Trioviz glasses rock with VPX 10.8 GL

Are you saying you have been able to dial in the Trioviz successfully, or that it would rock if it were possible?

**Comment by vbousquet** [comment]
This is now possible, suing the calibration feature of the new anaglyph implementation.
