### ISSUE TITLE
NVAPI issue since latest update(s)

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpinball#72]
**Describe the bug**
@vbousquet Please see https://www.vpforums.org/index.php?showtopic=44135&page=166#entry502502

**Comment by wiesshund** [comment]
You get a series of 4 NVAPI errors on table launch
None of the errors are legible, filled with random symbols

You get 4 more NVAPI errors trying to exit
same problem though, none of the errors are legible

Does NOT happen on a generic intel onboard GPU (HD4000)

Do not have an Nvidia card to test with

Does happen on AMD GPU

**Comment by toxieainc** [comment]
@wiesshund Can you please verify on your setup again? Thanks!

**Comment by vbousquet** [comment]
Sorry, was away for the week and did not have time to handle this bug I created with my latest changes. Thanks for doing it!

**Comment by toxieainc** [comment]
No hurry, this is all a hobby after all.  :)
And i had some spare time to look into it, no prob.
