### ISSUE TITLE
Not applying `MaxTexDimension` from .ini file for a specific table

### ISSUE THREAD

**Issue by julianmrodri** [vpinball/vpinball#721]
**Describe the bug**

In 10.8, you can define a version of the `vpinballx.ini`  for each table, by setting the file to the Table name and placing it in the `tables` folder.

However if you do it for the `MaxTexDimension` (under Video Options) and set for example the value to 0 in the ini file, this is not being applied when you run the table.

If you go to the Settings in `VPX` you will see that it is correctly set to the value from the ini file, but for some reason IT IS NOT APPLIED when you start the table.

**To Reproduce**
1. Create a .ini file for any table, place it in the `tables` folder
2. Modify `MaxTexDimension` to any value
3. Open the table with VPX 10.8,. you will see that in Preference/Video Options the correct value is picked up from the file
4. Run the table.. the value is NOT APPLIED! and opens with the previous/default setting instead.

**Comment by gitbittidbit** [comment]
I can report I am also experiencing the same exact issue.

**Comment by lminimart** [comment]
Also seeing this bug.

**Comment by julianmrodri** [comment]
I think this is likely a cache issue. Even in some situation within VPX no I switch to Unlimited, start the table and remains in the previous quality which was 2K. This is weird, but there seems to be a cache that is ignoring whatever setting is there in VPX (wether it comes from the ini file or manual setup).

**Comment by lminimart** [comment]
When doing it manually, I find you have to set it, exit VPX, and then restart VPX and the setting usually "takes."

**Comment by gitbittidbit** [comment]
i think this is becoming a really important issue. especially because with x64 tables from VPW, they're using 8K texture sizes now. for some tables i'd like to increase maxtexdimension (so it's not blurry), but not for all because it can reduce performance.

**Comment by vbousquet** [comment]
This has been fixed by latest changes to the user setting system
