### ISSUE TITLE
GL Anaglyph 1392: Eye contrast settings not usable outside of deghost filter

### ISSUE THREAD

**Issue by Billiam** [vpinball/vpinball#725]
**Describe the bug**

When the Debois or None filters are selected, the behavior of the individual eye contrast settings changes pretty radically, compared to when deghost is selected.

I feel like the contrast settings are working the way I'd hope/expect with deghost and that the behavior in the other two modes is incorrect.

Affects all glasses colors

**To Reproduce**

With Red/Cyan glasses (as an example):

1. In the live editor, select the Deghost filter
2. Turn left-eye contrast down to 0.9
3. Observe left eye contrast (red) has been reduced, which generally helps with ghosting in dark areas (depending on scene/colors, etc)
4. Change filter to none or dubois
5. Observe entire screen, including black backgrounds, now has a red overlay.

At contrast 0.0, the entire screen is a uniform red.

**Expected behavior**

Eye contrast works similarly in all modes.

**Screenshots**

### Deghost filter
Photo through cyan lens with default contrast
![PXL_20230902_235121303](https://github.com/vpinball/vpinball/assets/242008/72eccc25-7165-42e4-8190-8cb81a1eaf6c)

Photo through cyan lens with reduced contrast
![PXL_20230902_235132120](https://github.com/vpinball/vpinball/assets/242008/49612b35-30eb-4e4c-88f2-cb3bc09d4071)

## No filter

Photo through cyan lens with reduced contrast

![PXL_20230902_235214442](https://github.com/vpinball/vpinball/assets/242008/48f05b2c-b8a4-49f9-bbb2-db2150e2a015)

Screenshot with reduced contrast, showing overlay-like behavior

![VPinballX_GL_1DeyK3Szax](https://github.com/vpinball/vpinball/assets/242008/7fd7a8e9-46bf-4a7a-b7ac-f4bc29adbe40)

**Versions & Settings**
 - VPX: 10.8.0 Beta (Revision 1392 (f915f95), 32bit)

**Comment by vbousquet** [comment]
This has been reimplemented and should be fixed now.
