### ISSUE TITLE
POV menu is rotated 90 degrees. hard to see it cabinet now

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#726]
**Describe the bug**
Since one of the latest releases of 10.8, the POV menu is rotated 90 degrees and makes it hard to read on cabinet
How can I change the menu to rotate, so I can see it when standing in front of my table ?
![image](https://github.com/vpinball/vpinball/assets/48748234/241848d3-0833-41fe-bb71-412cea1c8057)
I'm on 10.8 Rev 1392

**Comment by Loafmeister** [comment]
FYI on 1392, this bug appears to only be in the GL build, not the DX build

**Comment by MikedaSpike** [comment]
I need to recheck, but thought i tested on dx version.
