### ISSUE TITLE
Ball anti stretch does not seem to work in build 1392 for head tracking 

### ISSUE THREAD

**Issue by Loafmeister** [vpinball/vpinball#729]
Possibly tied to the new scale centric renderer, when using 10.8 gl and dx 1393 builds using head tracking, the ball shows up as oval even with the scale set to 1 for all 3 axis .  Any number higher than 1 and it is much worse 

![IMG_7045](https://github.com/vpinball/vpinball/assets/60628625/5359e9c4-984d-4fd8-bc1a-777bef9abb03)
![IMG_7046](https://github.com/vpinball/vpinball/assets/60628625/373a94ed-b2be-4129-a823-de2295d0f5e9)
![IMG_7044](https://github.com/vpinball/vpinball/assets/60628625/f67bf12e-5aa8-449e-b36e-421b57d73767)

**Versions & Settings**
 - VPX: beta build 1392 gl or dx
 - Windows version

**Comment by vbousquet** [comment]
Just pushed teh fix for this: https://github.com/vpinball/vpinball/commit/755105260b63369774a1874bd5b79f11716e662c

**Comment by Loafmeister** [comment]
Thanks I will go test shortly

**Comment by Loafmeister** [comment]
Shortly wasn't so shortly, apologies :).  Just wanted to say it now works just lovely!  Thanks
