### ISSUE TITLE
Green-Magenta setting applies instead of Blue-Amber.

### ISSUE THREAD

**Issue by workerb0y** [vpinball/vpinball#732]
In the latest working version (rev1392) 10.8, if I set the 3d to Blue-Amber glasses in the VPX graphics menu, during the game, for some reason, it changes the image according to the Green-Magenta glasses. This way, the 3d effect is incredibly beautiful, but unfortunately not with the blue-amber but with the green-magenta glasses. It's as if blue-amber is missing and the program displays green-magenta instead.

1. Go to VPX Graphics settings
2. Click on 3d settings, set Blue-Amber glasses
3. Load the table and turn on 3d (F10)
4. See the attached photo.

Versions & Settings
 - VPX: 10.8 beta revision 1392 (both DX and GL).
 - Windows 10 Pro 64 bit
 - GPU NVidia 3070 8gb, CPU i5 10400f

![a20230903_133017](https://github.com/vpinball/vpinball/assets/87616502/e56a14ea-f7d6-4373-b837-1afde56df03f)

**Comment by vbousquet** [comment]
Fixed in latest
