### ISSUE TITLE
Live editor moving camera away from centre point

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#743]
**Is your feature request related to a problem? Please describe.**
Not a problem.
I love the live editor added to 10.8. It makes it much easier (for me) to edit a (VR) table
But 1 thing that is bugging me, is that the camera is centered to the table, so no good "fly over"
When making VR room, it would be a 'nice to have' that the camera can be changed from center view as well, so you can zoom into an object on PF or backglass.

**Describe the solution you'd like**
using cursor keys to move the center point of view the camer. this will make it easier to focus on an object itself

**Comment by vbousquet** [comment]
It's already possible and described in the docs: https://github.com/vpinball/vpinball/blob/master/docs/LiveUI.md

**Comment by MikedaSpike** [comment]
Damned ! Sorry Vincent. I should have knows this earlier !
