### ISSUE TITLE
render UI in VR Headset-displaying below viewing area in HMD

### ISSUE THREAD

**Issue by RGYsr** [vpinball/vpinball#744]
I noticed that the render UI in VR Headset has been addressed on GitHub.  (Thank You). I tried VPinballX_GL-10.8.0-1392-f915f95-Release-win-x64 also tried ver 1408. The UI displays at the bottom left of the headset below viewing area, only about the top 10% is visible. I'm using steam and a Valve Index headset. However It looks centered on the cabinet display. Is there anyway to center it in the HMD?

**Comment by TurboHenk** [comment]
I have the same issue with my Pimax Crystal. 

It's not visible in VR at all; it's that far away in the corner it could only be seen in the mirror of PimaxXR (because the VPX mirror doesn't work see open issue #605). Thanks for your great work!
