### ISSUE TITLE
External DMD issue under 32 and 64 bit

### ISSUE THREAD

**Issue by msfree** [vpinball/vpinball#745]
Hi

VPX 10.8.0-1408 is installed.
WIN10 PRO

My configuration:
32" playfield monitor
19" backglass monitor
PC:
- i5-6400 CPU 2.7 GHz 
- Nvidia Geforce GTX 1500 Ti GPU 
- 16 GB RAM
- 500 GB SSD + 500 GB HDD

My problem:
I am using virtual DMD on the 2nd monitor.

When I run VPX GL in 32 bit and open a table using normal VPMDmd, the DMD appears on screen 2. This is the good monitor, but when I save the DMD position as global setting, the DmdDevice64.dll file size decreases from 12.33 Mbytes to 3 bytes.
When I open a table using FLEX DMD, the DMD is displayed on monitor 1. I moved it to monitor 2 and then save globally. Then the size of the DmdDevice64.dll file changes from 3 bytes to 277 bytes. For both table, the next time I start the DMD, it appears on monitor 2.

When running the 64 bit version (GL64) on a normal table, the DMD does not appear on screen 2 but on screen 1. If I reload and save the global setting, the DmdDevice64.dll file size does not change (remains 12.33 Mb) and the next time I start the DMD will be displayed correctly on screen 2. After closing the board, the DMD will close.

If I open a table using FLEXDMD in 64 bit version, the DMD will be displayed on screen 1. I move it to screen 2, save it as global setting. At this point the DmdDevice64.dll file size does not change (remains 12.33 Mb) and the next time I start the DMD it will reappear on screen 1. After closing the board the DMD does not close.

[ini and log.zip](https://github.com/vpinball/vpinball/files/12515202/ini.and.log.zip)

**Comment by vbousquet** [comment]
This is related to FlexDMD/FreezyDMD, not VPX. You may find help in the community sites like VPForum or VPUniverse
