### ISSUE TITLE
Rendering issues since 10.8 (rev1411) 

### ISSUE THREAD

**Issue by Jayhay89** [vpinball/vpinball#748]
Rendering issues (lighting) 10.8 rev 1411 Direct X
See comparison images below:

Cirqus Voltaire (Knorr) 10.8 (rev1411):
![image](https://github.com/vpinball/vpinball/assets/86264211/126b34c8-7f64-4463-9586-67f8de5bfb1a)

Cirqus Voltaire (Knorr) 10.7.4:
![image](https://github.com/vpinball/vpinball/assets/86264211/5f2b14c9-01de-4aa7-b91b-9b6051d9123f)

Lighting seem broken on Right Sideblade

**Comment by greatflash** [comment]
This varies by degrees depending on the table, using this table is a no go (though there are others nearly as bad) [https://vpuniverse.com/files/file/7189-viper-night-drivin-sega-1998/](url)

On 10.8.0.1 it is fine, 10.8.0.2 and up is terrible. This can be fixed (in my case) by turning reflections to "Ball only", but of course at a loss of quality.
![normal](https://github.com/vpinball/vpinball/assets/37930897/629ce362-e22a-4159-9f6f-816db48a54e3)

and on 10.8.0.2+

![bloom](https://github.com/vpinball/vpinball/assets/37930897/bc514238-3c06-4230-aae2-2cb7b45cb7db)

This is with an RDNA2 chipset, a gtx 1060, and a grx 3060, all with latest drivers etc.
