### ISSUE TITLE
Ball Trails cause white flashes

### ISSUE THREAD

**Issue by vbousquet** [vpinball/vpinball#749]
Up to VPX 10.8 v1048, seen at least for DX version

**Comment by Jayhay89** [comment]
@vbousquet 
Yes, was about to add this to the Cirqus Voltaire lighting issues. Though white lines appear across the screen when flashers go off

**Comment by francisdb** [comment]
Is this the same issue?

https://github.com/jsm174/vpx-standalone-scripts/issues/23#issuecomment-1603849190
