### ISSUE TITLE
Frame pacing frame drop on some tables

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#755]
Describe the bug
Some tables don't work well when "FRAME PACING" is activated. For instance, in "Theatre of magic", even without launching the ball, there is a severe drop in frames per second.

It seems that some flashers cause this issue.

To Reproduce

In Video/Graphics Options, set Video Synchronization to "Frame Pacing"
Open the table Theater of magic 
https://www.vpforums.org/index.php?app=downloads&showfile=14817
Press F11 and check the frame rate. Also if you play the table you will experience severe stuttering (unplayable).
The table plays well with frame pacing turned off.

CPU Ryzen 5
GPU RTX3080

Versions & Settings

VPX: 10.8 64bits GL Revision 1414

----

As always, thanks for your awesome work.

**Comment by dacstyle** [comment]
another table with the same problem https://vpuniverse.com/files/file/8152-class-of-1812-gottlieb-1991-w-vr-room/

**Comment by bhamscott** [comment]
I have similar issue with all tables. Ball stutters as if 10-15 fps but readout indicates 90 fps.
GPU is RTX 3070 Ti Founders Edition
Ryzen 5 3600
Asus 43" 4K 144hz with 10 bit color enabled.
When using Frame Pacing I have "0" for both inputs (FPS and Prerendered frames)
Using any sync option except Frame Pacing results in smooth, fluid ball motion with no stuttering and very good flipper response.
Frame Pacing enabed is unplayable.

As always, your work is incredibly appreciated. Love where you are taking VPX.

**Comment by Spacegoogie** [comment]
I know this is older but I'm running VPX GL-10.8.0-1629 and the same for me, I do now however also notice shutter anytime flashers go off.

**Comment by toddsay** [comment]
In case it helps, I tried my Volkan test (frame pacing at 60) on some older VPX 10.8 versions. I tried builds 1348, 1360, 1606, 1722. Of those, only the oldest (1348) gave me normal frame rates (low 30's in my case). All the others gave me a frame rate around 1.6.

That table does have flashers going off (mostly virtual flashers), so perhaps that is related.

**Comment by vbousquet** [comment]
After checking, the problem is on the table side, not VPX. The table has a lot of timers expected to be ran every 1ms. When running in Frame Pacing mode, most of these will be honored causing lags. The tables have to be fixed or just don't use Frame Pacing with these tables

**Comment by toddsay** [comment]
Huh, interesting. So Frame Pacing is able to give the table way more cycles than before. Makes me wonder how many tables are abusing timers in that way. Maybe there should be a limit to how often those timers are allowed to run. But anyway...

Thanks!
