### ISSUE TITLE
VR tables in versions after v1408 64bit do not work due to shader errors.

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpinball#756]
**Describe the bug**
Versions till v1408 in 64bit works in VR.
After that version v1410-v1414 doesn't work, because after the start there are shader errors and VPX crashed.

**To Reproduce**
Open a table in VPinballX_GL v1410 64bit or later and load a table.
Start the table.
Shader errors occure.

**Comment by studlygoorite** [comment]
I see the same issue, thanks for posting, going back to v1408

**Comment by toxieainc** [comment]
Usual question: Did you guys also update all shader files?

**Comment by vbousquet** [comment]
No, that's me :)

I have the fix, just working on a branch (full rewrite of anaglyph), I will push the fix just after.

**Comment by vbousquet** [comment]
This is now fixed, so closing
