### ISSUE TITLE
Can't access Environment Emmision setting when editing POV like it was possible in 10.7

### ISSUE THREAD

**Issue by lukpcn** [vpinball/vpinball#757]
**Describe the bug**
Can't access Environment Emmision setting when editing POV like it was possible in 10.7
I go into POV Edit Window mode and trying to switch to that setting but can't reach it.
for example on my OLED screen most of the tables are too bright so I make them darker with that, 
there Was no problem changing it in 10.7
here is a video me trying to get to this setting: https://1drv.ms/v/s!AszhfOiAjudYg6QL2mH0UQSfU8Egkg?e=gVUUdK

**To Reproduce**
Run Table in POV Edit mode, try to set this settings, try to select it with magna save buttons.
Tested on couple of 10.7 tables and on 10.8 one (Johny Mnemonic VPW laters)

**Expected behavior**
Possibility to change this setting as it was in 10.7

**Screenshots**
here is a video me trying to get to this setting: https://1drv.ms/v/s!AszhfOiAjudYg6QL2mH0UQSfU8Egkg?e=gVUUdK

**Versions & Settings**
VPX 10.8 rev 1414
 - Windows 10
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**
[VPinballX.zip](https://github.com/vpinball/vpinball/files/12547931/VPinballX.zip)

**Comment by Drybonz** [comment]
Starting in a recent 10.8 build (not sure which one exactly, sorry) environment emission is not a selectable option in the legacy camera/light editor.

**Comment by lukpcn** [comment]
But why ? It is really important to be able to alter that setting, is it gonna be available ?

**Comment by Drybonz** [comment]
Yes... I'm echoing your initial bug report so they know more than one person is having the problem.  I'm not a developer... I'm just a guy with the same problem you are having.

**Comment by vbousquet** [comment]
It was a bug and it should be fixed now. Can you confirm that this is ok in the latest (not the beta, but the one from you can download from the action build) ?

**Comment by Drybonz** [comment]
Vbousquet... just check this in build 1419, and it is working properly.  Thank you for the quick fix.
