### ISSUE TITLE
Game Name cannot be found on certain Pup pack tables on 64 Bit VPX

### ISSUE THREAD

**Issue by bossman500** [vpinball/vpinball#760]
I have spent quite a bit of time going through my library trying out various VPX tables top compare 64 bit compatibility. 

My setup is very current and it needs to be to have 64 bit run correctly.

 

VPinMAME-sc-3.6-573-5d6459d-win-x64

dmdext-v2.2.0-x64

x64_dmd-extensions_with_pin2color_and_serum_plugin

VPinballX-10.8.0-1347-3d585e7-Release-win-x64

FlexDMD 1.9

 

So out of the 500 VPX tables I tried, these are the ones that still only run in 32 bit.

 

Superman (puppack)

Jeckyl and Hyde (puppack)

Dukes of Hazard (puppack)

Hateful 8 (puppack)

Logan's Run (puppack)

Gunship (puppack)
 

They all act similar and can't find the Game Name when starting up.(64 bit)

Cliffy has an older version of VPX 8 and he seems to not have the problem (64 bit).  Not sure it is VPX or another module......

**Comment by passionforpins** [comment]
actually I always have the newest beta versions of vpx 10.8 betas and for myself I have no problems with logans run nor superman with pups. I do not have those other tables. I run desktop only and always use the latest vpinmame-sc as well. Having the parent rom and proper vpmalias.txt is key when it comes to gamename not found errors. 
Best of luck, bossman500

**Comment by Loafmeister** [comment]
Gunship’s latest update works with vp10.8 (build from earlier this week) as I played it last night

the only pup I’ve not been able to get working so far is tron legacy. I thought I’d heard that’s a known issue

**Comment by toxieainc** [comment]
Also this, if at all, would be a PinMAME issue, so closing.
But i think the vpmalias comment should do the trick.

**Comment by bossman500** [comment]
I know this ticket is closed, but I successfully got the 64 bit versions of those tables to run by using a previous version of VPinMAME.  I installed an older version of VPinMAME..... No changes were made to the VPMalias.txt file. 

"VPinMAME-sc-3.6-369-102e419-win-x64" does work correctly.

The latest release "VPinMAME-sc-3.6-573-5d6459d-win-x64" does not work correctly for the previously mentioned (puppack) tables. 

I did not try the 64 bit release in between those two versions to see if it worked for those particular puppack tables.

Not sure what is going on, just reporting results

Thanks for your help and hard work.!

**Comment by toxieainc** [comment]
Did you run setup64.exe -> install for the newer version?

**Comment by lukpcn** [comment]
Did You instal 64bit patch for pinup ?
https://nailbuster.com/pinupdates/PinUPSystem_x64_drivers_v1_beta.zip

**Comment by bossman500** [comment]
Yes, I ran both the 32 bit and 64 bit setups.  
It looks like I installed the 64 bit patch for pinup on 8/31/2023 and the latest zip file size matches the one I downloaded the 31st. 
I will try the 2nd to last beta to see if that works for those particular tables.  (the rest of my collection works great with the newest beta!)

**Comment by bossman500** [comment]
I tried v3.6-488-980d8e3 and I had no problems.  So, I am going to try the last beta again to verify that it does not work.

**Comment by droscoe** [comment]
This still sounds like a VPinMAME issue, should be an issue created there

**Comment by vbousquet** [comment]
Since this issue is entirely linked to PinMame and not VPX, I will close here. Please open on PinMame project (https://github.com/vpinball/pinmame) if you are still experiencing this issue.
