### ISSUE TITLE
MSCOMM

### ISSUE THREAD

**Issue by shinobisan786** [vpinball/vpinball#761]
Adding 

Dim MSComm1
Set MSComm1 = CreateObject("MSCommLib.MSComm")
MSComm1.CommPort = 4 ' Set the COM port number   ARDUINO LAM BOARD
MSComm1.Settings = "115200,N,8,1" ' Set the baud rate, parity, data bits, and stop bits
MSComm1.PortOpen = True ' Open the serial port

No longer works to open comm port from within the table script...both 32 and 64 bit...Worked fine in previous versions.
We need an example of how its done now please...A sample of the methods used. The Flasher boards I've made and others no longer work.
Release 10.8 is the future on VPX...This simple comm method change has completely destroyed the use of our boards.

**Comment by toxieainc** [comment]
There is no explicit support or not for that interface, its just VBS itself. Are you sure this is not a general windows issue nowadays?
Does this still work in 10.7.X on the exact same setup?

Apart from that, VPX offers also an interface for serial communication, see CommandReference.txt:

```
GetSerialDevices(strings) - returns all serial communication port names
OpenSerial(string) - open serial communication for port 'name'
CloseSerial - close serial communication
FlushSerial - flush
SetupSerial(int baud, int bits, int parity, int stopbit, VARIANT_BOOL rts, VARIANT_BOOL dtr) - setup the parameters of the serial communication
ReadSerial(int size, VARIANT pVal) - read size bytes
WriteSerial(VARIANT pVal) - write bytes
```

Would that also work?

**Comment by shinobisan786** [comment]
"Does this still work in 10.7.X on the exact same setup?"

Yes it does.

Does'nt even throw an error...Does nothing...loads the table as normal...Does not connect to the board at all...In 10.7 it does.

**Comment by shinobisan786** [comment]
Ok I can confirm the code I've used originally Works on the 
(VPinballX-10.8.0-1347-3d585e7-Release-win-x86.zip)
32bit version

but Not on the
(VPinballX-10.8.0-1347-3d585e7-Release-win-x64.zip)
64bit version

**Comment by toxieainc** [comment]
That explains it.. So you'd have to use a 64bit variant maybe? Or the new internal functions i described above..
