### ISSUE TITLE
10.8 beta 5. command line -DisableTrueFullscreen doesn't seem to work

### ISSUE THREAD

**Issue by gitbittidbit** [vpinball/vpinball#762]
**Describe the bug**
-DisableTrueFullscreen command line argument doesn't seem to actually disable forced fullscreen. problem doesn't exist with 10.7.

**To Reproduce**
launch with command line argument -DisableTrueFullscreen

**Expected behavior**
expect forced fullscreen to be disabled.

**Versions & Settings**
 - VPX: 10.8 beta 5
 - Windows 10 x64

**Additional context**
10.7 doesn't have the problem.

**Comment by francisdb** [comment]
There was some related commit as we had a similar issue on standalone. (77a9273)

Have you tried the latest build?

**Comment by vbousquet** [comment]
This has been fixed and is fully working in latest versions, available from the action tab of github (but these are unstable version). This will be ok in the next beta
