### ISSUE TITLE
Cannot access environment emission

### ISSUE THREAD

**Issue by Pinbalbilly** [vpinball/vpinball#764]
Hello, in version 1420 I cannot access environmental emission.

**Comment by francisdb** [comment]
this is a duplicate of #757 which is already fixed

**Comment by francisdb** [comment]
ah no, that was 1419 where it was fixed?

**Comment by vbousquet** [comment]
I can not reproduce any problem on this. Using the absolute latest cna you circle all the options or not ? if not could you fill in a complete issue template (without this, there is no chance I can help or fix)

**Comment by Pinbalbilly** [comment]
> I can not reproduce any problem on this. Using the absolute latest cna you circle all the options or not ? if not could you fill in a complete issue template (without this, there is no chance I can help or fix)

**Comment by Pinbalbilly** [comment]
The problem is solved.  Thank you

**Comment by lukpcn** [comment]
Thanks a lot
