### ISSUE TITLE
Anaglyph luminance calibration is applied to wrong profile

### ISSUE THREAD

**Issue by Billiam** [vpinball/vpinball#766]
**Describe the bug**

Default VPinballX.ini, after launching once:

[VPinballX - Default.ini.txt](https://github.com/vpinball/vpinball/files/12566632/VPinballX.-.Default.ini.txt)

VPinballX, after enabling 3d, and calibrating the Custom 1 Profile:

[VPinballX - Incorrect.ini.txt](https://github.com/vpinball/vpinball/files/12566634/VPinballX.-.Incorrect.ini.txt)

**To Reproduce**

Steps to reproduce the behavior

Delete VPinballX.ini

1. Enable anaglyph 3d in video settings (cannot be done from live editor)
2. Launch game, open live editor
3. Select Custom 1 profile
5. Calibrate luminance for green/magenta glasses
6. Observe that color icons still appear red/cyan
7. Observe that playfield is using red/cyan color
8. Change profile to the default amber/blue profile
9. Observe that amber/blue has been calibrated as green/magenta

**Expected behavior**

Luminance calibration applies to currently selected profile

**Versions & Settings**
 - VPX: 10.8.0 (Revision 1420 (2a1d7ea), 64bit)

**Comment by bhamscott** [comment]
Great find @Billiam and thanks for quick fix @vbousquet 
What a great time to be a pinhead!
