### ISSUE TITLE
Modo cabinet

### ISSUE THREAD

**Issue by Pinbalbilly** [vpinball/vpinball#770]
Hello, in the latest versions to be able to launch the table in cabinet and POV window mode, I have seen that we have to change the rotation that we always had at 270 to 0, because if not, it runs rotated.  While legacy or camera mode if they are in cabinet mode with 270.

**Comment by vbousquet** [comment]
This is not a bug but the expected behavior. Window mode is aligned to the screen

**Comment by Pinbalbilly** [comment]
OK, many thanks for your response.
 Congratulations for all your work.

**Comment by studlygoorite** [comment]
If you are not aware, just hit the launch button to rotate the table and set up a new POV for these tables.

**Comment by Pinbalbilly** [comment]
> If you are not aware, just hit the launch button to rotate the table and set up a new POV for these tables.

Thanks
