### ISSUE TITLE
Refraction probe on plastics kills some insert lighting techniques (Star Light)

### ISSUE THREAD

**Issue by a-bord** [vpinball/vpinball#780]
When adding a refraction probe to the plastics of Star Light the inserts stop working properly.

To reproduce you can use this build of the table https://drive.google.com/open?id=15B-ghOaX_66SYbGCtCJ-xIfK4htLW1Qo&usp=drive_fs and turn the refraction probe on layer3plastic on and off. This was tested on two different systems to confirm. Using 10.8 rev 1347.

With refraction probe:
![image](https://github.com/vpinball/vpinball/assets/90645800/ecda40d4-47fb-4163-9a83-201cdb8bf83f)

Without refraction probe:
![image](https://github.com/vpinball/vpinball/assets/90645800/6df47a29-e4a4-4671-8783-7a846bb0d404)

**Comment by vbousquet** [comment]
Just tested (with latest, so quite a few fix since your report) and it did run well with and without refraction:
![image](https://github.com/vpinball/vpinball/assets/2796036/5b0fb696-9c45-45b5-a7b6-eeda27ea6e41)

Is the bug still active on your side with latest build ? If so, could you share your setting file as well ?

**Comment by a-bord** [comment]
@vbousquet This is still broken for me in F5 (play) with the most recent build. cb8e4d1

However, the inserts appear fine when in F6 mode.

![image](https://github.com/vpinball/vpinball/assets/90645800/4a4e263b-f802-4f96-bede-77fe73aaa0ce)

**Comment by vbousquet** [comment]
Could you share the ini file ? It allows to test with the same settings

**Comment by a-bord** [comment]
@vbousquet  How do I go about creating an ini file with my VPX settings?

**Comment by vbousquet** [comment]
It's already there. In 10.8, all settings are saved in an ini file (no more Windows registry). It is in your %AppData% folder under VpinballX subfolder
