### ISSUE TITLE
Hawkman (Taito 1983) and most of the Taito tables freeze and crash VPX when Quit

### ISSUE THREAD

**Issue by Mrtr32** [vpinball/vpinball#783]
This issues arrive with the latest build of VPX 1448 and somes of the previous builds

Somes of the others noticed table crash:

Lortium (Juegos Populares 1987)
Lunelle (Taito 1981)
Shock (Taito 1979)
Shark (Taito 1982)
Rally (Taito 1980)

The crash is intermittent
No crash dump file has been created by VPX

VPX8 x86 build 1448
B2SServer-2.0.4-ca459cc-Release-win-x86
VpinMAME 3.6 x86 build 607
dmdext-2.2.1-SNAPSHOT-r14

Thanks for all your work!

**Comment by gjupp** [comment]
Also experiencing many tables crashing (perhaps all)  on exit with DX9 1443 build. After pressing q q , the table seems to lock up and stays on screen, unable to Alt Tab back to desktop and need to Ctrl Alt Del to close it.

Interestingly I think this may only be happening if "Exclusive fullscreen" mode is set. I switched to "window" in graphics settings and the two tables I just tested closed correctly when I tested (same tables that had previously crashed on exit earlier).

**Comment by Mrtr32** [comment]
I never used « Exclusive full screen » on my test computer and my Cab.
I have over 1000 tables on my two setup and the issue seems to be related to Taito and Juegos Populares tables only.

**Comment by gjupp** [comment]
Hmm... might be a different bug then. I just updated to VPinballX-10.8.0-1450-f71a2a1-Release-win-x86 and still experiencing the issue when exiting a table in exclusive fullscreen mode. If I press CTRL alt del, the table will disappear off the screen without me having to actually close any process and I can get back to the VPX editor again, however if I attempt to start another table in fullscreen mode it crashes VPX with a video error.

**Comment by Mrtr32** [comment]
Rolling back to VPinballX-10.8.0-1347-3d585e7-Release-win-x86
VPinMAME-sc-3.6-560-350864b-win-x86
Same issue

**Comment by toxieainc** [comment]
What about 10.7.4 beta and VPM 3.5?

**Comment by Mrtr32** [comment]
Tested **VPinballX-10.7.4-417-5a3439f-Release-win-x86**
**VPinMAME-sc-3.6-607-51667e2-win-x86**
No Crash on exit issues anymore with all the Taito and and others tables mentioned at the previous post
This is not a **VPM** issue so a **VPX8** issue.

**Comment by passionforpins** [comment]
Can confirm with JP Salas Hawkman v4. I ran it with vpx 10.8 rev 1452 x86 and it played and closed fine but then ran it again with 10.8 rev 1452 x64 and it locked up on quitting. Had to hard close from task manager. No crash.txt was created.

I played Space Patrol Taito and it was ok in all versions of vpx 1097.4 and 10.8. No crash at all. 
[VPinballX.ini.txt](https://github.com/vpinball/vpinball/files/12666204/VPinballX.ini.txt)

**Comment by Mrtr32** [comment]
@passionforpins

The issue is intermittent, sometime it close properly and sometime not

**Comment by passionforpins** [comment]
Just had Hawkman totally lock up two times in a row with 10.8 x86. Definitely a vpx 10.8 problem with taito. 10.7.4 x64 no lockup at all after several tries

**Comment by Mrtr32** [comment]
I experiencing 1 time a process not responsive warning and not closing with the latest VPX 10.7.4 build  417 x86 so it seems more stable
The test table is Lunelle from Taito

**Comment by toxieainc** [comment]
What happens if you use VPM 3.5 though?

Also, could you try moving/deleting the corresponding Taito NVRAMs in the PinMAME/NVRAM directory to see if this has any influence?

**Comment by Mrtr32** [comment]
The nvram and cfg files removing test has been done without success

When i’m returning at home in evening I will test VPM 3.5

**Comment by passionforpins** [comment]
I just overwrote my vpinmame 3.6 with rev 3.5 release.
Ran Hawkman 8 times through with vpx 10.8 x86, x64 rev 1452 and 10.7.4 x86 and x64.
Zero problems closing with pinmame 3.5. Looks like you found it @toxieainc but I'll let the OP try it out and verify and if that's the case then he needs to create an issue on the pinmame side.

**Comment by Mrtr32** [comment]
Tested VPinMAME-sc-3.5-225-1e9f092-win-x86 with VPinballX-10.8.0-1452-db6787f-Release-win-x86 without success.
the Lunelle and Hawkman and the tables Freeze and crash VPX8 and a Warning VPX not responding appeare when quiting the table.

**Comment by passionforpins** [comment]
I used the non -sc version of vpinmame 3.5 from the release page and the Main zip here;
https://github.com/vpinball/pinmame/releases/download/v3.5-217-bd54096/Main.Download.-.VPinMAME35.zip

By the way, I just put back the latest 3.6 -sc vpinmame dll's and hawkman locked up on quit first try. Maybe we should try the non -sc 3.6 dll's?

**Comment by passionforpins** [comment]
Holy moly I think the SAM enabled -sc version is the problem. I just unzipped the latest  3.6 rev 607 non -sc vpinmame.dll and hawkaman ran and quite 4 times in a row no problem

**Comment by toxieainc** [comment]
Which would be completely weird though. I fear this is one of those nasty sideeffect-bugs then.

**Comment by toxieainc** [comment]
Closing here then.. Will continue in https://github.com/vpinball/pinmame/issues/162

**Comment by Mrtr32** [comment]
@passionforpins
I have the issue  #162 opened to pinmame github

**Comment by gjupp** [comment]
> @passionforpins I have the issue #162 opened to pinmame github

Looks like the link autogenerated for the VPX project instead of pinmame.

**Comment by toxieainc** [comment]
For future devs looking in here:
The solution was removal of an endless loop in the Taito scripts (so maybe some race condition or false assumption). See the link above for details.
