### ISSUE TITLE
10.8 rev 1445 missing options for 10bit color and max texture size

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#785]
10.8 rev 1445 missing options for 10bit color and 

**To Reproduce**
1. Go to 'video preferences'
Notice the options no longer present

**Expected behavior**
Expect to see force 10 bit color, as without it vpx seems to bounce back to 8 bit color even when monitor and os/driver are running in 10 bit

**Screenshots**
![image](https://github.com/vpinball/vpinball/assets/8684777/80f6880f-bdff-4c68-b079-0dafcd31d29a)

10.7 and previous 10.8 builds
![image](https://github.com/vpinball/vpinball/assets/8684777/803166b9-d89c-4539-adc5-4fa76e827a8e)

**Crash dump**
Not applicable

**Versions & Settings**
 - VPX: 10.8 rev 1445
 - Windows version 11 enterprise
 - GPU and video settings if applicable Radeon RX 6600

**Comment by vbousquet** [comment]
10 bit had always been only supported on fullscreen modes. So using fullscrene is needed for that.
It's just that it is more clear than it used to be.

Max texture dimension is exactly what it says.

**Comment by wiesshund** [comment]
max texture size i meant to edit out
apparently it did not

but 10bit color, there is no option for it
and it does not work, even with entire system running in 10bit color, vpx reverts to 8 bit
which it always did unless force was checked

im not taking about needing fullscreen mode, i already know that, the option is gone and you cant enable 10bit color

**Comment by wiesshund** [comment]
going to blow the whole thing out again prog ini registry and all, see if it makes any difference
