### ISSUE TITLE
Playfield not rendering (black screen) in VPX10.8 beta 4 and 5 (all tables)

### ISSUE THREAD

**Issue by k0uin** [vpinball/vpinball#786]
**Describe the bug**
Playfield not rendering (black screen) in VPX10.8 beta 4 and 5 (all tables). Ï am using the 64 bit versions under Windows 10. 

**To Reproduce**
Setup VPX 10.8 beta 5 on side on existing (working VPX 10.7.4, latest stable) 64 bit version.
Launch any table.
Menus are showing on the playfield (F1..editor menu..) and table plays (all features seems to be working, game can be started and all DOF, sounds and pinmame events seems to be working normally.
 
**Versions & Settings**
 - VPX: v10.8.0-1347-3d585e7
 - Windows version : Windows 10 22H2
 - GPU and video settings if applicable : Gefore RTX 3060 TI (latest drivers, version 537.34). I tried exclusive fullscreen and windowed mode. 3140x2160 (4K) 120hz with (tested without) vsync enabled. I verified all settings multiple times, and tried to revert all to defaults (VPX settings and NVIDIA settings). 

**Additional context**
I searched for users having the same issue (here and on VPForum) but it looks like I am alone, making this issue more strange. I tried to upgrade the the latest vpinmame (3.6) and b2sserver (2.0.3) without success. 

I can see the display menu and change from "Legacy" to the other modes without seeing anything else than black. I tried to manipulate lightings, positions, without success as well. It is a complete black screen every time. The only thing I noticed is that if I open the "Adjust Headtracking" menu (despite I am not using VR at all) and I click onto "force BAM display", then a small and deformed representation of the table appears (which seems expected to me, but tends to confirm that the screen setup is good, which I belive it is, since all previous versions (VPX8, 9, 10.7...) are working flawlessly.

Thanks for all the work. This software is a gem, and the community behind it is breathtaking.
  
[VPinballX.zip](https://github.com/vpinball/vpinball/files/12643033/VPinballX.zip)

**Comment by KrakenByteKraken** [comment]
It's looks like it's the same family of bugs I noticed when '[DirectX9 rendering not working with old PC](https://github.com/vpinball/vpinball/issues/693)'... or maybe not, who knows?

At least, I can play throught the OpenGL flavor so no problem!

Anyway, big thanks to everyone involved.

**Comment by k0uin** [comment]
thanks @KrakenByteKraken for making me remind that I tried the opengl version as well as the 32 bit versions for each, without success infortunately.

**Comment by gjupp** [comment]
Did you try pressing the enter key after changing to another mode such as "Window" ?

**Comment by KrakenByteKraken** [comment]
Yes, I did, thanks for the idea. I tried but, in my case, it's a rendering issue so itsn't a recentering problem: I can see the table in it right place but some (too much) elements don't appear anywhere in DirectX 9 version. Instead, in OpenGL version, with the same POV config, all elements are rendered well.

**Comment by k0uin** [comment]
Hi Ggupp, thanks for the help. I gave it a second try a few seconds ago to be 100% sure, then yes I can confirm the issue persists in this case as well.

**Comment by Crrispy** [comment]
> delete your old POV and reopen the table, create a new windows POV by pressing your launch button, adjust it and then press the start key. Then reopen the table and your issue will be fixed.

Maybe there are 2 different issues there. Mine has nothing to do with pov. Anyway, I just deleted all of them since they must be redone for the new Window mode, it didn't change anything. And all tables are like this, even those where I still used the default legacy pov. Some don't have the black playfield but tons of transparency issues.

**Comment by k0uin** [comment]
Not sure for whom your suggestion was @movieguru1 - so just to confirm, indeed this does not apply to the issue I raised as well (no VR/POV used in my case). Thanks

**Comment by caseycarp** [comment]
I was having the same issue after playing around with VR settings.  Somehow BAM headtracking got turned on in the Video/Graphics options.  Once I unchecked that box everything worked again.

**Comment by k0uin** [comment]
That was the issue. Dumb me dit not notice the new menu entry under Video/Graphics options. Thanks a lot @caseycarp !

**Comment by movieguru1** [comment]
glad you guys were able to solve it with such a simple fix. I thought it was the fact that the POV needed to be redone.
Unchecking BAM is much easier so that is great....

**Comment by Crrispy** [comment]
In my case it was a different issue, something got somehow corrupted in my vpinballx.ini, but that was not correctable in the settings ui. I deleted it, relaunched VPX, re-did my settings, and it worked again with normal display. Strange.

**Comment by grantmgay** [comment]
I had the same issue. I believe unchecking compress textures in the global settings for Video Preferences fixed it.
