### ISSUE TITLE
Visual Pinball X 10.8.0 beta 5 support gamepad controller in WINE ?

### ISSUE THREAD

**Issue by Augusto7743** [vpinball/vpinball#789]
Hello.
Thanks for reading my topic.
Here Ubuntu 20.04.6 and WINE 8.10.
Is possible in WINE run windows games with support for Playstation 4 DS4 controller in host Linux Ubuntu. Works correctly.
In Visual Pinball X running in WINE in options to configure input is possible use keyboard , but when trying to configure using the gamepad controller not is assigned the key to controller button.

Visual Pinball X have support for game controllers ? If yes as enable it ?

Have an nice week.

**Comment by toxieainc** [comment]
In general there is support for game controllers under windows, yes (via Direct Input and XInput, see the preferences in the UI).
How much of that is also available under WINE, i have unfortunately no clue.  :/

Did you try both DInput and XInput?

**Comment by Augusto7743** [comment]
Thanks for replying =)
I have tested in VPX both DInput and XInput and not any input is assigned.
However others games running in WINE have access to game controller.
WINE use much SDL. Possibly WINE use host SDL to access game controllers and convert to dinput and xinput.

I remember using game controller in VPX running in windows.

**Comment by francisdb** [comment]
You might want to check vpx standalone. Join https://discord.com/channels/652274650524418078/1076655472846831667 on discord for more info. However I have not tried gamepads.
See also #790

**Comment by Augusto7743** [comment]
Only reporting ... tested current VPinballX_GL-10.8.0-1347-3d585e7-Release-win-x86 in WINE 8.19 with an Sony PS4 DS4 controller works ...
I not understand if was done an fix in Visual Pinball or WINE.

well ... I need say thanks very much.
