### ISSUE TITLE
(Question) Window POV settings: Is it safe to adjust "viewport Z strech"?

### ISSUE THREAD

**Issue by Duglim** [vpinball/vpinball#791]
Is it safe to adjust the "viewport Z strech" option in Window-POV settings, without chaning table physics or ramps, etc?
Do any Window-POV settings alter table physics or are they only visual options? 

Thanks for clarification.

Why to I ask? I changed "viewport Z strech" to values around 60-70% to get rid of the optical distortion and have the feeling, the ball handles very differently, much heavier, dropping quicker.

Greetings, Duglim

**Comment by vbousquet** [comment]
Short answer: yes. 
It is as long as you are using the latest build of 10.8 (so not even the last beta but the one you can get in the GitHub Action tab, which are really alpha build, be warned before going further :) ).

Long answer: yes and you should.
As you may have seen, I'm working on improving the camera in VPX and to get better results, I'm moving to a more physically correct camera. With respect to this, the stretching should be the same (or at least fairly similar) on X, Y and Z axis to look correct. This is fairly obvious when you are using stereo rendering (anaglyph).

Still, this is one of the last thing I'm improving for the 10.8 release and it is not yet cleaned. I need to check it further. To do so, I'm making more advanced tests with custom headtracking (and since I don't want to make VPX source code heavier, I'm drafting a way to add it externally through a simple plugin approach, all of this taking some time). Depending on the results, I may have to change the improved POV system to be sure it works for all use cases (this is why I did not pushed a new beta yet).

**Comment by Duglim** [comment]
Thank you for this explaination. 
Currently, I encounter massivly Z-streched items in the back of tables (e.G. the T-Rex on JurassicPark is twice a high, as normal) if X-Y-Z are scaled equal. So I need to lower "viewport Z strech" from 100% to 60% to have better sizing. 

But maybe I'm doing something completly wrong with all the settings.

**Comment by Duglim** [comment]
Okay, my issues with ball physics had another origin. Adjusting the POV with Z-STrech indeed is phantastic. Thanks for your work!

**Comment by Wylted1** [comment]
> Thank you for this explaination. Currently, I encounter massivly Z-streched items in the back of tables (e.G. the T-Rex on JurassicPark is twice a high, as normal) if X-Y-Z are scaled equal. So I need to lower "viewport Z strech" from 100% to 60% to have better sizing. Having Player-Z-Position set to 67cm, lower values make it worse.
> 
> But maybe I'm doing something completly wrong with all the settings.

If you're setting Player-Z to your actual playing position and the window to fit your setup, objects at the back of the table will appear perfect from the defined position but stretched when seen from straight-on because it's rendering them for that oblique viewing angle.

**Comment by jasoncross** [comment]
> > Thank you for this explaination. Currently, I encounter massivly Z-streched items in the back of tables (e.G. the T-Rex on JurassicPark is twice a high, as normal) if X-Y-Z are scaled equal. So I need to lower "viewport Z strech" from 100% to 60% to have better sizing. Having Player-Z-Position set to 67cm, lower values make it worse.
> > But maybe I'm doing something completly wrong with all the settings.
> 
> If you're setting Player-Z to your actual playing position and the window to fit your setup, objects at the back of the table will appear perfect from the defined position but stretched when seen from straight-on because it's rendering them for that oblique viewing angle.

That's an interesting statement.  I've measured to my eye height and distance from table, have my screen pretty much exactly below the glass, yet it looks stretched for me too at 100% Z.  Maybe a bit more info on the best way to measure for initial setup would be helpful?  I thought I was following the diagram but clearly something is off.

**Comment by SmedleyB** [comment]
> > > Thank you for this explaination. Currently, I encounter massivly Z-streched items in the back of tables (e.G. the T-Rex on JurassicPark is twice a high, as normal) if X-Y-Z are scaled equal. So I need to lower "viewport Z strech" from 100% to 60% to have better sizing. Having Player-Z-Position set to 67cm, lower values make it worse.
> > > But maybe I'm doing something completly wrong with all the settings.
> > 
> > 
> > If you're setting Player-Z to your actual playing position and the window to fit your setup, objects at the back of the table will appear perfect from the defined position but stretched when seen from straight-on because it's rendering them for that oblique viewing angle.
> 
> That's an interesting statement. I've measured to my eye height and distance from table, have my screen pretty much exactly below the glass, yet it looks stretched for me too at 100% Z. Maybe a bit more info on the best way to measure for initial setup would be helpful? I thought I was following the diagram but clearly something is off.

What size screen are you using? If a 32" or smaller, the actual/real player Z distance will not be ideal. It will likely need to be a larger number than actually measured.

**Comment by jasoncross** [comment]
> What size screen are you using? If a 32" or smaller, the actual/real player Z distance will not be ideal. It will likely need to be a larger number than actually measured.

42".  Plus I have a physical apron so I'm fairly close to true ratio.

**Comment by Wylted1** [comment]
> > > Thank you for this explaination. Currently, I encounter massivly Z-streched items in the back of tables (e.G. the T-Rex on JurassicPark is twice a high, as normal) if X-Y-Z are scaled equal. So I need to lower "viewport Z strech" from 100% to 60% to have better sizing. Having Player-Z-Position set to 67cm, lower values make it worse.
> > > But maybe I'm doing something completly wrong with all the settings.
> > 
> > 
> > If you're setting Player-Z to your actual playing position and the window to fit your setup, objects at the back of the table will appear perfect from the defined position but stretched when seen from straight-on because it's rendering them for that oblique viewing angle.
> 
> That's an interesting statement. I've measured to my eye height and distance from table, have my screen pretty much exactly below the glass, yet it looks stretched for me too at 100% Z. Maybe a bit more info on the best way to measure for initial setup would be helpful? I thought I was following the diagram but clearly something is off.

Not sure if it's a typo or miscommunication; Player and Window measurements are in cm or VP units, while the Scale adjustments are in %.  Those should all be close to parity...though I'm not above squishing the vertical to fit a little more table on my screen!

> At this point, I'm going to wait for better documentation because I suspect how some older tables were built is the culprit rather than some deficiency in the VPX camera. I will say that more recent VPW tables, where we know all the objects and playfield were super accurately scanned, built and placed (like Godzilla) seem to be fairly easy to get just right as far as POV.

This is probably the best take, especially if there are more changes to the view calculations before 10.8 final.
