### ISSUE TITLE
GL rendering issue

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#792]
Hello,

GL x64, build 1450. Some lights create a strong halo which goes through objects, example on BM66:

![GL BM66](https://github.com/vpinball/vpinball/assets/28100190/ce934acb-bcb4-4588-974e-034bc64bf737)

Thanks.

**Comment by bhamscott** [comment]
This appears to be the same issue that can be seen on Cactus Canyon table. The lights go through the guns on the apron.

64bit GL version build 1450

**Comment by bhamscott** [comment]
![Screenshot 2023-09-18 213521](https://github.com/vpinball/vpinball/assets/9481404/8c5dbf6c-c95b-4bf3-a71f-0966d8105929)

**Comment by vbousquet** [comment]
Fix in latest build (as long as the table as not been edited and saved in 10.8, if so, please redownload the original 10.7 table)
