### ISSUE TITLE
Disable/Fix appveyor

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#794]
Is nobody annoyed that every build is marked failed?

**Comment by wiesshund** [comment]
where? link?

**Comment by jsm174** [comment]
I believe @freezy would have to do this, https://ci.appveyor.com/project/freezy/vpinball-c2whj/builds/48084537

**Comment by francisdb** [comment]
here: https://github.com/vpinball/vpinball/commits/master

<img width="567" alt="image" src="https://github.com/vpinball/vpinball/assets/161305/7a2ed76d-fd59-4bf6-af1b-7001b0e75f89">

**Comment by jsm174** [comment]
Before doing that, ping @freezy .

**Comment by freezy** [comment]
Sure, go ahead!

**Comment by jsm174** [comment]
done. Thanks @freezy. Didn't want to do this earlier until first hearing from you.
