### ISSUE TITLE
10.8 nightly - "Visible" gets unchecked in live, despite being checked in startup

### ISSUE THREAD

**Issue by avanrider** [vpinball/vpinball#795]
**Describe the bug**
I've only run into this bug in Firepower II Bigus (and the table it's based on) The Apron visibility gets turned off, despite being checked in the properties. If I go into live edit, the "Live" version has visibility unchecked, despite "Startup" version being checked. 
Only applies to cabinet mode, tried on two computers, one with a fresh install of VPX (No prior install on system)

**To Reproduce**
1. Start Firepower II - Bigus mod in cabinet mode
2. No curtain visible.
3. View properties of layer 1 - primitive 13. Visibility is checked.

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Versions & Settings**
 - VPX: 10.8 1443+
 - Windows version Windows 10 and 11

**Comment by vbousquet** [comment]
Did you check the table script ? Usually this is because the script modify the table state (that's the reason there are 2 states: startup which is the one in the editor and live)

**Comment by avanrider** [comment]
aha! there's a holdover in there for desktop view, with it set to 0 if not desktop.
Very weird, as this table worked perfectly in cabinet mode in earlier versions.

**Comment by vbousquet** [comment]
Perhaps you could contact the table author since this is a table bug and other player will likely face it.
