### ISSUE TITLE
Hankin.vbs not found even though it's there

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#796]
**Describe the bug**
Loading a Hankin table results in pop up error "Controller needed, hankin.vbs not found"
**To Reproduce**
1. try to load Star Wars Empire Strikes Back, The (Hankin 1980) MOD v3.1.vpx in 10.8 or 10.7.4, 32 or 64 bit.

2. See error

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
https://vpuniverse.com/files/file/4908-star-wars-empire-strikes-back-the-hankin-1980-mod/?do=download&r=159043&confirm=1&t=1&csrfKey=7821a47641f6b1d490d4fd461f170793

**Expected behavior**
It should open and run

**Screenshots**

**Crash dump**
NA

**Versions & Settings**
 - VPinballX-10.7.4-417-5a3439f-Release-win-x64, VPinballX-10.8.0-1449-396bcce-Release-win-x86
 - Windows 11 Home
 - GPU Nvidia Geforce 1660 Super 6GB
 
**Additional context**
I unzipped the hankin.vbs from an August version of vpx 10.8.x and it works. I'm not sure at what point the hankin.vbs became unusable

**Comment by francisdb** [comment]
@toxieainc what exactly fixed this issue as it's hard to derive from the big commit?

**Comment by wiesshund** [comment]
let me look at it

**Comment by toxieainc** [comment]
its already fixed, nothing to do anymore

**Comment by wiesshund** [comment]
https://drive.google.com/file/d/1bSYSSSidnZe7_dD1BSsnbpHYQtF_8iRn/view?usp=drive_link

**Comment by wiesshund** [comment]
somehow i doubled the keycode line
AFTER having it working and tested

go figure
