### ISSUE TITLE
Ball sometimes becomes translucent

### ISSUE THREAD

**Issue by workerb0y** [vpinball/vpinball#798]
I've noticed that since some versions of 10.8 (from around 1434) a translucent ball appears occasionally during gameplay. Almost only its outlines are visible and the pf graphic is visible through it. At first I thought it was because of the use of reflections (they are all disabled globally, only enabled in the table preferences (default)), but it doesn't seem to be affected by any settings. 
After restarting the game (or restarting VPX) the problem goes away, but it may reappear on the next launch. 

**Versions & Settings**
 - VPX: [VPinballX_GL-10.8.0-1452-db6787f-Release-win-x64]
 - Windows version: Wun 10 Pro 64bit
 - GPU and video settings if applicable: NVidia RTX3070, every reflections, Ambient Occlusion and Sc.Sp.Reflections are turned OFF, use Frame Pacing and use anaglyph Amber-Blue settings.
 
![20230920_091655](https://github.com/vpinball/vpinball/assets/87616502/7ba1581c-d03e-4256-8a7a-f7c134d50835)

**Comment by wiesshund** [comment]
Just to chime in, i have seen this in latest build, DirectX version also on occasion

If the cause is found, isolate the cause and turn it into a useable feature if possible
i'd love to do it in the table script at will

**Comment by gjupp** [comment]
Who ya gonna call???

**Comment by wiesshund** [comment]
@vbousquet 
Is there any way to employ the bug purposely, as an effect?
