### ISSUE TITLE
World Poker Tour. Playfield LEDs don't work.

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#799]
Hello. I have the latest VPX 10.8 and the playfield LEDs don't work on World Poker Tour table. They did work on 10.7.4. Please find a solution. Thanks in advance.
![WPT](https://github.com/vpinball/vpinball/assets/81928693/9e8d6816-43e0-4736-a065-1ccd43145a75)

**Comment by passionforpins** [comment]
Can confirm. I tested with all versions of vpx 10.8 that I have all the way back to rev 924 and the playfield led's do NOT work. I cannot determine when it got broken but it was before rev 924. They do still work in 10.7.4 x86 and x64 rev 417

**Comment by vbousquet** [comment]
@JorgePedro65 Please retest and tell me if this is good for you too

**Comment by passionforpins** [comment]
Tested with 1483 x32 and x64 and LED's work again Vincent- thanks!

**Comment by JorgePedro65** [comment]
Sorry, tested with 1483 x32 and x64 but the problem persists for me, so I have to open the bug again.

**Comment by embryodead** [comment]
> Sorry, tested with 1483 x32 and x64 but the problem persists for me, so I have to open the bug again.

same thing doesnt work either dx or gl version rev 1519

**Comment by passionforpins** [comment]
Hmmm. Works ok for me with DX X64 1529
![wpt-leds-working-1529dxx64](https://github.com/vpinball/vpinball/assets/52011304/ef7b6bf3-407e-4300-85c5-4279a6b82939)

**Comment by embryodead** [comment]
i've dowloaded again and now the table is working good!
so it seems that a save in a previous version of vpx10.8 modified the table somehow
so you have to retart with a fresh download if you save it in a previous vpx 10.8 revision and everything will be fine
thank youfor your fast reply
