### ISSUE TITLE
GUI Does Not Open When Launching VPX

### ISSUE THREAD

**Issue by jreiman** [vpinball/vpinball#80]
**Describe the bug**
When launching VPX, the GUI will not open, but the VPX process will be running in windows task manager.  I have to then end the process from windows task manager.  There are no pop-up error messages or crash log generated from VPX.  This issue occurs at least 50% of the time when launching VPX.

In releases v10.7.1-217-6883e97,  v10.7.1-215-4b91041, v10.7.1-207-d4b8595, it occurs at least 50% of the time.
In releases v10.7.1-203-23e9ca0, v10.7.1-196-993e8c4, v10.7.1-187-ebe5596,  it does occur, but much less often (around 10% of the time).
I have downgraded to release v10.7.1-112-580a2c which is the next oldest compiled release and I have not yet encountered the issue.

**To Reproduce**
1. Launch VPX.
2. GUI will not open.
3. VPX process will be running in Windows task manager.

**Expected behavior**
I expected the VPX GUI to open when I launched VPX within a few seconds.

**Screenshots**
N/A

**Crash dump**
Issue does not generate a crash dump.

**Versions**
 - VPX: v10.7.1-217-6883e97,  v10.7.1-215-4b91041, v10.7.1-207-d4b8595, v10.7.1-203-23e9ca0, v10.7.1-196-993e8c4, v10.7.1-187-ebe5596.  Running the "Release-win-x86" version.
 - Windows version: Windows 10
 - GPU and video settings:  Nvidia RTX 3060Ti

**Additional context**

**Comment by sverrewl** [comment]
Can confirm seeing this happening. Win10 64bit. Not yet on Win7.

**Comment by TalOfAruk** [comment]
I have videos illustrating this over here if anyone is interested.
-Joshua

**Comment by TalOfAruk** [comment]
VPX beta 112 seems to be working well for me over here!

**Comment by sverrewl** [comment]
Ref : https://www.vpforums.org/index.php?showtopic=44135&p=504748

Extracted all versions as ... VPinballX-187.exe - etc to standard VP install folder. Started opening them one by one from the lowest number. Got a "hang". Needing to kill the app on as early as 196. Killed it. Started over from 187, 196, 203 - hang on 207. Started over again - 187, 196, 203, 207, 215 hang on 217. Started over from beginning again - hang very first 187. So, conclusion is : this started happening before 187 and it is intermittent. I had some older backups from my cab, I was able to crash/hang 173, bug got really bored trying to get a hang with 162. (not able), On this new computer, a Win10, 32gb ram, Intel Core i7-12700F CPU,  ASUS GeForce RTX 3080 TUF Gaming OC V2 - w nvidia driver 516.59. I don't have dev environment installed anymore/yet ? So, I won't be able to build any versions between 162 and 173 myself. These test where all done extracting ONLY the *.exe into a 221 release, if any of those other dll's is to blame.

**Comment by jreiman** [comment]
I recently just rebuilt my cabinet on Windows 11 Home version and have been running VPX version v10.7.2-277 and have not yet experienced this issue.   All of my hardware is exactly the same as it was when I reported the issue.  I have launched VPX well over 100 times so I can safely say that the issue no longer exists on my system using this new combination of Win11 Home and VPX v10.7.2-277.

**Comment by sverrewl** [comment]
Without having any proof as feedback is a bit on the slow and inaccurate side. It might be Intel in combination with Win10. At the moment I'm on H1H2 19044-.1889. Seen a few amd and now this report on Win11 working.

**Comment by jreiman** [comment]
> Without having any proof as feedback is a bit on the slow and inaccurate side. It might be Intel in combination with Win10. At the moment I'm on H1H2 19044-.1889. Seen a few amd and now this report on Win11 working. Quite sure though this is the same bug as #90

My CPU is AMD Ryzen 5.  When I was running Win10, I was on the same 19044 build as you listed.

**Comment by jreiman** [comment]
I've been back to running Win10 on my cabinet since early October and I have not experienced this issue on any version of 10.7.2 or 10.8.0 and I'm currently up to running 10.8.0-510.  Based on this, I'm going to consider this issue resolved and close out this issue ticket.  Thanks.

**Comment by toxieainc** [comment]
Thanks for verifying. We tweaked the build process in https://github.com/vpinball/vpinball/commit/0eab6c11c2b7c7d0cc8a4d38f05cdc9992826ada , so most likely this fixed it.
