### ISSUE TITLE
Going into Adjust Camera mode by pressing ENTER resets the POV to default values

### ISSUE THREAD

**Issue by lukpcn** [vpinball/vpinball#800]
**Describe the bug**
Going into Adjust Camera mode by pressing ENTER resets the POV to default values.
When clicking Adjust Camera with a mouse doesn't do that.

**To Reproduce**
1. Go Into Play Mode (F5)
2. Press Q to open Menu
3. use TAB to select Adjust Camera
4. Press Enter
Notice that on entering the Adjust Camera screen it loads Default POV values that are mapped to the Launch Key (ENTER)
When clicking Adjust Camera with a mouse it doesn't do that.

**Expected behavior**
When You press enter it enters the Adjust Camera but You need to press Enter again if You want to load the defaults.

**Screenshots**
Attached
**Crash dump**

**Versions & Settings**
VPX 10.8 rev 1442
 - Windows version
Windows 10
![AdjustCamera](https://github.com/vpinball/vpinball/assets/82708104/57a744b5-d7fe-42c4-9f50-4c6a94ee916c)

**Comment by francisdb** [comment]
I can confirm this issue on beta5. Also the selected item is not visible when pressing Q, only when using the arrow keys does a selection appear.

**Comment by vbousquet** [comment]
Fixed by https://github.com/vpinball/vpinball/commit/5cad23ce49f7b1c932cfe233ee8c6e5d1809379d

**Comment by francisdb** [comment]
Could it be that there has been a regression here? Anybody else seeing this pop up again with the latest builds?

**Comment by francisdb** [comment]
Thanks, confirming the fix
