### ISSUE TITLE
GL rendering issue - follow up of #792

### ISSUE THREAD

**Issue by Crrispy** [vpinball/vpinball#804]
Hello,

I upgraded to 1459 and then 1467 (still GL 64), the issue with the big halo is fixed, but there is another one now, some lit inserts appear through solid objects like the crane on this picture. The table is unedited, straight VPU redownload. It seems it also affects the white arrow insert on the left of the picture where the white light should not be visible in the "Commissioner Gordon" playfield zone.

![GL BM 66 2](https://github.com/vpinball/vpinball/assets/28100190/bc17255d-0a1c-44eb-901e-639e35a31e45)

**Comment by dacstyle** [comment]
Another example of the same bug on twister table

![20230924_203845](https://github.com/vpinball/vpinball/assets/119076983/c62c119a-6b92-4381-92fa-b89c507f8714)

**Comment by vbousquet** [comment]
@Crrispy @dacstyle Could you fill in a complete bug report ? There is nearly nothing we can do without the requested informations

**Comment by Crrispy** [comment]
> @Crrispy @dacstyle Could you fill in a complete bug report ? There is nearly nothing we can do without the requested informations

Hello, for sure, I just have to find out how :-)

**Comment by vbousquet** [comment]
When you click 'New Issue', just click 'Bug Report'

**Comment by francisdb** [comment]
the template is here:
https://github.com/vpinball/vpinball/blob/master/.github/ISSUE_TEMPLATE/bug-report.md?plain=1

**Comment by Crrispy** [comment]
Thanks, going there now.

**Comment by Crrispy** [comment]
I don't know in which build it was fixed, but jut tried 1544 and the issue is gone.

Thanks.

**Comment by vbousquet** [comment]
My pleasure :)

And thanks for reporting back !
