### ISSUE TITLE
Unable to Load Latest Builds after #1455 From Front End 

### ISSUE THREAD

**Issue by movieguru1** [vpinball/vpinball#805]
**Describe the bug**
With builds before #1455 I could open them using my frontend (pinup popper) without issue.
With builds after #1455 I cannot anymore, I now get invalid parameter error message when it tried to load.
I am able to load VPX manually without using a command line to load it.
I have added a screenshot of the error message.

See error

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
Normally VPX Will open and I am able to play

![image](https://github.com/vpinball/vpinball/assets/132297728/cd6aebb3-a135-4bda-95b4-5d492cf2dce9)
![image](https://github.com/vpinball/vpinball/assets/132297728/e066f548-573e-4ff0-9b56-c42e6ed5cedc)

Thank you Billiam for the solution, changed popper to:
START "" /D "[DIREMU]" /min "%VPXEXE%" -%FSMODE% -minimized -play "[GAMEFULLNAME]"

**Comment by BostonBuckeye** [comment]
Up to version 1459 works for me. It is all versions after this that I run into the same issue.

**Comment by toxieainc** [comment]
Related to https://github.com/vpinball/vpinball/issues/793, will try to find a balance between the 2 use cases.

**Comment by LynnInDenver** [comment]
I would recommend this be like the "ignore certain errors and run anyway" setting with VPinMAME. Basically set it up so that the default is "error out", and then give us the option to turn off the error condition alert versus changing the front end loading script.

I do get that VPX should always have basically errored out in invalid parameters, but we're now stuck with years of a legacy, and recent other events with other software in the community shows how long issues can linger when a change is made to how things are done.

**Comment by Drybonz** [comment]
After this change, the "/exit" command, which I have always used to completely close out everything, from my frontend is now showing as an invalid parameter.

**Comment by toxieainc** [comment]
Any other params i should know of then? Which frontend do you use?
@nailbuster Do you know of some more somewhere?

**Comment by toxieainc** [comment]
@Drybonz please retest

**Comment by Drybonz** [comment]
Toxie, I tested in 1482, and everything works perfectly.  Thanks for taking the time to do that.  I use LaunchBox, but there were questions about the /exit command earlier in the VPF beta thread, and it sounds like people using other frontends use it as well.  At least for me, there aren't any other parameter errors now.

**Comment by Drybonz** [comment]
Toxie, it looks like (testing in 1577 dx 64) the -minimize and possibly also /play parameters are no longer working.  This seems to have just started, after the previous parameters were fixed.
