### ISSUE TITLE
Completely black DMD window when ROL=1

### ISSUE THREAD

**Issue by Skitsoo** [vpinball/vpinball#81]
VPX 10.7 rev 221 64bit 

I use single screen in portait, so I need to rotate DMD to get it right. When I set ROL=1, DMD is just black. with ROL=0 it works normally. Same settings with 10.6 DMD works with no problems while rotated.

UPDATE: found out the 64bit Vpinmame is bugged and doesn't support ROL. (black screen) chaning VPX 10.7 to 32bit solved the issue.

**Comment by toxieainc** [comment]
Will file a feature request for PinMAME then
