### ISSUE TITLE
Godzilla VPW broken since PostProcAA: cleanups (also fix DX build) vpinball #1961

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#810]
Since the new 1961 release; the Godzilla VPW table is broken in GL / VR.

If you move your head then ALL the light/inlet lights in the playfield of the table get a huge unwanted ghosting effect.
This doesn't happen all the time, but if you play the table for a few minutes and you move your head, you surely see it.

With the most recent release at the time of the Godzilla VPW release(so last week, I downloaded the latest version at that time) this didn't happen. It started once I installed the new #1961 which was just released.

So something is clearly wrong with the new update. Thanks.

**Comment by vbousquet** [comment]
Please fill in the bug report template. There is nothing we can do without teh requested informations
