### ISSUE TITLE
frame pacing

### ISSUE THREAD

**Issue by davy33000** [vpinball/vpinball#812]
**Describe the bug**
the table vpw big bang bang doesn t work the credits doesn t work with frame pacing and vsync is too hard for manu config

**To Reproduce**
set frame pacing and supersampling 200 and had reflections maybe and bilateral cas and open the table bbb the credits doesn t work and it s not a problem of rom everything is ok at home

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Versions & Settings**
 - VPX: 10.8 last release x64
 - Windows version 10
 - rtx 3050
 - i5 10400f

**Comment by vbousquet** [comment]
Duplicate of https://github.com/vpinball/vpinball/issues/755
