### ISSUE TITLE
View Layout Mode: Window  <--drastically reduces playfield quality (sharpness) compared to Legacy

### ISSUE THREAD

**Issue by redbone75** [vpinball/vpinball#817]
Description:  Playfield quality (sharpness) is reduced when Playing a table with F5 vs viewing with F6

To Reproduce:  To easily see the quality degradation, press F6 and Zoom into table with both Legacy and Window Layout Modes. Save a screenshot in each of these modes.  Play the table with F5 in each of these modes. Save a screenshot while playing each mode.  Compare the screenshots.  It will be noticed that Legacy mode doesn't exhibit any degradation in quality of the playfield.

Expected behavior:  I would expect the quality to be the same in all Layout Modes.  I would expect the quality not to change in the same layout mode while playing F5 or adjusting modes with F6.  

Versions & Settings:
 - VPX:10.8 beta 5+
![Capture](https://github.com/vpinball/vpinball/assets/20893831/9ab33ded-840a-404c-bf5f-6bcdce8e1fdf)

**Comment by vbousquet** [comment]
Could you fill in the bug report template ? With this information, I can not reproduce and therefore I can't fix anything.
What would be even better would be to provide the 2 version of the table with the setup that lead to this problem
