### ISSUE TITLE
World Poker Tour. The problem persists

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/vpinball#821]
Sorry Vincent, the problem persists for me. No playfield LEDs x86 and x64 yet. 10.8 v1483. Please find a solution.

**Comment by JorgePedro65** [comment]
I have a 4
![WPT](https://github.com/vpinball/vpinball/assets/81928693/b3b0c897-8e97-48aa-a96f-5f77cd74e308)
K laptop, NVIDIA 3080ti

**Comment by JorgePedro65** [comment]
![WPT2](https://github.com/vpinball/vpinball/assets/81928693/8d57802c-8496-4834-a8e8-28dacb82a119)
With 10.7.4 v400, it does work. Please find a solution. Thanks.

**Comment by JorgePedro65** [comment]
I updated to 10.8 v1484 but the problem persists.

**Comment by JorgePedro65** [comment]
Hello again, I solved the problem by re-installing the table on VPX 10.7.4 and, after that, updating it to 10.8 v1484. Thanks so much.

**Comment by vbousquet** [comment]
My bad, forget to tell that the fix needed to be run against the original table, not a table modified in 10.8. Anyway, one more bug down !
