### ISSUE TITLE
'cmake --install build' not working on Archlinux

### ISSUE THREAD

**Issue by Brensom** [vpinball/vpinball#822]
**Describe the bug**
'cmake --install build' not working

**To Reproduce**
```
build() {
  cd ${srcdir}/vpinball/standalone/linux
  ./external.sh

  cd ${srcdir}/vpinball
  [[ -d build ]] && rm -rf build
  cp standalone/cmake/CMakeLists_gl-linux-x64.txt CMakeLists.txt
  cmake -DCMAKE_BUILD_TYPE=Release -B build
  cmake --build build
}

package () {
  cd "${srcdir}/vpinball"
  DESTDIR="$pkgdir" cmake --install build

```

**Expected behavior**
cmake should install the files in the correct directory

**Versions & Settings**
10.7.3

**Additional context**
You can test PKGBUILD for yourself on an Arch or similar distribution: https://aur.archlinux.org/packages/vpinball

**Comment by toxieainc** [comment]
Sounds like something for @jsm174   :)

**Comment by jsm174** [comment]
Hello. Sorry I didn't see this. We do not have an install task for cmake.

We are definitely open to patches, if you would like to provide one. 😄
