### ISSUE TITLE
Crash bug when adjusting camera

### ISSUE THREAD

**Issue by tweety231323** [vpinball/vpinball#824]
**Describe the bug**
VPX rev 1347 crashes (crash.dmp created).

**To Reproduce**
1. Go to 'New' - 'Completely blank table' (you know, the one with 428 lines of script, 5878 vertices and 1170 polygons) ;-)
2. Click on 'Play Table'
3. Press 'ESC', 'TAB', 'TAB' 'Space' to 'Adjust camera'
4. Press left or right Shift key.
5. Press 'ESC', 'TAB', 'Space' to 'Resume game'
6. Crash.dmp is created

**Versions & Settings**
 - VPinballX_GL-10.8.0-1347-3d585e7-Release-win-x64
 - Windows version 11

[crash.txt](https://github.com/vpinball/vpinball/files/12730404/crash.txt)
[VPinballX.ini.log](https://github.com/vpinball/vpinball/files/12730408/VPinballX.ini.log)
[vpinball.log](https://github.com/vpinball/vpinball/files/12730424/vpinball.log)
[crash.zip](https://github.com/vpinball/vpinball/files/12730427/crash.zip)

**Comment by tweety231323** [comment]
Similar crash when in Live Editor, clicking "Debug", then "Renderer Inspection".

**Comment by tweety231323** [comment]
Update: same with rev.1488

**Comment by vbousquet** [comment]
Could you use the debug build and share the crash log ?

**Comment by tweety231323** [comment]
Tested with 10.8.0-1504-6a22c42-Debug:
With the debug version, i can't even click "Adjust camera". VPX will crash with an "Assertion failed".

[crash.txt](https://github.com/vpinball/vpinball/files/12756414/crash.txt)
[crash.zip](https://github.com/vpinball/vpinball/files/12756417/crash.zip)
[vpinball.log](https://github.com/vpinball/vpinball/files/12756421/vpinball.log)
![2023-09-29 07_35_35-Microsoft Visual C++ Runtime Library](https://github.com/vpinball/vpinball/assets/98708681/9a810d4b-c0bf-47f3-b3a9-e0a020943cf8)

**Comment by tweety231323** [comment]
I found that I don't have to really adjust the camera for VPX to crash. In Release, just ESC Adjust ESC Resume and it crashes.
