### ISSUE TITLE
Can't edit POV if MSAA option is enabled

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#825]
**Describe the bug**
When I try to modify the POV, if the MSAA Samples option is enable, the POV editor will not work correcly, it shows a lot of incorrect textures and black shadows.
I need to disable MSAA Amples option if I need to adjust POV.

**To Reproduce**
1. Encable MSAA Samples 4, 6 or 8
2. Load a table and press F6
3.Try to adjust the pov

![Screenshot_321](https://github.com/vpinball/vpinball/assets/119076983/95e992d3-56d8-46f9-9b8c-93e40a43cfe2)

**Versions & Settings**
 - VPX: VPX 10.8 GL x64 build 1488
 - Windows 10
 - GPU RTX 3080

**Comment by vbousquet** [comment]
Could you use the debug build and share the crash log ?

**Comment by dacstyle** [comment]
sorry for my bad explanation. There is no crash, but the table looks very bad, like the attached screenshot. The problem is the same for any table.

Tested on 1504 same problem

**Comment by dacstyle** [comment]
screenshot 
![Screenshot_3-min](https://github.com/vpinball/vpinball/assets/119076983/a04fb862-a41d-46c7-beb5-e647d51845f2)

**Comment by vbousquet** [comment]
Could you attach your ini file ?

**Comment by dacstyle** [comment]
tested 1514 and the issue still persist
![Screenshot_4-min](https://github.com/vpinball/vpinball/assets/119076983/ca33ed83-78ff-47c9-bca2-5060968db33e)

**Comment by vbousquet** [comment]
This should be fixed now. Could you give it a try ?

**Comment by dacstyle** [comment]
solved, thank you
