### ISSUE TITLE
Standalone build binaries are missing the executable flag

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#826]
**Describe the bug**
The github actions builds when extracted don't have the executable marked as executable

**To Reproduce**
1. Download a mac/linux artifact
2. Extract
3. `./VPinballX_GL`
4. `zsh: permission denied: ./VPinballX_GL`

**Expected behavior**
The executable flag is set on `VPinballX_GL`

**Workaround**

```bash
chmod +x VPinballX_GL
# these are also needed on macOS, or the user has to go through the "Security and Privacy settings" but not something to handle in this issue
xattr -d com.apple.quarantine VPinballX_GL
xattr -d com.apple.quarantine libbass.dylib
```

Probably related to the fact that these are `.zip` files and `tar.gz` is required for storing this flag

**Comment by francisdb** [comment]
see also

https://github.com/actions/upload-artifact#permission-loss
https://github.com/actions/upload-artifact/issues/109

**Comment by jsm174** [comment]
Yes, this is not a bug and is working as expected. Zip files do not store unix style permissions.  

A possible workaround (untested) would be to first store the files in a tar.gz prior to upload-artifact, however, then the user will have to uncompress twice.

Another idea might be to include a `setup.sh` that a user can `source setup.sh`

**Comment by jsm174** [comment]
I ended up adding the `setup.sh` script for linux and macos. 

So now when you download an artifact you can unzip and run `source setup.sh`.

You will not have to run the quarantine command or set the executable flag.

**Comment by francisdb** [comment]
I would change this to building a `tar.gz` (and having github make it a `tar.gz` inside a `zip` for artifacts 🙄)
The setup file can then be dropped.

As for final releases in the releases section there should be actual `tar.gz` files unlike what we currently have
https://github.com/vpinball/vpinball/releases/tag/v10.8.0-1807-39824d6
(the extra zipping github does is only for actions build artifacts)
eg https://github.com/neovim/neovim/releases/tag/v0.9.4

Can this be re-opened?

**Comment by jsm174** [comment]
since macos builds now make a dmg which is then zipped, I'm fine with this.

**Comment by jsm174** [comment]
This is now complete. See: https://github.com/vpinball/vpinball/commit/e9a08a8590d8c82e1fc204102c246dd88d6b656f

it has also been backported to the standalone branch
