### ISSUE TITLE
GL-Version: Cycling through Anaglyph-Profiles shows wrong profile name on screen

### ISSUE THREAD

**Issue by Duglim** [vpinball/vpinball#829]
I'm setting up anaglyph stereo 3D on my tables currently, using most recent VPX GL 64bit version. 
I noticed a small issue with the shown Anaglyph profile name:

- If you press F10 to cycle through the 10 anaglyph profiles, the profile number and name is show on screen.
- Cyclying the profiles works fine, but the shown profile name belongs to the previous profile. 
 
Example: 
- Start a table with Anaglyh mode (GL 64bit Real Stereo mode).
- Game starts up with the first anaglyph profile (_anaglyph1_ in .ini).
- Press F10 to cycle to next anaglyph profile.
- Game switches to correct next profile (_anaglyph2_ in .ini), but shows "Profile 1: _<Name of Profile 1>_"  on screen. 

This issue may result in the shown profile number starting with 0 to 9, while the profiles in the vpinballx.ini starts with 1 to 10. This may occure also on DX-Version or with Fake Stereo mode, but I was not able to test it so far.

_Additional questions (not bug releated):_
- Is it possible to delete not needed anaglyph profiles, so you only cycle through 1-2 needed profiles and "disabled" and not all 10? I tries deleting profiles in the .ini, but they are recreated on start. LiveEditor also has no option to delete profiles.
- If you cycle all 10 profiles, the next option ist "disabled". This shows the table in 2D. Is the table still rendered 2x per eye in the background or just one time to increase 2D FPS? Why I'm asking? I imagine an setup to switch between 2D and Anaglyph with a single button press and have optimal performance.

Greetings, 
Duglim

**Comment by vbousquet** [comment]
- Is it possible to delete not needed anaglyph profiles, so you only cycle through 1-2 needed profiles and "disabled" and not all 10? I tries deleting profiles in the .ini, but they are recreated on start. LiveEditor also has no option to delete profiles.
No

- If you cycle all 10 profiles, the next option ist "disabled". This shows the table in 2D. Is the table still rendered 2x per eye in the background or just one time to increase 2D FPS? Why I'm asking? I imagine an setup to switch between 2D and Anaglyph with a single button press and have optimal performance.
No again. It's just a quick display hack but teh rendering is still made with 2 view points
