### ISSUE TITLE
Pup videos on playfield or apron colors different

### ISSUE THREAD

**Issue by passionforpins** [vpinball/vpinball#83]
**Describe the bug**
Pinup player pup videos playback on playfield elements such as the apron or billboards have different coloring than on the backglass or topper videos. 

For example, on Deadpool the pup videos show him as blue on the apron card videos instead of red.

This does not happen on rev 215 and earlier

**Versions**
 - VPX 10.7.1 beta revision 217
 - Windows 10 x64
 - GPU GTX 1060 Founders 6GB

**Comment by toxieainc** [comment]
This should be fixed with https://github.com/vpinball/vpinball/releases/tag/v10.7.1-222-3eff4d6

**Comment by passionforpins** [comment]
Fixed! Thanks Toxie
