### ISSUE TITLE
10.8 Pup pack screens blacking out, Using AMD video card

### ISSUE THREAD

**Issue by gman1126** [vpinball/vpinball#830]
I use AMD radeon video card user and am a pup pack creator.  
Pup packs I have made specifically for 10.8 tables systematically black out after around 4-5 minutes every single time.  USUALLY towards the end of a pinball game strangely, but its still pretty random WHEN.
Only the fulldmd and backglass screens black out, playfield screen is not effected.

I've reinstalled 3 different times, and tried everything I can think of that might be causing it.
I've tried the pup64 bit beta files.... not fixing it
I've tried reverting vlc back to 2.2.8.... didnt fix it

I've tried with the 10.8 GL and DX release .exes...... same blackouts

all 64-bit 32bit 10.7.4 pups work perfectly.  It's purely the 10.8

**Comment by gman1126** [comment]
[VPinballX-INI.zip](https://github.com/vpinball/vpinball/files/12742486/VPinballX-INI.zip)

**Comment by gman1126** [comment]
Can send you a 10.8 pup to test, i've had people test it with nvidea and its worked perfect.  I don't know what is causing it to black out other than AMD issue. =/  It's a real bummer for me, means i wont be making 10.8 pups until its figured out

**Comment by nailbuster** [comment]
try running vpx not-full screen exclusive and see if theres any difference.

also see this :  https://www.nailbuster.com/wikipinup/doku.php?id=puppack_troubleshoot#on_certain_packs_back_glass_videos_will_crash_close-out_after_10-20_minutes_of_play_vpx_still_plays

**Comment by gman1126** [comment]
I just did another fresh install this morning, tried both screen exclusive and windows, same deal, 10.8 pups close out to black screens after about 1 minute or less now each time.  10.7.4 pups work perfectly in 64 or 32 bit.  used this guide for the reinstall this morning

https://www.youtube.com/watch?v=x0CFLSs7R3c&t=126s

**Comment by gman1126** [comment]
I deleted the vlc folder from %appdata% doing more testing, it seems to be behaving in window mode, NOT fullscreen exclusive mode.  Doing some more testing now...

**Comment by gman1126** [comment]
This is great news, made my day!!  I think that fixed it.... apparently vlc was using the old 3.0.18+ settings from before i reverted, i guess deleting that folder fixed it..... and im guessing it was a vlc thing the whole time.... 
Thank you so much nailbuster!!! You Rule!!!
