### ISSUE TITLE
centaur table, ball disappears at plunger section

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#836]
**Describe the bug**
using version 1504 in centaur table the ball disappears
[VPinballXini.txt](https://github.com/vpinball/vpinball/files/12755729/VPinballXini.txt)
[Centaur (Bally 1981)pov.txt](https://github.com/vpinball/vpinball/files/12755730/Centaur.Bally.1981.pov.txt)
 when the ball is released to plunger section, so it is unplayable.

table link https://vpuniverse.com/files/file/12948-centaur-bally-1981/
pov and ini files attached

**Comment by Drybonz** [comment]
I just tested on DX x64 build 1514, and can confirm ball disappears as it enters the plunger lane.  Last working version for me was DX x64 1482.

Dacstyle, they may want to know what VPX version you are using.

**Comment by dacstyle** [comment]
Sorry I missed to mention that I'm using VPX 10.8 GL x64 build 1514

Also had a simillar problem with the table GAY 90's the ball rises above the plunger and it's impossible to launch

**Comment by vbousquet** [comment]
I was not able to reproduce in latest build using your settings and the linked table. Does it still happen for you ? could you redownload teh table and check it it solves the problem ?

**Comment by dacstyle** [comment]
build 1540 and re download the table solved the problem, thank you!

**Comment by Drybonz** [comment]
Sorry for the delay.  Testing on 1541 x64, and I get the same problem.  I haven't reset/redownloaded the table.  Is this necessary?  If so, how do I determine which tables in my library would need replaced?  Would I need to test every table?  Is there a solution that would avoid this?  Thanks for the help.

**Comment by Drybonz** [comment]
Works perfectly now, tested in 1577... but now DMD scores are gone from the desktop background on the same table.

**Comment by toxieainc** [comment]
@Drybonz Could you please file a new issue then? Thanks!

**Comment by Drybonz** [comment]
I'm on DX x64, not GL... but yes, Toxie, I can file a new issue.  Sorry about that.

**Comment by passionforpins** [comment]
DX version 1609 b2s with dmd works for me
![centaur-hauntdmd](https://github.com/vpinball/vpinball/assets/52011304/e0046648-a673-4ef1-bda0-b7e8419bfdbc)

**Comment by Drybonz** [comment]
Ok... well, I just updated from 1577 to 1610 and the DMD scores in desktop are showing normally.  So, maybe something happened in between those builds, or maybe I had some other weirdness going on.  Anyway, consider the new ticket opened and closed!   :D
Thanks.
