### ISSUE TITLE
Calibrated/fitted Anaglyph settings not properly saved

### ISSUE THREAD

**Issue by Duglim** [vpinball/vpinball#839]
I'm futher testing and adjuisting with anaglyph stereo 3D settings, this time with focus on the new eye calibration in Live Editor.

**Analysis:**
- There are default values per Eye and Color (Red/Green/Blue) per Anaglyph profile (e.g. Red/Blue, Magenta/Green, ...). These default values are saved in the .ini once you click "Reset" at least one time.
- - Default values for Red/Blue are: 
- - anaglyph1leftred = 0.930000
- - anaglyph1leftgreen = 0.220000
- - anaglyph1leftblue = 0.080000
- - anaglyph1rightred = 0.080000
- - anaglyph1rightgreen = 0.930000
- - anaglyph1rightblue = 0.320000

- If you did the Calibration of the profile, there are new "fitted" values per Eye and Color, that represent your calibration. They are also saved in the .ini after a calibration happened
- - Example calibrated values for Red/Blue are:
- - anaglyph1fittedleftred = 0.921338
- - anaglyph1fittedleftgreen = 0.065870
- - anaglyph1fittedrightred = 0.012416
- - anaglyph1fittedrightgreen = 0.854735
- - anaglyph1fittedgamma = 1.792889

**Finding:** 
There are no fitted values for ANY Blue color saved. 
I made a lot of tests with differnt profiles and also manually editing values in the .ini.
If I manually add values like "anaglyph1fittedrightblue = 0.5", there are actually visible changes on the table, so values for Blue are read from the .ini if present.

**Question:**
Is it correct, that fitted Blue values are never stored after the calibration? Is Blue irrelevant for the fitting and the default values always are the right ones? I wouldn't say so, but I could be wrong.

**Why I'm asking?**
I have 2 pairs of anaplyph grassis. Red/Blue and Magenta/Green (TrioViz). While I managed to find a nice calibrated profile for Red/Blue, I cannot get a good results with Magents/Green so far. I have massiv ghosting and need more time to tweak the calibration. During this procedure, I wondered about the missing fitted Blue values, since this could be a cause of my issues.

Greetings und thx again, 
Duglim

**Comment by vbousquet** [comment]
This is normal and not a bug (blue is computed from others). Anyway this part is under heavy development and should entirely change in the coming weeks
