### ISSUE TITLE
Unable to change text boxes size

### ISSUE THREAD

**Issue by jpsalas59** [vpinball/vpinball#84]
**Describe the bug**
If you try to change the font size of a text box it will always be 43.

**To Reproduce**
Add a simple text box to the backdrop and try to change the font size.

**Expected behavior**
I expect to show the old font size when editing an existing text box, but it always shows 43. After changing the size and opening again it will show the font size also as 43.

**Screenshots**

**Crash dump**

**Versions**
 - VPX: all 10.7 versions, even the last beta one. 10.6 worked fine.
 - Windows version 10 Pro
 - The bug is present on any GPU

**Additional context**

**Comment by fuzzelhjb** [comment]
fixed with the next build

**Comment by jpsalas59** [comment]
Thanks fuzzel!
