### ISSUE TITLE
I get an error every time when I run a table in the latest version of VP via PinUP Popper, I am attaching a picture

### ISSUE THREAD

**Issue by eliory** [vpinball/vpinball#852]
Hi champs, 

Everything works fine through the explorer, but when  I'm trying to launch a table in PinUP Popper, I get the following error attached in the following image.

**I'm getting the same error with this versions:**
[VPinballX-10.8.0-1514-edd129c-Release-win-x64]
[VPinballX_GL-10.8.0-1514-edd129c-Release-win-x64]

![vp](https://github.com/vpinball/vpinball/assets/114809420/64b9ee0b-042a-4128-a472-e89240b6857f)

**I want to point out that I update all your new versions, and so far everything has worked fine, this is the first time this has happened.**

**Comment by studlygoorite** [comment]
If the VPinballX.exe has a "64" try removing the "64" from the .exe name.

**Comment by eliory** [comment]
> If the VPinballX.exe has a "64" try removing the "64" from the .exe name.

There is no "64" in the name of any of the files, neither the 32 bit nor the 64 bit nor in GL.

**Comment by francisdb** [comment]
Vpinball now has stricter argument validation. Looks like you pass a `-`. Check your popper setup.
See #793

**Comment by studlygoorite** [comment]
> > If the VPinballX.exe has a "64" try removing the "64" from the .exe name.
> 
> There is no "64" in the name of any of the files, neither the 32 bit nor the 64 bit nor in GL.
> 
> **Hope I can fix it, this is very strange, me and a friend installed the latest version together and the friend has it working fine, and we did the same thing.**

From your top pic it shows you are using the VPinballX-10.8.0-1514-edd129c-Release-win-x64, the .exe will look like this VPinballX64.exe  See the 64 in the name, try removing it.

**Comment by eliory** [comment]
> VPinballX

My launcher is like this - "VPinballX.exe"

**Comment by passionforpins** [comment]
> > VPinballX
> 
> My launcher is like this - "VPinballX.exe"

Well then it's most likely launching vpx 10.7 or vpx 10.8-32. If you want your launcher to launch vpx 64 then thats what you need to point it to, ie, vpinballx64.exe. Or, as studlygoorite suggested rename the vpinballx64.exe to vpinballx.exe.

I use Launchbox and have all my vpinball executables named like this;
VPinballX.exe (this is vpx 10.7.4 32 bit)
VpinballX-64.exe (this is 10.7.4 64 bit)
VpinballX8-32.exe
VpinballX-64.exe
In launchbox I add these as separate emulators so they are available to choose if a game requires a specific version.

**Comment by eliory** [comment]
> > > VPinballX
> > 
> > 
> > My launcher is like this - "VPinballX.exe"
> 
> Well then it's most likely launching vpx 10.7 or vpx 10.8-32. If you want your launcher to launch vpx 64 then thats what you need to point it to, ie, vpinballx64.exe. Or, as studlygoorite suggested rename the vpinballx64.exe to vpinballx.exe.
> 
> I use Launchbox and have all my vpinball executables named like this; VPinballX.exe (this is vpx 10.7.4 32 bit) VpinballX-64.exe (this is 10.7.4 64 bit) VpinballX8-32.exe VpinballX-64.exe VpinballX-GL64.exe In launchbox I add these as separate emulators so they are available to choose if a game requires a specific version.

I've tried this, and it didn't help me mate

**Comment by eliory** [comment]
> Vpinball now has stricter argument validation. Looks like you pass a `-`. Check your configured popper vpinball emulator launch script. See #793
> 
> Documentation is here [https://www.nailbuster.com/wikipinup/doku.php?id=emulator_vpx&s[]=emulator#launch_script_default](https://www.nailbuster.com/wikipinup/doku.php?id=emulator_vpx&s%5B%5D=emulator#launch_script_default)

I'm trying to understand what's the next step for me to solve this with what you attached and I really don't know what to do now :)

**Comment by passionforpins** [comment]
> Vpinball now has stricter argument validation. Looks like you pass a `-`. Check your configured popper vpinball emulator launch script. See #793
> 
> Documentation is here [https://www.nailbuster.com/wikipinup/doku.php?id=emulator_vpx&s[]=emulator#launch_script_default](https://www.nailbuster.com/wikipinup/doku.php?id=emulator_vpx&s%5B%5D=emulator#launch_script_default)

Aha. A couple of vpx versions ago vpx 10.8 any revision would stop when launched from Launchbox with a similar error as eliory. The error notification was specific though. It did not like "-exit" in startup parameters. The default parameters for vpx in launchbox is -minimized -exit -play.  I removed the -exit and it then worked. However, just yesterday I put the -exit back in and vpx 10.8 all revs work without error.

**Comment by toxieainc** [comment]
Yes, i added support for '-exit', too, in the meantime.

So should be fine now, closing.
