### ISSUE TITLE
Ball vanishes in plunger lane with Abracadabra and Astro

### ISSUE THREAD

**Issue by Duracuir62** [vpinball/vpinball#853]
Abracadabra and Astro  work perfectly with 10.8.0-1347. But with 10.8.0.1514, the ball dont come in plunger lane. It seems the problem appears with some old table

**Comment by michroch** [comment]
Same for me also, ball won't come out with Abacadabra table, use to be fine before updating to build 1514

**Comment by Drybonz** [comment]
See bug report #836

**Comment by vbousquet** [comment]
Duplicate of https://github.com/vpinball/vpinball/issues/836

**Comment by toxieainc** [comment]
@Duracuir62 Can you please verify if this issue is solved for you with latest builds?
Cause the possible duplicate #836 was fixed.
