### ISSUE TITLE
Store settings in INI, JSON, etc --- not Windows Registry

### ISSUE THREAD

**Issue by Ltek** [vpinball/vpinball#854]
Please change all settings storage to be file based, and remove all from the Windows Registry

This is far better for multiple reasons...
Backup/restore is easier
Portability is easier
This will also help us manually inject settings when VP has inefficiencies or out right hoses something... like Display Order Enumeration. We can much easier write a text, json, etc file with the proper display order and settings prior to loading VP since VP likes to change this on its own if the displays enumerate differently.

... windows registry is only a benefit if the settings need to be secured by the OS.

**Comment by Duglim** [comment]
Had a similar thing last week and you can easily solve it. 
Just launch vpinballx.exe with the parameter `-ini "name of you inifile.ini"`. 
It will create the .ini file on first run and you can edit or copy it afterwards. 

This way, you could also have different settings via different .ini-files. 
E.g. you could edit the popper launch script a bit and open specific tables with different inis. In my case, I needed to activate supersampling 75% on the newest VPW tables, as they are too demanding for 120 fps in 4K. 

Greetings, Duglim

**Comment by KrakenByteKraken** [comment]
Good ideas, I think. But, maybe...

Perhaps I'm wrong but, I thought that all these new and good improvements were now yet included in the last 10.8 releases, aren't they?

**Comment by toxieainc** [comment]
Yup, this is already done in 10.8 beta: https://github.com/vpinball/vpinball/blob/edd129cdae4f990b2f67fcf3a64c5e05999aed02/txt/Changelog.txt#L94
