### ISSUE TITLE
Toggling 3D with table running produces wrong output

### ISSUE THREAD

**Issue by julianmrodri** [vpinball/vpinball#857]
There seems to be a bug in VPX 10.8 when the 3D is toggled ON with F10, once the table is already running.  

In my case I use Cyan/Red as preferred method. Funny thing, If you close the table and reopen it with 3D enabled, it works perfectly and the image shows correctly. You can then switch with F10 with no issues.

But when the table is opened with 3D disabled, and you click F10, the image looks pretty bad.  Below is an output for the latest GNR from VPW, when toggling Cyan/Red with F10, once the table opens and is running. You can see the image is not correct at all.

There seems to be a different behavior when you toggle for the first time with F10 the 3D stereo  vs. when you open it directly with 3D enabled.

![WhatsApp Image 2023-10-02 at 11 56 40](https://github.com/vpinball/vpinball/assets/56316686/168af8c6-e620-40b7-ace0-e5a7dccc9512)

Im using VPX 10.8 1514 GL version, and was able to replicate this with many tables.

Any additional info you need please let me know.

**Comment by vbousquet** [comment]
This part has been completely rewritten. Are you still experienceing issues ?

**Comment by vbousquet** [comment]
Without additional feedback and since this has been rewritten and is working as expected on my side, I will close the issue
