### ISSUE TITLE
pause button

### ISSUE THREAD

**Issue by dacstyle** [vpinball/vpinball#866]
First and foremost, I want to thank you for bringing VPX to life. The emulation of the tables has truly reached incredible levels.

If possible, I would like to add a native PAUSE button to VPX, as many of us find ourselves needing to use this feature when playing at home.

Ideally, the user should be able to choose which key activates the PAUSE mode, so that each user can adjust it according to the key availability on their cabinet.

**Comment by vbousquet** [comment]
Added in latest
