### ISSUE TITLE
Question: Window POV rendering and Stereo separation changed. Please help.

### ISSUE THREAD

**Issue by Duglim** [vpinball/vpinball#868]
Since build 1523 I see a drastic changes how window POV is rendered. There are also new settings for inclination and some POV settings are now global. 
Could you help a bit and explain how things are working now? 

**My problems:**
- Anaglyph 3D separation (Real 3D, GL) is much to high. Separation of 66mm is gigantic. Anaglyph is unusable right now. (Edit: Fixed in built 1529)
- My former Player Y of 5cm produces a very strange view.  It gets better if I set it to negative values. Is this correct?
- POV menu shows a new "Camera position", which is similar to my Player settings, but Y is slightly off. What is the camera position? Why Camera is not = Player?
- I see new "Inclination" in the settings and DOC. Should I use this now instead of the Table top/bottom offset? How do both work together? Would this maybe be redundant?
- Why do the tables now have much more depth view? I try to understand the new rendering logic but cant get it. :) 

Maybe @vbousquet could help a bit and tell more about the recent changes? 
Thx, Duglim

**Comment by Duglim** [comment]
I took some time to test with the recent built 1529 to understand the new settings better. 

**Stereo Anaglyph stuff:**
- Stereo 3D separation is fixed. Thx @vbousquet :)
- All Anaglyph profiles besides Red/Cyan (the first) are bugged. I tested with Magenta/Green and even after calibration it goes back to some blueish colors. I will open a bug for this, if you dont mind.
- Setting a correct "Inclination" in the video settings (for me 6%) seems to make the "Table Top/Bottom offset" obsolete. In Stereo 3D the Zero-Depth layer is wonderful aligned at the table playfield on bottom and top. Seems like inclination is the key here, so you can have a nice slope and the zero depth is not flat but also inclinated. Really really nice! I could only think of a need for "Table Top/Bottom offset", if a table would have bad coding and you would need to manually adjust the zero line. But maybe you could explain more, why the offset options are still there.

**Perspective-Stuff:**
- All tables seem to have much more z height. I look "into" the playfield, not from bird perspective, BUT....
- I need to set not real values for Player Y and Player Z:
- - Player Y shows the table in a quite big angle, even if I set it to 0. A value of -5 seems nice, it was +5 before. 
- - Player Z 60-70 shows the table from a quite low perspective. A value of 80 seems nice, it was 67 before. 

I know, my pincab is a small one, just 28'' screen and just 6% screen inclination. 
Maybe this has to do with my observations. Maybe the Real2Virtual calculation has problems with small screen sizes and the new inclination setting. 

Keep on your great work @vbousquet, I love testing every new stuff. :) 
Greetz, Duglim

**Comment by eighties8** [comment]
These are helpful comments Duglim. I experienced the similar 3D misalignment issues last night upon testing with #1526 in OpenGL 64bit on a 43" Asus 144hz display at 10bit color.
For me, in addition to the stereo separation issues, the POV menu could only be read cleanly with one eye closed. Perhaps a stereo separation issue there. I'll take latest as of today as you indicate some things should be fixed since #1526 build

**Comment by Duglim** [comment]
@eighties8 yes, the separation was quickly fixed an hour ago by @vbousquet. I was very happy, as I can continue testing now.

**Comment by Duglim** [comment]
**Further testing and understanding:**

- The new "inclination" seems not to define the angle the playfield is angled, not rather how all objects on and above the playfield are angled. So this would explain to me, why "Table Top/Bottom Offset" is still needed.
- - I could use "Table Top/Bottom Offset" to have the playfield/table correctly angled for my screen
- - I could use "Inclination" to have the objects on the playfield perspectivly correctly aligned in Y/Z direction

**This is resulting in an Anaglyph problem:**
- Using a "Table Top/Bottom Offset" shifts the playfield away from the Zero-Depth-Layer. I think, it's really needed to have the playfield on 0-Depth, otherwise it's not sharp and causes a lot of eyestrain. 
- Idea: Realign the 0-Depth-Line automatically to match with the "Table Top/Bottom Offset"?!

**Comment by vbousquet** [comment]
This part has been completely rewritten. Are you still experiencing issues ?
The meaning for top/bottom offset and inclination is given in the docs (see the figure).
Note that this part should be changed before next beta to have the top/bottom being defined relatively from the table top/bottom glass height
