### ISSUE TITLE
Add button assignment for left/right nudge to left and right mouse click, VPX allows to assign to flippers but not to nudge

### ISSUE THREAD

**Issue by BostonBuckeye** [vpinball/vpinball#871]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by francisdb** [comment]
Now I am wondering how you are planning to flipper and nudge if one hand is on your mouse? Do you use the side buttons as flippers?

**Comment by BostonBuckeye** [comment]
> Now I am wondering how you are planning to flipper and nudge if one hand is on your mouse? Do you use the side buttons as flippers?

Hi, I have an X-Arcade Tankstick that has two side buttons on each side of the control panel to use for pinball. The first set are programmable and I like to use them for the flippers. The second set which are a little further back on the side of the control panel I like to use to nudge so that I don't have to take my hands off the side of the panel while playing. Just my finger. These two buttons are hard wired to left/right mouse click.

**Comment by BostonBuckeye** [comment]
I currently use an Autohotkey script to disable the left/right mouse clicks and re-assign them to a keyboard character. It works okay but I feel the hotkey may be causing some minor issues within VPX. I also don't like having the right/left mouse click disabled. I know there are other programs I can use to re-map buttons but having it built into the program is optimal. I realize I probably am the only one requesting this feauture. If it is too difficult to implement it then I understand. Thank you very much for responding to my request.

**Comment by kenangel** [comment]
Found myself interested in this same thing and think I have something working to allow left,right, and center nudge with mouse buttons.

Going to test this on my arcade for a bit this evening and if it checks out I'm happy to submit a PR.

**Comment by toxieainc** [comment]
Sounds good!

**Comment by BostonBuckeye** [comment]
Thank you very much!

**Comment by kenangel** [comment]
PR #1512 opened for this, tested with Nudge test and Attack from Mars tables. Also cleaned up some hard binding between mouse buttons and flippers to make this more flexible.

Wanted to make this code less-horrible, but didn't see a way to cleanly map mouse/joy keys to the keyboard Assignment Enums without a ton more work.

It will bug me so I may keep staring at it, but have something that at least works.

Note: Debug builds Pause on Right Click, so testing right click is exciting.
