### ISSUE TITLE
Ball falls through playfield mesh and wall on trough eject - 

### ISSUE THREAD

**Issue by a-bord** [vpinball/vpinball#880]
With recent updates to VPX 10.8 the ball falls through the playfield mesh and a wall beneath the playfield when ejected. Does not happen with 10.8 beta or previous versions of VPX.

![image](https://github.com/vpinball/vpinball/assets/90645800/a875040d-79e1-4e7f-8438-6f5e9a744354)

Haven't seen this on other games, but on this in-progress version of EBD the ball falls through the playfield on launch. Works fine if I revert to older VPX versions, including 10.8 beta.

https://drive.google.com/open?id=1LYDs_04ivJ16i0QaqDvbiSlLNCk-Du6y&usp=drive_fs

**Comment by toxieainc** [comment]
Maybe related to #836 and #853

**Comment by vbousquet** [comment]
Ok, I can reproduce with the file you attached. I will try to understand what changed here

**Comment by dacstyle** [comment]
I had this problem with centaur table, and seems the issue was caused because I save the table with some build that causes that problem (maybe 1504). When I downloaded the table again and tested with 1541 there is no issues.
