### ISSUE TITLE
Crash when exiting a table

### ISSUE THREAD

**Issue by jpsalas59** [vpinball/vpinball#881]
**Describe the bug**
A crash happens sometimes when exiting a table, but not always. It has happened in almost all versions of 10.8
This is the crash.txt:
Crash report VPX rev1529 (5fb73cc)
============
Process: VPinballX.exe
Reason: 0xC0000005 - EXCEPTION_ACCESS_VIOLATION at 0023:0043797B
Attempt to write to 0x09553C84
Thread ID: 0x1090 [4240]

Call stack
==========
0043797B VPinballX.exe (0x00000010 0x00000000 0x00000000 0x00080766)
0057B4A1 VPinballX.exe (0x00000010 0x00000000 0x00000000 0x00000010)
00437337 VPinballX.exe (0x004372E0 0x00080766 0x00000010 0x00000000)
75AC3736 USER32.dll CallWindowProcW + 0x716 (0x004372E0 0x00000000 0x00000010 0x00000000)
75AC31BA USER32.dll CallWindowProcW + 0x19A (0x03F173B0 0x00000000 0x00000010 0x00000000)
75ACD0BF USER32.dll GetPropW + 0xFF (0x0019EF9C 0x00000020 0x0019F0B4 0x76ff86a0)
76FF876D ntdll.dll KiUserCallbackDispatcher + 0x4D (0x03F173B0 0x00000000 0x00000000 0x00000001)
75AD90C8 USER32.dll SetWindowsHookExAW + 0x198 (0x00000000 0x00000000 0x00000001 0x0f6ffce0)
75B371CD USER32.dll SendMessageA + 0x3D (0x00080766 0x00000010 0x00000000 0x00000000)

Environment
===========
Date/time: 8/10/2023, 06:01:43:677
Number of CPUs: 16
Processor type: 586
System: Windows 10 (10.0 22621)

Memory status
=============
Total Reserved: 243976K (238M) bytes
Total Commited: 334044K (326M) bytes
Total Free: 3616220K (3531M) bytes
Largest Free: 2095668K (2046M) bytes

Registers
=========
EAX=00000000 EBX=00000000 ECX=0019F1B8 EDX=03555860
ESI=09553C80 EDI=00000010 EBP=00000000 ESP=0019F068 EIP=00578BDD
FLG=00010202 CS=0023 DS=002B SS=002B ES=002B FS=0053 GS=002B

Mini dump saved successfully.
**To Reproduce**
Run a table, quit the table and sometimes instead of the editor coming back, VPX crashes.

**Expected behavior**
To do not crash and open back the editor.

**Screenshots**

**Crash dump**
This is the dump file:
https://drive.google.com/file/d/1kks1ed02Sux21f6r1Eoywo1dBSiXXMbw/view?usp=sharing

**Versions & Settings**
 - VPX: it happens in all the versions of 10.8 I have tried.
 - Windows 11 22H2
 - NVidia GTX 3080, driver version 536.40, but it happens with other drivers too.

**Additional context**

[VPinballX.zip](https://github.com/vpinball/vpinball/files/12839760/VPinballX.zip)

**Comment by vbousquet** [comment]
Just pushed a fix for this. Could you confirm that everything is good for you and I can keep this issue closed ?

**Comment by jpsalas59** [comment]
I have tried the latest revision many times, and it has not crashed once, so it seems to be good :)
Thanks for fixing this so fast :) It was annoying when building and testing tables :)

**Comment by passionforpins** [comment]
I just tested JP's Hawkman, Lunelle and Mr Black and it looks like the close without having to ctrl-alt-del anymore. YAY! fingers crossed it holds true. I tried each one 5 times in dx x86 and x64 and so far so good. One immediate giveaway was with Hawkman the lane changes would lag terribly. With rev 1544 there is no lag on lane change. Fingers crossed you nailed it Vincent!
