### ISSUE TITLE
Window pov  player y and player z  problem

### ISSUE THREAD

**Issue by Pinbalbilly** [vpinball/vpinball#884]
**Describe the bug**
Settings "player y" and "player z" in the cabinet layout options are modified when you set a POV for a specific table, it is impossible to use a different player y or z for different tables

**To Reproduce**
1. Go to 'vpx GL 64  1543'
2. Click on 'open any table in camera mode F6 window mode, choose player z or player y different from the one we have in cabinet laylut in video options, save POV, close the table.

3. We see that the changes of player z or player y have been changed in video options / cabinet layout to the ones we have put in the last table.

**Expected behavior**
The general options of player z and player and within the video/cabinet layout options should not be modified to create a specific POV for a table, because it will always save the last modification and break another POV that we have from another table with player z and player and different .  Excuse my English, I am using the translator, thank you.

**Versions & Settings**
 - VPX: 10.8 GL 64  1543
 - Windows version Windows 10

**Comment by vbousquet** [comment]
This is the intended behavior. As stated in the doc, the player X/Y/Z of window mode is not per table but a global setting. You should not have to tweak this. If you still want to do it, you can have a per table ini with whatever option you want to tweak

**Comment by Pinbalbilly** [comment]
Thanks.
