### ISSUE TITLE
Improved SDL window overlaying #883 causes troubles in Standalone Player on MacOS

### ISSUE THREAD

**Issue by cwscws** [vpinball/vpinball#887]
With this "fix" the standalone player on MacOS X is ruined. The improvement seems to help Windows only.

Before this the windowed fullscreen mode made it possible to display all 3 windows (main player window, b2s and dmd) on one single screen. Now this is not possible anymore. The main player window always is in front and pushes the other windows to the back and as they are not windows with frame there is no possibility to manually arrange them in front.

Can you revert that? Or a better solution? Keep in mind this should be multi system compatible.

**Comment by jsm174** [comment]
@cwscws  - I have temporarily reverted the https://github.com/vpinball/vpinball/pull/883 changes in standalone. 

Mac is a different beast when it comes to windowing, so I'm hoping that SDL3 ([this](https://github.com/libsdl-org/SDL/issues/7364)) might solve some of our issues.

**Comment by francisdb** [comment]
@cwscws many things have changed meanwhile, can this be closed?

**Comment by jsm174** [comment]
Yes, this was all fixed.

Also related:

`-listres` was updated to show fullscreen desktop modes too:

```
2024-06-20 07:26:11.338 INFO  [11696] [VPApp::InitInstance@950] Available window fullscreen desktop resolutions:
2024-06-20 07:26:11.338 INFO  [11696] [VPApp::InitInstance@954] display 0: 2560x1440 (refreshRate=60)
2024-06-20 07:26:11.338 INFO  [11696] [VPApp::InitInstance@954] display 1: 1728x1117 (refreshRate=120)
```

`FullScreen = 0`, `Width = 2560`, `Height = 1440`, windows can be overlayed on macos.
