### ISSUE TITLE
The Ball "flies" 1-2cm above the Ringmaster "Spell wow" magnet of Cirqus Voltaire (Bally 1997) VPW Mod

### ISSUE THREAD

**Issue by TurboHenk** [vpinball/vpinball#890]
**Describe the bug**
The magnet at the Ringmaster "Spell wow" magnet should hold the ball, but instead it "_flies above that magnet_" for 1-2cm.

**To Reproduce**
Play Cirqus Voltaire (Bally 1997) VPW Mod and shoot the ball a few times on the Ringmaster until the magnet catches it (see rules of the table). 

The table can be downloaded here: https://vpuniverse.com/files/file/15989-cirqus-voltaire-bally-1997-vpw-mod/

A similair bug also happened in the Monster Bash VPW table: https://vpuniverse.com/files/file/9091-monster-bash-williams-1998-vpwmod/ with the magnet that should hold te ball at the left side of the table (above the green hologram "Creature feature"). But here it floats only ~a half cm. So it's way more clear at the Cirqus Voltaire table but the bug is the same.

**Expected behavior**
It should be stuck on the magnet, as it was in previous releases. 

**Screenshots**
I can supply a screenshot if wishes, but I think that it's quite clear.

**Versions & Settings**
 - VPX: VPinballX_GL-10.8.0-1544-132c40f-Release-win-x64 This didn't happen in releases from a few weeks ago(at the time of the Cirqus Voltaire release I had a recent build that worked perfect), so it's caused by "a recent change".
 - Default table settings, no slope or anything changed manually, everything default.

**Comment by vbousquet** [comment]
Solved in 1552
