### ISSUE TITLE
Ball does not sink down into kicker hole.

### ISSUE THREAD

**Issue by matsbar** [vpinball/vpinball#891]
**Describe the bug**
Ball does not sink down into kicker hole when caught, but stays at playfield level.

**To Reproduce**
Play a table with kicker holes for instanche 
Harmony (Gottlieb 1967) 1.0
https://www.vpforums.org/index.php?app=downloads&showfile=14242

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**
Ball should sink down into kicker hole when caught.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://ibb.co/FXrJH2x

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 VPinballX_GL-10.8.0-1547-bd951f1-Release-win-x64
VPinballX-10.8.0-1547-bd951f1-Release-win-x64

Windows 11 Pro 

 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**

**Comment by vbousquet** [comment]
Solved in 1552
