### ISSUE TITLE
Standalone: collaboration hindered

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#893]
Collaborating on the development of vpinball standalone is a pain. The branch contains a single squashed commit that is being re-based/squashed every day. I understand this is to keep things manageable for a 1-man team but it comes with a whole list of issues:

- No way to know why things are done a certain way because there is no code history
- No way to find out what code has changed between builds
- PR's need to be rebased every day
- Contribution history is lost
- Hard to see dependency updates
- Keeping track of existing issues is done in some not trivial to find readme
- Any commits to the main branch don't consider what is in use on standalone

@jsm174 has done a tremendous job setting up standalone. It's about time other people can join in on the effort.

**Describe the solution you'd like**

I'd like to see standalone merged into master. At least the `linux` and `macos` portions of it. The sooner the better.

**Comment by toxieainc** [comment]
We are obviously fully aware of that and everything is according to plan so far.
Instead of keeping it closed/private while heavily WIP, jsm opted to have it visible to everyone, so please take that open branch as a bonus-gift instead.
As soon as VPX 10.8 is out the door, standalone will come back into main, and collaboration will be working as before.

**Comment by freezy** [comment]
@jsm174 if the reason why you're squashing is avoiding to resolve the same conflicts over and over, [`git rerere`](https://www.git-scm.com/book/en/v2/Git-Tools-Rerere) might be your friend.

**Comment by jsm174** [comment]
Awesome. I will check it out!

fwiw, I know rebasing is not the best way to do things, but I have been trying to keep an accurate change log in the readme.

**Comment by droscoe** [comment]
> @jsm174 if the reason why you're squashing is avoiding to resolve the same conflicts over and over, [`git rerere`](https://www.git-scm.com/book/en/v2/Git-Tools-Rerere) might be your friend.

Wow!  That sounds cool.. never knew about this feature.

**Comment by francisdb** [comment]
Just for reference
https://github.com/vpinball/vpinball/issues/351#issuecomment-1829496816

**Comment by vbousquet** [comment]
Merged done for 10.8.1. I will close this one then
