### ISSUE TITLE
VPX_GL crashes with every table after closing (v1559 and some older versions)

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpinball#895]
**Describe the bug**
In the last program versions of 64bit VPX_GL (last v1559) always crashed after the table was closed.
It doesn't matter whether I start the respective table with a double click or via the editor with F5.
As soon as the table is closed, the VR window stays open for a few seconds.
Then both the VR window and the editor are closed and a crash file is written.
The v1514 works.

**To Reproduce**
Start the table with the _GL v1559 64bit with doubleclick or with F5 in the editor
Exit the table.
Table and Editor crashes

**If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.
Happens with all tested tables.

**Crash dump**
[crash.txt](https://github.com/vpinball/vpinball/files/12871067/crash.txt)
https://mega.nz/file/0QlHnIqS#Eb4NUb_FFS5T5xayFu-QpsGhKS-a6IEQaSl7SPo-ijQ

**Versions & Settings**
 - VPX_GL 1559 (and some older versions)
 - Windows version 10
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
[VPinballX.log](https://github.com/vpinball/vpinball/files/12871098/VPinballX.log)

**Comment by Joey-2001** [comment]
I tested the v1570 and the same issue occures.

**Comment by Joey-2001** [comment]
I tested the older versions. The last working version is v1544. There were no crashes at ending.
With v1547 the player window freeze and table and editor crashes while esc from table.

**Comment by vbousquet** [comment]
Could you run with a debug build and share the crash.txt ? I can't reproduce this bug on my side

**Comment by Joey-2001** [comment]
There is nothing more in the crash.txt either. But maybe you can do something with it.
Here is the file. I have used the debug version 1579 64bit.
If you want me to try something else, please contact me.
The change must have been made between these two versions:
Improve SDL window overlaying #2045 (works)
https://github.com/vpinball/vpinball/actions/runs/6447929544

Rewrite regutils to allow clean separation between app settings and t... #2048 (crashes)
https://github.com/vpinball/vpinball/actions/runs/6450048930

[crash.txt](https://github.com/vpinball/vpinball/files/12894479/crash.txt)
