### ISSUE TITLE
Standalone GL-10.8.0-1554, issues on Macbook Pro with M1 Pro, Monterey

### ISSUE THREAD

**Issue by sjudkins** [vpinball/vpinball#896]
**Describe the bug**
When I start the the standalone from the command line (I have only tried the three included tables: Screen Size Calibration, Nudge Test and Calibration and the Elasticity Test). 

- No Command Line Options. The app and table load, but it takes over all 3 of my displays (goes full screen) and seems to "freeze". I waited 15 minutes (I could still hear the app accepting keys up until the buffer was full, then if I hit Escape, it would accept keys again.)
- -DisableTrueFullScreen - The app and table load in a window (that I can't resize)  but they all seem to work. 👍  (I noticed the following errors are always logged: "MessageBox(): caption=Visual Pinball Error, text=Failed to create the synchronization device.
Synchronization switched to adaptive sync." AND "[RenderDevice::CreateDevice@1133] Failed to create the synchronization device for frame pacing. Synchronization switched to adaptive sync."

Note: I can't get any of the downloaded tables to start/play... (Guns N Roses, Popeye, Rollercoaster Tycoon) I always get messages about missing files (in VPinMAMEController) and "SOUND WAS DISABLED DUE TO PROBLEMS WITH SOUND ROMS
ERROR: required files are missing, the game cannot be run."

I "assume" the message "ERROR: required files are missing, the game cannot be run." is the reason I can't get any of them to start?

I am running version "GL-10.8.0-1554".

My Hardware Info:

 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	8422.121.1
  OS Loader Version:	7459.141.1

3 Displays: 16" 3456 x 2234 "built-in", 2 x HP P27h G4 (1920 x 1080)

I know I didn't follow the template. The truth is, I didn't really want to do this post here, but it seemed like the best place to start, for getting info on the "Mac" version of the app.  (Also, I have over 34 years experience in Software Engineering and may be interested in contributing in the future, maybe "after" I get my homebrew pin finished.) Anyway.. if I need to add additional info, I certainly can do that. Or, if you would rather me start in a forum or some other venue, please let me know. Otherwise, I am willing and happy to be a "beta tester" for the Mac version.

**Comment by jsm174** [comment]
Hello. 

Roms go in

`~/.pinmame/roms`

It's a dot directory, so it is hidden.

We have a discord channel for help here:

https://discord.gg/HFUkaBPD

**Comment by sjudkins** [comment]
Thanks for the nudge.

**Comment by francisdb** [comment]
> the following errors are always logged: "MessageBox(): caption=Visual Pinball Error, text=Failed to create the synchronization device.

This is normal for now as frame pacing is not available on standalone. Maybe we can change the default for standalone or have this logged more as a warning with context.

**Comment by jsm174** [comment]
I really would love to implement frame pacing. I've looked for ways to get vsync callbacks on Mac (`CVDisplayLink`?), iOS, Android, and Linux. I believe windows is using a DXGI function even on the GL version. 

I can't find anything comparable cross platform or in SDL2.
