### ISSUE TITLE
screen left at 200% causes dmddevice.ini settings to be doubled.

### ISSUE THREAD

**Issue by ivo71** [vpinball/vpinball#902]
**Describe the bug**
I am not sure if this is a bug or if this is just supposed to be different in 10.8 vs 10.7.
When leaving the playfield screen accidentally at 200%, versions before 10.8 save the settings of the external dmd correctly in dmddevice.ini.
When at 200% and starting 10.8 and saving the position of the external dmd, the saved settings are halved and when loading a table with the correct dmd position settings, the value is doubled before it is displayed. For example when the dmd position is saved at x=4400, then 10.8 will display it on x=8800, which then results in seeing only the dmd window (using alt-tab) with a pinballX logo in it.

**To Reproduce**
1. set windows playscreen at 200%
2. start vpx 10.8 and load a pinball machine.
3. save correct settings of external dmd.
4. check dmddevice.ini and notice that the saved settings will be half of the actual setting.

**Expected behavior**
Position of DMD correctly saved and displayed without being affected b the 200% setting.

**Comment by Rappelbox** [comment]
screens shouldn't be scaled as it causes much trouble on various programs, not only vpx. Pinup sytsem, puppacks and external dmddevice.dlls are all affected by scaling. To be honest, i CAN understand the need for bigger mouse arrow, folders, text and such ;) If you need to change settings try to do it on your fullhd screen, like the backglass or fulldmd screen if you have one.

**Comment by francisdb** [comment]
> screens shouldn't be scaled as it causes much trouble on various programs, not only vpx.

With 4k screens it's not a matter of choice. Good to report these issues so they can actually be fixed. However this probably needs to be reported at https://github.com/freezy/dmd-extensions

see also https://github.com/freezy/dmd-extensions/issues/354

**Comment by Drybonz** [comment]
People no longer leave their Windows scaling at 100%.  That is a practice from years ago.  Using scaling is now a common practice.  Developers are not be "forced", simply asked to implement what is now incredibly common.

**Comment by ivo71** [comment]
I don't really mind if you  change it in the program or not, I just noticed that 10.7 handles this differently.
Working at 200% on a 4k screen is a lot more comfortable, especially when getting older ;-)
I know I am supposed to switch to 100%, but sometimes I forget and then my external dmd is not shown in 10.8.
Because I could imagine everybody always using 100% as they're told to, that if this is a bug, the chance of finding it would be small, therefore I mentioned it. I am happy either way, but it has cost me a lot of grief and about 4x a complete new installation before I found out by accident that the virtual dmd wasn't shown in 10.8 because my screen was still set at 200%. 
In 10.7 I didn't have any problems and noticed that the layout of scores was sometimes a bit out of proportion, but while adding tables that is not an issue, only when playing.
Anyway, thanks for all the replies.

**Comment by vbousquet** [comment]
VPX 10.8 is now fully "DPI aware" so you can set whatever DPI scale you want to each of your screen. Before 10.8, it would not handle it correctly and would hide it from its plugin. The side effect of this improvment is that other apps may have to be adjusted, depending on how they are made, this may need to change their settings (or perhaps the author to update their app). Still being able to change the DPI scale with VPX handling it correctly is the expected behavior.
