### ISSUE TITLE
Visual Nudge Strength not working

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/vpinball#911]
Visual Nudge Strength not working in 10.8 DX or GL   Still works in 10.7.4
No matter what you put in as soon as you close the window the number resets to 0.000000
preferences  video/graphics options
![n](https://github.com/vpinball/vpinball/assets/115115011/353c71b8-f4d3-44dd-84d8-3120923eb135)

**Comment by vbousquet** [comment]
This is fixed in latest
