### ISSUE TITLE
Save all from Live editor

### ISSUE THREAD

**Issue by MikedaSpike** [vpinball/vpinball#913]
**Is your feature request related to a problem? Please describe.**
When changing multiple objects (lights/primitives/walls etc) in LE and forgot to save some of those, it would be handy to get a popup with :" Unsaved changed are detected. Do you want to save all ?" when closing LE with the stop button.
With Yes/No and Cancel (cancel will jump back to LE) as question, we could decide what to do

**Comment by vbousquet** [comment]
The live editor is only able (at least for now) to edit the live table. This means that all property are being modified by the simulation, script or table author through the live UI. Therefore there is no way to identify who has modified what. what you propose would be meaningful if we would have a live editor for the startup table
