### ISSUE TITLE
Standalone: Fullscreen global setting not respected

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#915]
**Describe the bug**

Since yesterday tables start in fullscreen even with `Fullscreen=0` in the ini file
(standalone branch today)

**To Reproduce**

Use these global settings in `VPinballX.ini`

```ini
Fullscreen = 0
Width = 1080
Height = 1920
BGSet = 1
```

```
./VPinballX_GL -play res/exampleTable.vpx
```

You will see the table start fullscreen

**Expected behavior**

The fullscreen setting is respected and I get a window like it did the day before yesterday

**Workaround**

```
./VPinballX_GL -disabletruefullscreen -play res/exampleTable.vpx
```

**Comment by toxieainc** [comment]
I guess this may be due to Vinces changes that the exact case is now required?
https://github.com/vpinball/vpinball/commit/a70d861d7505504f4df161f4346a6524444403ab
So 'FullScreen'?

**Comment by vbousquet** [comment]
Yes, I think so. Sadly most config file will have to be remade but I still think this is a good thing to be done **before** 10.8 release since the ini holds quite a lot of information and it is far more readable with the case

**Comment by vbousquet** [comment]
Note that this file is automatically generated by VPX (on Windows) with the correct case

**Comment by jsm174** [comment]
Just to understand, the entries are now case sensitive in the ini file?

It looks like FullScreen is still Fullscreen in the default ini? 

https://github.com/vpinball/vpinball/blob/master/res/Default%20VPinballX.ini#L134C11-L134C11

**Comment by vbousquet** [comment]
My bad, FullScreen is the right name (legacy case that was used in Windows registry). I just miscased it when creating the default ini. Will fix

**Comment by francisdb** [comment]
Any plan to document that default ini (description, possible values, defaults) or is this already available elsewhere?

**Comment by vbousquet** [comment]
This is fixed in latest so I will close
