### ISSUE TITLE
Ball jumps out of playfield

### ISSUE THREAD

**Issue by francisdb** [vpinball/vpinball#923]
**Describe the bug**

on Airborne when doing a full force launch the ball leaves the playfield and floats somewhere on top

VPinballX-10.8.0-1585-518dce6-Release-win-x64 

On 10.8 beta 5 this does not happen

Table can be downloaded here (new Versins77 version has same issue)
https://www.vpforums.org/index.php?app=downloads&showfile=14974
https://vpuniverse.com/files/file/1281-airborne-capcom-1996-abv106/

https://github.com/vpinball/vpinball/assets/161305/0a2e75ce-de03-4901-aead-304dbfbaced7

**Comment by vbousquet** [comment]
This was fixed this morning
