### ISSUE TITLE
<Table Name>.ini file is created automaticaly at each started table in the table folder.

### ISSUE THREAD

**Issue by Mrtr32** [vpinball/vpinball#937]
A .ini file is created automaticaly at each started table in the table folder.

VPinballX-10.8.0-1606-ecffbb0-Release-win-x86

the lines in the ini file is:
**[Player]
BallTrailStrength = 0.490196**

Is it intended?

Thanks!

**Comment by Duglim** [comment]
Yes, it's new since yesterdays releases. The table inis hold some table settings and the POV settings. So far, the old .pov file is still created, don't know it it will be obsolete in the future.

**Comment by Mrtr32** [comment]
Ok good to know!

Thanks Duglim!

**Comment by Mrtr32** [comment]
Intended

**Comment by vbousquet** [comment]
It's not fully intended. So far (as we are in the middle of a large refactoring on how the settings are handled), it happens, but for a well behaving app, I would prefer the ini to be only created if the table is actually saved. I will reopen and see if this can be achieved
