### ISSUE TITLE
InGame AO and ScSp reflec options are gone

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpinball#940]
After the recent update (1602) I noticed under the table tab the: 4x AA (SSAA), Post-proc AA,, In-game AO, ScSp. reflect were removed.

I noticed if I turned off In-game AO and ScSp.reflect I got way better performance... the new versions seems to have these set to default automatically.

Is there another place I could turn these off?

**Comment by vbousquet** [comment]
Yes:
- for user settings, it's in video settings
- for table author, it's in table visual properties

**Comment by psiomicron** [comment]
Thanks, I've located it but I noticed if I unchecked the boxes, save it,
close and reload the table it sometimes rechecks the boxes.
