### ISSUE TITLE
Not a bug just a query please

### ISSUE THREAD

**Issue by Urkz** [vpinball/vpinball#945]
https://github.com/vpinball/vpinball/releases/tag/v10.8.0-1347-3d585e7  <<< this is the latest version of DX VPX im using 10.8 beta 5 ?, i have seen talk of higher numbers on the net.

Cheers.

**Comment by vbousquet** [comment]
Please use forums for this type of request like VPForum or VPUniverse

**Comment by gjupp** [comment]
@Urkz . Vincent is correct in asking you to use the various forums for this type of question, however the quick answer is to ensure you have a github account and are logged in to github, then click on the "Actions" tab at the top. You will likely then be looking for any release marked as "master", click on the latest release and scroll the page to find the newer files you need.

You wont be able to see these files if not logged in to github with your user account.

**Comment by jsm174** [comment]
https://github.com/vpinball/vpinball/assets/1197137/1305180e-cbc9-46b9-a737-3ae80bd9dae0

**Comment by francisdb** [comment]
⚠️ Be warned that these builds can mess up your configuration and are not considered stable.

**Comment by Urkz** [comment]
Im just staying with the latest posted here https://github.com/vpinball/vpinball/releases
