### ISSUE TITLE
Shaders issue or some other graphical issue - Not sure the cause but SS included. 

### ISSUE THREAD

**Issue by gear323** [vpinball/vpinball#952]
**Describe the bug**
I'm not sure if it is missing shaders or some other graphics changes but I noticed that at least with the GL version of 10.8  and playing in VR, materials have odd colors and no longer look how the author intended them to look,  I have included an example screenshot of T2 where the lock down bar, legs, side rails, gun etc. all have the issue. 

**To Reproduce**
Load a table and play

**Expected behavior**
The legs, lockdown bar and Gun handle should have a metallic look to it like it did on previous versions of VPX. 

**Screenshots**
![Missing Shaders or other change](https://github.com/vpinball/vpinball/assets/108252542/2d588001-6980-4978-9046-757045822134)

**Versions & Settings**
 - VPX: [e.g. 10.8  GL version 1609 (x64)
 - Windows version 11
 - GPU and video settings if applicable: Nvidia 3090

**Comment by gear323** [comment]
This table also has a weird graphical glitch  that never was there before that follows your head around now when moving closer to the table.     Screenshot below. 
![graphics issue](https://github.com/vpinball/vpinball/assets/108252542/61fd14bc-ff6d-4d86-a95c-550f75fd7358)

**Comment by gear323** [comment]
This is what is is supposed to look like 

![image](https://github.com/vpinball/vpinball/assets/108252542/df512f4c-4c22-47ca-b98e-04fe7080ee77)

**Comment by gear323** [comment]
Link to table 

https://vpuniverse.com/files/file/6032-terminator-2-g5k-minimal-vr-room-williams-1991/

**Comment by vbousquet** [comment]
I had a look and this is not really a bug. VPVR used to ignore the roughness of metal parts leading to non shiny parts being rendered shiny (here the material MetalShiny). This used to be a bug and in this situation, the bug is not on VPX side but on the table. So the table needs to be updated (put 1 in shininess instead of 0)
