### ISSUE TITLE
Error parsing POV XML file: 'desktop' element is missing

### ISSUE THREAD

**Issue by kapter316** [vpinball/vpinball#955]
**Describe the bug**
I'm currently on [VPinballX_GL-10.8.0-1610-64eafbe-Release-win-x64], when editing at POV xmal is only saving the 'customsettings' and nothing else. When opening the xmal i notice the 'desktop','fullscreen','fullsingscreen' settings are missing. While the table plays fine going directly through the 'VPinballX_GL' application, when trying to play from PinUp Player the error comes up: "Error parsing POV XML file: 'desktop' element is missing". I also noticed on the 'customsettings' none of the adjustment numbers are being saved. Yes, I have configured my Cabinet Layout in the settings, and i click the start button before exiting the table after adjusting the POV, i see the confirmation on the screen that both the pov and ini files were saved, after i exit I also save my table. Oh and I made sure that there were no previously saved POV's for that table before I started.
So far I've tried 2 tables and they happened on both, the new Mustang table just released today, and the ACDC VPW version. 

Also would like to say, thank you so much for updating and putting your time and effort into a great product, it is very appreciated!  [](url)
![IMG_8090](https://github.com/vpinball/vpinball/assets/88853215/b8261dfb-bc5b-49fd-96c4-c4a3a36b1629)
![IMG_8091](https://github.com/vpinball/vpinball/assets/88853215/5d62b878-1c73-4d91-8d59-4f4e19d0eb62)
![IMG_8092](https://github.com/vpinball/vpinball/assets/88853215/967388b2-a6c4-41bd-8333-2950b1cb1bdc)

**Comment by vbousquet** [comment]
This is the intended behavior. POV files are being deprecated in favor of generalized settings in ini files. This is in progress and just nightly build so far
