### ISSUE TITLE
Kl25z key assignement

### ISSUE THREAD

**Issue by khalidibn** [vpinball/vpinball#958]
Kl25z Key assigned to left flipper acts also as a start game button.

Assign left flipper to button 4 of kl25z
Assign kl25z to button 2 to start a game
When playing if i press left flipper and there is a credit, i will  activate the left flipper, and if there are credit it will add a new player or start a new play. The button 4 acts at the same time like button 4 and 2
The bug is likely appearing not in all the tables.
PS: i tested it on pinscape, buttons works well. 

**Versions & Settings**
 - VPX: 10.8 beta 64bit rev 1591 
 - windows 10
 - GPU rtx 3070ti

**Comment by Karl030167** [comment]
kl25z have no "buttons" - it has input- and output ports. With pinscape tool you can assign any input port to any key. Flipper keys should be left and right shift keys. So there is no interference with start button (key 1) or credit buttons (key 3/4/5) assigning

**Comment by khalidibn** [comment]
The problem doesnt occurre in 10.8 beta 5

**Comment by TurboHenk** [comment]
Somehow my buttons also didn't work anymore in the latest beta, I also use pinscape/Kl25z. So clearly something went wrong with that indeed.

I thought that it had to do something with my setup but once I returned to a previous beta everything worked fine again.

**Comment by vbousquet** [comment]
Latest pre-beta version have complete new settings, so you will need to either delete all your ini file or reassign all your keys in the settings.

I have tested it with the new settings and all the keyboard/joy worked as before, so I will close
