### ISSUE TITLE
Exported DATA such as POV's is corrupt beginning at revision 228

### ISSUE THREAD

**Issue by wiesshund** [vpinball/vpinball#97]
See full description here
https://www.vpforums.org/index.php?showtopic=44135#entry505404

An exported POV looks like thus
https://i.imgur.com/wvpxKWL.png

up to revision 227 it is fine

from 228 through current exported POV and possibly other data is corrupted

**Comment by toxieainc** [comment]
Thanks (as always, btw!) for the report and exact revision!

**Comment by toxieainc** [comment]
Fixed again.
