### ISSUE TITLE
Per-Table .ini Auto Generating

### ISSUE THREAD

**Issue by Drybonz** [vpinball/vpinball#973]
**Describe the bug**
There was some discussion on the VPF forum abour the recent per-table .ini auto generating when a table is launched on recent builds.  We are not sure if this is a bug or intended behavior, and if intended what is the intended purpose.

**To Reproduce**
Open a table on recent builds, an .ini with a couple parameters is auto-generated in the tables folder, named after that table.

**Expected behavior**
Expected behavior would just be no .ini auto-generated, but not sure if this is a new intended process or bug.

**Versions & Settings**
 - VPX: VPX dx (late 1500's and 1600's, not sure which one it started).
 - Win 11
 - 4060
[VPinballX.log](https://github.com/vpinball/vpinball/files/13043808/VPinballX.log)

**Comment by Karl030167** [comment]
with v1618 in flavor dx x86 no more "auto ini create"

**Comment by vbousquet** [comment]
Fixed in latest
