### ISSUE TITLE
Anaglyph 

### ISSUE THREAD

**Issue by Painterboy21** [vpinball/vpinball#974]
It’s washed out in the new beta also was able to turn it on and of buy one key but now it scrolls through them. *Describe the bug**

**To Reproduce**

If the bug appears when playing a specific table, give a link to a place where the exact version of the table file can be downloaded.

**Expected behavior**

**Screenshots**

**Crash dump**
If it's about a crash, please attach `crash.dmp` as well.

**Versions & Settings**
 - VPX: [e.g. 1.7.0 Final Revision 367 (e242d7c), 32 bit - see *Help - About*]
 - Windows version
 - GPU and video settings if applicable
 - If this bug report is for VPX 10.8+, please join your setting file (locate 'VPinballX.ini' in '%AppData%\VPinballX', either zip it or change its extension to '.log', then drag'n drop it here)
 - If this bug report is for VPX 10.8+, please enable log in your settingd and join your log file

**Additional context**

**Comment by vbousquet** [comment]
These are the expected behavior. Anaglyph has been entirely rewriteen and your settings needs to be entirely redone in the latest builds using the Live UI
