### ISSUE TITLE
Desktop plunger auto-cycles when the plunger key is held down

### ISSUE THREAD

**Issue by Scottacus64** [vpinball/vpinball#975]
I'm not sure if this is a bug or not but in vpx 10.8 64 bit 1577 if the plunger is set to enable mechanical and auto plunger is off and the plunger key is held the plunger pulls back nicely and then slowly moves forward to start and then again pulls back to full pull etc.  I'm scripting Onevox's new American Graffiti table and there is a drag race mode where the player will want to hold the plunger back to release it at the right time to win a drag race which is why this is important for me to get to work right.  Here's a video of the behavior.

https://youtu.be/ciCZL5cwbKE

If I enable auto plunger then in desktop the plunger pulls back nicely and holds but if I try a mechanical plunger in a cab then the plunger will work but there is no animation of pulling it back

**Comment by toxieainc** [comment]
Sounds like a regression with the '1s plunger retract' feature (which causes the described behavior, but by design).

**Comment by Scottacus64** [comment]
Is there a way to override this in the script or a setting?

**Comment by Scottacus64** [comment]
Another possibility is to leave the code as is so that all tables using plunger.pullBack will function as they currently do and add in a new command plunger.pullBackand Hold that will always invoke the plunger.pullback method as originally designed?

**Comment by Scottacus64** [comment]
I mentioned this issue to Bill Rothbauer today and he said that auto-cycling the plunger is a setting under DOF etc.  Turns out this is a user error on my part and not a bug!
