### ISSUE TITLE
B2S not working in VPX108R1347

### ISSUE THREAD

**Issue by GeraldCOY** [vpinball/vpinball#976]
No more B2S (at all) 

See attached pictures, one with version 10.7.3 and the other with 10.8.R1347 showing both tasks switcher.

VPX: 10.8 Revision 1347

![VPX1073](https://github.com/vpinball/vpinball/assets/114358822/2d6ee37a-a650-497a-82c8-85d4e20e891e)
![VPX108R1347](https://github.com/vpinball/vpinball/assets/114358822/3c386129-b203-4b0c-9356-433cd5ce6a66)

**Comment by tweety231323** [comment]
What you describe happends often with old B2S versions.
Are you using the latest B2S Server?
[[https://github.com/vpinball/b2s-backglass/releases]]([https://github.com/vpinball/b2s-backglass/releases])

**Comment by GeraldCOY** [comment]
Well, as far as I knew, I was usinfg v2.0.3 but anyway, I downloaded it from here 
https://github.com/vpinball/b2s-backglass/releases
It replaced some files, and after registration... everything seems working fine !
Thanks

**Comment by francisdb** [comment]
I wonder if this whole system could not be made more user friendly and warning users about failures of loading dll's or other issues.
Silent failures are never a good user experience.
