### ISSUE TITLE
altsound with vpmalias crashes in 64 bit

### ISSUE THREAD

**Issue by linojon** [vpinball/vpinball#977]
**Describe the bug**
I have a modded table that uses an aliased rom name and altsound. It runs fine in 32 bit (both 10.7.4 and 10.8 beta), but crashes in 64bit (both 10.7.4 and 10.8). The playfield loads then after a second vpx closes with no processes running in Task Manager.

**To Reproduce**
1. Download and Install
* Dirty Harry (Williams 1995) table (https://vpuniverse.com/files/file/12442-dirty-harry-williams-1995/), 
* dh_lx2 rom (https://www.vpforums.org/index.php?app=downloads&showfile=1265)
* altsound (https://mega.nz/file/O7ZUlY5Z#lHK924fqEa59RKy92r6vMgCKdAHmwKz9hUQrH8bQAfQ)
2. Ensure Alt Sound Mode is set to 1
3. run in vpx 32 bit and vpx 64 bit. All is good.
4. change cGameName to a different name eg dh_lx2_a, and add an alias to VPinMame\vpmalias.txt
5. rename the altsound folder too
6. run in vpx 32 bit OK
7. run in vpx 64 bit. The playfield loads, then it quits immediately with no message.

**Expected behavior**
Expect table to run in 64 bit with altsound without crashing

**Crash dump**
None generated.

**Versions & Settings**
- VPX 10.7.4 Final (Revision 404 (f3fa3d8), 64bit)
 - Windows version
 - GPU and video settings if applicable

**Comment by droscoe** [comment]
@linijon Can you go into the .ini for the altsound you are trying to run and turn on "Debug" level logging, and reproduce?  Also, in the meantime, can you post the altsound.log file (in your tables folder) from an attempt before increasing the logging?  Thanks

**Comment by linojon** [comment]
hi @droscoe i dont see an altsound.log file.

VPinMame version 3.6 (x64) Mar 13, 2023 (from Setup64.exe > Info box)

**Comment by droscoe** [comment]
> hi @droscoe i dont see an altsound.log file.
> 
> VPinMame version 3.6 (x64) Mar 13, 2023 (from Setup64.exe > Info box)

Sounds like you have a version prior to the new AltSound code.  Can you install this version please and try again?
https://github.com/vpinball/pinmame/releases/download/v3.6-573-5d6459d/VPinMAME-sc-3.6-573-5d6459d-win-x64.zip

**Comment by linojon** [comment]
FIXED. Seems to be working.  Thanks! I'll reopen if i start having problems again. 
Will be good when this fix is added to the baller installer 64bit migration package
