### ISSUE TITLE
[VR] "VR Preview" viewport cropped instead of fitted to window?

### ISSUE THREAD

**Issue by SuperFromND** [vpinball/vpinball#978]
**Describe the bug**
So I'm not entirely sure if this is a bug or a consequence of the hardware/settings I'm using, but the VR Preview mode does not seem to properly "scale" its viewport to show the entirety of what the given eye(s) are seeing. Specifically, it seems to only show a portion of the bottom-left corner of the screen rather than the entire screen.

**To Reproduce**
This assumes you're using an Oculus Quest, but given the nature of this bug it should "work" with any headset:
1. Start up a VR headset and get it working with SteamVR. For the Quest:
    - Plug in the Quest to a USB3 port on your PC.
    - Start the Quest.
    - It'll prompt you if you want to enable Quest Link. Select Yes.
    - You don't *need* to open SteamVR (Visual Pinball prompts you if you want to start it anyways), but if you want, go ahead and start it up in advance. The bug happens either way.
2. Open up Visual Pinball X.
3. Select any table and start it.
4. Observe the window that appears on the desktop.
5. **(Optional!)** In the SteamVR mini-window, click the menu bar and toggle on "Display VR Preview" and compare the resulting visuals. For those on Oculus headsets, you can alternatively run Oculus Mirror (`C:\Program Files\Oculus\Support\oculus-diagnostics\oculusmirror.exe`) for a smoother preview framerate (which is what I'm using here).

**Expected behavior**
What I'm trying to do is have a full-screen preview of what the person is seeing in VR displayed on my regular monitor, similar to other VR applications.

When using the preview, I would expect the window displayed to the monitor to show the entirety of what the given eye (or eyes, if both eyes are enabled in VR settings) is seeing. See both Oculus Mirror and SteamVR's preview window as examples of what I mean.

I'm not able to just use those mirror tools as a workaround either, as Visual Pinball X doesn't appear to have any way of reading inputs unless its the focused window... and I can't do that if the mirror tools are fullscreened or focused!

**Screenshots**
To illustrate what I mean, I made a comparison video between what Visual Pinball X displays and Oculus Mirror (an official program that shows what the eye sees in the headset, albeit cropped a bit to suit a widescreen display). It's not a *perfect* comparison, but the problem is pretty evident just from comparing the two.

https://github.com/vpinball/vpinball/assets/22881403/c11c58dd-43db-4c97-a014-b4c735b0b982

Screenshots of the above video, just in case it doesn't embed or upload properly:
![vlcsnap-2023-10-20-14h25m11s479](https://github.com/vpinball/vpinball/assets/22881403/780f6697-ecbe-4c99-bf77-0222b35129db)
![vlcsnap-2023-10-20-14h25m20s869](https://github.com/vpinball/vpinball/assets/22881403/f2ca3665-7097-42c5-bd19-c74dfeae3460)

**Versions & Settings**
 - VPX: [10.8.0 beta 5](https://github.com/vpinball/vpinball/releases/tag/v10.8.0-1347-3d585e7) (commit 3d585e7), 64-Bit (VPX_GL version for VR support)
 - Windows 10 Pro, 22H2 19045.3570
 - NVidia RTX 3060 Ti, Driver 536.23 (via Windows Update, not through Nvidia's own site)
 - Headset: Oculus Quest 1, running over Quest Link
 - [My VPinballX.ini](https://github.com/vpinball/vpinball/files/13057826/VPinballX.ini.log)
 - [My vpinball.log](https://github.com/vpinball/vpinball/files/13057827/vpinball.log)

**Additional context**
I've already tried messing with the resolution options to see if maybe something there would fix it (whether that's toggling on and off "Exclusive fullscreen" or simply messing with the resolution), but no combination seems to fix the issue fully.

I also noticed while scrolling through my log this line:
```
2023-10-20 14:04:50.253 INFO  [1552] [Player::CreateWnd@621] SDL display mode: 640x480 60Hz SDL_PIXELFORMAT_RGB888
```
It seems like this *could* be a clue as to what the problem is (my resolution for the window *should be* set to 1920x1080), and it would explain the unusually small viewport relative to the window size itself.

**Comment by TurboHenk** [comment]
I reported this long ago here: https://github.com/vpinball/vpinball/issues/605

The mirror has been broken for a long time. I don't understand that it's not repored more. 

But good that you posted it, so that it's clear that it's not a Pimax problem(same as with my other reports).

**Comment by SuperFromND** [comment]
Ah thank you Henk, I was trying to find threads about this problem from Googling around earlier and couldn't find anything. Your bug report slipped through the cracks, I guess!

Oh, and just to confirm vbousquet's question over on that issue, I downloaded the latest build possible (up to latest commit from master, [via Github Artifacts](https://github.com/vpinball/vpinball/actions/runs/6597015467)) and this problem is still unfortunately there. :<

https://github.com/vpinball/vpinball/assets/22881403/983eec23-fce1-441b-af96-be0bca49dcc2

**Comment by TurboHenk** [comment]
Thanks for reporting. I'm glad that it's on the radar now. It's clear when it started, since I "investigated" it; it happened in the changes that were made between version 1261-1265 GL. So it's surely solvable.

It's a big problem when you play with multiple people (which I do most of the time..) but luckily I have the OpenXR mirror, so it's not a huge problem because of that.. But it would be nice if the changes between 1261-1265 could be undone... so that it works properly again for all users including people that don't have the option to use "a other mirror".

**Comment by studlygoorite** [comment]
Yeah I noticed this also quite some time ago. I believe the change was made to support the 3D Anaglyph but it does make it pretty difficult to take a screenshot of your score for a competition or to show any kind of issue going on with a table. You have to be looking away from what you want to take a pic of and try to look under your headset at the VR preview screen to see if what you want a picture of is actually on the screen. Hope there is a fix for this as I just deal with it but have to try and take pics quite often.

**Comment by TurboHenk** [comment]
Thanks but it's not fixed here. So I have to open it again.

See attached screenshot.
![notfixed](https://github.com/vpinball/vpinball/assets/132104433/dc1a8fbd-811d-40f6-ace1-cfeecf502859)

**Comment by vbousquet** [comment]
Should be good now

**Comment by SuperFromND** [comment]
Posting to confirm it's all working now, here's a direct recording from VPX as of latest commit. Excellent work! :)


https://github.com/vpinball/vpinball/assets/22881403/ba4864d9-e6f0-4454-a249-0fba93e1b371

**Comment by TurboHenk** [comment]
I hope that my comment doesn't reopen it. I just want to confirm that it works great here too with the Pimax Crystal and to say: Thank you!
