### ISSUE TITLE
Auto day/night cycle

### ISSUE THREAD

**Issue by tommkell** [vpinball/vpinball#983]
**Describe the bug**
Auto day/night cycle not working, always works off slider whether box is ticked or not

**Expected behavior**
After entering latitude/longitude and checking the enable box in settings, then unchecking the box beside the day/night slider in the editor, the table brightness should vary depending on the time of day

**Versions & Settings**
 - VPX 10.8.0 Beta revision 1623 (027461f) 64 bit
 - Windows version 11

**Comment by vbousquet** [comment]
Just tested, and so far, I only see the intended behavior: you need to have bith checkbox checked for auto night/day
![image](https://github.com/vpinball/vpinball/assets/2796036/da87ef3d-03d6-4c6a-b3cd-90ff3ad360aa)

Pleas eprovide more information if it is not working for you
