### ISSUE TITLE
Freeze when exit a table with flex dmd or pinup video

### ISSUE THREAD

**Issue by strangeleo7** [vpinball/vpinball#998]
Freeze when exit a table with flex dmd or pinup video

in Pinballx dont kill the app when exit a table wiht flexdmd or pinupvideo

version 1635

**Comment by Bingopinballmania** [comment]
I have the same problem but only when my VP cabinet is offline from internet. When my VP cabinet is connected on internet there are no problems and everyting works fine. How to fix this problem ?

**Comment by francisdb** [comment]
You'll need to give us a bit more info as requested in the issue template.

What table do you have this on? Download link?
Does the problem go away if you use the table without pup pack?
Are you using anything else that might be making network calls like scorbit?

**Comment by Smackxs** [comment]
I updated to Flex 1.9.1 and that problem went away.  Hope this helps

**Comment by toxieainc** [comment]
@strangeleo7 @Bingopinballmania Can you please test with 1.9.1?

**Comment by strangeleo7** [comment]
Yes! its fine for me… I tested a few hours…
